# Speaker Verification Training & Inference

Complete pipeline for speaker verification using:
- **PTM Encoder**: WavLM/HuBERT/Wav2Vec2 (multi-layer weighted sum)
- **Handcrafted Encoder**: MFBE + F0 features with CNN
- **Fusion Methods**: Concatenation or Cross-Attention
- **Backbone**: ECAPA-TDNN
- **Loss**: AAM-Softmax
- **Features**: Early stopping, LR scheduling, heatmap visualization

## 1. Setup & Parse Arguments

In [1]:
# Auto-reload modules
%load_ext autoreload
%autoreload 2

import os

# Notebook-local runtime knobs (không dùng biến môi trường)
KMP_DUPLICATE_LIB_OK = True
OMP_NUM_THREADS = 1

import torch
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import argparse
import sys
from datetime import datetime

# Hạn chế số luồng nội bộ của PyTorch
torch.set_num_threads(OMP_NUM_THREADS)

# Check device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

Device: cuda
GPU: NVIDIA GeForce RTX 5080
GPU Memory: 17.09 GB

In [2]:
from config import (
    BATCH_SIZE, NUM_EPOCHS, LEARNING_RATE, EMBEDDING_DIM,
    MODE, FUSION_METHOD, FEATURE_MODE,
    CHECKPOINT_DIR, BEST_MODEL_NAME,
 )
from train import train

# 1. Cấu hình các biến lặp
ROOT_DIR = "D:/"
durations = ['train_raw', 'train_vi_full', 'train_vi_3s', 'train_vi_5s', 'train_vi_7s']
pretrained_models = ['hubert', 'wavlm', 'wav2vec2']

# Tên thư mục feature trên ổ cứng
feature_folders = ['mfbe', 'pitch', 'mfcc', 'mfbe_pitch', 'mfcc_pitch']

# Fusion methods
fusion_methods = ["gating", "film", "concat"]

# Map tên thư mục sang tên config FEATURE_MODE để model nhận diện đúng dim
feat_name_map = {
    'mfbe': 'mfbe_only',
    'pitch': 'pitch_only',
    'mfcc': 'mfcc_only',
    'mfbe_pitch': 'mfbe_pitch',
    'mfcc_pitch': 'mfcc_pitch'
}

dur_prefix_map = {
    'train_raw': '',
    'train_vi_3s': '3s_',
    'train_vi_5s': '5s_',
    'train_vi_7s': '7s_',
    'train_vi_full': 'full_'
}

def get_base_args():
    """Hàm tạo arguments cơ bản giống như lúc parse_args()"""
    parser = argparse.ArgumentParser()
    # Thêm các đối số cơ bản
    parser.add_argument("--output_dir", type=str, default="./outputs")
    parser.add_argument("--experiments_dirname", type=str, default="experiments_new")
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--learning_rate", type=float, default=0.0001)
    parser.add_argument("--lr_scheduler", type=str, default="plateau")
    parser.add_argument("--num_epochs", type=int, default=60)
    parser.add_argument("--optimizer", type=str, default="adam")
    parser.add_argument("--weight_decay", type=float, default=0.001)
    parser.add_argument("--aam_margin", type=float, default=0.25)
    parser.add_argument("--aam_scale", type=float, default=30)
    parser.add_argument("--embedding_dim", type=int, default=512)
    parser.add_argument("--mixed_precision", type=bool, default=True)
    parser.add_argument("--early_stop_patience", type=int, default=12)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--augment_prob", type=float, default=0.30)
    parser.add_argument("--feature_noise_std", type=float, default=0.003)
    parser.add_argument("--embedding_noise_std", type=float, default=0.002)
    parser.add_argument("--max_frames", type=int, default=350)
    
    # Sẽ gán động trong lúc lặp
    parser.add_argument("--mode", type=int, default=3)
    parser.add_argument("--exp_name", type=str, default="")
    parser.add_argument("--embedding_path", type=str, default="")
    parser.add_argument("--feature_path", type=str, default="")
    parser.add_argument("--feature_mode", type=str, default="")
    parser.add_argument("--fusion_method", type=str, default="")
    parser.add_argument("--use_gating", type=bool, default=False)
    parser.add_argument("--use_augment", type=bool, default=True)
    parser.add_argument("--branch_dropout_prob", type=float, default=0.0)
    
    # 2-stage fine-tune cho Mode 3
    parser.add_argument("--use_two_stage_ft", type=bool, default=True)
    parser.add_argument("--stage1_epochs", type=int, default=6)
    parser.add_argument("--stage2_ptm_lr_scale", type=float, default=0.35)
    
    # Custom fields để lưu lại log
    parser.add_argument("--duration", type=str, default="")
    parser.add_argument("--pretrained_model", type=str, default="")
    parser.add_argument("--init_mode1_ckpt", type=str, default=None)
    parser.add_argument("--init_mode2_ckpt", type=str, default=None)
    parser.add_argument("--use_ptm_on_the_fly", type=bool, default=False)
    parser.add_argument("--ptm_model_id", type=str, default="facebook/wav2vec2-base")
    parser.add_argument("--audio_base_dir", type=str, default="")
    parser.add_argument("--audio_sample_rate", type=int, default=16000)
    parser.add_argument("--max_audio_seconds", type=float, default=8.0)
    
    args, _ = parser.parse_known_args([])
    return args

def check_skip(exp_name, experiments_dirname="experiments_new"):
    """Cơ chế Skip if done: Kiểm tra xem kết quả đã tồn tại chưa"""
    results_file = os.path.join("./outputs", experiments_dirname, exp_name, "results.json")
    if os.path.exists(results_file):
        print(f"⏭ Bỏ qua {exp_name} - Đã huấn luyện xong!")
        return True
    return False

## 2. Training

In [3]:
# # Cập nhật tên exp để biết đang chạy fusion gì
# fusion = "cross_attention" # Ví dụ: đang chạy fusion gating
# dur = "train_raw" # Ví dụ: đang chạy với duration full
# ptm = "wavlm" # Ví dụ: đang chạy với pretrained model hubert
# feat_dir = "mfbe_pitch" # Ví dụ: đang chạy với feature mfbe_pitch
# feat_mode = feat_name_map[feat_dir]

# exp_name = f"Mode3_{fusion}_{dur}_{ptm}_{feat_mode}"

# print(f"\n{'='*60}\nĐANG CHẠY: {exp_name}\n{'='*60}")
# args = get_base_args()
# args.mode = 3
# args.exp_name = exp_name
# args.duration = dur
# args.pretrained_model = ptm
# args.feature_mode = feat_mode
# args.fusion_method = fusion    

# prefix = dur_prefix_map[dur]
# args.embedding_path = os.path.join(ROOT_DIR, "Embeddings", dur, f"{prefix}{ptm}_shards")
# args.feature_path = os.path.join(ROOT_DIR, "extracted_features", dur, f"{feat_dir}_shards")

# # Bật cờ use_gating nếu fusion là gating (để log/phân tích)
# args.use_gating = True if fusion == "gating" else False
# args.use_augment = True # Mode 3 dùng augment để tăng độ robust

# train(args)

In [ ]:
import gc
import os
import time
import traceback

import pandas as pd
import torch

from train import train

SEARCH_TAG = "overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1"
EXPERIMENTS_DIRNAME = f"experiments_{SEARCH_TAG}"
REPORT_PREFIX = SEARCH_TAG

# Đặt None để chạy full qua đêm; đặt số nhỏ như 1 hoặc 2 để test nhanh
MAX_RUNS = None

FEAT_NAME_MAP = {
    "mfbe": "mfbe_only",
    "pitch": "pitch_only",
    "mfcc": "mfcc_only",
    "mfbe_pitch": "mfbe_pitch",
    "mfcc_pitch": "mfcc_pitch",
}

DUR_PREFIX_MAP = {
    "train_raw": "",
    "train_vi_3s": "3s_",
    "train_vi_5s": "5s_",
    "train_vi_7s": "7s_",
    "train_vi_full": "full_",
}


def get_cell7_base_args():
    args = get_base_args()
    args.experiments_dirname = EXPERIMENTS_DIRNAME
    args.early_stop_patience = 10
    args.use_two_stage_ft = False
    args.stage1_epochs = 0
    args.stage2_ptm_lr_scale = 1.0
    return args


def check_skip_cell7(exp_name, experiments_dirname=EXPERIMENTS_DIRNAME):
    results_file = os.path.join("./outputs", experiments_dirname, exp_name, "results.json")
    if os.path.exists(results_file):
        print(f"[SKIP] {exp_name} already finished")
        return True
    return False


def make_exp_name(cfg):
    ap = str(cfg["augment_prob"]).replace(".", "p")
    fn = str(cfg["feature_noise_std"]).replace(".", "p")
    en = str(cfg["embedding_noise_std"]).replace(".", "p")
    am = str(cfg["aam_margin"]).replace(".", "p")
    scale_tag = str(int(cfg["aam_scale"]))
    return SEARCH_TAG + "_" + cfg["tag"] + "_ap" + ap + "_fn" + fn + "_en" + en + "_m" + am + "_s" + scale_tag


def build_run_plan():
    base = {
        "fusion": "film",
        "duration": "train_raw",
        "ptm": "wav2vec2",
        "feat_dir": "mfcc_pitch",
        "branch_dropout_prob": 0.05,
        "num_epochs": 60,
        "early_stop_patience": 10,
        "learning_rate": 1e-4,
        "weight_decay": 1e-3,
        "use_two_stage_ft": False,
        "stage1_epochs": 0,
        "stage2_ptm_lr_scale": 1.0,
    }
    base["feat_mode"] = FEAT_NAME_MAP[base["feat_dir"]]

    grid = [
        {"tag": "top_bal_s42", "seed": 42, "use_augment": True, "augment_prob": 0.30, "feature_noise_std": 0.003, "embedding_noise_std": 0.002, "aam_margin": 0.25, "aam_scale": 30},
        {"tag": "top_full_s42", "seed": 42, "use_augment": True, "augment_prob": 0.20, "feature_noise_std": 0.005, "embedding_noise_std": 0.002, "aam_margin": 0.25, "aam_scale": 30},
        {"tag": "near1_s42", "seed": 42, "use_augment": True, "augment_prob": 0.25, "feature_noise_std": 0.004, "embedding_noise_std": 0.002, "aam_margin": 0.25, "aam_scale": 30},
        {"tag": "near2_s42", "seed": 42, "use_augment": True, "augment_prob": 0.30, "feature_noise_std": 0.005, "embedding_noise_std": 0.001, "aam_margin": 0.25, "aam_scale": 30},
        {"tag": "aam1_s42", "seed": 42, "use_augment": True, "augment_prob": 0.20, "feature_noise_std": 0.005, "embedding_noise_std": 0.002, "aam_margin": 0.20, "aam_scale": 32},
        {"tag": "aam2_s42", "seed": 42, "use_augment": True, "augment_prob": 0.30, "feature_noise_std": 0.003, "embedding_noise_std": 0.002, "aam_margin": 0.20, "aam_scale": 32},
        {"tag": "top_bal_s3407", "seed": 3407, "use_augment": True, "augment_prob": 0.30, "feature_noise_std": 0.003, "embedding_noise_std": 0.002, "aam_margin": 0.25, "aam_scale": 30},
        {"tag": "top_full_s3407", "seed": 3407, "use_augment": True, "augment_prob": 0.20, "feature_noise_std": 0.005, "embedding_noise_std": 0.002, "aam_margin": 0.25, "aam_scale": 30},
    ]

    run_plan = []
    for cfg in grid:
        merged = dict(base)
        merged.update(cfg)
        merged["exp_name"] = make_exp_name(cfg)
        run_plan.append(merged)
    return run_plan


def run_one(cfg):
    args = get_cell7_base_args()
    args.mode = 3
    args.exp_name = cfg["exp_name"]
    args.duration = cfg["duration"]
    args.pretrained_model = cfg["ptm"]
    args.feature_mode = cfg["feat_mode"]
    args.fusion_method = cfg["fusion"]
    args.branch_dropout_prob = cfg["branch_dropout_prob"]
    args.use_gating = False
    args.use_augment = cfg["use_augment"]
    args.augment_prob = cfg["augment_prob"]
    args.feature_noise_std = cfg["feature_noise_std"]
    args.embedding_noise_std = cfg["embedding_noise_std"]
    args.num_epochs = cfg["num_epochs"]
    args.early_stop_patience = cfg["early_stop_patience"]
    args.learning_rate = cfg["learning_rate"]
    args.weight_decay = cfg["weight_decay"]
    args.aam_margin = cfg["aam_margin"]
    args.aam_scale = cfg["aam_scale"]
    args.use_two_stage_ft = cfg["use_two_stage_ft"]
    args.stage1_epochs = cfg["stage1_epochs"]
    args.stage2_ptm_lr_scale = cfg["stage2_ptm_lr_scale"]
    args.freeze_ptm_extractor = True
    args.train_mode3_ptm_layer_fusion = True
    args.use_mode3_warmstart = False
    args.use_mode3_init_mode1 = False
    args.use_mode3_init_mode2 = False
    args.seed = cfg["seed"]

    prefix = DUR_PREFIX_MAP[cfg["duration"]]
    args.embedding_path = os.path.join(ROOT_DIR, "Embeddings", cfg["duration"], prefix + cfg["ptm"] + "_shards")
    args.feature_path = os.path.join(ROOT_DIR, "extracted_features", cfg["duration"], cfg["feat_dir"] + "_shards")
    args.init_mode1_ckpt = os.path.join(
        "./outputs",
        "experiments",
        "Mode1_PTM_" + cfg["duration"] + "_" + cfg["ptm"],
        "best_model.pth",
    )
    args.init_mode2_ckpt = os.path.join(
        "./outputs",
        "experiments",
        "Mode2_HC_" + cfg["duration"] + "_" + cfg["feat_mode"],
        "best_model.pth",
    )
    train(args)


run_plan = build_run_plan()
if MAX_RUNS is not None:
    run_plan = run_plan[: max(0, int(MAX_RUNS))]

print("SEARCH_TAG:", SEARCH_TAG)
print("EXPERIMENTS_DIRNAME:", EXPERIMENTS_DIRNAME)
print("REPORT_PREFIX:", REPORT_PREFIX)
print("TOTAL RUNS:", len(run_plan))
for i, cfg in enumerate(run_plan, 1):
    print("[{0:02d}] {1}".format(i, cfg["exp_name"]))

results = []
wall_start = time.time()
os.makedirs("./outputs", exist_ok=True)

for i, cfg in enumerate(run_plan, 1):
    if check_skip_cell7(cfg["exp_name"]):
        results.append({"exp_name": cfg["exp_name"], "status": "skipped_existing", "minutes": 0.0})
        continue

    run_start = time.time()
    print("\n" + "=" * 72)
    print("[{0}/{1}] START: {2}".format(i, len(run_plan), cfg["exp_name"]))
    print("=" * 72)

    try:
        run_one(cfg)
        minutes = round((time.time() - run_start) / 60.0, 2)
        results.append({"exp_name": cfg["exp_name"], "status": "done", "minutes": minutes})
        print("DONE:", cfg["exp_name"], "|", minutes, "min")
    except KeyboardInterrupt:
        print("Interrupted by user. Stop overnight plan.")
        raise
    except Exception as ex:
        minutes = round((time.time() - run_start) / 60.0, 2)
        results.append({"exp_name": cfg["exp_name"], "status": "error: " + type(ex).__name__, "minutes": minutes})
        print("ERROR:", cfg["exp_name"], "->", type(ex).__name__, ex)
        traceback.print_exc()
        print("Continue to next run...")
    finally:
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

summary_df = pd.DataFrame(results)
summary_path = os.path.join("./outputs", SEARCH_TAG + "_overnight_run_summary.csv")
if len(summary_df) > 0:
    summary_df.to_csv(summary_path, index=False)
    print("Saved overnight summary:", summary_path)
    print(summary_df.to_string(index=False))

print("Total wall time (hours):", round((time.time() - wall_start) / 3600.0, 2))
print("Morning steps: run Cell 11 rồi Cell 12.")

## 3. Tensorboard

In [ ]:
# Load TensorBoard extension
%load_ext tensorboard

# Chạy giao diện TensorBoard trỏ vào thư mục chứa tất cả các experiments
%tensorboard --logdir train/outputs/experiments

## 4. Benchmark & Ensemble

In [ ]:
import gc
import os
import glob
import json
import warnings
from collections import OrderedDict
from itertools import combinations

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from tqdm.auto import tqdm

from model import get_model
from metrics import compute_eer, compute_mindcf

warnings.filterwarnings("ignore")

# ============================================================================
# CONFIG
# - Duration ensemble: keep the requested fixed duration combinations
# - Representation ensemble: generate all PTM/HC combinations within the same duration
# - Equal-weight runs are generated first, then anchor-biased weights
# - Ensemble scores are combined by fixed trial_idx vectors, not DataFrame merge
# - Explicit cache cleanup between test sets to avoid kernel crash on long runs
# - Resume mode: skip test sets that already have per-test CSV reports
# ============================================================================
REPORT_PREFIX = "ensemble_duration_representation_v2"
TEST_BASE_DIR = r"D:\test_o"
LIST_GT_DIR = os.path.join(TEST_BASE_DIR, "list_gt")
OUTPUT_DIR = "./outputs"
P_TARGET = 0.05
SKIP_EXISTING_TEST_REPORTS = True

TARGET_MODE = 3
TARGET_FUSION = "film"
ANCHOR_DURATION = "train_raw"
ANCHOR_PTM = "wav2vec2"
ANCHOR_FEATURE = "mfcc_pitch"

DURATION_ORDER = ["train_raw", "train_vi_full", "train_vi_3s", "train_vi_5s", "train_vi_7s"]
PTM_ORDER = ["wav2vec2", "wavlm", "hubert"]
FEATURE_ORDER = ["mfcc_pitch", "mfbe_pitch", "mfcc_only", "mfbe_only", "pitch_only"]

TEST_SET_CONFIGS = [
    {"name": "full_length", "trial_file": "test_list_gt.csv", "duration": "full_length"},
    {"name": "test_vi", "trial_file": "test_list_gt_vi.csv", "duration": "test_vi"},
    {"name": "test_3s", "trial_file": "test_list_gt_3s.csv", "duration": "test_3s"},
    {"name": "test_5s", "trial_file": "test_list_gt_5s.csv", "duration": "test_5s"},
    {"name": "test_7s", "trial_file": "test_list_gt_7s.csv", "duration": "test_7s"},
]

SOURCE_EXPERIMENT_ROOTS = []
for pattern in ["./outputs/experiments", "./outputs/experiments_*"]:
    for candidate in sorted(glob.glob(pattern)):
        if os.path.isdir(candidate) and candidate not in SOURCE_EXPERIMENT_ROOTS:
            SOURCE_EXPERIMENT_ROOTS.append(candidate)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")
print(f"Report prefix: {REPORT_PREFIX}")
print(f"Target mode/fusion: {TARGET_MODE}/{TARGET_FUSION}")
print(f"Skip existing per-test reports: {SKIP_EXISTING_TEST_REPORTS}")
print("Source experiment roots:")
for root in SOURCE_EXPERIMENT_ROOTS:
    print(" -", root)

HC_FILENAME_MAP = {
    "mfbe_only": "Only_MFBE.pt",
    "pitch_only": "Only_Pitch.pt",
    "mfcc_only": "Only_MFCC.pt",
    "mfbe_pitch": "MFBE_Pitch.pt",
    "mfcc_pitch": "MFCC_Pitch.pt",
}

BASE_DURATION_ENSEMBLE_SPECS = [
    {"family": "duration", "name": "raw_vi_full", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_3s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_3s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_5s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_5s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_7s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_7s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_3s_5s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_3s__wav2vec2__mfcc_pitch",
        "train_vi_5s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_3s_7s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_3s__wav2vec2__mfcc_pitch",
        "train_vi_7s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_5s_7s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_5s__wav2vec2__mfcc_pitch",
        "train_vi_7s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_3s_5s_7s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_3s__wav2vec2__mfcc_pitch",
        "train_vi_5s__wav2vec2__mfcc_pitch",
        "train_vi_7s__wav2vec2__mfcc_pitch",
    ]},
]

def parse_trial_csv(trial_csv_path: str) -> pd.DataFrame:
    raw_df = pd.read_csv(trial_csv_path, header=None)
    if raw_df.shape[1] >= 3:
        df = raw_df.iloc[:, :3].copy()
        df.columns = ["label", "path1", "path2"]
    else:
        df = raw_df.rename(columns={0: "raw"}).copy()
        parsed = df["raw"].astype(str).str.strip('"').str.extract(r"^\s*([01])\s+(.+?)\s+(.+?)\s*$")
        parsed.columns = ["label", "path1", "path2"]
        df = parsed
    df["label"] = df["label"].astype(int)
    df["path1"] = df["path1"].astype(str)
    df["path2"] = df["path2"].astype(str)
    df = df.reset_index(drop=True)
    df["trial_idx"] = np.arange(len(df), dtype=np.int64)
    return df[["trial_idx", "label", "path1", "path2"]]

def _candidate_keys(path_text: str):
    p = str(path_text).replace('\\', '/').strip()
    base = os.path.basename(p)
    stem = os.path.splitext(base)[0]
    rel = p.lstrip('./')
    out, seen = [], set()
    for key in [p, rel, base, stem]:
        if key not in seen:
            out.append(key)
            seen.add(key)
    return out

def _register_lookup(lookup, path_text, value):
    for key in _candidate_keys(path_text):
        if key not in lookup:
            lookup[key] = value

def _get_feature_from_lookup(lookup, path_text):
    if lookup is None:
        return None
    for key in _candidate_keys(path_text):
        if key in lookup:
            return lookup[key]
    return None

def resolve_ptm_path(ptm_name: str, ptm_dir: str):
    ptm_name = str(ptm_name).lower()
    cands = [
        os.path.join(ptm_dir, f"Embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"all_embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"{ptm_name}.pt"),
    ]
    for p in cands:
        if os.path.exists(p):
            return p
    return None

def resolve_hc_path(feature_mode: str, feature_dir: str):
    feature_mode = str(feature_mode).lower()
    if feature_mode in HC_FILENAME_MAP:
        p = os.path.join(feature_dir, HC_FILENAME_MAP[feature_mode])
        if os.path.exists(p):
            return p
    for p in [
        os.path.join(feature_dir, f"{feature_mode}.pt"),
        os.path.join(feature_dir, f"all_features_{feature_mode}.pt"),
    ]:
        if os.path.exists(p):
            return p
    return None

def _to_float_tensor(value):
    if torch.is_tensor(value):
        return value.float().detach().cpu()
    return torch.tensor(value, dtype=torch.float32)

def build_lookup_from_pt_file(obj, value_field: str):
    lookup = {}
    if not isinstance(obj, dict):
        raise ValueError(f"Unsupported .pt format: expected dict, got {type(obj).__name__}")

    if "filenames" in obj and value_field in obj:
        filenames = obj["filenames"]
        values = obj[value_field]
        if len(filenames) != len(values):
            raise ValueError(
                f"Unsupported .pt format: len(filenames)={len(filenames)} != len({value_field})={len(values)}"
            )
        for idx, name in enumerate(filenames):
            _register_lookup(lookup, str(name), _to_float_tensor(values[idx]))
        return lookup

    if len(obj) > 0 and all(isinstance(k, str) for k in obj.keys()):
        for name, value in obj.items():
            if isinstance(value, (dict, list, tuple, str, int, float, bool, type(None))) and not torch.is_tensor(value):
                continue
            _register_lookup(lookup, str(name), _to_float_tensor(value))
        if len(lookup) > 0:
            return lookup

    raise ValueError("Unsupported .pt format: missing expected keys")

def _safe_float(value, default=None):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default

def _ordered_index(value, ordered_values):
    try:
        return ordered_values.index(value)
    except ValueError:
        return len(ordered_values)

def _config_alias(duration, ptm_name, feature_mode):
    return f"{duration}__{ptm_name}__{feature_mode}"

def _short_feature_name(feature_mode):
    return str(feature_mode).replace("_only", "")

def _canonical_member_sort_key(alias):
    duration, ptm_name, feature_mode = alias.split("__", 2)
    anchor_bias = 0 if (duration == ANCHOR_DURATION and ptm_name == ANCHOR_PTM and feature_mode == ANCHOR_FEATURE) else 1
    return (
        anchor_bias,
        _ordered_index(duration, DURATION_ORDER),
        _ordered_index(ptm_name, PTM_ORDER),
        _ordered_index(feature_mode, FEATURE_ORDER),
        alias,
    )

def discover_experiments(exp_roots):
    experiments = []
    seen = set()
    for root in exp_roots:
        if not os.path.isdir(root):
            continue
        for exp_dir in sorted(glob.glob(os.path.join(root, "*"))):
            model_path = os.path.join(exp_dir, "best_model.pth")
            config_path = os.path.join(exp_dir, "config.json")
            results_path = os.path.join(exp_dir, "results.json")
            if not (os.path.exists(model_path) and os.path.exists(config_path)):
                continue
            exp_name = os.path.basename(exp_dir)
            dedup_key = (root, exp_name)
            if dedup_key in seen:
                continue
            seen.add(dedup_key)
            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)
            results = {}
            if os.path.exists(results_path):
                with open(results_path, "r", encoding="utf-8") as f:
                    results = json.load(f)
            experiments.append({
                "exp_name": exp_name,
                "root_dir": root,
                "exp_dir": exp_dir,
                "model_path": model_path,
                "mode": int(cfg.get("mode", 3)),
                "fusion_method": str(cfg.get("fusion_method", "concat")).lower(),
                "feature_mode": str(cfg.get("feature_mode", "mfbe_pitch")).lower(),
                "pretrained_model": str(cfg.get("pretrained_model", "wavlm")).lower(),
                "duration": str(cfg.get("duration", "")).lower(),
                "branch_dropout_prob": _safe_float(cfg.get("branch_dropout_prob"), None),
                "use_augment": bool(cfg.get("use_augment", False)),
                "best_val_eer": _safe_float(results.get("best_val_eer"), np.inf),
            })
    return experiments

def build_exact_config_bank(experiments):
    grouped = OrderedDict()
    for exp in experiments:
        if exp["mode"] != TARGET_MODE:
            continue
        if exp["fusion_method"] != TARGET_FUSION:
            continue
        if not exp["duration"] or not exp["pretrained_model"] or not exp["feature_mode"]:
            continue
        alias = _config_alias(exp["duration"], exp["pretrained_model"], exp["feature_mode"])
        grouped.setdefault(alias, []).append(exp)

    resolved = OrderedDict()
    rows = []
    for alias in sorted(grouped.keys(), key=_canonical_member_sort_key):
        candidates = sorted(
            grouped[alias],
            key=lambda x: (np.isinf(x.get("best_val_eer", np.inf)), x.get("best_val_eer", np.inf), x["exp_name"]),
        )
        picked = candidates[0]
        resolved[alias] = picked
        rows.append({
            "alias": alias,
            "picked_experiment": picked["exp_name"],
            "candidate_count": len(candidates),
            "duration": picked["duration"],
            "ptm": picked["pretrained_model"],
            "feature": picked["feature_mode"],
            "fusion": picked["fusion_method"],
            "best_val_eer": None if np.isinf(picked.get("best_val_eer", np.inf)) else picked.get("best_val_eer"),
        })
    return resolved, pd.DataFrame(rows)

def make_weight_variants(member_count):
    if member_count == 2:
        return [
            ("eq", [0.5, 0.5]),
            ("a60", [0.6, 0.4]),
            ("a70", [0.7, 0.3]),
        ]
    if member_count == 3:
        return [
            ("eq", [1 / 3, 1 / 3, 1 / 3]),
            ("a50", [0.5, 0.3, 0.2]),
            ("a60", [0.6, 0.25, 0.15]),
        ]
    if member_count == 4:
        return [
            ("eq", [0.25, 0.25, 0.25, 0.25]),
            ("a45", [0.45, 0.25, 0.15, 0.15]),
            ("a50", [0.5, 0.2, 0.15, 0.15]),
        ]
    if member_count == 5:
        return [
            ("eq", [0.2, 0.2, 0.2, 0.2, 0.2]),
            ("a40", [0.4, 0.25, 0.15, 0.1, 0.1]),
            ("a45", [0.45, 0.2, 0.15, 0.1, 0.1]),
        ]
    equal = [1.0 / member_count] * member_count
    return [("eq", equal)]

def _append_weighted_jobs(jobs, family, name_prefix, member_aliases):
    ordered_members = sorted(member_aliases, key=_canonical_member_sort_key)
    for weight_tag, weights in make_weight_variants(len(ordered_members)):
        weight_sum = sum(weights)
        normalized = [float(w / weight_sum) for w in weights]
        jobs.append({
            "family": family,
            "name": name_prefix,
            "member_aliases": ordered_members,
            "weights": normalized,
            "weight_tag": weight_tag,
            "ensemble_name": f"ENS_{family}_{name_prefix}__{weight_tag}",
        })

def expand_duration_jobs(base_specs, exact_bank):
    jobs = []
    for spec in base_specs:
        missing = [alias for alias in spec["members"] if alias not in exact_bank]
        if missing:
            print(f"[SKIP DURATION] {spec['name']} missing members: {missing}")
            continue
        _append_weighted_jobs(jobs, spec["family"], spec["name"], spec["members"])
    return jobs

def _subset_lists(aliases):
    aliases = sorted(aliases, key=_canonical_member_sort_key)
    out = []
    for size in range(2, len(aliases) + 1):
        for combo in combinations(aliases, size):
            out.append(list(combo))
    return out

def generate_representation_jobs(exact_bank):
    jobs = []
    grouped_by_duration = OrderedDict()
    for alias, exp in exact_bank.items():
        grouped_by_duration.setdefault(exp["duration"], []).append((alias, exp))

    for duration in sorted(grouped_by_duration.keys(), key=lambda d: (_ordered_index(d, DURATION_ORDER), d)):
        items = grouped_by_duration[duration]
        by_feature = OrderedDict()
        by_ptm = OrderedDict()

        for alias, exp in items:
            by_feature.setdefault(exp["feature_mode"], []).append(alias)
            by_ptm.setdefault(exp["pretrained_model"], []).append(alias)

        for feature_mode, aliases in sorted(by_feature.items(), key=lambda kv: (_ordered_index(kv[0], FEATURE_ORDER), kv[0])):
            if len(aliases) < 2:
                continue
            for member_aliases in _subset_lists(aliases):
                ptm_tags = [exact_bank[a]["pretrained_model"] for a in member_aliases]
                name_prefix = f"{duration}_ptm_{feature_mode}__{'_'.join(ptm_tags)}"
                _append_weighted_jobs(jobs, "representation_ptm", name_prefix, member_aliases)

        for ptm_name, aliases in sorted(by_ptm.items(), key=lambda kv: (_ordered_index(kv[0], PTM_ORDER), kv[0])):
            if len(aliases) < 2:
                continue
            for member_aliases in _subset_lists(aliases):
                feat_tags = [_short_feature_name(exact_bank[a]["feature_mode"]) for a in member_aliases]
                name_prefix = f"{duration}_hc_{ptm_name}__{'_'.join(feat_tags)}"
                _append_weighted_jobs(jobs, "representation_hc", name_prefix, member_aliases)

    return jobs

def get_test_set_dirs(test_set_name: str, duration: str):
    base_dir = os.path.join(TEST_BASE_DIR, test_set_name)
    ptm_dir = os.path.join(base_dir, "embeddings")
    feature_dir = os.path.join(base_dir, "features")
    if duration and duration != "full_length":
        alt_ptm = os.path.join(base_dir, duration, "embeddings")
        alt_hc = os.path.join(base_dir, duration, "features")
        if os.path.isdir(alt_ptm):
            ptm_dir = alt_ptm
        if os.path.isdir(alt_hc):
            feature_dir = alt_hc
    return ptm_dir, feature_dir

def build_path_embedding_dict(model, mode, ptm_lookup, hc_lookup, paths):
    path_to_emb = {}
    for path in tqdm(sorted(paths), desc="Embedding paths", leave=False):
        ptm_feat = _get_feature_from_lookup(ptm_lookup, path) if mode in [1, 3] else None
        hc_feat = _get_feature_from_lookup(hc_lookup, path) if mode in [2, 3] else None
        if mode in [1, 3] and ptm_feat is None:
            continue
        if mode in [2, 3] and hc_feat is None:
            continue

        inputs = {}
        if mode in [1, 3]:
            inputs["embedding"] = ptm_feat.unsqueeze(0).to(DEVICE).float()
        if mode in [2, 3]:
            inputs["feature"] = hc_feat.unsqueeze(0).to(DEVICE).float()

        _, emb = model(**inputs)
        path_to_emb[path] = F.normalize(emb, p=2, dim=1).squeeze(0).detach().cpu().numpy().astype(np.float32)
    return path_to_emb

def build_pair_score_df(model, mode, ptm_lookup, hc_lookup, trials_df):
    unique_paths = set(trials_df["path1"].tolist() + trials_df["path2"].tolist())
    path_to_emb = build_path_embedding_dict(model, mode, ptm_lookup, hc_lookup, unique_paths)
    if len(path_to_emb) < 2:
        return None

    trial_idx_list, valid_labels, pair_i, pair_j = [], [], [], []
    paths = list(path_to_emb.keys())
    path_to_idx = {p: i for i, p in enumerate(paths)}
    emb_matrix = np.stack([path_to_emb[p] for p in paths], axis=0)

    for _, row in trials_df.iterrows():
        trial_idx = int(row["trial_idx"])
        p1 = row["path1"]
        p2 = row["path2"]
        if p1 not in path_to_idx or p2 not in path_to_idx:
            continue
        trial_idx_list.append(trial_idx)
        valid_labels.append(int(row["label"]))
        pair_i.append(path_to_idx[p1])
        pair_j.append(path_to_idx[p2])

    if len(pair_i) == 0:
        return None

    pair_i = np.asarray(pair_i, dtype=np.int32)
    pair_j = np.asarray(pair_j, dtype=np.int32)
    raw_scores = np.sum(emb_matrix[pair_i] * emb_matrix[pair_j], axis=1).astype(np.float32)
    return pd.DataFrame({
        "trial_idx": np.asarray(trial_idx_list, dtype=np.int64),
        "label": np.asarray(valid_labels, dtype=np.int32),
        "score": raw_scores,
    })

def summarize_scores_from_arrays(labels_np, scores_np):
    eer, _ = compute_eer(labels_np, scores_np)
    mindcf, _ = compute_mindcf(labels_np, scores_np, p_target=P_TARGET)
    return {
        "EER (%)": float(eer * 100.0),
        "MinDCF": float(mindcf),
        "Used Pairs": int(len(scores_np)),
    }

def score_df_to_dense_arrays(score_df, num_trials):
    if score_df is None or len(score_df) == 0:
        return None
    if score_df["trial_idx"].duplicated().any():
        dup_count = int(score_df["trial_idx"].duplicated().sum())
        raise RuntimeError(f"Duplicate trial_idx detected in score_df: {dup_count}")
    score_vec = np.full(num_trials, np.nan, dtype=np.float32)
    label_vec = np.full(num_trials, -1, dtype=np.int32)
    trial_idx = score_df["trial_idx"].to_numpy(dtype=np.int64)
    labels = score_df["label"].to_numpy(dtype=np.int32)
    scores = score_df["score"].to_numpy(dtype=np.float32)
    score_vec[trial_idx] = scores
    label_vec[trial_idx] = labels
    return score_vec, label_vec

LOOKUP_CACHE = {"ptm": {}, "hc": {}}

def clear_lookup_cache():
    LOOKUP_CACHE["ptm"].clear()
    LOOKUP_CACHE["hc"].clear()
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def get_ptm_lookup(test_set_name, duration, ptm_name, ptm_dir):
    key = (test_set_name, duration, ptm_name)
    if key not in LOOKUP_CACHE["ptm"]:
        ptm_path = resolve_ptm_path(ptm_name, ptm_dir)
        LOOKUP_CACHE["ptm"][key] = None if ptm_path is None else build_lookup_from_pt_file(
            torch.load(ptm_path, map_location="cpu"),
            "embeddings",
        )
    return LOOKUP_CACHE["ptm"][key]

def get_hc_lookup(test_set_name, duration, feature_mode, feature_dir):
    key = (test_set_name, duration, feature_mode)
    if key not in LOOKUP_CACHE["hc"]:
        hc_path = resolve_hc_path(feature_mode, feature_dir)
        LOOKUP_CACHE["hc"][key] = None if hc_path is None else build_lookup_from_pt_file(
            torch.load(hc_path, map_location="cpu"),
            "features",
        )
    return LOOKUP_CACHE["hc"][key]

@torch.no_grad()
def score_single_experiment(exp_info, trials_df, test_set_name, ptm_dir, feature_dir):
    model = None
    ckpt = None
    score_df = None
    try:
        mode = exp_info["mode"]
        ptm_name = exp_info["pretrained_model"]
        feature_mode = exp_info["feature_mode"]

        ptm_lookup = get_ptm_lookup(test_set_name, exp_info["duration"], ptm_name, ptm_dir) if mode in [1, 3] else None
        hc_lookup = get_hc_lookup(test_set_name, exp_info["duration"], feature_mode, feature_dir) if mode in [2, 3] else None
        if mode in [1, 3] and ptm_lookup is None:
            return None, None, None
        if mode in [2, 3] and hc_lookup is None:
            return None, None, None

        model = get_model(
            num_speakers=1000,
            device=str(DEVICE),
            mode=mode,
            fusion_method=exp_info["fusion_method"],
            feature_mode=feature_mode,
            use_gating=(exp_info["fusion_method"] == "gating"),
        )
        ckpt = torch.load(exp_info["model_path"], map_location=DEVICE)
        model.load_state_dict(ckpt["model_state_dict"], strict=True)
        model.eval()

        score_df = build_pair_score_df(model, mode, ptm_lookup, hc_lookup, trials_df)
        if score_df is None or len(score_df) == 0:
            return None, None, None

        dense_pack = score_df_to_dense_arrays(score_df, len(trials_df))
        if dense_pack is None:
            return None, None, None
        score_vec, label_vec = dense_pack
        valid_mask = np.isfinite(score_vec)
        metrics = summarize_scores_from_arrays(label_vec[valid_mask], score_vec[valid_mask])
        row = {
            "TestSet": test_set_name,
            "Experiment": exp_info["exp_name"],
            "Kind": "single",
            "Family": "single",
            "Members": exp_info["exp_name"],
            "Weights": "1.0",
            "Mode": mode,
            "Fusion": exp_info["fusion_method"],
            "Feature": feature_mode,
            "PTM": ptm_name,
            "Duration": exp_info["duration"],
            **metrics,
            "Missing Pairs": int(len(trials_df) - int(valid_mask.sum())),
        }
        return row, score_vec, label_vec
    finally:
        del score_df
        del ckpt
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

def score_ensemble_job(job, test_set_name, trials_df, score_cache, exact_bank):
    member_aliases = job["member_aliases"]
    member_exp_names = [exact_bank[alias]["exp_name"] for alias in member_aliases]
    score_vectors = []
    label_reference = None
    for exp_name in member_exp_names:
        cache_item = score_cache.get(exp_name)
        if cache_item is None:
            return None
        score_vec, label_vec = cache_item
        if label_reference is None:
            label_reference = label_vec
        elif not np.array_equal(label_reference, label_vec):
            raise RuntimeError(f"Label mismatch across ensemble members for {job['ensemble_name']}")
        score_vectors.append(score_vec)

    stacked = np.stack(score_vectors, axis=0)
    valid_mask = np.all(np.isfinite(stacked), axis=0)
    used_pairs = int(valid_mask.sum())
    if used_pairs == 0:
        return None

    weights = np.asarray(job["weights"], dtype=np.float32).reshape(-1, 1)
    fused_scores = np.sum(stacked * weights, axis=0)
    labels_used = label_reference[valid_mask]
    scores_used = fused_scores[valid_mask]
    metrics = summarize_scores_from_arrays(labels_used, scores_used)
    resolved_members = [exact_bank[alias]["exp_name"] for alias in member_aliases]
    return {
        "TestSet": test_set_name,
        "Experiment": job["ensemble_name"],
        "Kind": "ensemble",
        "Family": job["family"],
        "Members": " | ".join(member_aliases),
        "ResolvedMembers": " | ".join(resolved_members),
        "Weights": ",".join([f"{w:.4f}" for w in job["weights"]]),
        "Mode": "ensemble",
        "Fusion": "ensemble",
        "Feature": "ensemble",
        "PTM": "ensemble",
        "Duration": "multi",
        **metrics,
        "Missing Pairs": int(len(trials_df) - used_pairs),
    }

all_experiments = discover_experiments(SOURCE_EXPERIMENT_ROOTS)
print(f"Discovered {len(all_experiments)} experiments")

exact_bank, bank_df = build_exact_config_bank(all_experiments)
bank_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_exact_config_bank.csv")
os.makedirs(OUTPUT_DIR, exist_ok=True)
bank_df.to_csv(bank_path, index=False)
print(f"Saved exact config bank: {bank_path}")
display(bank_df)

duration_jobs = expand_duration_jobs(BASE_DURATION_ENSEMBLE_SPECS, exact_bank)
representation_jobs = generate_representation_jobs(exact_bank)
ensemble_jobs = duration_jobs + representation_jobs

plan_rows = []
for job in ensemble_jobs:
    plan_rows.append({
        "ensemble_name": job["ensemble_name"],
        "family": job["family"],
        "members": " | ".join(job["member_aliases"]),
        "weights": ",".join([f"{w:.4f}" for w in job["weights"]]),
    })
plan_df = pd.DataFrame(plan_rows)
plan_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_ensemble_plan.csv")
plan_df.to_csv(plan_path, index=False)
print(f"Saved ensemble plan: {plan_path}")
display(plan_df.head(50))

resolved_members = exact_bank
if len(resolved_members) == 0:
    raise RuntimeError("Không resolve được model nào trong exact config bank.")

all_results = []
for test_cfg in TEST_SET_CONFIGS:
    clear_lookup_cache()
    test_set_name = test_cfg["name"]
    trial_path = os.path.join(LIST_GT_DIR, test_cfg["trial_file"])
    duration = test_cfg.get("duration", "")
    out_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_{test_set_name}.csv")
    print("\n" + "=" * 88)
    print(f"TEST SET: {test_set_name}")
    print("=" * 88)

    if SKIP_EXISTING_TEST_REPORTS and os.path.exists(out_path):
        print(f"[SKIP TEST] Existing report found: {out_path}")
        try:
            existing_df = pd.read_csv(out_path)
            all_results.extend(existing_df.to_dict(orient="records"))
            print(f"Loaded {len(existing_df)} existing rows from {test_set_name}")
        except Exception as ex:
            print(f"⚠ Could not load existing report {out_path}: {ex}")
        continue

    if not os.path.exists(trial_path):
        print(f"⚠ Skip {test_set_name}: missing trial file {trial_path}")
        continue

    ptm_dir, feature_dir = get_test_set_dirs(test_set_name, duration)
    if not os.path.isdir(ptm_dir) or not os.path.isdir(feature_dir):
        print(f"⚠ Skip {test_set_name}: missing feature directories")
        continue

    trials_df = parse_trial_csv(trial_path)
    score_cache = {}
    per_test_rows = []

    for alias, exp_info in tqdm(resolved_members.items(), desc=f"Singles {test_set_name}"):
        try:
            row, score_vec, label_vec = score_single_experiment(exp_info, trials_df, test_set_name, ptm_dir, feature_dir)
            if row is not None and score_vec is not None and label_vec is not None:
                row["BankAlias"] = alias
                per_test_rows.append(row)
                score_cache[exp_info["exp_name"]] = (score_vec, label_vec)
        except Exception as ex:
            print(f"[ERROR][single] {test_set_name} | {alias} | {exp_info['exp_name']}: {ex}")
        finally:
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    for job in tqdm(ensemble_jobs, desc=f"Ensembles {test_set_name}"):
        try:
            row = score_ensemble_job(job, test_set_name, trials_df, score_cache, exact_bank)
            if row is not None:
                per_test_rows.append(row)
        except Exception as ex:
            print(f"[ERROR][ensemble] {test_set_name} | {job['ensemble_name']}: {ex}")

    per_test_df = pd.DataFrame(per_test_rows)
    if len(per_test_df) == 0:
        print(f"⚠ No valid results for {test_set_name}")
        clear_lookup_cache()
        del score_cache
        del per_test_rows
        gc.collect()
        continue

    per_test_df = per_test_df.sort_values(["EER (%)", "MinDCF"], ascending=[True, True]).reset_index(drop=True)
    per_test_df.to_csv(out_path, index=False)
    print(f"✓ Saved: {out_path}")
    display(per_test_df.head(30))
    all_results.extend(per_test_rows)

    clear_lookup_cache()
    del score_cache
    del trials_df
    del per_test_rows
    del per_test_df
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

all_df = pd.DataFrame(all_results)
all_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_all_models.csv")
if len(all_df) > 0:
    all_df = all_df.sort_values(["TestSet", "EER (%)", "MinDCF"], ascending=[True, True, True]).reset_index(drop=True)
    all_df.to_csv(all_path, index=False)
    print(f"✓ Saved total report: {all_path}")
    display(all_df.head(50))
else:
    print("⚠ No valid benchmark or ensemble results.")

## 5. Gating Analysis (Only for Mode 3 + Gating)

In [ ]:
from train import analyze_gating_behavior
import matplotlib.image as mpimg

# Load Best Model
best_model_path = os.path.join(exp_dir, BEST_MODEL_NAME)
model, _, _, _ = load_checkpoint(best_model_path, model)
model = model.to(device)

# Kiểm tra điều kiện để chạy phân tích
if args.mode == 3 and args.fusion_method == "gating":
    print("Đang thực hiện phân tích cơ chế Gating trên tập Test...")
    
    # Gọi hàm phân tích từ train.py
    # Lưu ý: Hàm này trả về 2 giá trị: gates (trọng số PTM) và labels
    gates, labels = analyze_gating_behavior(model, test_loader, device, exp_dir)
    
    # Hiển thị biểu đồ phân phối trọng số đã được lưu
    gate_plot_path = os.path.join(exp_dir, "gating_analysis", "gate_distribution.png")
    if os.path.exists(gate_plot_path):
        plt.figure(figsize=(10, 6))
        img = mpimg.imread(gate_plot_path)
        plt.imshow(img)
        plt.axis('off')
        plt.title("Phân phối trọng số Gating (Trục X > 0.5 ưu tiên PTM, < 0.5 ưu tiên Handcrafted)")
        plt.show()
        
    # In thông tin thống kê tóm tắt
    ptm_wins = np.sum(gates > 0.5)
    hc_wins = np.sum(gates <= 0.5)
    print(f"Thống kê nhanh:")
    print(f"   - Số lần ưu tiên PTM (WavLM/HuBERT): {ptm_wins} ({100*ptm_wins/len(gates):.2f}%)")
    print(f"   - Số lần ưu tiên Handcrafted (MFCC/Pitch): {hc_wins} ({100*hc_wins/len(gates):.2f}%)")
else:
    print("ℹChế độ hiện tại không sử dụng Gating. Bỏ qua bước phân tích này.")

## 6. Experiment Comparison

In [1]:
import pandas as pd
import os
import json

# List all experiments
exp_base_dir = "./outputs/experiments"
if os.path.exists(exp_base_dir):
    experiments = []
    for exp_name_dir in sorted(os.listdir(exp_base_dir)):
        exp_path = os.path.join(exp_base_dir, exp_name_dir)
        results_file = os.path.join(exp_path, "results.json")
        if os.path.exists(results_file):
            with open(results_file, "r") as f:
                data = json.load(f)
                config = data.get("config", {})
                experiments.append({
                    "Experiment": exp_name_dir,
                    "Mode": config.get("mode", ""),
                    "Fusion": config.get("fusion_method", "N/A"),
                    "Feature": config.get("feature_mode", "N/A"),
                    "PTM": config.get("pretrained_model", "N/A"),
                    "Best Val EER": f"{data.get('best_val_eer', 0):.4f}",
                    "Best Val MinDCF": f"{data.get('best_val_mindcf',0):.4f}",
                    "Epochs": data.get("epochs_trained", 0),
                })
    
    if experiments:
        df = pd.DataFrame(experiments)
        print("\n" + "="*120)
        print("EXPERIMENT COMPARISON")
        print("="*120)
        print(df.to_string(index=False))
        print("="*120)
    else:
        print("No experiments found.")
else:
    print(f"Directory {exp_base_dir} does not exist yet.")

========================================================================================================================
EXPERIMENT COMPARISON
========================================================================================================================
                                    Experiment  Mode Fusion    Feature      PTM Best Val EER Best Val MinDCF  Epochs
                    Mode1_PTM_train_raw_hubert     1               N/A   hubert       8.5400          0.4730      12
                  Mode1_PTM_train_raw_wav2vec2     1               N/A wav2vec2       8.9300          0.4927      16
                     Mode1_PTM_train_raw_wavlm     1               N/A    wavlm       8.2700          0.4640      12
                  Mode1_PTM_train_vi_3s_hubert     1               N/A   hubert       6.2000          0.3231      14
                Mode1_PTM_train_vi_3s_wav2vec2     1               N/A wav2vec2       7.0400          0.3538      14
                   Mode1_PTM_train_vi_3s_wavlm     1               N/A    wavlm       6.0200          0.2925      17
                  Mode1_PTM_train_vi_5s_hubert     1               N/A   hubert       5.4000          0.2893      23
                Mode1_PTM_train_vi_5s_wav2vec2     1               N/A wav2vec2       5.4900          0.2958      21
                   Mode1_PTM_train_vi_5s_wavlm     1               N/A    wavlm       4.7900          0.2289      18
                  Mode1_PTM_train_vi_7s_hubert     1               N/A   hubert       5.5700          0.3234      22
                Mode1_PTM_train_vi_7s_wav2vec2     1               N/A wav2vec2       7.3500          0.3430      23
                   Mode1_PTM_train_vi_7s_wavlm     1               N/A    wavlm       6.1800          0.3305      23
                Mode1_PTM_train_vi_full_hubert     1               N/A   hubert      14.3500          0.7172      12
              Mode1_PTM_train_vi_full_wav2vec2     1               N/A wav2vec2      15.5600          0.7468       8
                 Mode1_PTM_train_vi_full_wavlm     1               N/A    wavlm      14.1700          0.7205       8
                  Mode2_HC_train_raw_mfbe_only     2         mfbe_only      N/A       9.3400          0.5193      31
                 Mode2_HC_train_raw_mfbe_pitch     2        mfbe_pitch      N/A      10.5100          0.6184      23
                  Mode2_HC_train_raw_mfcc_only     2         mfcc_only      N/A      10.2600          0.5674      21
                 Mode2_HC_train_raw_mfcc_pitch     2        mfcc_pitch      N/A      10.1300          0.5153      25
                 Mode2_HC_train_raw_pitch_only     2        pitch_only      N/A      30.8700          1.0000      11
                Mode2_HC_train_vi_3s_mfbe_only     2         mfbe_only      N/A       5.0800          0.2591      10
               Mode2_HC_train_vi_3s_mfbe_pitch     2        mfbe_pitch      N/A       4.7200          0.2411      15
                Mode2_HC_train_vi_3s_mfcc_only     2         mfcc_only      N/A       4.3000          0.2167      22
               Mode2_HC_train_vi_3s_mfcc_pitch     2        mfcc_pitch      N/A       4.5200          0.2151      23
               Mode2_HC_train_vi_3s_pitch_only     2        pitch_only      N/A      22.5400          0.9706      16
                Mode2_HC_train_vi_5s_mfbe_only     2         mfbe_only      N/A       3.8900          0.2132      25
               Mode2_HC_train_vi_5s_mfbe_pitch     2        mfbe_pitch      N/A       4.0900          0.2320      23
                Mode2_HC_train_vi_5s_mfcc_only     2         mfcc_only      N/A       4.8400          0.2408      15
               Mode2_HC_train_vi_5s_mfcc_pitch     2        mfcc_pitch      N/A       4.5700          0.2340      13
               Mode2_HC_train_vi_5s_pitch_only     2        pitch_only      N/A      21.3000          1.0000      17
                Mode2_HC_train_vi_7s_mfbe_only     2         mfbe_only      N/A       7.0400          0.4289      15
               Mode2_HC_train_vi_7s_mfbe_pitch     2        mfbe_pitch      N/A       6.9400          0.4158      14
                Mode2_HC_train_vi_7s_mfcc_only     2         mfcc_only      N/A       6.0600          0.3475      14
               Mode2_HC_train_vi_7s_mfcc_pitch     2        mfcc_pitch      N/A       5.7900          0.3540      31
               Mode2_HC_train_vi_7s_pitch_only     2        pitch_only      N/A      27.1100          0.9994      28
              Mode2_HC_train_vi_full_mfbe_only     2         mfbe_only      N/A      17.0500          0.8089      21
             Mode2_HC_train_vi_full_mfbe_pitch     2        mfbe_pitch      N/A      19.6100          0.8130      18
              Mode2_HC_train_vi_full_mfcc_only     2         mfcc_only      N/A      16.8800          0.8007      19
             Mode2_HC_train_vi_full_mfcc_pitch     2        mfcc_pitch      N/A      18.1100          0.8021      22
             Mode2_HC_train_vi_full_pitch_only     2        pitch_only      N/A      30.2000          0.9997      10
       Mode3_concat_train_raw_hubert_mfbe_only     3 concat  mfbe_only   hubert       7.6400          0.3880      11
      Mode3_concat_train_raw_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       8.4100          0.4271      12
       Mode3_concat_train_raw_hubert_mfcc_only     3 concat  mfcc_only   hubert       8.0300          0.4335       8
      Mode3_concat_train_raw_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       7.6100          0.4009      10
      Mode3_concat_train_raw_hubert_pitch_only     3 concat pitch_only   hubert       9.6600          0.4854       8
     Mode3_concat_train_raw_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       7.5600          0.5043       6
    Mode3_concat_train_raw_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       8.4300          0.4727      10
     Mode3_concat_train_raw_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       8.7900          0.5059       7
    Mode3_concat_train_raw_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       8.0800          0.4811       7
    Mode3_concat_train_raw_wav2vec2_pitch_only     3 concat pitch_only wav2vec2      10.4600          0.5140       7
        Mode3_concat_train_raw_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       8.4700          0.4379       8
       Mode3_concat_train_raw_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       7.6300          0.4412       7
        Mode3_concat_train_raw_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       7.9300          0.4547       7
       Mode3_concat_train_raw_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       8.7400          0.4248       9
       Mode3_concat_train_raw_wavlm_pitch_only     3 concat pitch_only    wavlm       9.7800          0.4269       9
     Mode3_concat_train_vi_3s_hubert_mfbe_only     3 concat  mfbe_only   hubert       4.8400          0.2547       9
    Mode3_concat_train_vi_3s_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       5.2100          0.2421      14
     Mode3_concat_train_vi_3s_hubert_mfcc_only     3 concat  mfcc_only   hubert       4.8500          0.2180       6
    Mode3_concat_train_vi_3s_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       5.2200          0.2802       7
    Mode3_concat_train_vi_3s_hubert_pitch_only     3 concat pitch_only   hubert       7.1700          0.3412      10
   Mode3_concat_train_vi_3s_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       8.3000          0.3974       8
  Mode3_concat_train_vi_3s_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       7.8800          0.3734      11
   Mode3_concat_train_vi_3s_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       8.2300          0.3733      12
  Mode3_concat_train_vi_3s_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       8.3200          0.4019       8
  Mode3_concat_train_vi_3s_wav2vec2_pitch_only     3 concat pitch_only wav2vec2       7.6900          0.3778       8
      Mode3_concat_train_vi_3s_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       5.2900          0.2458       8
     Mode3_concat_train_vi_3s_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       5.0100          0.2223      10
      Mode3_concat_train_vi_3s_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       4.6200          0.2120       7
     Mode3_concat_train_vi_3s_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       5.4400          0.2616       9
     Mode3_concat_train_vi_3s_wavlm_pitch_only     3 concat pitch_only    wavlm       7.0500          0.3595       6
     Mode3_concat_train_vi_5s_hubert_mfbe_only     3 concat  mfbe_only   hubert       4.9000          0.2756       6
    Mode3_concat_train_vi_5s_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       4.8200          0.2590       7
     Mode3_concat_train_vi_5s_hubert_mfcc_only     3 concat  mfcc_only   hubert       5.2500          0.2723       7
    Mode3_concat_train_vi_5s_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       5.1600          0.2581       7
    Mode3_concat_train_vi_5s_hubert_pitch_only     3 concat pitch_only   hubert       7.3200          0.3783      10
   Mode3_concat_train_vi_5s_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       4.7400          0.2490       7
  Mode3_concat_train_vi_5s_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       4.5200          0.2515       8
   Mode3_concat_train_vi_5s_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       5.2600          0.2627      11
  Mode3_concat_train_vi_5s_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       5.1700          0.2664       6
  Mode3_concat_train_vi_5s_wav2vec2_pitch_only     3 concat pitch_only wav2vec2       6.5600          0.3048       9
      Mode3_concat_train_vi_5s_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       4.4000          0.2343       6
     Mode3_concat_train_vi_5s_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       4.5900          0.2442       6
      Mode3_concat_train_vi_5s_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       4.4900          0.2656      11
     Mode3_concat_train_vi_5s_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       4.7600          0.2496       8
     Mode3_concat_train_vi_5s_wavlm_pitch_only     3 concat pitch_only    wavlm       6.0900          0.3091       6
     Mode3_concat_train_vi_7s_hubert_mfbe_only     3 concat  mfbe_only   hubert       5.8300          0.3317      18
    Mode3_concat_train_vi_7s_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       4.7200          0.2914      10
     Mode3_concat_train_vi_7s_hubert_mfcc_only     3 concat  mfcc_only   hubert       5.6100          0.3152      12
    Mode3_concat_train_vi_7s_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       5.8700          0.3717       6
    Mode3_concat_train_vi_7s_hubert_pitch_only     3 concat pitch_only   hubert       7.7900          0.3608      10
   Mode3_concat_train_vi_7s_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       6.4900          0.3690       9
  Mode3_concat_train_vi_7s_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       5.8600          0.3574      10
   Mode3_concat_train_vi_7s_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       6.0800          0.3441      10
  Mode3_concat_train_vi_7s_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       4.8800          0.2764      18
  Mode3_concat_train_vi_7s_wav2vec2_pitch_only     3 concat pitch_only wav2vec2       8.5600          0.3684      13
      Mode3_concat_train_vi_7s_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       5.4000          0.3595       7
     Mode3_concat_train_vi_7s_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       5.1300          0.3255      12
      Mode3_concat_train_vi_7s_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       5.6800          0.3400      12
     Mode3_concat_train_vi_7s_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       5.5400          0.2980      12
     Mode3_concat_train_vi_7s_wavlm_pitch_only     3 concat pitch_only    wavlm       8.6300          0.3712      14
   Mode3_concat_train_vi_full_hubert_mfbe_only     3 concat  mfbe_only   hubert      13.7400          0.7044       6
  Mode3_concat_train_vi_full_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert      14.2800          0.7012       7
   Mode3_concat_train_vi_full_hubert_mfcc_only     3 concat  mfcc_only   hubert      13.6700          0.7039       6
  Mode3_concat_train_vi_full_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert      15.2000          0.7573       6
  Mode3_concat_train_vi_full_hubert_pitch_only     3 concat pitch_only   hubert      12.8300          0.6938       6
 Mode3_concat_train_vi_full_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2      15.1600          0.7404       6
Mode3_concat_train_vi_full_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2      15.1600          0.7350       6
 Mode3_concat_train_vi_full_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2      15.4100          0.7327       6
Mode3_concat_train_vi_full_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2      15.5600          0.7426       6
Mode3_concat_train_vi_full_wav2vec2_pitch_only     3 concat pitch_only wav2vec2      13.6900          0.7238       6
    Mode3_concat_train_vi_full_wavlm_mfbe_only     3 concat  mfbe_only    wavlm      15.8500          0.7130       7
   Mode3_concat_train_vi_full_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm      14.8000          0.7250       6
    Mode3_concat_train_vi_full_wavlm_mfcc_only     3 concat  mfcc_only    wavlm      14.8200          0.7214       6
   Mode3_concat_train_vi_full_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm      16.3300          0.7381       6
   Mode3_concat_train_vi_full_wavlm_pitch_only     3 concat pitch_only    wavlm      15.1300          0.7270       7
         Mode3_film_train_raw_hubert_mfbe_only     3   film  mfbe_only   hubert       7.9100          0.4105      10
        Mode3_film_train_raw_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       8.2400          0.4257       8
         Mode3_film_train_raw_hubert_mfcc_only     3   film  mfcc_only   hubert       7.7900          0.4055      12
        Mode3_film_train_raw_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       7.3900          0.4016      14
        Mode3_film_train_raw_hubert_pitch_only     3   film pitch_only   hubert       8.8800          0.4475       9
       Mode3_film_train_raw_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       8.2900          0.4504      10
      Mode3_film_train_raw_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       8.0100          0.4273      12
       Mode3_film_train_raw_wav2vec2_mfcc_only     3   film  mfcc_only wav2vec2       8.0600          0.4309      10
      Mode3_film_train_raw_wav2vec2_mfcc_pitch     3   film mfcc_pitch wav2vec2       7.7300          0.4347      11
      Mode3_film_train_raw_wav2vec2_pitch_only     3   film pitch_only wav2vec2       9.0100          0.4608       9
          Mode3_film_train_raw_wavlm_mfbe_only     3   film  mfbe_only    wavlm       8.0000          0.4469       7
         Mode3_film_train_raw_wavlm_mfbe_pitch     3   film mfbe_pitch    wavlm       7.8300          0.4211      10
          Mode3_film_train_raw_wavlm_mfcc_only     3   film  mfcc_only    wavlm       7.6500          0.4142       8
         Mode3_film_train_raw_wavlm_mfcc_pitch     3   film mfcc_pitch    wavlm       7.3500          0.4253       8
         Mode3_film_train_raw_wavlm_pitch_only     3   film pitch_only    wavlm       9.2800          0.4910       7
       Mode3_film_train_vi_3s_hubert_mfbe_only     3   film  mfbe_only   hubert       4.1000          0.2046      14
      Mode3_film_train_vi_3s_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       4.4500          0.1995      10
       Mode3_film_train_vi_3s_hubert_mfcc_only     3   film  mfcc_only   hubert       4.4000          0.2155       8
      Mode3_film_train_vi_3s_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       4.2000          0.1900       6
      Mode3_film_train_vi_3s_hubert_pitch_only     3   film pitch_only   hubert       6.0200          0.2816      13
     Mode3_film_train_vi_3s_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       6.4900          0.3317      11
    Mode3_film_train_vi_3s_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       6.8000          0.3174      15
     Mode3_film_train_vi_3s_wav2vec2_mfcc_only     3   film  mfcc_only wav2vec2       6.9500          0.3646      10
    Mode3_film_train_vi_3s_wav2vec2_mfcc_pitch     3   film mfcc_pitch wav2vec2       6.7800          0.3418      11
    Mode3_film_train_vi_3s_wav2vec2_pitch_only     3   film pitch_only wav2vec2       6.7500          0.3430      12
        Mode3_film_train_vi_3s_wavlm_mfbe_only     3   film  mfbe_only    wavlm       4.6400          0.2102      17
       Mode3_film_train_vi_3s_wavlm_mfbe_pitch     3   film mfbe_pitch    wavlm       4.6200          0.2233      10
        Mode3_film_train_vi_3s_wavlm_mfcc_only     3   film  mfcc_only    wavlm       4.1900          0.1967      11
       Mode3_film_train_vi_3s_wavlm_mfcc_pitch     3   film mfcc_pitch    wavlm       4.5600          0.2286       9
       Mode3_film_train_vi_3s_wavlm_pitch_only     3   film pitch_only    wavlm       5.8400          0.2657       9
       Mode3_film_train_vi_5s_hubert_mfbe_only     3   film  mfbe_only   hubert       4.2200          0.2233       7
      Mode3_film_train_vi_5s_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       4.2200          0.2167       9
       Mode3_film_train_vi_5s_hubert_mfcc_only     3   film  mfcc_only   hubert       4.5000          0.2457       7
      Mode3_film_train_vi_5s_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       3.9400          0.2070       9
      Mode3_film_train_vi_5s_hubert_pitch_only     3   film pitch_only   hubert       5.7300          0.2890       7
     Mode3_film_train_vi_5s_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       4.0600          0.2048       7
    Mode3_film_train_vi_5s_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       3.9800          0.2097       8
     Mode3_film_train_vi_5s_wav2vec2_mfcc_only     3   film  mfcc_only wav2vec2       4.3300          0.2373       8
    Mode3_film_train_vi_5s_wav2vec2_mfcc_pitch     3   film mfcc_pitch wav2vec2       4.5500          0.2260       9
    Mode3_film_train_vi_5s_wav2vec2_pitch_only     3   film pitch_only wav2vec2       5.7400          0.2849       8
        Mode3_film_train_vi_5s_wavlm_mfbe_only     3   film  mfbe_only    wavlm       4.0200          0.2195       7
       Mode3_film_train_vi_5s_wavlm_mfbe_pitch     3   film mfbe_pitch    wavlm       3.8000          0.1954       8
        Mode3_film_train_vi_5s_wavlm_mfcc_only     3   film  mfcc_only    wavlm       3.9100          0.2153       6
       Mode3_film_train_vi_5s_wavlm_mfcc_pitch     3   film mfcc_pitch    wavlm       4.2100          0.2096       8
       Mode3_film_train_vi_5s_wavlm_pitch_only     3   film pitch_only    wavlm       5.5300          0.2441      10
       Mode3_film_train_vi_7s_hubert_mfbe_only     3   film  mfbe_only   hubert       3.8600          0.2715      14
      Mode3_film_train_vi_7s_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       4.6100          0.3042      12
       Mode3_film_train_vi_7s_hubert_mfcc_only     3   film  mfcc_only   hubert       3.7500          0.2686      13
      Mode3_film_train_vi_7s_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       3.0900          0.2129      23
      Mode3_film_train_vi_7s_hubert_pitch_only     3   film pitch_only   hubert       6.0500          0.3368      11
     Mode3_film_train_vi_7s_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       4.5200          0.3154      12
    Mode3_film_train_vi_7s_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       4.5400          0.3121       8

In [3]:
import gc
import glob
import os

import torch
from train import train

# ==============================
# RUN TRAIN_RAW - MODE 1/2/3 - 7 HC FEATURES
# ==============================

ROOT_DIR = "D:/"
EMBEDDING_PATH = r"F:/train_raw/wav2vec2_shards"
HC_BASE = r"D:/extracted_features/train_raw"

# PTM input mode:
# - "precomputed": dùng PTM shards tại EMBEDDING_PATH
# - "on_the_fly": đọc waveform từ AUDIO_BASE_DIR và trích PTM trong model runtime
PTM_INPUT_MODE = "on_the_fly"
if PTM_INPUT_MODE not in ["precomputed", "on_the_fly"]:
    raise ValueError(f"SV_PTM_INPUT_MODE must be precomputed|on_the_fly, got: {PTM_INPUT_MODE}")

USE_PTM_ON_THE_FLY = PTM_INPUT_MODE == "on_the_fly"
PTM_MODEL_ID = "facebook/wav2vec2-base"
AUDIO_BASE_DIR = r"D:/Speech_Verification/audio/train_raw"
AUDIO_SAMPLE_RATE = 16000
MAX_AUDIO_SECONDS = 4

print(f"PTM input mode: {PTM_INPUT_MODE}")
if USE_PTM_ON_THE_FLY:
    if not AUDIO_BASE_DIR:
        raise ValueError(
            "SV_AUDIO_BASE_DIR is required for on_the_fly mode. "
            "Example: set SV_AUDIO_BASE_DIR to your train_raw audio root."
        )
    print(f"PTM runtime model: {PTM_MODEL_ID}")
    print(f"Audio base dir: {AUDIO_BASE_DIR}")

# Re-shard config mới
PTM_SAMPLES_PER_SHARD = 200

# Gợi ý an toàn RAM/VRAM
MODE1_BATCH_SIZE = 16
MODE2_BATCH_SIZE = 128
MODE3_BATCH_SIZE = 16
MODE2_MAX_FRAMES = 350
MODE3_MAX_FRAMES = 350
MODE2_VAL_BATCH_SIZE = 128
MODE3_VAL_BATCH_SIZE = 16
MODE3_MIXED_PRECISION = True
VALIDATE_EVERY_EPOCHS = 1
# Fast-epoch knobs: giảm mạnh wall-time mỗi epoch cho on_the_fly
MAX_TRAIN_STEPS_PER_EPOCH = 2500
TRAIN_SUBSET_FRACTION = 0.30
MAX_TRAIN_SAMPLES = 0

# DataLoader knobs (điều chỉnh trực tiếp trong notebook, không dùng env)
NUM_WORKERS = 6
WIN_MODE13_MAX_WORKERS = 6
PIN_MEMORY = True
PERSISTENT_WORKERS = True
PREFETCH_FACTOR = 6
NON_BLOCKING_TRANSFER = True

# Chặn sớm trường hợp shard quá lớn gây crash kernel
MAX_SAFE_SHARD_GB = 8

# Nếu shard PTM quá lớn, mặc định KHÔNG chạy Mode 3 để tránh kernel crash.
# Muốn ép chạy: set SV_ALLOW_MODE3_LARGE_SHARD=1 trước khi chạy cell.
ALLOW_MODE3_LARGE_SHARD = False

FEATURE_DIRS_7 = [
    "mfbe_shards",
    "mfcc_shards",
    "pitch_shards",
    "mfbe_pitch_shards",
    "mfcc_pitch_shards",
    "fbank_shards",
    "fbank_pitch_shards",
]
MODE2_FEATURE_DIRS = ["fbank_shards", "fbank_pitch_shards"]
MODE3_FEATURE_DIRS = FEATURE_DIRS_7

FEAT_MODE_MAP = {
    "mfbe_shards": "mfbe_only",
    "mfcc_shards": "mfcc_only",
    "pitch_shards": "pitch_only",
    "mfbe_pitch_shards": "mfbe_pitch",
    "mfcc_pitch_shards": "mfcc_pitch",
    "fbank_shards": "fbank_only",
    "fbank_pitch_shards": "fbank_pitch",
}

EXPERIMENTS_DIRNAME = "experiments_train_raw_w2v2_7hc"

# cross_attention tốn VRAM; chỉ bật khi thực sự cần
RUN_CROSS_ATTENTION = False
FUSION_METHODS_MODE3 = ["gating", "film", "concat"] + (["cross_attention"] if RUN_CROSS_ATTENTION else [])

# Giảm phân mảnh CUDA allocator: cấu hình trực tiếp theo biến notebook, không dùng env var.
PYTORCH_CUDA_ALLOC_CONF = "expandable_segments:True,max_split_size_mb:128"


def _cleanup_after_run():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def _run_train_safe(args, tag):
    try:
        train(args)
    finally:
        _cleanup_after_run()
        print(f"[CLEANUP] Done after {tag}")


def _largest_ptm_shard_gb(shard_dir):
    if not os.path.isdir(shard_dir):
        return 0.0, None
    max_size = 0
    max_name = None
    for fn in os.listdir(shard_dir):
        if not fn.endswith(".pt"):
            continue
        fp = os.path.join(shard_dir, fn)
        sz = os.path.getsize(fp)
        if sz > max_size:
            max_size = sz
            max_name = fn
    return max_size / (1024 ** 3), max_name


def _precheck_embedding_shards_or_raise(shard_dir):
    biggest_gb, biggest_name = _largest_ptm_shard_gb(shard_dir)
    print(f"Largest PTM shard: {biggest_name} | {biggest_gb:.2f} GB")
    if biggest_gb > MAX_SAFE_SHARD_GB:
        print(
            f"[WARN] PTM shard quá lớn ({biggest_gb:.2f} GB > {MAX_SAFE_SHARD_GB:.2f} GB). "
            f"Tiếp tục chạy theo aligned-prefix mode (không chặn bằng RuntimeError)."
        )
    return biggest_gb


def _apply_ptm_runtime_args(args):
    args.use_ptm_on_the_fly = bool(USE_PTM_ON_THE_FLY)
    args.ptm_model_id = PTM_MODEL_ID
    args.audio_base_dir = AUDIO_BASE_DIR
    args.audio_sample_rate = int(AUDIO_SAMPLE_RATE)
    args.max_audio_seconds = float(MAX_AUDIO_SECONDS)
    args.num_workers = int(NUM_WORKERS)
    args.win_mode13_max_workers = int(WIN_MODE13_MAX_WORKERS)
    args.pin_memory = bool(PIN_MEMORY)
    args.persistent_workers = bool(PERSISTENT_WORKERS)
    args.prefetch_factor = int(PREFETCH_FACTOR)
    args.non_blocking_transfer = bool(NON_BLOCKING_TRANSFER)
    args.validate_every = int(VALIDATE_EVERY_EPOCHS)
    args.max_train_steps_per_epoch = int(MAX_TRAIN_STEPS_PER_EPOCH)
    args.train_subset_fraction = float(TRAIN_SUBSET_FRACTION)
    args.max_train_samples = int(MAX_TRAIN_SAMPLES)


def run_train_mode1_mode2_mode3_7hc():
    if USE_PTM_ON_THE_FLY:
        biggest_gb = 0.0
        should_run_mode1 = False
        should_run_mode3 = True
        print("[INFO] on_the_fly mode: skip PTM shard precheck and disable Mode1 in this cell.")
    else:
        biggest_gb = _precheck_embedding_shards_or_raise(EMBEDDING_PATH)
        allow_mode1_with_large_shard = False
        should_run_mode1 = (biggest_gb <= MAX_SAFE_SHARD_GB) or allow_mode1_with_large_shard
        should_run_mode3 = (biggest_gb <= MAX_SAFE_SHARD_GB) or ALLOW_MODE3_LARGE_SHARD

    # --------------------------
    # MODE 1: PTM only (run once)
    # --------------------------
    mode1_exp_name = "Mode1_PTM_train_raw_wav2vec2"
    mode1_ckpt = os.path.join("./outputs", EXPERIMENTS_DIRNAME, mode1_exp_name, "best_model.pth")

    if USE_PTM_ON_THE_FLY:
        print("[SKIP] MODE1 disabled in on_the_fly mode (cell này tập trung Mode3 fusion).")
    elif should_run_mode1 and not os.path.isfile(mode1_ckpt):
        args = get_base_args()
        args.output_dir = "./outputs"
        args.experiments_dirname = EXPERIMENTS_DIRNAME
        args.mode = 1
        args.duration = "train_raw"
        args.pretrained_model = "wav2vec2"
        args.embedding_path = EMBEDDING_PATH
        args.feature_path = ""
        args.feature_mode = "mfcc_pitch"
        args.batch_size = MODE1_BATCH_SIZE
        args.max_frames = MODE2_MAX_FRAMES
        args.val_batch_size = MODE2_VAL_BATCH_SIZE
        args.skip_model_summary = True
        args.num_epochs = 50
        args.early_stop_patience = 7
        args.lr_scheduler = "plateau"
        args.lr_scheduler_patience = 3
        args.use_augment = True
        args.exp_name = mode1_exp_name
        _apply_ptm_runtime_args(args)

        print("\n" + "=" * 80)
        print(f"RUN MODE1: {args.exp_name}")
        print("=" * 80)
        _run_train_safe(args, args.exp_name)
    elif not should_run_mode1:
        print("[SKIP] MODE1 vì PTM shard quá lớn, tránh crash kernel.")
    else:
        print(f"[SKIP] MODE1 checkpoint already exists: {mode1_ckpt}")

    # --------------------------
    # MODE 2: chỉ chạy fbank + fbank_pitch
    # --------------------------
    for feat_dir in MODE2_FEATURE_DIRS:
        feature_path = os.path.join(HC_BASE, feat_dir)
        feat_mode = FEAT_MODE_MAP[feat_dir]

        if not os.path.isdir(feature_path):
            print(f"[SKIP] Missing feature shard dir: {feature_path}")
            continue

        mode2_exp_name = f"Mode2_HC_train_raw_{feat_mode}"
        mode2_ckpt = os.path.join("./outputs", EXPERIMENTS_DIRNAME, mode2_exp_name, "best_model.pth")

        if not os.path.isfile(mode2_ckpt):
            args = get_base_args()
            args.output_dir = "./outputs"
            args.experiments_dirname = EXPERIMENTS_DIRNAME
            args.mode = 2
            args.duration = "train_raw"
            args.pretrained_model = "wav2vec2"
            args.embedding_path = EMBEDDING_PATH
            args.feature_path = feature_path
            args.feature_mode = feat_mode
            args.batch_size = MODE2_BATCH_SIZE
            args.max_frames = MODE2_MAX_FRAMES
            args.val_batch_size = MODE2_VAL_BATCH_SIZE
            args.skip_model_summary = True
            args.num_epochs = 50
            args.early_stop_patience = 7
            args.lr_scheduler = "plateau"
            args.lr_scheduler_patience = 3
            args.fusion_method = "concat"
            args.use_gating = False
            args.use_augment = True
            args.exp_name = mode2_exp_name
            _apply_ptm_runtime_args(args)

            print("\n" + "=" * 80)
            print(f"RUN MODE2: {args.exp_name}")
            print("=" * 80)
            _run_train_safe(args, args.exp_name)
        else:
            print(f"[SKIP] MODE2 checkpoint already exists: {mode2_ckpt}")

    # --------------------------
    # MODE 3: vẫn chạy đủ 7 HC features
    # --------------------------
    if not should_run_mode3:
        print(
            "[SKIP] MODE3 vì PTM shard đang quá lớn so với ngưỡng an toàn. "
            "Để ép chạy (có rủi ro crash), set SV_ALLOW_MODE3_LARGE_SHARD=1."
        )
    else:
        for feat_dir in MODE3_FEATURE_DIRS:
            feature_path = os.path.join(HC_BASE, feat_dir)
            feat_mode = FEAT_MODE_MAP[feat_dir]

            if not os.path.isdir(feature_path):
                print(f"[SKIP] Missing feature shard dir: {feature_path}")
                continue

            for fusion in FUSION_METHODS_MODE3:
                mode3_exp_name = f"Mode3_{fusion}_train_raw_wav2vec2_{feat_mode}"
                mode3_ckpt = os.path.join("./outputs", EXPERIMENTS_DIRNAME, mode3_exp_name, "best_model.pth")

                if os.path.isfile(mode3_ckpt):
                    print(f"[SKIP] MODE3 checkpoint already exists: {mode3_ckpt}")
                    continue

                args = get_base_args()
                args.output_dir = "./outputs"
                args.experiments_dirname = EXPERIMENTS_DIRNAME
                args.mode = 3
                args.duration = "train_raw"
                args.pretrained_model = "wav2vec2"
                args.embedding_path = "" if USE_PTM_ON_THE_FLY else EMBEDDING_PATH
                args.feature_path = feature_path
                args.feature_mode = feat_mode
                args.fusion_method = fusion
                args.use_gating = (fusion == "gating")
                args.branch_dropout_prob = 0.05
                args.batch_size = MODE3_BATCH_SIZE
                args.max_frames = MODE3_MAX_FRAMES
                args.val_batch_size = MODE3_VAL_BATCH_SIZE
                args.learning_rate = 5e-5
                args.mixed_precision = bool(MODE3_MIXED_PRECISION)
                args.skip_model_summary = True
                args.num_epochs = 50
                args.early_stop_patience = 7
                args.lr_scheduler = "plateau"
                args.lr_scheduler_patience = 3
                args.use_augment = True
                args.use_two_stage_ft = False
                args.stage1_epochs = 6
                args.stage2_ptm_lr_scale = 0.35
                args.freeze_ptm_extractor = True
                args.train_mode3_ptm_layer_fusion = True
                args.use_mode3_warmstart = False
                args.use_mode3_init_mode1 = False
                args.use_mode3_init_mode2 = False
                # Train Mode3 from scratch (no warm-start for early-fusion setup)
                args.init_mode1_ckpt = None
                args.init_mode2_ckpt = None
                args.exp_name = mode3_exp_name
                _apply_ptm_runtime_args(args)

                print("\n" + "=" * 80)
                print(f"RUN MODE3: {args.exp_name}")
                print("=" * 80)
                _run_train_safe(args, args.exp_name)


run_train_mode1_mode2_mode3_7hc()

PTM input mode: on_the_fly
PTM runtime model: facebook/wav2vec2-base
Audio base dir: D:/Speech_Verification/audio/train_raw
[INFO] on_the_fly mode: skip PTM shard precheck and disable Mode1 in this cell.
[SKIP] MODE1 disabled in on_the_fly mode (cell này tập trung Mode3 fusion).
[SKIP] MODE2 checkpoint already exists: ./outputs\experiments_train_raw_w2v2_7hc\Mode2_HC_train_raw_fbank_only\best_model.pth
[SKIP] MODE2 checkpoint already exists: ./outputs\experiments_train_raw_w2v2_7hc\Mode2_HC_train_raw_fbank_pitch\best_model.pth

================================================================================
RUN MODE3: Mode3_gating_train_raw_wav2vec2_mfbe_only
================================================================================
TensorBoard logs will be saved to: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_gating_train_raw_wav2vec2_mfbe_only\tensorboard_logs

================================================================================
SPEAKER VERIFICATION TRAINING - CONFIGURATION
================================================================================
Experiment Name                Mode3_gating_train_raw_wav2vec2_mfbe_only
Device                         cuda
Mode                           3 (1=PTM, 2=Handcrafted, 3=Fusion)
Fusion Method                  gating
Feature Mode                   mfbe_only
PTM Input Source               on-the-fly
Use Gating                     True
Use Augment                    True
PTM On-the-fly                 True
PTM Runtime Model              facebook/wav2vec2-base
Audio Base Dir                 D:/Speech_Verification/audio/train_raw
Audio Sample Rate              16000

Learning Rate                  5e-05
Optimizer                      ADAM
Batch Size                     16
Epochs                         50
Weight Decay                   0.001
Mixed Precision                True

Early Stop Patience            7
LR Scheduler                   plateau
AAM Margin                     0.25
AAM Scale                      30
Branch Dropout (Mode3)         0.05
Use 2-Stage FT (Mode3)         False
Stage1 Epochs                  6
Stage2 PTM LR Scale            0.35
Mode3 Warm-start               False
Mode3 PTM Residual Alpha       0.0
Freeze PTM Extractor           True
Train PTM Layer Fusion         True

Experiment Dir                 ./outputs\experiments_train_raw_w2v2_7hc\Mode3_gating_train_raw_wav2vec2_mfbe_only
================================================================================

Spk-Balanced Sampler           False
Hard Negative Mining           False
Hard Neg Weight/TopK           0.03 / 8
Augment Prob                   0.3
Feature Noise Std              0.003
Embedding Noise Std            0.002
Validation Batch Size          16
Num Workers                    6
Pin Memory                     True
Persistent Workers             True
Prefetch Factor                6
Validate Every (epochs)        1
Max Train Steps/Epoch          2500
Train Subset Fraction          0.300
Max Train Samples              All
Val Max Pos Pairs              5000
Loading Train/Val data...
ℹ Mode3 join mode: filename-based (aligned fast-path disabled).
🔍 Đang nạp metadata Handcrafted từ: D:/extracted_features/train_raw\mfbe_shards...
✅ Đã nạp xong metadata 26 HC shards. Tổng số sample HC: 258168
📦 PTM input source: on-the-fly audio
✅ Mode3 on-the-fly: dùng HC metadata làm sample index (258168 samples), bỏ qua PTM precomputed shards.

🎤 CHIA DỮ LIỆU THEO OPEN-SET (Unseen Speakers):
   - Tập Train: 2023 speakers (231657 samples)
   - Tập Val:   357 speakers (26511 samples)

[FAST-EPOCH] Train subset fraction applied: 0.300 -> 69497 train samples
✓ Loaded 2023 speakers
  Train: 69497, Val: 26511

Creating model...

c:\Users\Dung\anaconda3\Lib\site-packages\transformers\configuration_utils.py:334: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.05
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 2023
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

ℹ Mode3 warm-start disabled by args.use_mode3_warmstart=False

Generating model summary...
✓ Model summary saved to ./outputs\experiments_train_raw_w2v2_7hc\Mode3_gating_train_raw_wav2vec2_mfbe_only\model_summary.txt

[Trainable Params by Group]
  - PTM Extractor     : 0
  - PTM Layer Fusion  : 3,841
  - HC Encoder        : 891,904
  - Temporal Fusion   : 1,771,008
  - Speaker Backbone  : 9,723,456

c:\Users\Dung\anaconda3\Lib\site-packages\torch\profiler\profiler.py:217: UserWarning: Warning: Profiler clears events at the end of each cycle.Only events from the current cycle will be reported.To keep events across cycles, set acc_events=True.
  _warn_once(

[PROFILE] Estimated GFLOPs/sample (actual batch profiler): 34.6817
Đang chuẩn bị fixed validation trials...
✓ Đã nạp fixed validation trials: ./outputs\fixed_val_trials\val_trials_train_raw_26511s_357spk_3cf0118b3732.json
✓ Đã đồng bộ trial protocol csv: ./outputs\fixed_val_trials\val_trials_train_raw_26511s_357spk_3cf0118b3732.csv
  Positive pairs: 5000 | Negative pairs: 5000
Starting training...

Epoch   1 | Train Loss: 8.8790, Acc: 0.2429 | EER: 14.90%, MinDCF: 0.7490 | LR: 0.000050 | TrainTime: 4632.08s, ValTime: 3461.12s, EpochTime: 8093.19s

Epoch   2 | Train Loss: 6.1482, Acc: 0.3694 | EER: 13.40%, MinDCF: 0.6708 | LR: 0.000050 | TrainTime: 4562.86s, ValTime: 3057.94s, EpochTime: 7620.80s

Epoch   3 | Train Loss: 4.9211, Acc: 0.4472 | EER: 13.44%, MinDCF: 0.5952 | LR: 0.000050 | TrainTime: 5239.19s, ValTime: 3454.17s, EpochTime: 8693.35s
EarlyStopping counter: 1/7

Epoch   4 | Train Loss: 4.1750, Acc: 0.5040 | EER: 11.74%, MinDCF: 0.5572 | LR: 0.000050 | TrainTime: 5081.56s, ValTime: 3349.74s, EpochTime: 8431.29s

Epoch   5 | Train Loss: 3.5761, Acc: 0.5536 | EER: 12.04%, MinDCF: 0.5616 | LR: 0.000050 | TrainTime: 4986.23s, ValTime: 2273.27s, EpochTime: 7259.50s
EarlyStopping counter: 1/7

Epoch   6 | Train Loss: 3.1858, Acc: 0.5862 | EER: 10.44%, MinDCF: 0.5084 | LR: 0.000050 | TrainTime: 4540.42s, ValTime: 2978.87s, EpochTime: 7519.28s

Epoch   7 | Train Loss: 2.8479, Acc: 0.6178 | EER: 9.86%, MinDCF: 0.4702 | LR: 0.000050 | TrainTime: 4519.87s, ValTime: 2975.19s, EpochTime: 7495.05s

Epoch   8 | Train Loss: 2.5616, Acc: 0.6444 | EER: 10.44%, MinDCF: 0.4854 | LR: 0.000050 | TrainTime: 4507.66s, ValTime: 2973.80s, EpochTime: 7481.46s
EarlyStopping counter: 1/7

Epoch   9 | Train Loss: 2.3387, Acc: 0.6684 | EER: 10.24%, MinDCF: 0.4822 | LR: 0.000050 | TrainTime: 4379.58s, ValTime: 2143.81s, EpochTime: 6523.39s
EarlyStopping counter: 2/7

Epoch  10 | Train Loss: 2.1329, Acc: 0.6904 | EER: 10.18%, MinDCF: 0.4462 | LR: 0.000050 | TrainTime: 3209.90s, ValTime: 2126.46s, EpochTime: 5336.37s
EarlyStopping counter: 3/7

Epoch  11 | Train Loss: 1.9507, Acc: 0.7113 | EER: 9.84%, MinDCF: 0.4732 | LR: 0.000050 | TrainTime: 3184.44s, ValTime: 2531.55s, EpochTime: 5715.98s

Epoch  12 | Train Loss: 1.8117, Acc: 0.7266 | EER: 10.78%, MinDCF: 0.5022 | LR: 0.000050 | TrainTime: 5071.73s, ValTime: 3187.93s, EpochTime: 8259.66s
EarlyStopping counter: 1/7

Epoch  13 | Train Loss: 1.6648, Acc: 0.7442 | EER: 10.78%, MinDCF: 0.5028 | LR: 0.000050 | TrainTime: 4740.38s, ValTime: 2763.48s, EpochTime: 7503.86s
EarlyStopping counter: 2/7

Epoch  14 | Train Loss: 1.5559, Acc: 0.7593 | EER: 10.30%, MinDCF: 0.5020 | LR: 0.000050 | TrainTime: 3238.01s, ValTime: 2138.70s, EpochTime: 5376.71s
EarlyStopping counter: 3/7

Epoch  15 | Train Loss: 1.4527, Acc: 0.7734 | EER: 8.64%, MinDCF: 0.4366 | LR: 0.000050 | TrainTime: 3229.78s, ValTime: 2144.01s, EpochTime: 5373.79s

Epoch  16 | Train Loss: 1.3526, Acc: 0.7873 | EER: 9.18%, MinDCF: 0.5002 | LR: 0.000050 | TrainTime: 3210.22s, ValTime: 2153.69s, EpochTime: 5363.91s
EarlyStopping counter: 1/7

Epoch  17 | Train Loss: 1.2579, Acc: 0.8010 | EER: 9.54%, MinDCF: 0.4526 | LR: 0.000050 | TrainTime: 3223.86s, ValTime: 2609.80s, EpochTime: 5833.65s
EarlyStopping counter: 2/7

Epoch  18 | Train Loss: 1.1742, Acc: 0.8110 | EER: 9.24%, MinDCF: 0.4490 | LR: 0.000050 | TrainTime: 4556.70s, ValTime: 2987.73s, EpochTime: 7544.43s
EarlyStopping counter: 3/7

Epoch  19 | Train Loss: 1.1066, Acc: 0.8219 | EER: 11.02%, MinDCF: 0.4980 | LR: 0.000025 | TrainTime: 4473.63s, ValTime: 2948.69s, EpochTime: 7422.32s
EarlyStopping counter: 4/7

Epoch  20 | Train Loss: 0.9067, Acc: 0.8581 | EER: 9.98%, MinDCF: 0.4632 | LR: 0.000025 | TrainTime: 4457.70s, ValTime: 2953.93s, EpochTime: 7411.63s
EarlyStopping counter: 5/7

Epoch  21 | Train Loss: 0.8381, Acc: 0.8722 | EER: 9.72%, MinDCF: 0.4612 | LR: 0.000025 | TrainTime: 4929.86s, ValTime: 3416.99s, EpochTime: 8346.84s
EarlyStopping counter: 6/7

Epoch  22 | Train Loss: 0.7699, Acc: 0.8817 | EER: 9.96%, MinDCF: 0.4402 | LR: 0.000025 | TrainTime: 5181.67s, ValTime: 3416.98s, EpochTime: 8598.65s
EarlyStopping counter: 7/7

✓ Early stopping triggered!

Analyzing gating weights...

[CLEANUP] Done after Mode3_gating_train_raw_wav2vec2_mfbe_only

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (26511,) + inhomogeneous part.

In [1]:
# Single run standalone: Mode3_film_train_raw_wav2vec2_mfcc_pitch
import argparse
import gc
import os

import torch
from train import train

# ==============================
# STANDALONE CONFIG
# ==============================
ROOT_DIR = "D:/"
EMBEDDING_PATH = r"F:/train_raw/wav2vec2_shards"
HC_BASE = r"D:/extracted_features/train_raw"

PTM_INPUT_MODE = "on_the_fly"  # "precomputed" | "on_the_fly"
PTM_MODEL_ID = "facebook/wav2vec2-base"
AUDIO_BASE_DIR = r"D:/Speech_Verification/audio/train_raw"
AUDIO_SAMPLE_RATE = 16000
MAX_AUDIO_SECONDS = 4

EXPERIMENTS_DIRNAME = "experiments_train_raw_w2v2_7hc"

MODE3_BATCH_SIZE = 16
MODE3_MAX_FRAMES = 350
MODE3_VAL_BATCH_SIZE = 16
MODE3_MIXED_PRECISION = True

# DataLoader / speed knobs
NUM_WORKERS = 6
WIN_MODE13_MAX_WORKERS = 6
PIN_MEMORY = True
PERSISTENT_WORKERS = True
PREFETCH_FACTOR = 6
NON_BLOCKING_TRANSFER = True

# Train speed knobs
VALIDATE_EVERY_EPOCHS = 1
MAX_TRAIN_STEPS_PER_EPOCH = 2500
TRAIN_SUBSET_FRACTION = 0.30
MAX_TRAIN_SAMPLES = 0

# Fast validation knobs
FAST_VAL = True
FAST_VAL_EVERY = 2               # validate every 2 epochs
FAST_VAL_MAX_POS_PAIRS = 2500    # fewer validation pairs

USE_PTM_ON_THE_FLY = PTM_INPUT_MODE == "on_the_fly"
if PTM_INPUT_MODE not in ["precomputed", "on_the_fly"]:
    raise ValueError(f"PTM_INPUT_MODE must be precomputed|on_the_fly, got: {PTM_INPUT_MODE}")

if USE_PTM_ON_THE_FLY and not AUDIO_BASE_DIR:
    raise ValueError("AUDIO_BASE_DIR is required when PTM_INPUT_MODE='on_the_fly'.")

print(f"PTM input mode: {PTM_INPUT_MODE}")
if USE_PTM_ON_THE_FLY:
    print(f"PTM runtime model: {PTM_MODEL_ID}")
    print(f"Audio base dir: {AUDIO_BASE_DIR}")

FEAT_MODE_MAP = {
    "mfbe_shards": "mfbe_only",
    "mfcc_shards": "mfcc_only",
    "pitch_shards": "pitch_only",
    "mfbe_pitch_shards": "mfbe_pitch",
    "mfcc_pitch_shards": "mfcc_pitch",
    "fbank_shards": "fbank_only",
    "fbank_pitch_shards": "fbank_pitch",
}

def get_base_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output_dir", type=str, default="./outputs")
    parser.add_argument("--experiments_dirname", type=str, default="experiments_new")
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--learning_rate", type=float, default=1e-4)
    parser.add_argument("--lr_scheduler", type=str, default="plateau")
    parser.add_argument("--num_epochs", type=int, default=60)
    parser.add_argument("--optimizer", type=str, default="adam")
    parser.add_argument("--weight_decay", type=float, default=1e-3)
    parser.add_argument("--aam_margin", type=float, default=0.25)
    parser.add_argument("--aam_scale", type=float, default=30)
    parser.add_argument("--embedding_dim", type=int, default=512)
    parser.add_argument("--mixed_precision", type=bool, default=True)
    parser.add_argument("--early_stop_patience", type=int, default=12)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--augment_prob", type=float, default=0.30)
    parser.add_argument("--feature_noise_std", type=float, default=0.003)
    parser.add_argument("--embedding_noise_std", type=float, default=0.002)
    parser.add_argument("--max_frames", type=int, default=350)

    parser.add_argument("--mode", type=int, default=3)
    parser.add_argument("--exp_name", type=str, default="")
    parser.add_argument("--embedding_path", type=str, default="")
    parser.add_argument("--feature_path", type=str, default="")
    parser.add_argument("--feature_mode", type=str, default="")
    parser.add_argument("--fusion_method", type=str, default="")
    parser.add_argument("--use_gating", type=bool, default=False)
    parser.add_argument("--use_augment", type=bool, default=True)
    parser.add_argument("--branch_dropout_prob", type=float, default=0.0)

    parser.add_argument("--use_two_stage_ft", type=bool, default=True)
    parser.add_argument("--stage1_epochs", type=int, default=6)
    parser.add_argument("--stage2_ptm_lr_scale", type=float, default=0.35)

    parser.add_argument("--duration", type=str, default="")
    parser.add_argument("--pretrained_model", type=str, default="")
    parser.add_argument("--init_mode1_ckpt", type=str, default=None)
    parser.add_argument("--init_mode2_ckpt", type=str, default=None)
    parser.add_argument("--use_ptm_on_the_fly", type=bool, default=False)
    parser.add_argument("--ptm_model_id", type=str, default="facebook/wav2vec2-base")
    parser.add_argument("--audio_base_dir", type=str, default="")
    parser.add_argument("--audio_sample_rate", type=int, default=16000)
    parser.add_argument("--max_audio_seconds", type=float, default=8.0)

    args, _ = parser.parse_known_args([])
    return args

def _cleanup_after_run():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def _run_train_safe(args, tag):
    try:
        train(args)
    finally:
        _cleanup_after_run()
        print(f"[CLEANUP] Done after {tag}")

def _apply_ptm_runtime_args(args):
    args.use_ptm_on_the_fly = bool(USE_PTM_ON_THE_FLY)
    args.ptm_model_id = PTM_MODEL_ID
    args.audio_base_dir = AUDIO_BASE_DIR
    args.audio_sample_rate = int(AUDIO_SAMPLE_RATE)
    args.max_audio_seconds = float(MAX_AUDIO_SECONDS)
    args.num_workers = int(NUM_WORKERS)
    args.win_mode13_max_workers = int(WIN_MODE13_MAX_WORKERS)
    args.pin_memory = bool(PIN_MEMORY)
    args.persistent_workers = bool(PERSISTENT_WORKERS)
    args.prefetch_factor = int(PREFETCH_FACTOR)
    args.non_blocking_transfer = bool(NON_BLOCKING_TRANSFER)
    args.validate_every = int(VALIDATE_EVERY_EPOCHS)
    args.max_train_steps_per_epoch = int(MAX_TRAIN_STEPS_PER_EPOCH)
    args.train_subset_fraction = float(TRAIN_SUBSET_FRACTION)
    args.max_train_samples = int(MAX_TRAIN_SAMPLES)

feat_dir = "fbank_pitch_shards"
fusion = "cross_attention"
feature_path = os.path.join(HC_BASE, feat_dir)
feat_mode = FEAT_MODE_MAP[feat_dir]
mode3_exp_name = f"Mode3_{fusion}_train_raw_wav2vec2_{feat_mode}"
mode3_ckpt = os.path.join("./outputs", EXPERIMENTS_DIRNAME, mode3_exp_name, "best_model.pth")

if not os.path.isdir(feature_path):
    print(f"[SKIP] Missing feature shard dir: {feature_path}")
elif os.path.isfile(mode3_ckpt):
    print(f"[SKIP] MODE3 checkpoint already exists: {mode3_ckpt}")
else:
    args = get_base_args()
    args.output_dir = "./outputs"
    args.experiments_dirname = EXPERIMENTS_DIRNAME
    args.mode = 3
    args.duration = "train_raw"
    args.pretrained_model = "wav2vec2"
    args.embedding_path = "" if USE_PTM_ON_THE_FLY else EMBEDDING_PATH
    args.feature_path = feature_path
    args.feature_mode = feat_mode
    args.fusion_method = fusion
    args.use_gating = False
    args.branch_dropout_prob = 0.05
    args.batch_size = MODE3_BATCH_SIZE
    args.max_frames = MODE3_MAX_FRAMES
    args.val_batch_size = MODE3_VAL_BATCH_SIZE
    args.learning_rate = 5e-5
    args.mixed_precision = bool(MODE3_MIXED_PRECISION)
    args.skip_model_summary = True
    args.num_epochs = 50
    args.early_stop_patience = 7
    args.lr_scheduler = "plateau"
    args.lr_scheduler_patience = 3
    args.use_augment = True
    args.use_two_stage_ft = False
    args.stage1_epochs = 6
    args.stage2_ptm_lr_scale = 0.35
    args.freeze_ptm_extractor = True
    args.train_mode3_ptm_layer_fusion = True
    args.use_mode3_warmstart = False
    args.use_mode3_init_mode1 = False
    args.use_mode3_init_mode2 = False
    args.init_mode1_ckpt = None
    args.init_mode2_ckpt = None
    args.exp_name = mode3_exp_name

    if FAST_VAL:
        args.validate_every = int(FAST_VAL_EVERY)
        args.val_max_pos_pairs = int(FAST_VAL_MAX_POS_PAIRS)
        args.val_batch_size = max(int(args.val_batch_size), 16)

    _apply_ptm_runtime_args(args)

    print("\n" + "=" * 80)
    print(f"RUN MODE3 SINGLE: {args.exp_name}")
    if FAST_VAL:
        print(f"FAST_VAL enabled | validate_every={args.validate_every} | val_max_pos_pairs={args.val_max_pos_pairs}")
    print("=" * 80)
    _run_train_safe(args, args.exp_name)

PTM input mode: on_the_fly
PTM runtime model: facebook/wav2vec2-base
Audio base dir: D:/Speech_Verification/audio/train_raw

================================================================================
RUN MODE3 SINGLE: Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch
FAST_VAL enabled | validate_every=1 | val_max_pos_pairs=2500
================================================================================
TensorBoard logs will be saved to: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\tensorboard_logs

================================================================================
SPEAKER VERIFICATION TRAINING - CONFIGURATION
================================================================================
Experiment Name                Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch
Device                         cuda
Mode                           3 (1=PTM, 2=Handcrafted, 3=Fusion)
Fusion Method                  cross_attention
Feature Mode                   fbank_pitch
PTM Input Source               on-the-fly
Use Gating                     False
Use Augment                    True
PTM On-the-fly                 True
PTM Runtime Model              facebook/wav2vec2-base
Audio Base Dir                 D:/Speech_Verification/audio/train_raw
Audio Sample Rate              16000

Learning Rate                  5e-05
Optimizer                      ADAM
Batch Size                     16
Epochs                         50
Weight Decay                   0.001
Mixed Precision                True

Early Stop Patience            7
LR Scheduler                   plateau
AAM Margin                     0.25
AAM Scale                      30
Branch Dropout (Mode3)         0.05
Use 2-Stage FT (Mode3)         False
Stage1 Epochs                  6
Stage2 PTM LR Scale            0.35
Mode3 Warm-start               False
Mode3 PTM Residual Alpha       0.0
Freeze PTM Extractor           True
Train PTM Layer Fusion         True

Experiment Dir                 ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch
================================================================================

Spk-Balanced Sampler           False
Hard Negative Mining           False
Hard Neg Weight/TopK           0.03 / 8
Augment Prob                   0.3
Feature Noise Std              0.003
Embedding Noise Std            0.002
Validation Batch Size          16
Num Workers                    6
Pin Memory                     True
Persistent Workers             True
Prefetch Factor                6
Validate Every (epochs)        1
Max Train Steps/Epoch          2500
Train Subset Fraction          0.300
Max Train Samples              All
Val Max Pos Pairs              2500
Loading Train/Val data...
ℹ Mode3 join mode: filename-based (aligned fast-path disabled).
🔍 Đang nạp metadata Handcrafted từ: D:/extracted_features/train_raw\fbank_pitch_shards...
✅ Đã nạp xong metadata 26 HC shards. Tổng số sample HC: 258168
📦 PTM input source: on-the-fly audio
✅ Mode3 on-the-fly: dùng HC metadata làm sample index (258168 samples), bỏ qua PTM precomputed shards.

🎤 CHIA DỮ LIỆU THEO OPEN-SET (Unseen Speakers):
   - Tập Train: 2023 speakers (231657 samples)
   - Tập Val:   357 speakers (26511 samples)

[FAST-EPOCH] Train subset fraction applied: 0.300 -> 69497 train samples
✓ Loaded 2023 speakers
  Train: 69497, Val: 26511

Creating model...

c:\Users\Dung\anaconda3\Lib\site-packages\transformers\configuration_utils.py:334: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.05
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 2023
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

ℹ Mode3 warm-start disabled by args.use_mode3_warmstart=False

Generating model summary...
✓ Model summary saved to ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\model_summary.txt

[Trainable Params by Group]
  - PTM Extractor     : 0
  - PTM Layer Fusion  : 3,841
  - HC Encoder        : 893,184
  - Temporal Fusion   : 2,363,904
  - Speaker Backbone  : 9,723,456

c:\Users\Dung\anaconda3\Lib\site-packages\torch\profiler\profiler.py:217: UserWarning: Warning: Profiler clears events at the end of each cycle.Only events from the current cycle will be reported.To keep events across cycles, set acc_events=True.
  _warn_once(

[PROFILE] Estimated GFLOPs/sample (actual batch profiler): 35.0987
Đang chuẩn bị fixed validation trials...
✓ Đã nạp fixed validation trials: ./outputs\fixed_val_trials\val_trials_train_raw_26511s_357spk_3cf0118b3732.json
✓ Đã đồng bộ trial protocol csv: ./outputs\fixed_val_trials\val_trials_train_raw_26511s_357spk_3cf0118b3732.csv
  Positive pairs: 2500 | Negative pairs: 2500
Starting training...

Epoch   1 | Train Loss: 8.8271, Acc: 0.2482 | EER: 15.48%, MinDCF: 0.6972 | LR: 0.000050 | TrainTime: 4696.20s, ValTime: 3065.89s, EpochTime: 7762.09s

Epoch   2 | Train Loss: 6.2403, Acc: 0.3669 | EER: 15.88%, MinDCF: 0.6284 | LR: 0.000050 | TrainTime: 4622.28s, ValTime: 3036.85s, EpochTime: 7659.13s
EarlyStopping counter: 1/7

Epoch   3 | Train Loss: 5.0648, Acc: 0.4456 | EER: 14.44%, MinDCF: 0.6036 | LR: 0.000050 | TrainTime: 4622.23s, ValTime: 3038.01s, EpochTime: 7660.24s

Epoch   4 | Train Loss: 4.3167, Acc: 0.5002 | EER: 11.08%, MinDCF: 0.5588 | LR: 0.000050 | TrainTime: 4544.46s, ValTime: 2974.80s, EpochTime: 7519.26s

Epoch   5 | Train Loss: 3.8180, Acc: 0.5393 | EER: 11.16%, MinDCF: 0.5680 | LR: 0.000050 | TrainTime: 4487.19s, ValTime: 3023.83s, EpochTime: 7511.02s
EarlyStopping counter: 1/7

Epoch   6 | Train Loss: 3.3942, Acc: 0.5779 | EER: 10.56%, MinDCF: 0.5220 | LR: 0.000050 | TrainTime: 5199.16s, ValTime: 3419.61s, EpochTime: 8618.77s

Epoch   7 | Train Loss: 3.0452, Acc: 0.6065 | EER: 11.60%, MinDCF: 0.5404 | LR: 0.000050 | TrainTime: 5185.36s, ValTime: 3421.27s, EpochTime: 8606.63s
EarlyStopping counter: 1/7

Epoch   8 | Train Loss: 2.7530, Acc: 0.6357 | EER: 11.36%, MinDCF: 0.5152 | LR: 0.000050 | TrainTime: 5179.93s, ValTime: 3419.52s, EpochTime: 8599.45s
EarlyStopping counter: 2/7

Epoch   9 | Train Loss: 2.5462, Acc: 0.6546 | EER: 10.60%, MinDCF: 0.5272 | LR: 0.000050 | TrainTime: 5188.49s, ValTime: 3421.61s, EpochTime: 8610.10s
EarlyStopping counter: 3/7

Epoch  10 | Train Loss: 2.2891, Acc: 0.6828 | EER: 10.08%, MinDCF: 0.5008 | LR: 0.000050 | TrainTime: 5159.65s, ValTime: 3318.92s, EpochTime: 8478.57s

Epoch  11 | Train Loss: 2.1393, Acc: 0.6977 | EER: 10.64%, MinDCF: 0.4964 | LR: 0.000050 | TrainTime: 5045.84s, ValTime: 3390.22s, EpochTime: 8436.05s
EarlyStopping counter: 1/7

Epoch  12 | Train Loss: 1.9702, Acc: 0.7156 | EER: 8.56%, MinDCF: 0.4736 | LR: 0.000050 | TrainTime: 5120.02s, ValTime: 3383.36s, EpochTime: 8503.38s

Epoch  13 | Train Loss: 1.7967, Acc: 0.7354 | EER: 8.60%, MinDCF: 0.4668 | LR: 0.000050 | TrainTime: 5120.82s, ValTime: 3383.74s, EpochTime: 8504.56s
EarlyStopping counter: 1/7

Epoch  14 | Train Loss: 1.7007, Acc: 0.7485 | EER: 8.56%, MinDCF: 0.4436 | LR: 0.000050 | TrainTime: 4718.45s, ValTime: 3269.88s, EpochTime: 7988.34s
EarlyStopping counter: 2/7

Epoch  15 | Train Loss: 1.5977, Acc: 0.7592 | EER: 12.40%, MinDCF: 0.5300 | LR: 0.000050 | TrainTime: 5144.29s, ValTime: 3362.90s, EpochTime: 8507.19s
EarlyStopping counter: 3/7

Epoch  16 | Train Loss: 1.4896, Acc: 0.7759 | EER: 11.08%, MinDCF: 0.4904 | LR: 0.000025 | TrainTime: 5018.79s, ValTime: 3303.99s, EpochTime: 8322.78s
EarlyStopping counter: 4/7

Epoch  17 | Train Loss: 1.2292, Acc: 0.8128 | EER: 10.48%, MinDCF: 0.4744 | LR: 0.000025 | TrainTime: 4656.79s, ValTime: 2967.21s, EpochTime: 7624.00s
EarlyStopping counter: 5/7

Epoch  18 | Train Loss: 1.1012, Acc: 0.8341 | EER: 10.92%, MinDCF: 0.5016 | LR: 0.000025 | TrainTime: 4486.65s, ValTime: 2967.29s, EpochTime: 7453.94s
EarlyStopping counter: 6/7

Epoch  19 | Train Loss: 1.0208, Acc: 0.8451 | EER: 10.40%, MinDCF: 0.5120 | LR: 0.000025 | TrainTime: 4498.17s, ValTime: 2965.70s, EpochTime: 7463.87s
EarlyStopping counter: 7/7

✓ Early stopping triggered!

✓ Training completed!
  Best validation EER: 8.5600
  Experiment dir: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch
  Config: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\config.json
  Results: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\results.json
  Results CSV: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\results.csv
  Summary JSON (all modes): ./outputs\experiments_train_raw_w2v2_7hc\summary_all_modes.json
  Summary CSV (all modes): ./outputs\experiments_train_raw_w2v2_7hc\summary_all_modes.csv
  Model: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\best_model.pth
[CLEANUP] Done after Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch

In [1]:
import gc
import glob
import json
import os
import warnings

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
import torchaudio
from tqdm.auto import tqdm

from model import get_model
from metrics import compute_eer, compute_mindcf

warnings.filterwarnings("ignore")

# ============================================================================
# INFERENCE ALL MODELS x ALL TEST SETS (NO ENSEMBLE)
# ============================================================================
REPORT_PREFIX = "inference_all_models_v1"
TEST_BASE_DIR = r"D:/test_o"
LIST_GT_DIR = os.path.join(TEST_BASE_DIR, "list_gt")
OUTPUT_DIR = "./outputs"
P_TARGET = 0.05

# PTM inference mode:
# - "on_the_fly": read waveform and extract PTM runtime in model
# - "precomputed": use PTM .pt embedding files from test set
PTM_INFERENCE_MODE = "on_the_fly"
if PTM_INFERENCE_MODE not in ["on_the_fly", "precomputed"]:
    raise ValueError(f"SV_PTM_INFER_MODE must be on_the_fly|precomputed, got: {PTM_INFERENCE_MODE}")

TEST_AUDIO_BASE_DIR = r"D:/test_o_wav"
MAX_AUDIO_SECONDS = 12.0

# Map trial test-set name -> folder name under TEST_AUDIO_BASE_DIR
TEST_AUDIO_SPLIT_MAP = {
    "full_length": "raw",
    "test_vi": "vi_full",
    "test_3s": "3s",
    "test_5s": "5s",
    "test_7s": "7s",
}

# Filter tùy chọn: đặt None để lấy tất cả
MODE_FILTER = [1, 2, 3]
FUSION_FILTER = None  # ví dụ: ["concat", "gating", "film", "cross_attention"]

TEST_SET_CONFIGS = [
    {"name": "full_length", "trial_file": "test_list_gt.csv", "duration": "full_length"},
    {"name": "test_vi", "trial_file": "test_list_gt_vi.csv", "duration": "test_vi"},
    {"name": "test_3s", "trial_file": "test_list_gt_3s.csv", "duration": "test_3s"},
    {"name": "test_5s", "trial_file": "test_list_gt_5s.csv", "duration": "test_5s"},
    {"name": "test_7s", "trial_file": "test_list_gt_7s.csv", "duration": "test_7s"},
]

SOURCE_EXPERIMENT_ROOTS = []
for pattern in ["./outputs/experiments_train_raw_w2v2_7hc"]:
    for candidate in sorted(glob.glob(pattern)):
        if os.path.isdir(candidate) and candidate not in SOURCE_EXPERIMENT_ROOTS:
            SOURCE_EXPERIMENT_ROOTS.append(candidate)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")
print(f"Report prefix: {REPORT_PREFIX}")
print(f"PTM inference mode: {PTM_INFERENCE_MODE}")
print(f"Test audio base dir: {TEST_AUDIO_BASE_DIR}")
print("Source experiment roots:")
for root in SOURCE_EXPERIMENT_ROOTS:
    print(" -", root)

HC_FILENAME_MAP = {
    "mfbe_only": "Only_MFBE.pt",
    "pitch_only": "Only_Pitch.pt",
    "mfcc_only": "Only_MFCC.pt",
    "mfbe_pitch": "MFBE_Pitch.pt",
    "mfcc_pitch": "MFCC_Pitch.pt",
    "fbank_only": "Only_FBank.pt",
    "fbank_pitch": "FBank_Pitch.pt",
}


def parse_trial_csv(trial_csv_path: str) -> pd.DataFrame:
    raw_df = pd.read_csv(trial_csv_path, header=None)
    if raw_df.shape[1] >= 3:
        df = raw_df.iloc[:, :3].copy()
        df.columns = ["label", "path1", "path2"]
    else:
        df = raw_df.rename(columns={0: "raw"}).copy()
        parsed = df["raw"].astype(str).str.strip('"').str.extract(r"^\s*([01])\s+(.+?)\s+(.+?)\s*$")
        parsed.columns = ["label", "path1", "path2"]
        df = parsed
    df["label"] = df["label"].astype(int)
    df["path1"] = df["path1"].astype(str)
    df["path2"] = df["path2"].astype(str)
    df = df.reset_index(drop=True)
    df["trial_idx"] = np.arange(len(df), dtype=np.int64)
    return df[["trial_idx", "label", "path1", "path2"]]


def _candidate_keys(path_text: str):
    p = str(path_text).replace('\\\\', '/').strip()
    base = os.path.basename(p)
    stem = os.path.splitext(base)[0]
    rel = p.lstrip('./')
    out, seen = [], set()
    for key in [p, rel, base, stem]:
        if key not in seen:
            out.append(key)
            seen.add(key)
    return out


def _register_lookup(lookup, path_text, value):
    for key in _candidate_keys(path_text):
        if key not in lookup:
            lookup[key] = value


def _get_feature_from_lookup(lookup, path_text):
    if lookup is None:
        return None
    for key in _candidate_keys(path_text):
        if key in lookup:
            return lookup[key]
    return None


def resolve_ptm_path(ptm_name: str, ptm_dir: str):
    if ptm_dir is None:
        return None
    ptm_name = str(ptm_name).lower()
    cands = [
        os.path.join(ptm_dir, f"Embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"all_embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"{ptm_name}.pt"),
    ]
    for p in cands:
        if os.path.exists(p):
            return p
    return None


def resolve_hc_path(feature_mode: str, feature_dir: str):
    if feature_dir is None:
        return None
    feature_mode = str(feature_mode).lower()
    if feature_mode in HC_FILENAME_MAP:
        p = os.path.join(feature_dir, HC_FILENAME_MAP[feature_mode])
        if os.path.exists(p):
            return p
    for p in [
        os.path.join(feature_dir, f"{feature_mode}.pt"),
        os.path.join(feature_dir, f"all_features_{feature_mode}.pt"),
    ]:
        if os.path.exists(p):
            return p
    return None


def _to_float_tensor(value):
    if torch.is_tensor(value):
        return value.float().detach().cpu()
    return torch.tensor(value, dtype=torch.float32)


def build_lookup_from_pt_file(obj, value_field: str):
    lookup = {}
    if not isinstance(obj, dict):
        raise ValueError(f"Unsupported .pt format: expected dict, got {type(obj).__name__}")

    # Case 1: chuẩn filenames + values
    if "filenames" in obj and value_field in obj:
        filenames = obj.get("filenames", [])
        values = obj.get(value_field, [])

        # Nếu values là tensor batch thì tách theo dim 0
        if torch.is_tensor(values):
            if values.dim() >= 2:
                values = [values[i] for i in range(values.shape[0])]
            else:
                values = [values]

        # Nếu filenames khớp, map theo filenames
        if isinstance(filenames, (list, tuple)) and len(filenames) == len(values) and len(filenames) > 0:
            for idx, name in enumerate(filenames):
                _register_lookup(lookup, str(name), _to_float_tensor(values[idx]))
            return lookup

        # filenames rỗng hoặc mismatch -> fallback theo index, không raise
        if isinstance(values, (list, tuple)) and len(values) > 0:
            for idx, value in enumerate(values):
                _register_lookup(lookup, f"idx_{idx}", _to_float_tensor(value))
            return lookup

    # Case 2: dict keyed-by-name -> tensor
    if len(obj) > 0 and all(isinstance(k, str) for k in obj.keys()):
        for name, value in obj.items():
            if torch.is_tensor(value):
                _register_lookup(lookup, str(name), _to_float_tensor(value))
        if len(lookup) > 0:
            return lookup

    raise ValueError("Unsupported .pt format: missing usable tensor entries")


def _safe_float(value, default=None):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def discover_experiments(exp_roots):
    experiments = []
    seen = set()
    for root in exp_roots:
        if not os.path.isdir(root):
            continue
        for exp_dir in sorted(glob.glob(os.path.join(root, "*"))):
            model_path = os.path.join(exp_dir, "best_model.pth")
            config_path = os.path.join(exp_dir, "config.json")
            results_path = os.path.join(exp_dir, "results.json")
            if not (os.path.exists(model_path) and os.path.exists(config_path)):
                continue

            exp_name = os.path.basename(exp_dir)
            dedup_key = (root, exp_name)
            if dedup_key in seen:
                continue
            seen.add(dedup_key)

            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)

            results = {}
            if os.path.exists(results_path):
                with open(results_path, "r", encoding="utf-8") as f:
                    results = json.load(f)

            mode = int(cfg.get("mode", 3))
            fusion = str(cfg.get("fusion_method", "concat")).lower()

            if MODE_FILTER is not None and mode not in MODE_FILTER:
                continue
            if FUSION_FILTER is not None and fusion not in FUSION_FILTER:
                continue

            experiments.append({
                "exp_name": exp_name,
                "root_dir": root,
                "exp_dir": exp_dir,
                "model_path": model_path,
                "mode": mode,
                "fusion_method": fusion,
                "feature_mode": str(cfg.get("feature_mode", "mfbe_pitch")).lower(),
                "pretrained_model": str(cfg.get("pretrained_model", "wavlm")).lower(),
                "duration": str(cfg.get("duration", "")).lower(),
                "use_ptm_on_the_fly": bool(cfg.get("use_ptm_on_the_fly", False)),
                "ptm_model_id": str(cfg.get("ptm_model_id", "facebook/wav2vec2-base")),
                "audio_sample_rate": int(cfg.get("audio_sample_rate", 16000)),
                "best_val_eer": _safe_float(results.get("best_val_eer"), np.inf),
            })
    return experiments


def get_test_set_dirs(test_set_name: str, duration: str):
    base_dir = os.path.join(TEST_BASE_DIR, test_set_name)
    ptm_dir = os.path.join(base_dir, "embeddings")
    feature_dir = os.path.join(base_dir, "features")
    if duration and duration != "full_length":
        alt_ptm = os.path.join(base_dir, duration, "embeddings")
        alt_hc = os.path.join(base_dir, duration, "features")
        if os.path.isdir(alt_ptm):
            ptm_dir = alt_ptm
        if os.path.isdir(alt_hc):
            feature_dir = alt_hc
    return ptm_dir, feature_dir


def score_df_to_dense_arrays(score_df, num_trials):
    if score_df is None or len(score_df) == 0:
        return None
    if score_df["trial_idx"].duplicated().any():
        dup_count = int(score_df["trial_idx"].duplicated().sum())
        raise RuntimeError(f"Duplicate trial_idx detected in score_df: {dup_count}")
    score_vec = np.full(num_trials, np.nan, dtype=np.float32)
    label_vec = np.full(num_trials, -1, dtype=np.int32)
    trial_idx = score_df["trial_idx"].to_numpy(dtype=np.int64)
    labels = score_df["label"].to_numpy(dtype=np.int32)
    scores = score_df["score"].to_numpy(dtype=np.float32)
    score_vec[trial_idx] = scores
    label_vec[trial_idx] = labels
    return score_vec, label_vec


def summarize_scores_from_arrays(labels_np, scores_np):
    eer, _ = compute_eer(labels_np, scores_np)
    mindcf, _ = compute_mindcf(labels_np, scores_np, p_target=P_TARGET)
    return {
        "EER (%)": float(eer * 100.0),
        "MinDCF": float(mindcf),
        "Used Pairs": int(len(scores_np)),
    }


def _resolve_audio_path(path_text: str, test_set_name: str, duration: str):
    p = str(path_text).strip().replace("\\", "/")
    if os.path.isfile(p):
        return os.path.normpath(p)

    rel = p.lstrip("./")
    rel_no_wav = rel[4:] if rel.lower().startswith("wav/") else rel
    base = os.path.basename(rel_no_wav)
    stem, ext = os.path.splitext(base)
    exts = [ext] if ext else [".wav", ".flac", ".mp3", ".m4a"]

    split = TEST_AUDIO_SPLIT_MAP.get(test_set_name, test_set_name)
    roots = [TEST_AUDIO_BASE_DIR, TEST_BASE_DIR]
    roots = [r for r in roots if r]

    cands = []
    for root in roots:
        cands.extend([
            os.path.join(root, rel),
            os.path.join(root, rel_no_wav),
            os.path.join(root, split, rel),
            os.path.join(root, split, rel_no_wav),
            os.path.join(root, test_set_name, rel),
            os.path.join(root, test_set_name, rel_no_wav),
        ])
        if stem:
            for e in exts:
                cands.extend([
                    os.path.join(root, stem + e),
                    os.path.join(root, split, stem + e),
                    os.path.join(root, test_set_name, stem + e),
                    os.path.join(root, split, "wav", stem + e),
                    os.path.join(root, test_set_name, "wav", stem + e),
                ])

    seen = set()
    for cand in cands:
        norm = os.path.normpath(cand)
        if norm in seen:
            continue
        seen.add(norm)
        if os.path.isfile(norm):
            return norm

    return None


def _load_audio_for_infer(path_text: str, test_set_name: str, duration: str, sample_rate: int):
    resolved = _resolve_audio_path(path_text, test_set_name, duration)
    if resolved is None:
        return None, None

    wav, sr = torchaudio.load(resolved)
    if wav.dim() == 2 and wav.size(0) > 1:
        wav = wav.mean(dim=0, keepdim=True)
    if wav.dim() == 2:
        wav = wav.squeeze(0)

    if int(sr) != int(sample_rate):
        wav = torchaudio.functional.resample(wav, orig_freq=int(sr), new_freq=int(sample_rate))

    if MAX_AUDIO_SECONDS is not None and float(MAX_AUDIO_SECONDS) > 0:
        max_n = int(float(MAX_AUDIO_SECONDS) * int(sample_rate))
        if wav.numel() > max_n:
            wav = wav[:max_n]

    wav = wav.float().contiguous()
    return wav, int(wav.shape[0])


@torch.no_grad()
def build_pair_score_df(model, mode, ptm_lookup, hc_lookup, trials_df, test_set_name, duration, sample_rate):
    unique_paths = set(trials_df["path1"].tolist() + trials_df["path2"].tolist())
    path_to_emb = {}

    for path in tqdm(sorted(unique_paths), desc="Embedding paths", leave=False):
        hc_feat = _get_feature_from_lookup(hc_lookup, path) if mode in [2, 3] else None
        if mode in [2, 3] and hc_feat is None:
            continue

        inputs = {}

        if mode in [1, 3]:
            if PTM_INFERENCE_MODE == "on_the_fly":
                wav, wav_len = _load_audio_for_infer(path, test_set_name, duration, sample_rate)
                if wav is None:
                    continue
                inputs["audio"] = wav.unsqueeze(0).to(DEVICE).float()
                inputs["audio_lengths"] = torch.tensor([wav_len], dtype=torch.long, device=DEVICE)
            else:
                ptm_feat = _get_feature_from_lookup(ptm_lookup, path)
                if ptm_feat is None:
                    continue
                inputs["embedding"] = ptm_feat.unsqueeze(0).to(DEVICE).float()

        if mode in [2, 3]:
            inputs["feature"] = hc_feat.unsqueeze(0).to(DEVICE).float()

        _, emb = model(**inputs)
        path_to_emb[path] = F.normalize(emb, p=2, dim=1).squeeze(0).detach().cpu().numpy().astype(np.float32)

    if len(path_to_emb) < 2:
        return None

    trial_idx_list, valid_labels, pair_i, pair_j = [], [], [], []
    paths = list(path_to_emb.keys())
    path_to_idx = {p: i for i, p in enumerate(paths)}
    emb_matrix = np.stack([path_to_emb[p] for p in paths], axis=0)

    for _, row in trials_df.iterrows():
        p1 = row["path1"]
        p2 = row["path2"]
        if p1 not in path_to_idx or p2 not in path_to_idx:
            continue
        trial_idx_list.append(int(row["trial_idx"]))
        valid_labels.append(int(row["label"]))
        pair_i.append(path_to_idx[p1])
        pair_j.append(path_to_idx[p2])

    if len(pair_i) == 0:
        return None

    pair_i = np.asarray(pair_i, dtype=np.int32)
    pair_j = np.asarray(pair_j, dtype=np.int32)
    raw_scores = np.sum(emb_matrix[pair_i] * emb_matrix[pair_j], axis=1).astype(np.float32)

    return pd.DataFrame({
        "trial_idx": np.asarray(trial_idx_list, dtype=np.int64),
        "label": np.asarray(valid_labels, dtype=np.int32),
        "score": raw_scores,
    })


LOOKUP_CACHE = {"ptm": {}, "hc": {}}


def clear_lookup_cache():
    LOOKUP_CACHE["ptm"].clear()
    LOOKUP_CACHE["hc"].clear()
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def get_ptm_lookup(test_set_name, duration, ptm_name, ptm_dir):
    if PTM_INFERENCE_MODE == "on_the_fly":
        return None
    key = (test_set_name, duration, ptm_name)
    if key not in LOOKUP_CACHE["ptm"]:
        ptm_path = resolve_ptm_path(ptm_name, ptm_dir)
        LOOKUP_CACHE["ptm"][key] = None if ptm_path is None else build_lookup_from_pt_file(
            torch.load(ptm_path, map_location="cpu"),
            "embeddings",
        )
    return LOOKUP_CACHE["ptm"][key]


def get_hc_lookup(test_set_name, duration, feature_mode, feature_dir):
    key = (test_set_name, duration, feature_mode)
    if key not in LOOKUP_CACHE["hc"]:
        hc_path = resolve_hc_path(feature_mode, feature_dir)
        LOOKUP_CACHE["hc"][key] = None if hc_path is None else build_lookup_from_pt_file(
            torch.load(hc_path, map_location="cpu"),
            "features",
        )
    return LOOKUP_CACHE["hc"][key]


@torch.no_grad()
def score_single_experiment(exp_info, trials_df, test_set_name, ptm_dir, feature_dir):
    model = None
    ckpt = None
    score_df = None
    try:
        mode = exp_info["mode"]
        ptm_name = exp_info["pretrained_model"]
        feature_mode = exp_info["feature_mode"]
        is_on_the_fly_ckpt = bool(exp_info.get("use_ptm_on_the_fly", False))

        # Cell này chạy on-the-fly thật cho nhánh PTM.
        # Chỉ giữ checkpoint hỗ trợ on-the-fly để tránh mismatch kiến trúc/weights.
        if PTM_INFERENCE_MODE == "on_the_fly" and mode in [1, 3] and not is_on_the_fly_ckpt:
            return None

        ptm_lookup = get_ptm_lookup(test_set_name, exp_info["duration"], ptm_name, ptm_dir) if mode in [1, 3] else None
        hc_lookup = get_hc_lookup(test_set_name, exp_info["duration"], feature_mode, feature_dir) if mode in [2, 3] else None

        if mode in [1, 3] and PTM_INFERENCE_MODE == "precomputed" and ptm_lookup is None:
            return None
        if mode in [2, 3] and hc_lookup is None:
            return None

        model = get_model(
            num_speakers=1000,
            device=str(DEVICE),
            mode=mode,
            fusion_method=exp_info["fusion_method"],
            feature_mode=feature_mode,
            use_gating=(exp_info["fusion_method"] == "gating"),
            use_ptm_on_the_fly=is_on_the_fly_ckpt,
            ptm_model_id=str(exp_info.get("ptm_model_id", "facebook/wav2vec2-base")),
            ptm_sample_rate=int(exp_info.get("audio_sample_rate", 16000)),
        )
        ckpt = torch.load(exp_info["model_path"], map_location=DEVICE)
        model.load_state_dict(ckpt["model_state_dict"], strict=True)
        model.eval()

        score_df = build_pair_score_df(
            model,
            mode,
            ptm_lookup,
            hc_lookup,
            trials_df,
            test_set_name,
            exp_info["duration"],
            int(exp_info.get("audio_sample_rate", 16000)),
        )
        dense_pack = score_df_to_dense_arrays(score_df, len(trials_df))
        if dense_pack is None:
            return None

        score_vec, label_vec = dense_pack
        valid_mask = np.isfinite(score_vec)
        if valid_mask.sum() == 0:
            return None

        metrics = summarize_scores_from_arrays(label_vec[valid_mask], score_vec[valid_mask])
        return {
            "TestSet": test_set_name,
            "Experiment": exp_info["exp_name"],
            "Mode": mode,
            "Fusion": exp_info["fusion_method"],
            "Feature": feature_mode,
            "PTM": ptm_name,
            "Duration": exp_info["duration"],
            "PTM_Input_Mode": PTM_INFERENCE_MODE,
            **metrics,
            "Missing Pairs": int(len(trials_df) - int(valid_mask.sum())),
            "Best Val EER": None if np.isinf(exp_info.get("best_val_eer", np.inf)) else exp_info.get("best_val_eer"),
        }
    finally:
        del score_df
        del ckpt
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()


all_experiments = discover_experiments(SOURCE_EXPERIMENT_ROOTS)
print(f"Discovered {len(all_experiments)} experiments after filters")

if len(all_experiments) == 0:
    raise RuntimeError("Không tìm thấy model phù hợp để inference.")

if PTM_INFERENCE_MODE == "on_the_fly":
    before_count = len(all_experiments)
    all_experiments = [
        e for e in all_experiments
        if e["mode"] not in [1, 3] or bool(e.get("use_ptm_on_the_fly", False))
    ]
    print(
        "Filtered experiments for on-the-fly PTM: "
        f"{before_count} -> {len(all_experiments)}"
    )

if len(all_experiments) == 0:
    raise RuntimeError("Không còn experiment tương thích sau khi lọc on-the-fly.")

os.makedirs(OUTPUT_DIR, exist_ok=True)
all_rows = []

for test_cfg in TEST_SET_CONFIGS:
    clear_lookup_cache()
    test_set_name = test_cfg["name"]
    trial_path = os.path.join(LIST_GT_DIR, test_cfg["trial_file"])
    duration = test_cfg.get("duration", "")
    out_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_{test_set_name}.csv")

    print("\n" + "=" * 88)
    print(f"TEST SET: {test_set_name}")
    print("=" * 88)

    if not os.path.exists(trial_path):
        print(f"[SKIP] Missing trial file: {trial_path}")
        continue

    ptm_dir, feature_dir = get_test_set_dirs(test_set_name, duration)
    if PTM_INFERENCE_MODE == "precomputed" and not os.path.isdir(ptm_dir):
        print(f"[SKIP] Missing PTM embedding dir for precomputed mode: {ptm_dir}")
        continue

    trials_df = parse_trial_csv(trial_path)
    rows = []

    for exp_info in tqdm(all_experiments, desc=f"Inference {test_set_name}"):
        try:
            row = score_single_experiment(exp_info, trials_df, test_set_name, ptm_dir, feature_dir)
            if row is not None:
                rows.append(row)
        except Exception as ex:
            print(f"[ERROR] {test_set_name} | {exp_info['exp_name']}: {type(ex).__name__} - {ex}")
        finally:
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    if len(rows) == 0:
        print(f"[WARN] No valid result rows for {test_set_name}")
        continue

    df = pd.DataFrame(rows).sort_values(["EER (%)", "MinDCF"], ascending=[True, True]).reset_index(drop=True)
    df.to_csv(out_path, index=False)
    print(f"Saved: {out_path}")
    display(df.head(30))

    all_rows.extend(rows)

all_df = pd.DataFrame(all_rows)
all_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_all_testsets.csv")
if len(all_df) > 0:
    all_df = all_df.sort_values(["TestSet", "EER (%)", "MinDCF"], ascending=[True, True, True]).reset_index(drop=True)
    all_df.to_csv(all_path, index=False)
    print(f"Saved total report: {all_path}")
    display(all_df.head(50))
else:
    print("No valid inference rows generated.")

Device: cuda
Report prefix: inference_all_models_v1
PTM inference mode: on_the_fly
Test audio base dir: D:/test_o_wav
Source experiment roots:
 - ./outputs/experiments_train_raw_w2v2_7hc
Discovered 3 experiments after filters
Filtered experiments for on-the-fly PTM: 3 -> 3

========================================================================================
TEST SET: full_length
========================================================================================

Inference full_length:   0%|          | 0/3 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

Embedding paths:   0%|          | 0/17786 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,125,249
  Trainable parameters: 106,125,249
======================================================================

Embedding paths:   0%|          | 0/17786 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

Embedding paths:   0%|          | 0/17786 [00:00<?, ?it/s]

Saved: ./outputs\inference_all_models_v1_full_length.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,full_length,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.902978,0.625071,9895,0,8.56
1,full_length,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,5.072004,0.690893,9895,0,NaN
2,full_length,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,5.227605,0.628219,9895,0,9.44

========================================================================================
TEST SET: test_vi
========================================================================================

Inference test_vi:   0%|          | 0/3 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,125,249
  Trainable parameters: 106,125,249
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

Saved: ./outputs\inference_all_models_v1_test_vi.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,test_vi,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.929095,0.258396,9895,0,9.44
1,test_vi,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,3.969673,0.266609,9895,0,NaN
2,test_vi,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.815109,0.281851,9895,0,8.56

========================================================================================
TEST SET: test_3s
========================================================================================

Inference test_3s:   0%|          | 0/3 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,125,249
  Trainable parameters: 106,125,249
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

Saved: ./outputs\inference_all_models_v1_test_3s.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,test_3s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.476019,0.582813,9895,0,9.44
1,test_3s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.044118,0.617350,9895,0,8.56
2,test_3s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,4.091408,0.605910,9895,0,NaN

========================================================================================
TEST SET: test_5s
========================================================================================

Inference test_5s:   0%|          | 0/3 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,125,249
  Trainable parameters: 106,125,249
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

Saved: ./outputs\inference_all_models_v1_test_5s.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,test_5s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.253722,0.810763,9895,0,8.56
1,test_5s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,4.497193,0.674142,9895,0,9.44
2,test_5s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,4.497193,0.709576,9895,0,NaN

========================================================================================
TEST SET: test_7s
========================================================================================

Inference test_7s:   0%|          | 0/3 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,125,249
  Trainable parameters: 106,125,249
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

Saved: ./outputs\inference_all_models_v1_test_7s.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,test_7s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,3.306993,0.574839,9895,0,8.56
1,test_7s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.354284,0.552657,9895,0,9.44
2,test_7s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,3.597754,0.597759,9895,0,NaN

Saved total report: ./outputs\inference_all_models_v1_all_testsets.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,full_length,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.902978,0.625071,9895,0,8.56
1,full_length,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,5.072004,0.690893,9895,0,NaN
2,full_length,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,5.227605,0.628219,9895,0,9.44
3,test_3s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.476019,0.582813,9895,0,9.44
4,test_3s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.044118,0.617350,9895,0,8.56
5,test_3s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,4.091408,0.605910,9895,0,NaN
6,test_5s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.253722,0.810763,9895,0,8.56
7,test_5s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,4.497193,0.674142,9895,0,9.44
8,test_5s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,4.497193,0.709576,9895,0,NaN
9,test_7s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,3.306993,0.574839,9895,0,8.56
10,test_7s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.354284,0.552657,9895,0,9.44
11,test_7s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,3.597754,0.597759,9895,0,NaN
12,test_vi,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.929095,0.258396,9895,0,9.44
13,test_vi,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,3.969673,0.266609,9895,0,NaN
14,test_vi,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.815109,0.281851,9895,0,8.56