# Speaker Verification Training & Inference

Complete pipeline for speaker verification using:
- **PTM Encoder**: WavLM/HuBERT/Wav2Vec2 (multi-layer weighted sum)
- **Handcrafted Encoder**: MFBE + F0 features with CNN
- **Fusion Methods**: Concatenation or Cross-Attention
- **Backbone**: ECAPA-TDNN
- **Loss**: AAM-Softmax
- **Features**: Early stopping, LR scheduling, heatmap visualization

## 1. Setup & Parse Arguments

In [1]:
# Auto-reload modules
%load_ext autoreload
%autoreload 2

import os

# Notebook-local runtime knobs (không dùng biến môi trường)
KMP_DUPLICATE_LIB_OK = True
OMP_NUM_THREADS = 1

import torch
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import argparse
import sys
from datetime import datetime

# Hạn chế số luồng nội bộ của PyTorch
torch.set_num_threads(OMP_NUM_THREADS)

# Check device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

Device: cuda
GPU: NVIDIA GeForce RTX 5080
GPU Memory: 17.09 GB

In [2]:
from config import (
    BATCH_SIZE, NUM_EPOCHS, LEARNING_RATE, EMBEDDING_DIM,
    MODE, FUSION_METHOD, FEATURE_MODE,
    CHECKPOINT_DIR, BEST_MODEL_NAME,
 )
from train import train

# 1. Cấu hình các biến lặp
ROOT_DIR = "D:/"
EXPERIMENTS_DIRNAME = "experiments_final"
durations = ['train_raw', 'train_vi_full', 'train_vi_3s', 'train_vi_5s', 'train_vi_7s']  # 'train_raw', 'train_vi_3s', 'train_vi_5s', 'train_vi_7s', 'train_vi_full'
pretrained_models = ['hubert', 'wavlm', 'wav2vec2']

# Tên thư mục feature trên ổ cứng
feature_folders = ['mfbe', 'pitch', 'mfcc', 'mfbe_pitch', 'mfcc_pitch', 'fbank', 'fbank_pitch']

# Fusion methods
fusion_methods = ["gating", "film", "concat"]

# Map tên thư mục sang tên config FEATURE_MODE để model nhận diện đúng dim
feat_name_map = {
    'mfbe': 'mfbe_only',
    'pitch': 'pitch_only',
    'mfcc': 'mfcc_only',
    'mfbe_pitch': 'mfbe_pitch',
    'mfcc_pitch': 'mfcc_pitch',
    'fbank': 'fbank_only',
    'fbank_pitch': 'fbank_pitch'
}

dur_prefix_map = {
    'train_raw': '',
    'train_vi_3s': '3s_',
    'train_vi_5s': '5s_',
    'train_vi_7s': '7s_',
    'train_vi_full': 'full_'
}

def get_base_args():
    """Hàm tạo arguments cơ bản giống như lúc parse_args()"""
    parser = argparse.ArgumentParser()
    # Thêm các đối số cơ bản
    parser.add_argument("--output_dir", type=str, default="./outputs")
    parser.add_argument("--experiments_dirname", type=str, default="experiments_final")
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--learning_rate", type=float, default=0.0001)
    parser.add_argument("--lr_scheduler", type=str, default="plateau")
    parser.add_argument("--num_epochs", type=int, default=50)
    parser.add_argument("--optimizer", type=str, default="adam")
    parser.add_argument("--weight_decay", type=float, default=0.001)
    parser.add_argument("--aam_margin", type=float, default=0.3)
    parser.add_argument("--aam_scale", type=float, default=30)
    parser.add_argument("--embedding_dim", type=int, default=512)
    parser.add_argument("--mixed_precision", type=bool, default=True)
    parser.add_argument("--early_stop_patience", type=int, default=5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--augment_prob", type=float, default=0.30)
    parser.add_argument("--feature_noise_std", type=float, default=0.003)
    parser.add_argument("--embedding_noise_std", type=float, default=0.002)
    parser.add_argument("--max_frames", type=int, default=350)
    
    # Sẽ gán động trong lúc lặp
    parser.add_argument("--mode", type=int, default=3)
    parser.add_argument("--exp_name", type=str, default="")
    parser.add_argument("--embedding_path", type=str, default="")
    parser.add_argument("--feature_path", type=str, default="")
    parser.add_argument("--feature_mode", type=str, default="")
    parser.add_argument("--fusion_method", type=str, default="")
    parser.add_argument("--use_gating", type=bool, default=False)
    parser.add_argument("--use_augment", type=bool, default=True)
    
    # Custom fields để lưu lại log
    parser.add_argument("--duration", type=str, default="")
    parser.add_argument("--pretrained_model", type=str, default="")
    
    args, _ = parser.parse_known_args([])
    return args

def check_skip(exp_name):
    """Cơ chế Skip if done: Kiểm tra xem kết quả đã tồn tại chưa"""
    results_file = os.path.join("./outputs", EXPERIMENTS_DIRNAME, exp_name, "results.json")
    if os.path.exists(results_file):
        print(f"⏭ Bỏ qua {exp_name} - Đã huấn luyện xong!")
        return True
    return False

## 2. Training

In [3]:
# # Cập nhật tên exp để biết đang chạy fusion gì
# fusion = "cross_attention" # Ví dụ: đang chạy fusion gating
# dur = "train_raw" # Ví dụ: đang chạy với duration full
# ptm = "wavlm" # Ví dụ: đang chạy với pretrained model hubert
# feat_dir = "mfbe_pitch" # Ví dụ: đang chạy với feature mfbe_pitch
# feat_mode = feat_name_map[feat_dir]

# exp_name = f"Mode3_{fusion}_{dur}_{ptm}_{feat_mode}"

# print(f"\n{'='*60}\nĐANG CHẠY: {exp_name}\n{'='*60}")
# args = get_base_args()
# args.mode = 3
# args.exp_name = exp_name
# args.duration = dur
# args.pretrained_model = ptm
# args.feature_mode = feat_mode
# args.fusion_method = fusion    

# prefix = dur_prefix_map[dur]
# args.embedding_path = os.path.join(ROOT_DIR, "Embeddings", dur, f"{prefix}{ptm}_shards")
# args.feature_path = os.path.join(ROOT_DIR, "extracted_features", dur, f"{feat_dir}_shards")

# # Bật cờ use_gating nếu fusion là gating (để log/phân tích)
# args.use_gating = True if fusion == "gating" else False
# args.use_augment = True # Mode 3 dùng augment để tăng độ robust

# train(args)

In [ ]:
# ============================================================================
# TRAIN ALL MODELS (Mode1 + Mode2 + Mode3) - FIXED CONFIG PROFILE
# ============================================================================
import os
import time
import traceback
import pandas as pd
import train as train_module

# Optional: set None để chạy full, hoặc số nhỏ để test nhanh
MAX_RUNS = None

# === FORCE GRID-CONSISTENT HYPERPARAMS (runtime + args) ===
GRID_HP = {
    "num_epochs": 60,
    "early_stop_patience": 3,
    "learning_rate": 1e-4,
    "weight_decay": 1e-3,
    "aam_margin": 0.25,
    "aam_scale": 30.0,
    "augment_prob": 0.20,
    "feature_noise_std": 0.005,
    "embedding_noise_std": 0.002,
    "batch_size": 256,
    "lr_scheduler": "plateau",
}

def apply_grid_hp(args):
    # Args actually consumed in train loop
    args.num_epochs = int(GRID_HP["num_epochs"])
    args.early_stop_patience = int(GRID_HP["early_stop_patience"])
    args.learning_rate = float(GRID_HP["learning_rate"])
    args.weight_decay = float(GRID_HP["weight_decay"])
    args.aam_margin = float(GRID_HP["aam_margin"])
    args.aam_scale = float(GRID_HP["aam_scale"])
    args.batch_size = int(GRID_HP["batch_size"])
    args.lr_scheduler = str(GRID_HP["lr_scheduler"])

    # Keep your profile values in args (for logs + future use)
    args.augment_prob = float(GRID_HP["augment_prob"])
    args.feature_noise_std = float(GRID_HP["feature_noise_std"])
    args.embedding_noise_std = float(GRID_HP["embedding_noise_std"])

    # Critical: train.py currently uses module-level globals for augmentation/noise
    train_module.AUGMENT_PROB = float(GRID_HP["augment_prob"])
    train_module.FEATURE_NOISE_STD = float(GRID_HP["feature_noise_std"])
    train_module.EMBEDDING_NOISE_STD = float(GRID_HP["embedding_noise_std"])

    return args

# Fixed config profile requested
CFG_TAG = "bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30"
CFG_BRANCH_DROPOUT = 0.3
CFG_AUG_ON = True
CFG_AUG_PROB = 0.30
CFG_FEATURE_NOISE_STD = 0.005
CFG_EMBEDDING_NOISE_STD = 0.002
CFG_AAM_MARGIN = 0.25
CFG_AAM_SCALE = 30

EMBEDDINGS_ROOT = os.environ.get("SV_EMBEDDINGS_ROOT", os.path.join(ROOT_DIR, "Embeddings"))
FEATURES_ROOT = os.environ.get("SV_FEATURES_ROOT", os.path.join(ROOT_DIR, "extracted_features"))

def _path_exists_for_loader(path):
    """PTM loader chấp nhận cả thư mục shards hoặc file .pt đơn."""
    return bool(path) and (os.path.isdir(path) or os.path.isfile(path))

def build_all_models_plan():
    plan = []

    # Mode 1: PTM only
    for dur in durations:
        for ptm in pretrained_models:
            base_exp_name = f"Mode1_PTM_{dur}_{ptm}"
            exp_name = f"{base_exp_name}_{CFG_TAG}"
            prefix = dur_prefix_map[dur]
            embedding_path = os.path.join(EMBEDDINGS_ROOT, dur, f"{prefix}{ptm}_shards")
            input_ok = _path_exists_for_loader(embedding_path)
            missing_reason = "" if input_ok else f"missing embedding_path: {embedding_path}"

            plan.append({
                "mode": 1,
                "exp_name": exp_name,
                "duration": dur,
                "pretrained_model": ptm,
                "feature_mode": "N/A",
                "fusion_method": "N/A",
                "embedding_path": embedding_path,
                "feature_path": "",
                "use_gating": False,
                "input_ok": input_ok,
                "missing_reason": missing_reason,
            })

    # Mode 2: Handcrafted only
    for dur in durations:
        for feat_dir in feature_folders:
            feat_mode = feat_name_map[feat_dir]
            base_exp_name = f"Mode2_HC_{dur}_{feat_mode}"
            exp_name = f"{base_exp_name}_{CFG_TAG}"
            feature_path = os.path.join(FEATURES_ROOT, dur, f"{feat_dir}_shards")
            input_ok = _path_exists_for_loader(feature_path)
            missing_reason = "" if input_ok else f"missing feature_path: {feature_path}"

            plan.append({
                "mode": 2,
                "exp_name": exp_name,
                "duration": dur,
                "pretrained_model": "N/A",
                "feature_mode": feat_mode,
                "fusion_method": "N/A",
                "embedding_path": "",
                "feature_path": feature_path,
                "use_gating": False,
                "input_ok": input_ok,
                "missing_reason": missing_reason,
            })

    # Mode 3: Fusion
    for dur in durations:
        for ptm in pretrained_models:
            for feat_dir in feature_folders:
                for fusion in fusion_methods:
                    feat_mode = feat_name_map[feat_dir]
                    base_exp_name = f"Mode3_{fusion}_{dur}_{ptm}_{feat_mode}"
                    exp_name = f"{base_exp_name}_{CFG_TAG}"
                    prefix = dur_prefix_map[dur]
                    embedding_path = os.path.join(EMBEDDINGS_ROOT, dur, f"{prefix}{ptm}_shards")
                    feature_path = os.path.join(FEATURES_ROOT, dur, f"{feat_dir}_shards")
                    has_embedding = _path_exists_for_loader(embedding_path)
                    has_feature = _path_exists_for_loader(feature_path)
                    input_ok = has_embedding and has_feature

                    missing_parts = []
                    if not has_embedding:
                        missing_parts.append(f"embedding_path: {embedding_path}")
                    if not has_feature:
                        missing_parts.append(f"feature_path: {feature_path}")

                    plan.append({
                        "mode": 3,
                        "exp_name": exp_name,
                        "duration": dur,
                        "pretrained_model": ptm,
                        "feature_mode": feat_mode,
                        "fusion_method": fusion,
                        "embedding_path": embedding_path,
                        "feature_path": feature_path,
                        "use_gating": (fusion == "gating"),
                        "input_ok": input_ok,
                        "missing_reason": " | ".join(missing_parts),
                    })

    return plan

def run_one(cfg):
    args = get_base_args()
    args.mode = cfg["mode"]
    args.exp_name = cfg["exp_name"]
    args.duration = cfg["duration"]
    args.pretrained_model = cfg["pretrained_model"]
    args.feature_mode = cfg["feature_mode"]
    args.fusion_method = cfg["fusion_method"]
    args.embedding_path = cfg["embedding_path"]
    args.feature_path = cfg["feature_path"]
    args.use_gating = cfg["use_gating"]
    args.experiments_dirname = EXPERIMENTS_DIRNAME

    # Keep your fixed profile tag fields
    args.branch_dropout_prob = float(CFG_BRANCH_DROPOUT)
    args.use_augment = bool(CFG_AUG_ON)

    # Force full match with best-grid runtime hyperparams
    args = apply_grid_hp(args)

    # Optional debug print for first runs
    print(
        f"[HP] epochs={args.num_epochs}, es_patience={args.early_stop_patience}, "
        f"aug_prob={train_module.AUGMENT_PROB}, fn={train_module.FEATURE_NOISE_STD}, "
        f"en={train_module.EMBEDDING_NOISE_STD}, aam=({args.aam_margin},{args.aam_scale})"
    )

    # Warm-up Mode3 from Mode1/Mode2 checkpoints (same CFG_TAG profile)
    if int(args.mode) == 3:
        args.use_mode3_warmstart = True
        args.use_mode3_init_mode1 = True
        args.use_mode3_init_mode2 = True

        mode1_exp = f"Mode1_PTM_{cfg['duration']}_{cfg['pretrained_model']}_{CFG_TAG}"
        mode2_exp = f"Mode2_HC_{cfg['duration']}_{cfg['feature_mode']}_{CFG_TAG}"

        args.init_mode1_ckpt = os.path.join(
            args.output_dir, args.experiments_dirname, mode1_exp, "best_model.pth"
        )
        args.init_mode2_ckpt = os.path.join(
            args.output_dir, args.experiments_dirname, mode2_exp, "best_model.pth"
        )
    else:
        # Not needed for Mode1/Mode2 runs
        args.use_mode3_warmstart = False
        args.use_mode3_init_mode1 = False
        args.use_mode3_init_mode2 = False
        args.init_mode1_ckpt = None
        args.init_mode2_ckpt = None

    train_module.train(args)

# =========================
# PRIORITY RUN CONTROL
# =========================
RUN_PRIORITY_FIRST = True
RUN_ONLY_PRIORITY = False      # True: chỉ chạy 3 model mục tiêu trước
FORCE_RETRAIN_PRIORITY = False  # True nếu muốn bỏ qua skip cho 3 model này

TARGET_DURATION = "train_raw"
TARGET_PTM = "wav2vec2"
TARGET_FEATURE_MODE = "mfcc_pitch"
TARGET_FUSION = "film"

def is_priority_cfg(cfg):
    m = int(cfg["mode"])
    if m == 1:
        return (
            cfg["duration"] == TARGET_DURATION and
            cfg["pretrained_model"] == TARGET_PTM
        )
    if m == 2:
        return (
            cfg["duration"] == TARGET_DURATION and
            cfg["feature_mode"] == TARGET_FEATURE_MODE
        )
    if m == 3:
        return (
            cfg["duration"] == TARGET_DURATION and
            cfg["pretrained_model"] == TARGET_PTM and
            cfg["feature_mode"] == TARGET_FEATURE_MODE and
            cfg["fusion_method"] == TARGET_FUSION
        )
    return False

def priority_order_key(cfg):
    # ép thứ tự Mode1 -> Mode2 -> Mode3
    mode_rank = {1: 0, 2: 1, 3: 2}
    return mode_rank.get(int(cfg["mode"]), 99)

run_plan = build_all_models_plan()
if MAX_RUNS is not None:
    run_plan = run_plan[:max(0, int(MAX_RUNS))]

priority_plan = [x for x in run_plan if is_priority_cfg(x)]
priority_plan = sorted(priority_plan, key=priority_order_key)
other_plan = [x for x in run_plan if not is_priority_cfg(x)]

if RUN_ONLY_PRIORITY:
    run_plan = priority_plan
elif RUN_PRIORITY_FIRST:
    run_plan = priority_plan + other_plan
else:
    run_plan = run_plan

print(f"Priority runs found: {len(priority_plan)}")
for p in priority_plan:
    print("  -", p["exp_name"])

if MAX_RUNS is not None:
    run_plan = run_plan[:max(0, int(MAX_RUNS))]

mode1_count = sum(1 for x in run_plan if x["mode"] == 1)
mode2_count = sum(1 for x in run_plan if x["mode"] == 2)
mode3_count = sum(1 for x in run_plan if x["mode"] == 3)
ready_count = sum(1 for x in run_plan if x.get("input_ok", False))
missing_count = len(run_plan) - ready_count

print("\n" + "=" * 80)
print("TRAIN ALL MODELS PLAN")
print("=" * 80)
print(f"Experiments dir: ./outputs/{EXPERIMENTS_DIRNAME}")
print(f"Embeddings root: {EMBEDDINGS_ROOT}")
print(f"Features root: {FEATURES_ROOT}")
print(f"Config tag: {CFG_TAG}")
print(f"Mode1 runs: {mode1_count}")
print(f"Mode2 runs: {mode2_count}")
print(f"Mode3 runs: {mode3_count}")
print(f"Total runs: {len(run_plan)}")
print(f"Ready runs: {ready_count}")
print(f"Missing-input runs: {missing_count}")
print("=" * 80)

results = []
wall_start = time.time()

for i, cfg in enumerate(run_plan, 1):
    exp_name = cfg["exp_name"]

    if not cfg.get("input_ok", True):
        reason = cfg.get("missing_reason", "missing input path")
        print(f"SKIP missing input: {exp_name} -> {reason}")
        results.append({
            "idx": i,
            "exp_name": exp_name,
            "mode": cfg["mode"],
            "status": "skipped_missing_input",
            "minutes": 0.0,
            "reason": reason,
        })
        continue

    if check_skip(exp_name):
        results.append({
            "idx": i,
            "exp_name": exp_name,
            "mode": cfg["mode"],
            "status": "skipped_existing",
            "minutes": 0.0,
            "reason": "existing results",
        })
        continue

    run_start = time.time()
    print("\n" + "=" * 72)
    print(f"[{i}/{len(run_plan)}] START: {exp_name}")
    print("=" * 72)

    try:
        run_one(cfg)
        minutes = round((time.time() - run_start) / 60.0, 2)
        results.append({
            "idx": i,
            "exp_name": exp_name,
            "mode": cfg["mode"],
            "status": "done",
            "minutes": minutes,
            "reason": "",
        })
        print(f"DONE: {exp_name} | {minutes} min")
    except KeyboardInterrupt:
        print("Interrupted by user. Stop training plan.")
        raise
    except Exception as ex:
        minutes = round((time.time() - run_start) / 60.0, 2)
        results.append({
            "idx": i,
            "exp_name": exp_name,
            "mode": cfg["mode"],
            "status": f"error: {type(ex).__name__}",
            "minutes": minutes,
            "reason": str(ex),
        })
        print(f"ERROR: {exp_name} -> {type(ex).__name__}: {ex}")
        traceback.print_exc()
        print("Continue to next run...")

summary_df = pd.DataFrame(results)
summary_path = os.path.join("./outputs", f"all_models_train_summary_{CFG_TAG}.csv")
os.makedirs("./outputs", exist_ok=True)
if len(summary_df) > 0:
    summary_df.to_csv(summary_path, index=False)
    print(f"\nSaved summary: {summary_path}")
    display(summary_df.head(30))

print(f"Total wall time (hours): {round((time.time() - wall_start) / 3600.0, 2)}")
print("\nTrain all models finished.")

## 3. Tensorboard

In [ ]:
# Load TensorBoard extension
# %load_ext tensorboard

# Chạy giao diện TensorBoard trỏ vào thư mục chứa tất cả các experiments
# %tensorboard --logdir train/outputs/experiments

## 4. Test Results

In [1]:
import os
import glob
import json
import random
import datetime
import warnings
import time
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from tqdm.auto import tqdm

from model import get_model
from metrics import compute_eer, compute_mindcf

warnings.filterwarnings("ignore")

# ============================================================================
# CONFIG
# ============================================================================
TEST_BASE_DIR = r"D:\test_o"
LIST_GT_DIR = os.path.join(TEST_BASE_DIR, "list_gt")

# Nguồn train để build external calibration set (fixed val trials)
TRAIN_EMB_BASE_DIR = r"D:\Embeddings"
TRAIN_HC_BASE_DIR = r"D:\extracted_features"
FIXED_VAL_TRIALS_DIR = "./outputs/fixed_val_trials"

TEST_SET_CONFIGS = [
    {"name": "test_celeb_e", "test_dir": r"D:/test_celeb_e", "trial_file": r"D:/test_celeb_e/list_gt.txt", "trial_in_test_dir": True, "duration": "full_length"},
    {"name": "test_celeb_h", "test_dir": r"D:/test_celeb_h", "trial_file": r"D:/test_celeb_h/list_gt.txt", "trial_in_test_dir": True, "duration": "full_length"},
    {"name": "full_length", "trial_file": "test_list_gt.csv", "duration": "full_length"},
    {"name": "test_vi", "trial_file": "test_list_gt_vi.csv", "duration": "test_vi"},
    {"name": "test_3s", "trial_file": "test_list_gt_3s.csv", "duration": "test_3s"},
    {"name": "test_5s", "trial_file": "test_list_gt_5s.csv", "duration": "test_5s"},
    {"name": "test_7s", "trial_file": "test_list_gt_7s.csv", "duration": "test_7s"},
]

EXPERIMENT_ROOTS = ["./outputs/experiments_final"]
OUTPUT_DIR = "./outputs"
PER_TEST_REPORT_TEMPLATE = os.path.join(OUTPUT_DIR, "final_inference_report_{test_set}.csv")
OUTPUT_REPORT = os.path.join(OUTPUT_DIR, "final_inference_report_all_models.csv")
P_TARGET = 0.05

# ------------------------------
# Post-processing (EER-focused)
# ------------------------------
ENABLE_SCORE_NORMALIZATION = False
SCORE_NORM_METHOD = "none"   # tắt score normalization
COHORT_SIZE = 500
ASNORM_TOPK = 120
COHORT_SEED = 42
EPS = 1e-6

ENABLE_LOGISTIC_CALIBRATION = False
CALIBRATION_MODE = "none"
CALIBRATION_STEPS = 400
CALIBRATION_LR = 0.03
CALIBRATION_L2 = 1e-4

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")

random.seed(42)
np.random.seed(42)
torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

HC_FILENAME_MAP = {
    "mfbe_only": "Only_MFBE.pt",
    "pitch_only": "Only_Pitch.pt",
    "mfcc_only": "Only_MFCC.pt",
    "mfbe_pitch": "MFBE_Pitch.pt",
    "mfcc_pitch": "MFCC_Pitch.pt",
    "fbank_only": "FBank.pt",
    "fbank_pitch": "FBank_Pitch.pt",
}

DUR_PREFIX_MAP = {
    "train_raw": "",
    "train_vi_3s": "3s_",
    "train_vi_5s": "5s_",
    "train_vi_7s": "7s_",
    "train_vi_full": "full_",
}

FEATURE_MODE_TO_DIR = {
    "mfbe_only": "mfbe",
    "pitch_only": "pitch",
    "mfcc_only": "mfcc",
    "mfbe_pitch": "mfbe_pitch",
    "mfcc_pitch": "mfcc_pitch",
    "fbank_only": "fbank",
    "fbank_pitch": "fbank_pitch",
}

CALIBRATOR_CACHE = {}


def parse_trial_csv(trial_csv_path: str) -> pd.DataFrame:
    if not os.path.exists(trial_csv_path):
        raise FileNotFoundError(f"Không tìm thấy file trial CSV: {trial_csv_path}")

    raw_df = pd.read_csv(trial_csv_path, header=None)
    if raw_df.shape[1] >= 3:
        df = raw_df.iloc[:, :3].copy()
        df.columns = ["label", "path1", "path2"]
    else:
        df = raw_df.rename(columns={0: "raw"}).copy()
        parsed = df["raw"].astype(str).str.strip('"').str.extract(r"^\s*([01])\s+(.+?)\s+(.+?)\s*$")
        parsed.columns = ["label", "path1", "path2"]
        if parsed["label"].isna().sum() > 0:
            raise ValueError(f"Có dòng trial không parse được trong {trial_csv_path}")
        df = parsed
    df["label"] = df["label"].astype(int)
    return df


def _candidate_keys(path_text: str):
    p = str(path_text).replace("\\", "/").strip()
    base = os.path.basename(p)
    stem = os.path.splitext(base)[0]
    rel = p.lstrip("./")
    p_us = p.replace("/", "_")
    rel_us = rel.replace("/", "_")
    base_us = base.replace("/", "_")
    stem_us = os.path.splitext(base_us)[0]
    candidates = [p, rel, base, stem, p_us, rel_us, base_us, stem_us]
    seen, out = set(), []
    for key in candidates:
        if key not in seen:
            out.append(key)
            seen.add(key)
    return out


def _register_lookup(lookup, path_text, value):
    for key in _candidate_keys(path_text):
        if key not in lookup:
            lookup[key] = value


def _get_feature_from_lookup(lookup, path_text):
    if lookup is None:
        return None
    for key in _candidate_keys(path_text):
        if key in lookup:
            return lookup[key]
    return None


def resolve_ptm_path(ptm_name: str, ptm_dir: str):
    ptm_name = str(ptm_name).lower()
    candidates = [
        os.path.join(ptm_dir, f"Embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"all_embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"{ptm_name}.pt"),
    ]
    for path in candidates:
        if os.path.exists(path):
            return path
    return None


def resolve_hc_path(feature_mode: str, feature_dir: str):
    feature_mode = str(feature_mode).lower()
    if feature_mode in HC_FILENAME_MAP:
        exact_file = os.path.join(feature_dir, HC_FILENAME_MAP[feature_mode])
        if os.path.exists(exact_file):
            return exact_file
    candidates = [
        os.path.join(feature_dir, f"{feature_mode}.pt"),
        os.path.join(feature_dir, f"all_features_{feature_mode}.pt"),
    ]
    for path in candidates:
        if os.path.exists(path):
            return path
    return None


def build_lookup_from_pt_file(obj, value_field: str):
    if isinstance(obj, dict) and "filenames" in obj and value_field in obj:
        filenames = obj["filenames"]
        values = obj[value_field]
        lookup = {}
        for idx, name in enumerate(filenames):
            value = values[idx]
            tensor_value = value.float() if hasattr(value, "float") else torch.tensor(value, dtype=torch.float32)
            _register_lookup(lookup, str(name), tensor_value)
        return lookup

    if isinstance(obj, dict):
        lookup = {}
        for k, v in obj.items():
            if not isinstance(k, str):
                continue
            tensor_value = v.float() if hasattr(v, "float") else torch.tensor(v, dtype=torch.float32)
            _register_lookup(lookup, k, tensor_value)
        if len(lookup) > 0:
            return lookup

    raise ValueError("Định dạng file .pt không được hỗ trợ để tạo lookup.")


def build_lookup_from_shards(shard_dir: str, value_field: str):
    if shard_dir is None or not os.path.isdir(shard_dir):
        return None
    shard_files = sorted(glob.glob(os.path.join(shard_dir, "*.pt")))
    if len(shard_files) == 0:
        return None

    lookup = {}
    for shard_path in shard_files:
        obj = torch.load(shard_path, map_location="cpu")
        if not (isinstance(obj, dict) and "filenames" in obj and value_field in obj):
            continue
        filenames = obj["filenames"]
        values = obj[value_field]
        for idx, name in enumerate(filenames):
            value = values[idx]
            tensor_value = value.float() if hasattr(value, "float") else torch.tensor(value, dtype=torch.float32)
            _register_lookup(lookup, str(name), tensor_value)

    return lookup if len(lookup) > 0 else None


def discover_experiments(exp_roots):
    experiments = []
    for root in exp_roots:
        if not os.path.isdir(root):
            continue
        for exp_dir in sorted(glob.glob(os.path.join(root, "*"))):
            if not os.path.isdir(exp_dir):
                continue

            model_path = os.path.join(exp_dir, "best_model.pth")
            config_path = os.path.join(exp_dir, "config.json")
            if not (os.path.exists(model_path) and os.path.exists(config_path)):
                continue

            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)

            experiments.append({
                "exp_name": os.path.basename(exp_dir),
                "exp_dir": exp_dir,
                "model_path": model_path,
                "mode": int(cfg.get("mode", 3)),
                "fusion_method": cfg.get("fusion_method", "concat"),
                "feature_mode": cfg.get("feature_mode", "mfbe_pitch"),
                "pretrained_model": str(cfg.get("pretrained_model", "wavlm")).lower(),
                "use_gating": bool(cfg.get("use_gating", False)),
                "duration": cfg.get("duration", "train_raw"),
            })
    return experiments


def get_test_set_dirs(test_set_name: str, duration: str, test_root: str = None):
    base_dir = str(test_root) if test_root else os.path.join(TEST_BASE_DIR, test_set_name)
    ptm_dir = os.path.join(base_dir, "embeddings")
    feature_dir = os.path.join(base_dir, "features")
    if duration and duration != "full_length":
        alt_ptm_dir = os.path.join(base_dir, duration, "embeddings")
        alt_feature_dir = os.path.join(base_dir, duration, "features")
        if os.path.isdir(alt_ptm_dir):
            ptm_dir = alt_ptm_dir
        if os.path.isdir(alt_feature_dir):
            feature_dir = alt_feature_dir
    return ptm_dir, feature_dir


def get_train_dirs_for_experiment(exp_info):
    duration = exp_info.get("duration", "train_raw")
    ptm_name = exp_info.get("pretrained_model", "wavlm")
    feature_mode = exp_info.get("feature_mode", "mfbe_pitch")

    prefix = DUR_PREFIX_MAP.get(duration, "")
    ptm_dir = os.path.join(TRAIN_EMB_BASE_DIR, duration, f"{prefix}{ptm_name}_shards")

    feat_dir_name = FEATURE_MODE_TO_DIR.get(str(feature_mode).lower(), None)
    hc_dir = os.path.join(TRAIN_HC_BASE_DIR, duration, f"{feat_dir_name}_shards") if feat_dir_name else None

    return ptm_dir, hc_dir


def read_existing_report(path):
    if os.path.exists(path):
        try:
            return pd.read_csv(path)
        except Exception:
            return pd.DataFrame()
    return pd.DataFrame()


def get_done_experiments(existing_df):
    if existing_df is None or len(existing_df) == 0 or "Experiment" not in existing_df.columns:
        return set()
    valid_df = existing_df.copy()
    if "EER (%)" in valid_df.columns:
        valid_df["EER (%)"] = pd.to_numeric(valid_df["EER (%)"], errors="coerce")
        valid_df = valid_df[valid_df["EER (%)"].notna()]
    if "MinDCF" in valid_df.columns:
        valid_df["MinDCF"] = pd.to_numeric(valid_df["MinDCF"], errors="coerce")
        valid_df = valid_df[valid_df["MinDCF"].notna()]
    return set(valid_df["Experiment"].astype(str).tolist())


def merge_append_and_sort(existing_df, new_df, key_cols, sort_cols):
    if existing_df is None:
        existing_df = pd.DataFrame()
    if new_df is None:
        new_df = pd.DataFrame()
    merged = pd.concat([existing_df.copy(), new_df.copy()], ignore_index=True)
    if len(merged) == 0:
        return merged
    for key in key_cols:
        if key not in merged.columns:
            merged[key] = ""
    merged = merged.drop_duplicates(subset=key_cols, keep="first")
    if all(col in merged.columns for col in sort_cols):
        merged[sort_cols[0]] = pd.to_numeric(merged[sort_cols[0]], errors="coerce")
        merged[sort_cols[1]] = pd.to_numeric(merged[sort_cols[1]], errors="coerce")
        merged = merged.sort_values(sort_cols, ascending=[True, True]).reset_index(drop=True)
    return merged


def fit_logistic_calibrator(scores, labels, lr=0.03, steps=400, l2=1e-4):
    scores_t = torch.tensor(scores, dtype=torch.float32)
    labels_t = torch.tensor(labels, dtype=torch.float32)

    a = torch.nn.Parameter(torch.tensor(1.0, dtype=torch.float32))
    b = torch.nn.Parameter(torch.tensor(0.0, dtype=torch.float32))
    optimizer = torch.optim.Adam([a, b], lr=lr)

    for _ in range(int(steps)):
        optimizer.zero_grad()
        logits = a * scores_t + b
        loss = F.binary_cross_entropy_with_logits(logits, labels_t) + l2 * (a * a + b * b)
        loss.backward()
        optimizer.step()

    return float(a.detach().cpu().item()), float(b.detach().cpu().item())


def apply_logistic_calibration(scores, a, b):
    return (a * np.asarray(scores, dtype=np.float32) + b).astype(np.float32)


def apply_score_normalization(raw_scores, pair_i, pair_j, emb_matrix, method="none", cohort_size=500, topk=120, seed=42):
    method = str(method).lower()
    if method in ["none", "off", "false"]:
        return np.asarray(raw_scores, dtype=np.float32), {"norm_method": "none"}

    n = emb_matrix.shape[0]
    if n < 4:
        return np.asarray(raw_scores, dtype=np.float32), {"norm_method": "none", "norm_note": "too_few_embeddings"}

    rng = np.random.default_rng(seed)
    k = min(cohort_size, max(2, n - 1))
    cohort_indices = rng.choice(np.arange(n), size=k, replace=False)
    cohort = emb_matrix[cohort_indices]
    cohort_sim = emb_matrix @ cohort.T

    s = np.asarray(raw_scores, dtype=np.float32)

    if method == "z-norm":
        mu = np.mean(cohort_sim, axis=1)
        sigma = np.maximum(np.std(cohort_sim, axis=1), EPS)
        z = (s - mu[pair_j]) / sigma[pair_j]
        return z.astype(np.float32), {"norm_method": "z-norm", "cohort_size": int(k)}

    if method == "s-norm":
        mu = np.mean(cohort_sim, axis=1)
        sigma = np.maximum(np.std(cohort_sim, axis=1), EPS)
        z_e = (s - mu[pair_i]) / sigma[pair_i]
        z_t = (s - mu[pair_j]) / sigma[pair_j]
        return (0.5 * (z_e + z_t)).astype(np.float32), {"norm_method": "s-norm", "cohort_size": int(k)}

    if method == "as-norm":
        m = min(max(10, int(topk)), k)
        sorted_sim = np.sort(cohort_sim, axis=1)
        top_sim = sorted_sim[:, -m:]
        mu = np.mean(top_sim, axis=1)
        sigma = np.maximum(np.std(top_sim, axis=1), EPS)
        z_e = (s - mu[pair_i]) / sigma[pair_i]
        z_t = (s - mu[pair_j]) / sigma[pair_j]
        return (0.5 * (z_e + z_t)).astype(np.float32), {"norm_method": "as-norm", "cohort_size": int(k), "topk": int(m)}

    return np.asarray(raw_scores, dtype=np.float32), {"norm_method": "none", "norm_note": "unknown_method"}


def build_path_embedding_dict(model, mode, ptm_lookup, hc_lookup, paths):
    path_to_emb = {}
    missing_paths = 0
    for path in tqdm(sorted(paths), desc="Embedding paths", leave=False):
        ptm_feat = _get_feature_from_lookup(ptm_lookup, path) if mode in [1, 3] else None
        hc_feat = _get_feature_from_lookup(hc_lookup, path) if mode in [2, 3] else None

        if mode in [1, 3] and ptm_feat is None:
            missing_paths += 1
            continue
        if mode in [2, 3] and hc_feat is None:
            missing_paths += 1
            continue

        inputs = {}
        if mode in [1, 3]:
            inputs["embedding"] = ptm_feat.unsqueeze(0).to(DEVICE).float()
        if mode in [2, 3]:
            inputs["feature"] = hc_feat.unsqueeze(0).to(DEVICE).float()

        _, emb = model(**inputs)
        path_to_emb[path] = F.normalize(emb, p=2, dim=1).squeeze(0).detach().cpu().numpy().astype(np.float32)
    return path_to_emb, missing_paths


def build_scores_from_trials(model, mode, ptm_lookup, hc_lookup, trials_df):
    unique_paths = set(trials_df["path1"].astype(str).tolist() + trials_df["path2"].astype(str).tolist())
    path_to_emb, _ = build_path_embedding_dict(model, mode, ptm_lookup, hc_lookup, unique_paths)

    if len(path_to_emb) < 2:
        return None

    paths = list(path_to_emb.keys())
    emb_matrix = np.stack([path_to_emb[p] for p in paths], axis=0)
    path_to_idx = {p: i for i, p in enumerate(paths)}

    pair_i, pair_j, labels = [], [], []
    missing_pairs = 0

    for _, row in trials_df.iterrows():
        p1, p2 = str(row["path1"]), str(row["path2"])
        if p1 not in path_to_idx or p2 not in path_to_idx:
            missing_pairs += 1
            continue
        pair_i.append(path_to_idx[p1])
        pair_j.append(path_to_idx[p2])
        labels.append(int(row["label"]))

    if len(pair_i) == 0:
        return None

    pair_i = np.asarray(pair_i, dtype=np.int32)
    pair_j = np.asarray(pair_j, dtype=np.int32)
    labels_np = np.asarray(labels, dtype=np.int32)
    raw_scores = np.sum(emb_matrix[pair_i] * emb_matrix[pair_j], axis=1).astype(np.float32)

    return {
        "raw_scores": raw_scores,
        "labels": labels_np,
        "pair_i": pair_i,
        "pair_j": pair_j,
        "emb_matrix": emb_matrix,
        "missing_pairs": int(missing_pairs),
    }


def find_fixed_val_trials_csv(duration_tag: str):
    if not os.path.isdir(FIXED_VAL_TRIALS_DIR):
        return None
    pattern = os.path.join(FIXED_VAL_TRIALS_DIR, f"val_trials_{duration_tag}_*.csv")
    cands = sorted(glob.glob(pattern), key=lambda p: os.path.getmtime(p), reverse=True)
    return cands[0] if len(cands) > 0 else None


def _scalar_metric(metric_out):
    return float(metric_out[0] if isinstance(metric_out, tuple) else metric_out)


def get_or_fit_external_calibrator(exp_info, model):
    exp_name = exp_info["exp_name"]
    if exp_name in CALIBRATOR_CACHE:
        return CALIBRATOR_CACHE[exp_name]

    if CALIBRATION_MODE == "none":
        CALIBRATOR_CACHE[exp_name] = None
        return None

    duration = exp_info.get("duration", "train_raw")
    trials_csv = find_fixed_val_trials_csv(duration)
    if trials_csv is None:
        CALIBRATOR_CACHE[exp_name] = None
        return None

    try:
        val_trials = parse_trial_csv(trials_csv)
    except Exception:
        CALIBRATOR_CACHE[exp_name] = None
        return None

    train_ptm_dir, train_hc_dir = get_train_dirs_for_experiment(exp_info)
    mode = int(exp_info["mode"])

    ptm_lookup = build_lookup_from_shards(train_ptm_dir, "embeddings") if mode in [1, 3] else None
    hc_lookup = build_lookup_from_shards(train_hc_dir, "features") if mode in [2, 3] else None

    if mode in [1, 3] and ptm_lookup is None:
        CALIBRATOR_CACHE[exp_name] = None
        return None
    if mode in [2, 3] and hc_lookup is None:
        CALIBRATOR_CACHE[exp_name] = None
        return None

    score_pack = build_scores_from_trials(model, mode, ptm_lookup, hc_lookup, val_trials)
    if score_pack is None:
        CALIBRATOR_CACHE[exp_name] = None
        return None

    raw_scores = score_pack["raw_scores"]
    labels = score_pack["labels"]

    norm_scores, _ = apply_score_normalization(
        raw_scores=raw_scores,
        pair_i=score_pack["pair_i"],
        pair_j=score_pack["pair_j"],
        emb_matrix=score_pack["emb_matrix"],
        method=SCORE_NORM_METHOD if ENABLE_SCORE_NORMALIZATION else "none",
        cohort_size=COHORT_SIZE,
        topk=ASNORM_TOPK,
        seed=COHORT_SEED,
    )

    dev_raw_eer = _scalar_metric(compute_eer(labels, raw_scores))
    dev_norm_eer = _scalar_metric(compute_eer(labels, norm_scores))

    best = {
        "strategy": "raw",
        "a": None,
        "b": None,
        "trials_csv": trials_csv,
        "dev_raw_eer": float(dev_raw_eer),
        "dev_norm_eer": float(dev_norm_eer),
        "dev_cal_eer": None,
    }

    if dev_norm_eer < dev_raw_eer:
        best["strategy"] = "norm"

    if ENABLE_LOGISTIC_CALIBRATION:
        try:
            a, b = fit_logistic_calibrator(
                scores=norm_scores,
                labels=labels,
                lr=CALIBRATION_LR,
                steps=CALIBRATION_STEPS,
                l2=CALIBRATION_L2,
            )
            cal_scores = apply_logistic_calibration(norm_scores, a, b)
            dev_cal_eer = _scalar_metric(compute_eer(labels, cal_scores))
            best["dev_cal_eer"] = float(dev_cal_eer)
            if dev_cal_eer < min(dev_raw_eer, dev_norm_eer):
                best["strategy"] = "norm+cal"
                best["a"] = float(a)
                best["b"] = float(b)
        except Exception:
            pass

    CALIBRATOR_CACHE[exp_name] = best
    return best


# ==========================
# Added profiling helpers
# ==========================
def _count_params_and_memory(model):
    total_params = int(sum(p.numel() for p in model.parameters()))
    trainable_params = int(sum(p.numel() for p in model.parameters() if p.requires_grad))
    total_param_bytes = int(sum(p.numel() * p.element_size() for p in model.parameters()))
    trainable_param_bytes = int(sum(p.numel() * p.element_size() for p in model.parameters() if p.requires_grad))
    return {
        "total_params": total_params,
        "trainable_params": trainable_params,
        "total_param_memory_mb": float(total_param_bytes / (1024 ** 2)),
        "trainable_param_memory_mb": float(trainable_param_bytes / (1024 ** 2)),
    }


def _profile_inference_gflops_per_sample(model, device, sample_inputs):
    if sample_inputs is None:
        return 0.0
    try:
        from torch.profiler import profile, ProfilerActivity
    except Exception:
        return 0.0

    batch_size = 0
    for _, value in sample_inputs.items():
        if isinstance(value, torch.Tensor):
            batch_size = int(value.shape[0])
            break
    if batch_size <= 0:
        return 0.0

    activities = [ProfilerActivity.CPU]
    if torch.cuda.is_available() and str(device).startswith("cuda"):
        activities.append(ProfilerActivity.CUDA)

    try:
        with torch.no_grad():
            with profile(activities=activities, with_flops=True, record_shapes=False) as prof:
                _ = model(**sample_inputs)

        total_flops = 0.0
        for evt in prof.key_averages():
            evt_flops = getattr(evt, "flops", 0) or 0
            total_flops += float(evt_flops)

        return float(max(0.0, (total_flops / 1e9) / float(batch_size)))
    except Exception:
        return 0.0


@torch.no_grad()
def run_benchmark(exp_info, test_pairs, test_set_name, ptm_dir, feature_dir):
    run_start = time.perf_counter()
    if torch.cuda.is_available() and str(DEVICE).startswith("cuda"):
        torch.cuda.reset_peak_memory_stats(DEVICE)

    exp_name = exp_info["exp_name"]
    mode = exp_info["mode"]
    fusion_method = exp_info["fusion_method"]
    feature_mode = exp_info["feature_mode"]
    ptm_name = str(exp_info["pretrained_model"]).lower()

    print("\n" + "=" * 90)
    print(f"[INFER] {exp_name} | test_set={test_set_name}")
    print(f"  mode={mode} | fusion={fusion_method} | feature={feature_mode} | ptm={ptm_name}")

    ptm_path = resolve_ptm_path(ptm_name, ptm_dir) if mode in [1, 3] and ptm_name != "n/a" else None
    hc_path = resolve_hc_path(feature_mode, feature_dir) if mode in [2, 3] and feature_mode != "N/A" else None

    if mode in [1, 3] and ptm_path is None:
        print(f"  -> Skip: thiếu PTM feature file trong {ptm_dir}")
        return None
    if mode in [2, 3] and hc_path is None:
        print(f"  -> Skip: thiếu Handcrafted feature file cho feature_mode={feature_mode} trong {feature_dir}")
        return None

    # 1) Load features
    t0 = time.perf_counter()
    ptm_lookup, hc_lookup = None, None
    if ptm_path is not None:
        ptm_lookup = build_lookup_from_pt_file(torch.load(ptm_path, map_location="cpu"), value_field="embeddings")
    if hc_path is not None:
        hc_lookup = build_lookup_from_pt_file(torch.load(hc_path, map_location="cpu"), value_field="features")
    runtime_feature_load = float(time.perf_counter() - t0)

    # 2) Load model + checkpoint
    t1 = time.perf_counter()
    model = get_model(
        num_speakers=1000,
        device=str(DEVICE),
        mode=mode,
        fusion_method=fusion_method,
        feature_mode=feature_mode,
        use_gating=(fusion_method == "gating"),
    )
    ckpt = torch.load(exp_info["model_path"], map_location=DEVICE)
    model.load_state_dict(ckpt["model_state_dict"], strict=True)
    model.eval()
    runtime_model_load = float(time.perf_counter() - t1)

    model_stats = _count_params_and_memory(model)

    # sample inputs for gflops
    sample_inputs = None
    probe_paths = []
    if len(test_pairs) > 0:
        probe_paths.append(str(test_pairs.iloc[0]["path1"]))
        probe_paths.append(str(test_pairs.iloc[0]["path2"]))

    for p in probe_paths:
        inputs = {}
        if mode in [1, 3]:
            ptm_feat = _get_feature_from_lookup(ptm_lookup, p)
            if ptm_feat is None:
                continue
            inputs["embedding"] = ptm_feat.unsqueeze(0).to(DEVICE).float()
        if mode in [2, 3]:
            hc_feat = _get_feature_from_lookup(hc_lookup, p)
            if hc_feat is None:
                continue
            inputs["feature"] = hc_feat.unsqueeze(0).to(DEVICE).float()
        if len(inputs) > 0:
            sample_inputs = inputs
            break

    gflops_per_sample = _profile_inference_gflops_per_sample(
        model=model,
        device=DEVICE,
        sample_inputs=sample_inputs,
    )

    # 3) build scores
    t2 = time.perf_counter()
    score_pack = build_scores_from_trials(model, mode, ptm_lookup, hc_lookup, test_pairs)
    runtime_embedding = float(time.perf_counter() - t2)

    if score_pack is None:
        print("  -> Skip: không có pair hợp lệ sau khi match key.")
        return None

    # 4) metric compute
    t3 = time.perf_counter()
    raw_scores = score_pack["raw_scores"]
    labels_np = score_pack["labels"]

    eer_out = compute_eer(labels_np, raw_scores)
    mindcf_out = compute_mindcf(labels_np, raw_scores, p_target=P_TARGET)
    eer = eer_out[0] if isinstance(eer_out, tuple) else eer_out
    mindcf = mindcf_out[0] if isinstance(mindcf_out, tuple) else mindcf_out
    runtime_score = float(time.perf_counter() - t3)

    runtime_total = float(time.perf_counter() - run_start)
    total_samples_accounted = int(score_pack["emb_matrix"].shape[0])
    gflops_total = float(gflops_per_sample * total_samples_accounted)

    peak_gpu_memory_allocated_mb = 0.0
    peak_gpu_memory_reserved_mb = 0.0
    if torch.cuda.is_available() and str(DEVICE).startswith("cuda"):
        peak_gpu_memory_allocated_mb = float(torch.cuda.max_memory_allocated(DEVICE) / (1024 ** 2))
        peak_gpu_memory_reserved_mb = float(torch.cuda.max_memory_reserved(DEVICE) / (1024 ** 2))

    result = {
        "TestSet": test_set_name,
        "Experiment": exp_name,
        "Mode": mode,
        "Fusion": fusion_method,
        "Feature": feature_mode,
        "PTM": ptm_name,
        "EER (%)": float(eer * 100.0),
        "MinDCF": float(mindcf),
        "Used Pairs": int(len(labels_np)),
        "Missing Pairs": int(score_pack["missing_pairs"]),

        # Added train-like metrics
        "Runtime Feature Load (s)": runtime_feature_load,
        "Runtime Model Load (s)": runtime_model_load,
        "Runtime Embedding (s)": runtime_embedding,
        "Runtime Score (s)": runtime_score,
        "Runtime Total (s)": runtime_total,
        "GFLOPs/sample": float(gflops_per_sample),
        "GFLOPs total": gflops_total,
        "Total Samples Accounted": total_samples_accounted,
        "Peak GPU Memory Allocated (MB)": peak_gpu_memory_allocated_mb,
        "Peak GPU Memory Reserved (MB)": peak_gpu_memory_reserved_mb,
        "Total Params": model_stats["total_params"],
        "Trainable Params": model_stats["trainable_params"],
        "Param Memory (MB)": model_stats["total_param_memory_mb"],
        "Trainable Param Memory (MB)": model_stats["trainable_param_memory_mb"],
    }

    print(
        f"  -> EER: {result['EER (%)']:.4f}% | MinDCF: {result['MinDCF']:.6f} | "
        f"Used={result['Used Pairs']} | Runtime={result['Runtime Total (s)']:.2f}s"
    )
    return result


# ============================================================================
# MAIN: append logic + overwrite file
# ============================================================================
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("\nDiscovering trained experiments...")
experiments = discover_experiments(EXPERIMENT_ROOTS)
print(f"✓ Found {len(experiments)} experiments with best_model + config")

all_new_results = []

for test_cfg in TEST_SET_CONFIGS:
    test_set_name = test_cfg["name"]
    test_root = test_cfg.get("test_dir", TEST_BASE_DIR)
    trial_file = str(test_cfg["trial_file"])
    trial_path = trial_file if os.path.isabs(trial_file) else os.path.join(LIST_GT_DIR, trial_file)
    duration = test_cfg.get("duration", "")

    print("\n" + "#" * 110)
    print(f"[TEST SET] {test_set_name} | trial={trial_path}")
    print("#" * 110)

    if not os.path.exists(trial_path):
        print(f"⚠ Skip {test_set_name}: thiếu trial file {trial_path}")
        continue

    ptm_dir, feature_dir = get_test_set_dirs(test_set_name, duration, test_root=test_root)
    print(f"PTM dir: {ptm_dir}")
    print(f"HC dir : {feature_dir}")

    if not os.path.isdir(ptm_dir):
        print(f"⚠ Skip {test_set_name}: thiếu thư mục embeddings {ptm_dir}")
        continue
    if not os.path.isdir(feature_dir):
        print(f"⚠ Skip {test_set_name}: thiếu thư mục features {feature_dir}")
        continue

    test_pairs = parse_trial_csv(trial_path)
    print(f"✓ Loaded {len(test_pairs)} test pairs")

    per_test_report_path = PER_TEST_REPORT_TEMPLATE.format(test_set=test_set_name)
    existing_per_test_df = read_existing_report(per_test_report_path)
    done_experiments = get_done_experiments(existing_per_test_df)

    if len(done_experiments) > 0:
        print(f"✓ Found existing per-test report: {per_test_report_path} ({len(done_experiments)} done experiments)")
    else:
        print(f"ℹ No valid done experiments in report: {per_test_report_path}")

    per_test_new_results = []
    for exp_info in tqdm(experiments, desc=f"Benchmark {test_set_name}"):
        exp_name = str(exp_info["exp_name"])
        if exp_name in done_experiments:
            continue

        try:
            out = run_benchmark(exp_info, test_pairs, test_set_name, ptm_dir, feature_dir)
            if out is not None:
                per_test_new_results.append(out)
                all_new_results.append(out)
        except Exception as ex:
            print(f"\n[ERROR] {test_set_name} | {exp_name}: {ex}")
        finally:
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    per_test_new_df = pd.DataFrame(per_test_new_results)
    merged_per_test_df = merge_append_and_sort(
        existing_df=existing_per_test_df,
        new_df=per_test_new_df,
        key_cols=["Experiment"],
        sort_cols=["EER (%)", "MinDCF"],
    )

    if len(merged_per_test_df) > 0:
        merged_per_test_df.to_csv(per_test_report_path, index=False)
        print(f"✓ Saved per-test report (overwrite merged): {per_test_report_path}")
    else:
        print(f"⚠ No valid result for {test_set_name}.")

existing_all_df = read_existing_report(OUTPUT_REPORT)
new_all_df = pd.DataFrame(all_new_results)
merged_all_df = merge_append_and_sort(
    existing_df=existing_all_df,
    new_df=new_all_df,
    key_cols=["TestSet", "Experiment"],
    sort_cols=["EER (%)", "MinDCF"],
)

if len(merged_all_df) == 0:
    print("\n⚠ Không có kết quả benchmark hợp lệ cho report tổng.")
else:
    merged_all_df.to_csv(OUTPUT_REPORT, index=False)
    print("\n" + "=" * 110)
    print("ALL-MODEL TEST BENCHMARK (all test sets, sorted by EER, MinDCF)")
    print("=" * 110)
    print(merged_all_df.to_string(index=False))
    print(f"\n✓ Saved total report (overwrite merged): {OUTPUT_REPORT}")
    print(f"✓ Timestamp: {datetime.datetime.now().isoformat()}")

Device: cuda

Discovering trained experiments...
✓ Found 199 experiments with best_model + config

##############################################################################################################
[TEST SET] test_celeb_e | trial=D:/test_celeb_e/list_gt.txt
##############################################################################################################
PTM dir: D:/test_celeb_e\embeddings
HC dir : D:/test_celeb_e\features
✓ Loaded 47484 test pairs
✓ Found existing per-test report: ./outputs\final_inference_report_test_celeb_e.csv (199 done experiments)

Benchmark test_celeb_e:   0%|          | 0/199 [00:00<?, ?it/s]

✓ Saved per-test report (overwrite merged): ./outputs\final_inference_report_test_celeb_e.csv

##############################################################################################################
[TEST SET] test_celeb_h | trial=D:/test_celeb_h/list_gt.txt
##############################################################################################################
PTM dir: D:/test_celeb_h\embeddings
HC dir : D:/test_celeb_h\features
✓ Loaded 51047 test pairs
✓ Found existing per-test report: ./outputs\final_inference_report_test_celeb_h.csv (199 done experiments)

Benchmark test_celeb_h:   0%|          | 0/199 [00:00<?, ?it/s]

✓ Saved per-test report (overwrite merged): ./outputs\final_inference_report_test_celeb_h.csv

##############################################################################################################
[TEST SET] full_length | trial=D:\test_o\list_gt\test_list_gt.csv
##############################################################################################################
PTM dir: D:\test_o\embeddings
HC dir : D:\test_o\features
⚠ Skip full_length: thiếu thư mục embeddings D:\test_o\embeddings

##############################################################################################################
[TEST SET] test_vi | trial=D:\test_o\list_gt\test_list_gt_vi.csv
##############################################################################################################
PTM dir: D:\test_o\test_vi\embeddings
HC dir : D:\test_o\test_vi\features
✓ Loaded 9895 test pairs
✓ Found existing per-test report: ./outputs\final_inference_report_test_vi.csv (199 done experiments)

Benchmark test_vi:   0%|          | 0/199 [00:00<?, ?it/s]

✓ Saved per-test report (overwrite merged): ./outputs\final_inference_report_test_vi.csv

##############################################################################################################
[TEST SET] test_3s | trial=D:\test_o\list_gt\test_list_gt_3s.csv
##############################################################################################################
PTM dir: D:\test_o\test_3s\embeddings
HC dir : D:\test_o\test_3s\features
✓ Loaded 9895 test pairs
✓ Found existing per-test report: ./outputs\final_inference_report_test_3s.csv (199 done experiments)

Benchmark test_3s:   0%|          | 0/199 [00:00<?, ?it/s]

✓ Saved per-test report (overwrite merged): ./outputs\final_inference_report_test_3s.csv

##############################################################################################################
[TEST SET] test_5s | trial=D:\test_o\list_gt\test_list_gt_5s.csv
##############################################################################################################
PTM dir: D:\test_o\test_5s\embeddings
HC dir : D:\test_o\test_5s\features
✓ Loaded 9895 test pairs
ℹ No valid done experiments in report: ./outputs\final_inference_report_test_5s.csv

Benchmark test_5s:   0%|          | 0/199 [00:00<?, ?it/s]

==========================================================================================
[INFER] Mode1_PTM_train_raw_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=hubert

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5851% | MinDCF: 0.772728 | Used=9895 | Runtime=2.43s

==========================================================================================
[INFER] Mode1_PTM_train_raw_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6934% | MinDCF: 0.704978 | Used=9895 | Runtime=3.03s

==========================================================================================
[INFER] Mode1_PTM_train_raw_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=wavlm

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.0653% | MinDCF: 0.856329 | Used=9895 | Runtime=2.29s

==========================================================================================
[INFER] Mode1_PTM_train_vi_3s_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=hubert

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3755% | MinDCF: 0.811589 | Used=9895 | Runtime=2.17s

==========================================================================================
[INFER] Mode1_PTM_train_vi_3s_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8691% | MinDCF: 0.781422 | Used=9895 | Runtime=2.55s

==========================================================================================
[INFER] Mode1_PTM_train_vi_3s_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=wavlm

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.3155% | MinDCF: 0.845486 | Used=9895 | Runtime=2.06s

==========================================================================================
[INFER] Mode1_PTM_train_vi_5s_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=hubert

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7880% | MinDCF: 0.848207 | Used=9895 | Runtime=2.06s

==========================================================================================
[INFER] Mode1_PTM_train_vi_5s_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.0653% | MinDCF: 0.855468 | Used=9895 | Runtime=3.19s

==========================================================================================
[INFER] Mode1_PTM_train_vi_5s_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=wavlm

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9976% | MinDCF: 0.769769 | Used=9895 | Runtime=2.93s

==========================================================================================
[INFER] Mode1_PTM_train_vi_7s_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=hubert

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.2749% | MinDCF: 0.858543 | Used=9895 | Runtime=2.05s

==========================================================================================
[INFER] Mode1_PTM_train_vi_7s_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.2343% | MinDCF: 0.686168 | Used=9895 | Runtime=2.21s

==========================================================================================
[INFER] Mode1_PTM_train_vi_7s_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=wavlm

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.3155% | MinDCF: 0.839106 | Used=9895 | Runtime=2.10s

==========================================================================================
[INFER] Mode1_PTM_train_vi_full_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=hubert

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4160% | MinDCF: 0.817331 | Used=9895 | Runtime=2.01s

==========================================================================================
[INFER] Mode1_PTM_train_vi_full_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6189% | MinDCF: 0.711697 | Used=9895 | Runtime=2.04s

==========================================================================================
[INFER] Mode1_PTM_train_vi_full_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=1 | fusion=N/A | feature=N/A | ptm=wavlm

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.1793% | MinDCF: 0.813793 | Used=9895 | Runtime=2.83s

==========================================================================================
[INFER] Mode2_HC_train_raw_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=fbank_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.4372% | MinDCF: 0.666114 | Used=9895 | Runtime=24.56s

==========================================================================================
[INFER] Mode2_HC_train_raw_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=fbank_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 6.5801% | MinDCF: 0.742735 | Used=9895 | Runtime=23.23s

==========================================================================================
[INFER] Mode2_HC_train_raw_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfbe_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.9714% | MinDCF: 0.713415 | Used=9895 | Runtime=23.94s

==========================================================================================
[INFER] Mode2_HC_train_raw_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfbe_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 8.4129% | MinDCF: 0.723813 | Used=9895 | Runtime=24.51s

==========================================================================================
[INFER] Mode2_HC_train_raw_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfcc_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,564,160
  Trainable parameters: 10,564,160
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7812% | MinDCF: 0.617864 | Used=9895 | Runtime=24.03s

==========================================================================================
[INFER] Mode2_HC_train_raw_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfcc_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,565,440
  Trainable parameters: 10,565,440
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.2749% | MinDCF: 0.685820 | Used=9895 | Runtime=24.18s

==========================================================================================
[INFER] Mode2_HC_train_raw_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=pitch_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,514,240
  Trainable parameters: 10,514,240
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 19.6659% | MinDCF: 0.981237 | Used=9895 | Runtime=21.82s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=fbank_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.7213% | MinDCF: 0.802197 | Used=9895 | Runtime=23.57s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=fbank_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 6.5057% | MinDCF: 0.791516 | Used=9895 | Runtime=23.86s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfbe_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 6.8709% | MinDCF: 0.698342 | Used=9895 | Runtime=23.56s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfbe_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 8.6359% | MinDCF: 0.738896 | Used=9895 | Runtime=24.40s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfcc_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,564,160
  Trainable parameters: 10,564,160
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 6.5801% | MinDCF: 0.706722 | Used=9895 | Runtime=23.14s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfcc_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,565,440
  Trainable parameters: 10,565,440
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.5995% | MinDCF: 0.624467 | Used=9895 | Runtime=25.83s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=pitch_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,514,240
  Trainable parameters: 10,514,240
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 30.8311% | MinDCF: 1.000000 | Used=9895 | Runtime=24.08s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=fbank_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 6.1743% | MinDCF: 0.706544 | Used=9895 | Runtime=23.76s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=fbank_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 6.2149% | MinDCF: 0.725296 | Used=9895 | Runtime=24.93s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfbe_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 9.1906% | MinDCF: 0.895106 | Used=9895 | Runtime=24.76s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfbe_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 9.5759% | MinDCF: 0.851133 | Used=9895 | Runtime=26.79s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfcc_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,564,160
  Trainable parameters: 10,564,160
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 7.7703% | MinDCF: 0.723867 | Used=9895 | Runtime=25.00s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfcc_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,565,440
  Trainable parameters: 10,565,440
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 7.1549% | MinDCF: 0.743480 | Used=9895 | Runtime=28.59s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=pitch_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,514,240
  Trainable parameters: 10,514,240
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 41.1307% | MinDCF: 0.983868 | Used=9895 | Runtime=23.43s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=fbank_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 7.1076% | MinDCF: 0.752796 | Used=9895 | Runtime=23.22s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=fbank_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 8.5413% | MinDCF: 0.830319 | Used=9895 | Runtime=24.47s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfbe_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 17.4545% | MinDCF: 0.935191 | Used=9895 | Runtime=22.78s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfbe_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 15.6151% | MinDCF: 0.957646 | Used=9895 | Runtime=25.25s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfcc_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,564,160
  Trainable parameters: 10,564,160
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 9.6504% | MinDCF: 0.856375 | Used=9895 | Runtime=23.65s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfcc_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,565,440
  Trainable parameters: 10,565,440
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 7.3172% | MinDCF: 0.717423 | Used=9895 | Runtime=25.33s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=pitch_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,514,240
  Trainable parameters: 10,514,240
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 19.9905% | MinDCF: 1.000000 | Used=9895 | Runtime=22.43s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=fbank_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6662% | MinDCF: 0.614087 | Used=9895 | Runtime=23.35s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=fbank_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 6.4178% | MinDCF: 0.849436 | Used=9895 | Runtime=25.49s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfbe_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 9.4002% | MinDCF: 0.746859 | Used=9895 | Runtime=30.56s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfbe_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 7.9259% | MinDCF: 0.737829 | Used=9895 | Runtime=31.55s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfcc_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,564,160
  Trainable parameters: 10,564,160
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.1532% | MinDCF: 0.630404 | Used=9895 | Runtime=30.94s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=mfcc_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,565,440
  Trainable parameters: 10,565,440
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.5184% | MinDCF: 0.695231 | Used=9895 | Runtime=31.39s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=2 | fusion=N/A | feature=pitch_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,514,240
  Trainable parameters: 10,514,240
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 21.0117% | MinDCF: 0.999591 | Used=9895 | Runtime=29.35s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7068% | MinDCF: 0.657289 | Used=9895 | Runtime=36.79s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.1126% | MinDCF: 0.827949 | Used=9895 | Runtime=34.14s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4972% | MinDCF: 0.751827 | Used=9895 | Runtime=34.18s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.2749% | MinDCF: 0.740937 | Used=9895 | Runtime=35.62s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8624% | MinDCF: 0.751042 | Used=9895 | Runtime=21.98s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5039% | MinDCF: 0.635205 | Used=9895 | Runtime=23.03s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.1870% | MinDCF: 0.778086 | Used=9895 | Runtime=21.86s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3010% | MinDCF: 0.582375 | Used=9895 | Runtime=22.28s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4227% | MinDCF: 0.745315 | Used=9895 | Runtime=22.07s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6662% | MinDCF: 0.731588 | Used=9895 | Runtime=21.86s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9368% | MinDCF: 0.664116 | Used=9895 | Runtime=22.06s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7812% | MinDCF: 0.635968 | Used=9895 | Runtime=22.55s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9030% | MinDCF: 0.760170 | Used=9895 | Runtime=22.14s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8218% | MinDCF: 0.825801 | Used=9895 | Runtime=21.35s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7812% | MinDCF: 0.720076 | Used=9895 | Runtime=22.22s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.4778% | MinDCF: 0.762667 | Used=9895 | Runtime=21.84s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7745% | MinDCF: 0.682087 | Used=9895 | Runtime=21.94s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.4305% | MinDCF: 0.877588 | Used=9895 | Runtime=22.05s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5311% | MinDCF: 0.833275 | Used=9895 | Runtime=34.43s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.3899% | MinDCF: 0.837541 | Used=9895 | Runtime=35.11s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 6.1743% | MinDCF: 0.846932 | Used=9895 | Runtime=33.60s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 6.0120% | MinDCF: 0.847001 | Used=9895 | Runtime=35.49s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5851% | MinDCF: 0.751342 | Used=9895 | Runtime=36.05s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6595% | MinDCF: 0.764884 | Used=9895 | Runtime=24.62s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5784% | MinDCF: 0.744305 | Used=9895 | Runtime=27.26s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.3155% | MinDCF: 0.830587 | Used=9895 | Runtime=23.56s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.3966% | MinDCF: 0.778495 | Used=9895 | Runtime=27.27s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4972% | MinDCF: 0.843583 | Used=9895 | Runtime=23.67s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4972% | MinDCF: 0.813293 | Used=9895 | Runtime=28.22s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5311% | MinDCF: 0.665068 | Used=9895 | Runtime=24.72s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7745% | MinDCF: 0.850899 | Used=9895 | Runtime=26.76s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5784% | MinDCF: 0.800294 | Used=9895 | Runtime=25.73s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8963% | MinDCF: 0.723006 | Used=9895 | Runtime=27.21s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7474% | MinDCF: 0.780314 | Used=9895 | Runtime=26.17s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8218% | MinDCF: 0.762001 | Used=9895 | Runtime=25.21s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6934% | MinDCF: 0.702814 | Used=9895 | Runtime=23.84s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5378% | MinDCF: 0.731396 | Used=9895 | Runtime=26.99s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4227% | MinDCF: 0.730886 | Used=9895 | Runtime=22.99s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5784% | MinDCF: 0.634778 | Used=9895 | Runtime=26.46s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.0720% | MinDCF: 0.755015 | Used=9895 | Runtime=24.80s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9436% | MinDCF: 0.714945 | Used=9895 | Runtime=25.75s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6934% | MinDCF: 0.746172 | Used=9895 | Runtime=26.13s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.0720% | MinDCF: 0.779070 | Used=9895 | Runtime=28.91s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4972% | MinDCF: 0.822787 | Used=9895 | Runtime=25.76s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3755% | MinDCF: 0.811101 | Used=9895 | Runtime=28.96s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3282% | MinDCF: 0.838598 | Used=9895 | Runtime=26.14s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.2943% | MinDCF: 0.764374 | Used=9895 | Runtime=26.04s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7340% | MinDCF: 0.775043 | Used=9895 | Runtime=21.83s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=concat | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4499% | MinDCF: 0.803955 | Used=9895 | Runtime=21.84s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7745% | MinDCF: 0.690173 | Used=9895 | Runtime=22.31s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8557% | MinDCF: 0.663092 | Used=9895 | Runtime=22.74s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4633% | MinDCF: 0.665013 | Used=9895 | Runtime=21.97s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8218% | MinDCF: 0.739649 | Used=9895 | Runtime=29.53s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6122% | MinDCF: 0.681500 | Used=9895 | Runtime=31.87s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8963% | MinDCF: 0.722221 | Used=9895 | Runtime=32.05s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.0314% | MinDCF: 0.868880 | Used=9895 | Runtime=32.07s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6528% | MinDCF: 0.823224 | Used=9895 | Runtime=31.10s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7068% | MinDCF: 0.619011 | Used=9895 | Runtime=31.42s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7340% | MinDCF: 0.676244 | Used=9895 | Runtime=31.78s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3755% | MinDCF: 0.685495 | Used=9895 | Runtime=31.97s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6595% | MinDCF: 0.803644 | Used=9895 | Runtime=31.77s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7407% | MinDCF: 0.687557 | Used=9895 | Runtime=30.06s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8624% | MinDCF: 0.704764 | Used=9895 | Runtime=28.69s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.1464% | MinDCF: 0.688414 | Used=9895 | Runtime=32.33s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.2682% | MinDCF: 0.771039 | Used=9895 | Runtime=30.75s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8285% | MinDCF: 0.642644 | Used=9895 | Runtime=30.56s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8218% | MinDCF: 0.676638 | Used=9895 | Runtime=31.93s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.7686% | MinDCF: 0.833423 | Used=9895 | Runtime=29.84s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9908% | MinDCF: 0.841390 | Used=9895 | Runtime=24.78s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.3155% | MinDCF: 0.800022 | Used=9895 | Runtime=26.33s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.1059% | MinDCF: 0.818633 | Used=9895 | Runtime=22.06s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4160% | MinDCF: 0.820424 | Used=9895 | Runtime=22.66s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3687% | MinDCF: 0.790145 | Used=9895 | Runtime=22.28s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4905% | MinDCF: 0.713896 | Used=9895 | Runtime=22.56s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.1059% | MinDCF: 0.855424 | Used=9895 | Runtime=22.61s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3010% | MinDCF: 0.691844 | Used=9895 | Runtime=22.94s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4566% | MinDCF: 0.803369 | Used=9895 | Runtime=21.66s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7340% | MinDCF: 0.723205 | Used=9895 | Runtime=23.09s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5716% | MinDCF: 0.689877 | Used=9895 | Runtime=22.41s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4566% | MinDCF: 0.825587 | Used=9895 | Runtime=22.67s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.2199% | MinDCF: 0.772591 | Used=9895 | Runtime=22.03s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3349% | MinDCF: 0.765308 | Used=9895 | Runtime=22.12s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.2537% | MinDCF: 0.670071 | Used=9895 | Runtime=22.27s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4972% | MinDCF: 0.710875 | Used=9895 | Runtime=22.21s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4093% | MinDCF: 0.810949 | Used=9895 | Runtime=21.59s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3010% | MinDCF: 0.710079 | Used=9895 | Runtime=22.18s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6934% | MinDCF: 0.795543 | Used=9895 | Runtime=22.03s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8691% | MinDCF: 0.630281 | Used=9895 | Runtime=25.23s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9908% | MinDCF: 0.732000 | Used=9895 | Runtime=25.71s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9368% | MinDCF: 0.675643 | Used=9895 | Runtime=23.97s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5445% | MinDCF: 0.616051 | Used=9895 | Runtime=24.93s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9097% | MinDCF: 0.728495 | Used=9895 | Runtime=24.28s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3687% | MinDCF: 0.793619 | Used=9895 | Runtime=26.63s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.2943% | MinDCF: 0.761415 | Used=9895 | Runtime=24.53s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5039% | MinDCF: 0.765485 | Used=9895 | Runtime=25.27s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5851% | MinDCF: 0.835736 | Used=9895 | Runtime=23.75s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3416% | MinDCF: 0.592792 | Used=9895 | Runtime=27.01s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.2537% | MinDCF: 0.723448 | Used=9895 | Runtime=24.00s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=film | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4227% | MinDCF: 0.825508 | Used=9895 | Runtime=27.02s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4160% | MinDCF: 0.637488 | Used=9895 | Runtime=25.05s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.1937% | MinDCF: 0.672380 | Used=9895 | Runtime=29.34s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4972% | MinDCF: 0.592589 | Used=9895 | Runtime=26.45s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6595% | MinDCF: 0.600950 | Used=9895 | Runtime=25.41s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9368% | MinDCF: 0.686522 | Used=9895 | Runtime=24.31s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4972% | MinDCF: 0.669858 | Used=9895 | Runtime=26.24s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5784% | MinDCF: 0.611359 | Used=9895 | Runtime=23.59s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3010% | MinDCF: 0.604622 | Used=9895 | Runtime=27.16s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.2410% | MinDCF: 0.645060 | Used=9895 | Runtime=25.33s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5716% | MinDCF: 0.586048 | Used=9895 | Runtime=25.03s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8963% | MinDCF: 0.667752 | Used=9895 | Runtime=24.48s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6934% | MinDCF: 0.711848 | Used=9895 | Runtime=24.49s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4633% | MinDCF: 0.619731 | Used=9895 | Runtime=22.18s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5716% | MinDCF: 0.785691 | Used=9895 | Runtime=21.80s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9436% | MinDCF: 0.618805 | Used=9895 | Runtime=22.67s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.0314% | MinDCF: 0.746277 | Used=9895 | Runtime=22.73s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4160% | MinDCF: 0.621135 | Used=9895 | Runtime=22.43s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4566% | MinDCF: 0.691757 | Used=9895 | Runtime=23.09s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4160% | MinDCF: 0.710257 | Used=9895 | Runtime=22.47s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.1464% | MinDCF: 0.639141 | Used=9895 | Runtime=22.55s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 5.0381% | MinDCF: 0.751140 | Used=9895 | Runtime=21.80s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4972% | MinDCF: 0.732902 | Used=9895 | Runtime=22.88s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5784% | MinDCF: 0.818771 | Used=9895 | Runtime=22.30s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7812% | MinDCF: 0.784891 | Used=9895 | Runtime=22.53s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3687% | MinDCF: 0.691682 | Used=9895 | Runtime=22.32s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9570% | MinDCF: 0.757894 | Used=9895 | Runtime=22.51s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5445% | MinDCF: 0.664934 | Used=9895 | Runtime=22.46s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3416% | MinDCF: 0.808362 | Used=9895 | Runtime=21.63s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4972% | MinDCF: 0.703238 | Used=9895 | Runtime=22.02s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8624% | MinDCF: 0.724873 | Used=9895 | Runtime=22.66s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.9841% | MinDCF: 0.710398 | Used=9895 | Runtime=21.86s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.3755% | MinDCF: 0.659362 | Used=9895 | Runtime=22.09s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8624% | MinDCF: 0.725456 | Used=9895 | Runtime=21.97s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7812% | MinDCF: 0.623428 | Used=9895 | Runtime=22.67s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8285% | MinDCF: 0.730423 | Used=9895 | Runtime=22.14s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4972% | MinDCF: 0.818521 | Used=9895 | Runtime=21.30s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5445% | MinDCF: 0.683603 | Used=9895 | Runtime=22.41s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6528% | MinDCF: 0.700329 | Used=9895 | Runtime=22.67s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7812% | MinDCF: 0.706475 | Used=9895 | Runtime=22.56s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6595% | MinDCF: 0.709977 | Used=9895 | Runtime=22.05s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8963% | MinDCF: 0.627249 | Used=9895 | Runtime=23.08s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.8557% | MinDCF: 0.694894 | Used=9895 | Runtime=22.20s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4905% | MinDCF: 0.704862 | Used=9895 | Runtime=22.22s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.6122% | MinDCF: 0.762503 | Used=9895 | Runtime=22.26s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5445% | MinDCF: 0.695068 | Used=9895 | Runtime=23.71s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5039% | MinDCF: 0.744396 | Used=9895 | Runtime=22.43s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4499% | MinDCF: 0.787287 | Used=9895 | Runtime=22.78s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.7812% | MinDCF: 0.673910 | Used=9895 | Runtime=22.20s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.4093% | MinDCF: 0.747826 | Used=9895 | Runtime=22.79s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_5s
  mode=3 | fusion=gating | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

  -> EER: 4.5378% | MinDCF: 0.834697 | Used=9895 | Runtime=22.05s
✓ Saved per-test report (overwrite merged): ./outputs\final_inference_report_test_5s.csv

##############################################################################################################
[TEST SET] test_7s | trial=D:\test_o\list_gt\test_list_gt_7s.csv
##############################################################################################################
PTM dir: D:\test_o\test_7s\embeddings
HC dir : D:\test_o\test_7s\features
✓ Loaded 9895 test pairs
ℹ No valid done experiments in report: ./outputs\final_inference_report_test_7s.csv

Benchmark test_7s:   0%|          | 0/199 [00:00<?, ?it/s]

==========================================================================================
[INFER] Mode1_PTM_train_raw_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=hubert

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5572% | MinDCF: 0.585407 | Used=9895 | Runtime=1.16s

==========================================================================================
[INFER] Mode1_PTM_train_raw_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7195% | MinDCF: 0.578848 | Used=9895 | Runtime=1.15s

==========================================================================================
[INFER] Mode1_PTM_train_raw_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=wavlm

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8074% | MinDCF: 0.625784 | Used=9895 | Runtime=1.23s

==========================================================================================
[INFER] Mode1_PTM_train_vi_3s_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=hubert

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3476% | MinDCF: 0.579514 | Used=9895 | Runtime=1.14s

==========================================================================================
[INFER] Mode1_PTM_train_vi_3s_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5978% | MinDCF: 0.586171 | Used=9895 | Runtime=1.15s

==========================================================================================
[INFER] Mode1_PTM_train_vi_3s_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=wavlm

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7195% | MinDCF: 0.618848 | Used=9895 | Runtime=1.30s

==========================================================================================
[INFER] Mode1_PTM_train_vi_5s_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=hubert

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6045% | MinDCF: 0.606941 | Used=9895 | Runtime=1.30s

==========================================================================================
[INFER] Mode1_PTM_train_vi_5s_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6856% | MinDCF: 0.629170 | Used=9895 | Runtime=1.35s

==========================================================================================
[INFER] Mode1_PTM_train_vi_5s_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=wavlm

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8345% | MinDCF: 0.635107 | Used=9895 | Runtime=1.27s

==========================================================================================
[INFER] Mode1_PTM_train_vi_7s_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=hubert

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8885% | MinDCF: 0.666371 | Used=9895 | Runtime=1.25s

==========================================================================================
[INFER] Mode1_PTM_train_vi_7s_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7668% | MinDCF: 0.609412 | Used=9895 | Runtime=1.31s

==========================================================================================
[INFER] Mode1_PTM_train_vi_7s_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=wavlm

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.9224% | MinDCF: 0.622824 | Used=9895 | Runtime=1.25s

==========================================================================================
[INFER] Mode1_PTM_train_vi_full_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=hubert

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4016% | MinDCF: 0.568457 | Used=9895 | Runtime=1.30s

==========================================================================================
[INFER] Mode1_PTM_train_vi_full_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3881% | MinDCF: 0.583985 | Used=9895 | Runtime=1.38s

==========================================================================================
[INFER] Mode1_PTM_train_vi_full_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=1 | fusion=N/A | feature=N/A | ptm=wavlm

======================================================================
Model created successfully
  Mode: 1 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 397,057
  Trainable parameters: 397,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.2731% | MinDCF: 0.567943 | Used=9895 | Runtime=1.16s

==========================================================================================
[INFER] Mode2_HC_train_raw_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=fbank_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.0035% | MinDCF: 0.618309 | Used=9895 | Runtime=10.18s

==========================================================================================
[INFER] Mode2_HC_train_raw_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=fbank_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.2131% | MinDCF: 0.684637 | Used=9895 | Runtime=10.20s

==========================================================================================
[INFER] Mode2_HC_train_raw_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfbe_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 6.0932% | MinDCF: 0.686710 | Used=9895 | Runtime=10.45s

==========================================================================================
[INFER] Mode2_HC_train_raw_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfbe_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 6.7897% | MinDCF: 0.696030 | Used=9895 | Runtime=9.93s

==========================================================================================
[INFER] Mode2_HC_train_raw_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfcc_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,564,160
  Trainable parameters: 10,564,160
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.0508% | MinDCF: 0.601113 | Used=9895 | Runtime=11.78s

==========================================================================================
[INFER] Mode2_HC_train_raw_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfcc_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,565,440
  Trainable parameters: 10,565,440
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8479% | MinDCF: 0.593219 | Used=9895 | Runtime=11.97s

==========================================================================================
[INFER] Mode2_HC_train_raw_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=pitch_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,514,240
  Trainable parameters: 10,514,240
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 17.7047% | MinDCF: 0.922110 | Used=9895 | Runtime=12.85s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=fbank_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.0035% | MinDCF: 0.640918 | Used=9895 | Runtime=11.03s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=fbank_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.4566% | MinDCF: 0.653903 | Used=9895 | Runtime=9.86s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfbe_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 5.1126% | MinDCF: 0.694778 | Used=9895 | Runtime=13.11s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfbe_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 6.4990% | MinDCF: 0.701631 | Used=9895 | Runtime=10.34s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfcc_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,564,160
  Trainable parameters: 10,564,160
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.7001% | MinDCF: 0.716541 | Used=9895 | Runtime=12.78s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfcc_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,565,440
  Trainable parameters: 10,565,440
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.0441% | MinDCF: 0.625313 | Used=9895 | Runtime=12.56s

==========================================================================================
[INFER] Mode2_HC_train_vi_3s_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=pitch_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,514,240
  Trainable parameters: 10,514,240
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 29.8099% | MinDCF: 0.961559 | Used=9895 | Runtime=10.42s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=fbank_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.2064% | MinDCF: 0.671696 | Used=9895 | Runtime=10.57s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=fbank_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.1253% | MinDCF: 0.648696 | Used=9895 | Runtime=13.04s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfbe_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 7.1549% | MinDCF: 0.760307 | Used=9895 | Runtime=13.90s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfbe_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 6.6546% | MinDCF: 0.706544 | Used=9895 | Runtime=11.14s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfcc_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,564,160
  Trainable parameters: 10,564,160
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 5.0720% | MinDCF: 0.657310 | Used=9895 | Runtime=11.69s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfcc_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,565,440
  Trainable parameters: 10,565,440
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 5.3966% | MinDCF: 0.726212 | Used=9895 | Runtime=12.73s

==========================================================================================
[INFER] Mode2_HC_train_vi_5s_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=pitch_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,514,240
  Trainable parameters: 10,514,240
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 38.7976% | MinDCF: 0.966002 | Used=9895 | Runtime=9.38s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=fbank_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 5.3155% | MinDCF: 0.738965 | Used=9895 | Runtime=13.06s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=fbank_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 6.3705% | MinDCF: 0.710039 | Used=9895 | Runtime=12.86s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfbe_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 12.6800% | MinDCF: 0.937139 | Used=9895 | Runtime=9.99s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfbe_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 12.4704% | MinDCF: 0.899071 | Used=9895 | Runtime=10.32s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfcc_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,564,160
  Trainable parameters: 10,564,160
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 9.0755% | MinDCF: 0.707478 | Used=9895 | Runtime=12.28s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfcc_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,565,440
  Trainable parameters: 10,565,440
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 7.1144% | MinDCF: 0.666497 | Used=9895 | Runtime=10.00s

==========================================================================================
[INFER] Mode2_HC_train_vi_7s_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=pitch_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,514,240
  Trainable parameters: 10,514,240
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 20.1056% | MinDCF: 0.947182 | Used=9895 | Runtime=10.71s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=fbank_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6789% | MinDCF: 0.604977 | Used=9895 | Runtime=12.65s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=fbank_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.3349% | MinDCF: 0.686396 | Used=9895 | Runtime=10.53s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfbe_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,615,360
  Trainable parameters: 10,615,360
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 7.3172% | MinDCF: 0.757818 | Used=9895 | Runtime=10.66s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfbe_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,616,640
  Trainable parameters: 10,616,640
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 7.2361% | MinDCF: 0.768723 | Used=9895 | Runtime=12.00s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfcc_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,564,160
  Trainable parameters: 10,564,160
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.2537% | MinDCF: 0.631924 | Used=9895 | Runtime=10.20s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=mfcc_pitch | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,565,440
  Trainable parameters: 10,565,440
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.0103% | MinDCF: 0.642908 | Used=9895 | Runtime=12.08s

==========================================================================================
[INFER] Mode2_HC_train_vi_full_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=2 | fusion=N/A | feature=pitch_only | ptm=n/a

======================================================================
Model created successfully
  Mode: 2 (1=PTM, 2=Handcrafted, 3=Fusion)
  Num speakers: 1000
  Total parameters: 10,514,240
  Trainable parameters: 10,514,240
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 20.4436% | MinDCF: 0.920822 | Used=9895 | Runtime=11.85s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8818% | MinDCF: 0.620122 | Used=9895 | Runtime=12.05s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.9562% | MinDCF: 0.637557 | Used=9895 | Runtime=11.94s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4422% | MinDCF: 0.607314 | Used=9895 | Runtime=13.70s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7939% | MinDCF: 0.608193 | Used=9895 | Runtime=14.37s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7195% | MinDCF: 0.629105 | Used=9895 | Runtime=11.72s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7601% | MinDCF: 0.589174 | Used=9895 | Runtime=11.17s

==========================================================================================
[INFER] Mode3_concat_train_raw_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.9224% | MinDCF: 0.619944 | Used=9895 | Runtime=11.95s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5166% | MinDCF: 0.590009 | Used=9895 | Runtime=14.83s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5572% | MinDCF: 0.551120 | Used=9895 | Runtime=12.24s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7601% | MinDCF: 0.614442 | Used=9895 | Runtime=11.52s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.9157% | MinDCF: 0.607412 | Used=9895 | Runtime=14.03s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8074% | MinDCF: 0.600523 | Used=9895 | Runtime=13.99s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7601% | MinDCF: 0.581949 | Used=9895 | Runtime=13.17s

==========================================================================================
[INFER] Mode3_concat_train_raw_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5639% | MinDCF: 0.587654 | Used=9895 | Runtime=11.71s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8006% | MinDCF: 0.610487 | Used=9895 | Runtime=12.95s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.9968% | MinDCF: 0.640563 | Used=9895 | Runtime=12.14s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8818% | MinDCF: 0.611446 | Used=9895 | Runtime=13.87s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.9224% | MinDCF: 0.637293 | Used=9895 | Runtime=12.60s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7195% | MinDCF: 0.610230 | Used=9895 | Runtime=11.44s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8006% | MinDCF: 0.615375 | Used=9895 | Runtime=11.11s

==========================================================================================
[INFER] Mode3_concat_train_raw_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.4160% | MinDCF: 0.660249 | Used=9895 | Runtime=14.75s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.5445% | MinDCF: 0.686041 | Used=9895 | Runtime=11.56s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5099% | MinDCF: 0.605172 | Used=9895 | Runtime=12.01s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7128% | MinDCF: 0.591141 | Used=9895 | Runtime=13.77s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8412% | MinDCF: 0.594311 | Used=9895 | Runtime=13.64s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7668% | MinDCF: 0.626041 | Used=9895 | Runtime=12.27s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.9968% | MinDCF: 0.638751 | Used=9895 | Runtime=12.48s

==========================================================================================
[INFER] Mode3_concat_train_vi_3s_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5233% | MinDCF: 0.593298 | Used=9895 | Runtime=13.80s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3610% | MinDCF: 0.610444 | Used=9895 | Runtime=12.81s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3949% | MinDCF: 0.581949 | Used=9895 | Runtime=12.95s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4016% | MinDCF: 0.578652 | Used=9895 | Runtime=11.84s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.1447% | MinDCF: 0.563490 | Used=9895 | Runtime=14.27s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4354% | MinDCF: 0.576438 | Used=9895 | Runtime=12.08s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3204% | MinDCF: 0.597423 | Used=9895 | Runtime=14.06s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3949% | MinDCF: 0.560841 | Used=9895 | Runtime=11.61s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4287% | MinDCF: 0.605867 | Used=9895 | Runtime=11.64s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.2731% | MinDCF: 0.568591 | Used=9895 | Runtime=14.11s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3137% | MinDCF: 0.587726 | Used=9895 | Runtime=14.65s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6316% | MinDCF: 0.581105 | Used=9895 | Runtime=10.68s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3949% | MinDCF: 0.625827 | Used=9895 | Runtime=13.05s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5166% | MinDCF: 0.629391 | Used=9895 | Runtime=12.16s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5166% | MinDCF: 0.606106 | Used=9895 | Runtime=12.82s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5910% | MinDCF: 0.630031 | Used=9895 | Runtime=11.87s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.2258% | MinDCF: 0.555624 | Used=9895 | Runtime=13.41s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4760% | MinDCF: 0.567755 | Used=9895 | Runtime=10.83s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.1108% | MinDCF: 0.543298 | Used=9895 | Runtime=13.36s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.1920% | MinDCF: 0.561116 | Used=9895 | Runtime=12.39s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6045% | MinDCF: 0.595548 | Used=9895 | Runtime=11.98s

==========================================================================================
[INFER] Mode3_concat_train_vi_full_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=concat | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: concat
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3070% | MinDCF: 0.562256 | Used=9895 | Runtime=12.22s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5639% | MinDCF: 0.605777 | Used=9895 | Runtime=14.32s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5978% | MinDCF: 0.605671 | Used=9895 | Runtime=14.14s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4422% | MinDCF: 0.626352 | Used=9895 | Runtime=10.76s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5099% | MinDCF: 0.603298 | Used=9895 | Runtime=11.39s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4827% | MinDCF: 0.608461 | Used=9895 | Runtime=13.68s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5639% | MinDCF: 0.606399 | Used=9895 | Runtime=12.85s

==========================================================================================
[INFER] Mode3_film_train_raw_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7668% | MinDCF: 0.628689 | Used=9895 | Runtime=10.55s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.9968% | MinDCF: 0.600187 | Used=9895 | Runtime=13.92s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5910% | MinDCF: 0.585530 | Used=9895 | Runtime=14.47s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6450% | MinDCF: 0.600045 | Used=9895 | Runtime=14.75s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4287% | MinDCF: 0.558016 | Used=9895 | Runtime=10.80s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6383% | MinDCF: 0.548790 | Used=9895 | Runtime=12.88s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6316% | MinDCF: 0.565986 | Used=9895 | Runtime=12.74s

==========================================================================================
[INFER] Mode3_film_train_raw_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7195% | MinDCF: 0.584847 | Used=9895 | Runtime=13.39s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7195% | MinDCF: 0.609554 | Used=9895 | Runtime=13.74s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7128% | MinDCF: 0.602079 | Used=9895 | Runtime=11.03s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7128% | MinDCF: 0.605288 | Used=9895 | Runtime=12.43s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8412% | MinDCF: 0.615882 | Used=9895 | Runtime=14.97s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8412% | MinDCF: 0.636298 | Used=9895 | Runtime=12.92s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7534% | MinDCF: 0.609322 | Used=9895 | Runtime=11.36s

==========================================================================================
[INFER] Mode3_film_train_raw_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.0374% | MinDCF: 0.638164 | Used=9895 | Runtime=13.43s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7262% | MinDCF: 0.643805 | Used=9895 | Runtime=14.30s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7128% | MinDCF: 0.601583 | Used=9895 | Runtime=13.93s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5166% | MinDCF: 0.569542 | Used=9895 | Runtime=12.05s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5166% | MinDCF: 0.591565 | Used=9895 | Runtime=13.32s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7601% | MinDCF: 0.631942 | Used=9895 | Runtime=12.12s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4760% | MinDCF: 0.595422 | Used=9895 | Runtime=13.88s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3610% | MinDCF: 0.600078 | Used=9895 | Runtime=10.77s

==========================================================================================
[INFER] Mode3_film_train_vi_3s_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6789% | MinDCF: 0.570794 | Used=9895 | Runtime=11.84s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3949% | MinDCF: 0.576626 | Used=9895 | Runtime=15.04s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3949% | MinDCF: 0.581265 | Used=9895 | Runtime=13.49s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3137% | MinDCF: 0.552816 | Used=9895 | Runtime=11.66s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.1920% | MinDCF: 0.566876 | Used=9895 | Runtime=11.90s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3204% | MinDCF: 0.566236 | Used=9895 | Runtime=11.04s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3610% | MinDCF: 0.577408 | Used=9895 | Runtime=12.99s

==========================================================================================
[INFER] Mode3_film_train_vi_full_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3881% | MinDCF: 0.589991 | Used=9895 | Runtime=12.87s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5166% | MinDCF: 0.589405 | Used=9895 | Runtime=11.87s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5099% | MinDCF: 0.604123 | Used=9895 | Runtime=14.77s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6856% | MinDCF: 0.631034 | Used=9895 | Runtime=11.42s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4693% | MinDCF: 0.613989 | Used=9895 | Runtime=12.84s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4016% | MinDCF: 0.603074 | Used=9895 | Runtime=11.79s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3137% | MinDCF: 0.586225 | Used=9895 | Runtime=11.92s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4354% | MinDCF: 0.633034 | Used=9895 | Runtime=13.61s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4354% | MinDCF: 0.573967 | Used=9895 | Runtime=14.68s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: fbank_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.2393% | MinDCF: 0.557802 | Used=9895 | Runtime=13.04s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,067,137
  Trainable parameters: 12,067,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5910% | MinDCF: 0.562531 | Used=9895 | Runtime=12.44s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,068,417
  Trainable parameters: 12,068,417
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5572% | MinDCF: 0.600426 | Used=9895 | Runtime=11.74s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,015,937
  Trainable parameters: 12,015,937
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.2393% | MinDCF: 0.557534 | Used=9895 | Runtime=13.27s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Num speakers: 1000
  Total parameters: 12,017,217
  Trainable parameters: 12,017,217
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3949% | MinDCF: 0.555367 | Used=9895 | Runtime=13.57s

==========================================================================================
[INFER] Mode3_film_train_vi_full_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=film | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Num speakers: 1000
  Total parameters: 11,966,017
  Trainable parameters: 11,966,017
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4287% | MinDCF: 0.580208 | Used=9895 | Runtime=10.61s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5978% | MinDCF: 0.613997 | Used=9895 | Runtime=13.72s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8412% | MinDCF: 0.653468 | Used=9895 | Runtime=13.96s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4693% | MinDCF: 0.607386 | Used=9895 | Runtime=15.89s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6450% | MinDCF: 0.590509 | Used=9895 | Runtime=12.97s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4693% | MinDCF: 0.590899 | Used=9895 | Runtime=11.47s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4354% | MinDCF: 0.601102 | Used=9895 | Runtime=13.46s

==========================================================================================
[INFER] Mode3_gating_train_raw_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5233% | MinDCF: 0.605198 | Used=9895 | Runtime=14.11s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4827% | MinDCF: 0.580501 | Used=9895 | Runtime=14.52s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8412% | MinDCF: 0.612958 | Used=9895 | Runtime=11.51s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4827% | MinDCF: 0.581630 | Used=9895 | Runtime=11.06s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5572% | MinDCF: 0.587263 | Used=9895 | Runtime=13.11s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6383% | MinDCF: 0.601750 | Used=9895 | Runtime=13.52s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4827% | MinDCF: 0.563721 | Used=9895 | Runtime=11.74s

==========================================================================================
[INFER] Mode3_gating_train_raw_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6316% | MinDCF: 0.570733 | Used=9895 | Runtime=11.10s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7668% | MinDCF: 0.601475 | Used=9895 | Runtime=14.58s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7128% | MinDCF: 0.598729 | Used=9895 | Runtime=14.89s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4827% | MinDCF: 0.587603 | Used=9895 | Runtime=12.80s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5166% | MinDCF: 0.592426 | Used=9895 | Runtime=12.03s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4693% | MinDCF: 0.590364 | Used=9895 | Runtime=14.42s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8412% | MinDCF: 0.624717 | Used=9895 | Runtime=10.91s

==========================================================================================
[INFER] Mode3_gating_train_raw_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7601% | MinDCF: 0.600223 | Used=9895 | Runtime=14.85s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6450% | MinDCF: 0.615205 | Used=9895 | Runtime=12.04s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4354% | MinDCF: 0.566619 | Used=9895 | Runtime=12.95s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 4.2131% | MinDCF: 0.587983 | Used=9895 | Runtime=11.12s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5639% | MinDCF: 0.568421 | Used=9895 | Runtime=16.13s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6383% | MinDCF: 0.596659 | Used=9895 | Runtime=14.38s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3204% | MinDCF: 0.595031 | Used=9895 | Runtime=12.25s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4827% | MinDCF: 0.578432 | Used=9895 | Runtime=11.17s

==========================================================================================
[INFER] Mode3_gating_train_vi_3s_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8006% | MinDCF: 0.546532 | Used=9895 | Runtime=12.89s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5978% | MinDCF: 0.584651 | Used=9895 | Runtime=12.30s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.8006% | MinDCF: 0.588996 | Used=9895 | Runtime=11.30s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3949% | MinDCF: 0.578030 | Used=9895 | Runtime=12.30s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4287% | MinDCF: 0.580100 | Used=9895 | Runtime=13.66s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4287% | MinDCF: 0.590454 | Used=9895 | Runtime=15.28s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.2798% | MinDCF: 0.549607 | Used=9895 | Runtime=12.05s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=pitch_only | ptm=hubert

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3949% | MinDCF: 0.582509 | Used=9895 | Runtime=12.39s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4422% | MinDCF: 0.603324 | Used=9895 | Runtime=12.59s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4693% | MinDCF: 0.574528 | Used=9895 | Runtime=14.08s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.7195% | MinDCF: 0.631631 | Used=9895 | Runtime=12.86s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.2325% | MinDCF: 0.578866 | Used=9895 | Runtime=11.25s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.6856% | MinDCF: 0.627922 | Used=9895 | Runtime=14.23s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5233% | MinDCF: 0.610096 | Used=9895 | Runtime=13.50s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=pitch_only | ptm=wav2vec2

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3949% | MinDCF: 0.582643 | Used=9895 | Runtime=14.77s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4693% | MinDCF: 0.584810 | Used=9895 | Runtime=11.61s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=fbank_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: fbank_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5099% | MinDCF: 0.575809 | Used=9895 | Runtime=13.47s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,328,257
  Trainable parameters: 12,328,257
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.5166% | MinDCF: 0.576040 | Used=9895 | Runtime=11.07s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfbe_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,329,537
  Trainable parameters: 12,329,537
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4693% | MinDCF: 0.571196 | Used=9895 | Runtime=12.90s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,277,057
  Trainable parameters: 12,277,057
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.4760% | MinDCF: 0.638501 | Used=9895 | Runtime=12.45s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=mfcc_pitch | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfcc_pitch
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,278,337
  Trainable parameters: 12,278,337
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3204% | MinDCF: 0.582936 | Used=9895 | Runtime=12.23s

==========================================================================================
[INFER] Mode3_gating_train_vi_full_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30 | test_set=test_7s
  mode=3 | fusion=gating | feature=pitch_only | ptm=wavlm

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: pitch_only
  Use gating: True
  Num speakers: 1000
  Total parameters: 12,227,137
  Trainable parameters: 12,227,137
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

  -> EER: 3.3543% | MinDCF: 0.578084 | Used=9895 | Runtime=12.38s
✓ Saved per-test report (overwrite merged): ./outputs\final_inference_report_test_7s.csv

==============================================================================================================
ALL-MODEL TEST BENCHMARK (all test sets, sorted by EER, MinDCF)
==============================================================================================================
TestSet                                                                                               Experiment  Mode Fusion     Feature      PTM   EER (%)   MinDCF  Used Pairs  Missing Pairs  Runtime Feature Load (s)  Runtime Model Load (s)  Runtime Embedding (s)  Runtime Score (s)  Runtime Total (s)  GFLOPs/sample  GFLOPs total  Total Samples Accounted  Peak GPU Memory Allocated (MB)  Peak GPU Memory Reserved (MB)  Total Params  Trainable Params  Param Memory (MB)  Trainable Param Memory (MB)
test_7s     Mode3_concat_train_vi_full_wavlm_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat  mfbe_pitch    wavlm  3.110813 0.543298        9895              0                  0.287583                0.190948              12.765134           0.000366          13.358149       0.011917     32.010260                     2686                      244.901367                          272.0      12329537          12329537          47.033451                    47.033451
test_7s    Mode3_concat_train_vi_full_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat  mfbe_pitch   hubert  3.144679 0.563490        9895              0                  0.283835                0.144644              13.733520           0.000388          14.271443       0.011917     32.010260                     2686                      244.901367                          272.0      12329537          12329537          47.033451                    47.033451
test_7s      Mode3_concat_train_vi_full_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat   mfcc_only    wavlm  3.191970 0.561116        9895              0                  0.231599                0.128448              11.916664           0.000358          12.387068       0.011917     32.010260                     2686                      243.869141                          270.0      12277057          12277057          46.833256                    46.833256
test_7s      Mode3_film_train_vi_full_hubert_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film  mfbe_pitch   hubert  3.191970 0.566876        9895              0                  0.397540                0.141396              11.250539           0.000351          11.904325       0.011395     30.607523                     2686                      240.916992                          268.0      12068417          12068417          46.037357                    46.037357
test_7s    Mode3_concat_train_vi_full_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat fbank_pitch    wavlm  3.225836 0.555624        9895              0                  0.344648                0.178913              12.783242           0.000353          13.414704       0.011407     30.638466                     2686                      244.879883                          264.0      12329537          12329537          47.033451                    47.033451
test_7s  Mode3_gating_train_vi_full_wav2vec2_mfbe_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 gating  mfbe_pitch wav2vec2  3.232548 0.578866        9895              0                  0.291125                0.181051              10.659395           0.000363          11.245925       0.011919     32.014386                     2686                      244.901367                          272.0      12329537          12329537          47.033451                    47.033451
test_7s        Mode3_film_train_vi_full_wavlm_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film   mfcc_only    wavlm  3.239261 0.557534        9895              0                  0.234687                0.127332              12.792815           0.000358          13.272938       0.011395     30.607523                     2686                      239.884766                          266.0      12015937          12015937          45.837162                    45.837162
test_7s      Mode3_film_train_vi_full_wavlm_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film fbank_pitch    wavlm  3.239261 0.557802        9895              0                  0.342157                0.158546              12.426747           0.000362          13.043711       0.010884     29.235729                     2686                      240.895508                          260.0      12068417          12068417          46.037357                    46.037357
test_7s                   Mode1_PTM_train_vi_full_wavlm_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     1    N/A         N/A    wavlm  3.273127 0.567943        9895              0                  0.047125                0.011368               1.095057           0.000345           1.159754       0.000816      2.192807                     2686                       21.985840                           42.0        397057            397057           1.514652                     1.514652
test_7s Mode3_concat_train_vi_full_wav2vec2_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat fbank_pitch wav2vec2  3.273127 0.568591        9895              0                  0.342139                0.182957              13.477501           0.000371          14.112433       0.011407     30.638466                     2686                      244.879883                          264.0      12329537          12329537          47.033451                    47.033451
test_7s    Mode3_gating_train_vi_full_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 gating  mfcc_pitch   hubert  3.279839 0.549607        9895              0                  0.254090                0.138600              11.549776           0.000351          12.049145       0.011919     32.014386                     2686                      243.894531                          270.0      12278337          12278337          46.838139                    46.838139
test_7s     Mode3_concat_train_vi_full_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat  pitch_only    wavlm  3.306993 0.562256        9895              0                  0.185425                0.129155              11.799721           0.000344          12.217857       0.011917     32.010260                     2686                      242.887207                          270.0      12227137          12227137          46.642826                    46.642826
test_7s       Mode3_film_train_vi_full_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film   mfbe_only   hubert  3.313705 0.552816        9895              0                  0.285763                0.147261              11.112988           0.000377          11.659991       0.011395     30.607523                     2686                      240.891602                          268.0      12067137          12067137          46.032475                    46.032475
test_7s    Mode3_film_train_vi_full_wav2vec2_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film  mfcc_pitch wav2vec2  3.313705 0.586225        9895              0                  0.246985                0.152537              11.411866           0.000355          11.922211       0.011395     30.607523                     2686                      239.910156                          266.0      12017217          12017217          45.842045                    45.842045
test_7s   Mode3_concat_train_vi_full_wav2vec2_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat   mfbe_only wav2vec2  3.313705 0.587726        9895              0                  0.420629                0.142857              13.975847           0.000361          14.645307       0.011917     32.010260                     2686                      244.875977                          272.0      12328257          12328257          47.028568                    47.028568
test_7s       Mode3_film_train_vi_full_hubert_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film   mfcc_only   hubert  3.320417 0.566236        9895              0                  0.234042                0.142204              10.538408           0.000355          11.038852       0.011395     30.607523                     2686                      239.884766                          266.0      12015937          12015937          45.837162                    45.837162
test_7s     Mode3_gating_train_vi_full_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 gating  mfcc_pitch    wavlm  3.320417 0.582936        9895              0                  0.241057                0.172251              11.710045           0.000351          12.234893       0.011919     32.014386                     2686                      243.894531                          270.0      12278337          12278337          46.838139                    46.838139
test_7s      Mode3_gating_train_vi_3s_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 gating  mfcc_pitch   hubert  3.320417 0.595031        9895              0                  0.373368                0.137879              11.630863           0.000347          12.246714       0.011919     32.014386                     2686                      243.894531                          270.0      12278337          12278337          46.838139                    46.838139
test_7s    Mode3_concat_train_vi_full_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat  mfcc_pitch   hubert  3.320417 0.597423        9895              0                  0.246229                0.127784              13.564141           0.000359          14.062572       0.011917     32.010260                     2686                      243.894531                          270.0      12278337          12278337          46.838139                    46.838139
test_7s                    Mode1_PTM_train_vi_3s_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     1    N/A         N/A   hubert  3.347571 0.579514        9895              0                  0.046200                0.010187               1.080140           0.000331           1.142676       0.000816      2.192807                     2686                       21.567871                           42.0        397057            397057           1.514652                     1.514652
test_7s     Mode3_gating_train_vi_full_wavlm_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 gating  pitch_only    wavlm  3.354284 0.578084        9895              0                  0.182425                0.172506              11.912815           0.000351          12.378029       0.011919     32.014386                     2686                      242.887207                          270.0      12227137          12227137          46.642826                    46.642826
test_7s      Mode3_film_train_vi_full_hubert_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film  mfcc_pitch   hubert  3.360996 0.577408        9895              0                  0.242065                0.132378              12.502850           0.000347          12.990476       0.011395     30.607523                     2686                      239.910156                          266.0      12017217          12017217          45.842045                    45.842045
test_7s        Mode3_film_train_vi_3s_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film  pitch_only   hubert  3.360996 0.600078        9895              0                  0.182629                0.310717              10.166717           0.000448          10.770146       0.011395     30.607523                     2686                      238.902832                          266.0      11966017          11966017          45.646732                    45.646732
test_7s    Mode3_concat_train_vi_full_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat  fbank_only   hubert  3.360996 0.610444        9895              0                  0.378171                0.156109              12.162572           0.000363          12.808736       0.011407     30.638466                     2686                      244.854980                          264.0      12328257          12328257          47.028568                    47.028568
test_7s                Mode1_PTM_train_vi_full_wav2vec2_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     1    N/A         N/A wav2vec2  3.388150 0.583985        9895              0                  0.143299                0.011613               1.213944           0.000349           1.375031       0.000816      2.192807                     2686                       21.985840                           42.0        397057            397057           1.514652                     1.514652
test_7s      Mode3_film_train_vi_full_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film  pitch_only   hubert  3.388150 0.589991        9895              0                  0.181050                0.128085              12.451634           0.000357          12.870232       0.011395     30.607523                     2686                      238.902832                          266.0      11966017          11966017          45.646732                    45.646732
test_7s       Mode3_film_train_vi_full_wavlm_mfcc_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film  mfcc_pitch    wavlm  3.394862 0.555367        9895              0                  0.243156                0.150390              13.069244           0.000356          13.566682       0.011395     30.607523                     2686                      239.910156                          266.0      12017217          12017217          45.842045                    45.842045
test_7s    Mode3_concat_train_vi_full_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat  pitch_only   hubert  3.394862 0.560841        9895              0                  0.185636                0.152278              11.159445           0.000353          11.607741       0.011917     32.010260                     2686                      242.887207                          270.0      12227137          12227137          46.642826                    46.642826
test_7s      Mode3_film_train_vi_full_hubert_fbank_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film  fbank_only   hubert  3.394862 0.576626        9895              0                  0.354046                0.184705              14.392786           0.000349          15.038724       0.010884     29.235729                     2686                      240.870605                          260.0      12067137          12067137          46.032475                    46.032475
test_7s     Mode3_gating_train_vi_full_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 gating   mfbe_only   hubert  3.394862 0.578030        9895              0                  0.294522                0.140874              11.757071           0.000352          12.295142       0.011919     32.014386                     2686                      244.875977                          272.0      12328257          12328257          47.028568                    47.028568
test_7s     Mode3_film_train_vi_full_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film fbank_pitch   hubert  3.394862 0.581265        9895              0                  0.344469                0.174251              12.857533           0.000349          13.494078       0.010884     29.235729                     2686                      240.895508                          260.0      12068417          12068417          46.037357                    46.037357
test_7s   Mode3_concat_train_vi_full_hubert_fbank_pitch_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat fbank_pitch   hubert  3.394862 0.581949        9895              0                  0.335581                0.159836              12.340705           0.000370          12.950373       0.011407     30.638466                     2686                      244.879883                          264.0      12329537          12329537          47.033451                    47.033451
test_7s    Mode3_gating_train_vi_full_hubert_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 gating  pitch_only   hubert  3.394862 0.582509        9895              0                  0.183569                0.146526              11.825995           0.000364          12.393503       0.011919     32.014386                     2686                      242.887207                          270.0      12227137          12227137          46.642826                    46.642826
test_7s  Mode3_gating_train_vi_full_wav2vec2_pitch_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 gating  pitch_only wav2vec2  3.394862 0.582643        9895              0                  0.182889                0.145080              14.334487           0.000351          14.766999       0.011919     32.014386                     2686                      242.887207                          270.0      12227137          12227137          46.642826                    46.642826
test_7s   Mode3_concat_train_vi_full_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat   mfcc_only wav2vec2  3.394862 0.625827        9895              0                  0.231114                0.127793              12.573927           0.000357          13.049926       0.011917     32.010260                     2686                      243.869141                          270.0      12277057          12277057          46.833256                    46.833256
test_7s                  Mode1_PTM_train_vi_full_hubert_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     1    N/A         N/A   hubert  3.401574 0.568457        9895              0                  0.045911                0.011765               1.237499           0.000352           1.301663       0.000816      2.192807                     2686                       21.985840                           42.0        397057            397057           1.514652                     1.514652
test_7s     Mode3_concat_train_vi_full_hubert_mfbe_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3 concat   mfbe_only   hubert  3.401574 0.578652        9895              0                  0.283094                0.128884              11.309992           0.000356          11.843758       0.011917     32.010260                     2686                      244.875977                          272.0      12328257          12328257          47.028568                    47.028568
test_7s     Mode3_film_train_vi_full_wav2vec2_mfcc_only_bdrop0p3_aug_aam_B_augOn_ap0p2_fn0p005_en0p002_m0p25_s30     3   film   mfcc_only wav2vec2  3.401574 0.603074        9895              0                  0.231803                0.158132              11.266840           0.000378          11.785365       0.011395     30.607523                     2686                      239.884766                          266.0      12015937          12015937          45.837162                    45.837162

## 5. Gating Analysis (Only for Mode 3 + Gating)

In [ ]:
from train import analyze_gating_behavior
import matplotlib.image as mpimg

# Load Best Model
best_model_path = os.path.join(exp_dir, BEST_MODEL_NAME)
model, _, _, _ = load_checkpoint(best_model_path, model)
model = model.to(device)

# Kiểm tra điều kiện để chạy phân tích
if args.mode == 3 and args.fusion_method == "gating":
    print("Đang thực hiện phân tích cơ chế Gating trên tập Test...")
    
    # Gọi hàm phân tích từ train.py
    # Lưu ý: Hàm này trả về 2 giá trị: gates (trọng số PTM) và labels
    gates, labels = analyze_gating_behavior(model, test_loader, device, exp_dir)
    
    # Hiển thị biểu đồ phân phối trọng số đã được lưu
    gate_plot_path = os.path.join(exp_dir, "gating_analysis", "gate_distribution.png")
    if os.path.exists(gate_plot_path):
        plt.figure(figsize=(10, 6))
        img = mpimg.imread(gate_plot_path)
        plt.imshow(img)
        plt.axis('off')
        plt.title("Phân phối trọng số Gating (Trục X > 0.5 ưu tiên PTM, < 0.5 ưu tiên Handcrafted)")
        plt.show()
        
    # In thông tin thống kê tóm tắt
    ptm_wins = np.sum(gates > 0.5)
    hc_wins = np.sum(gates <= 0.5)
    print(f"Thống kê nhanh:")
    print(f"   - Số lần ưu tiên PTM (WavLM/HuBERT): {ptm_wins} ({100*ptm_wins/len(gates):.2f}%)")
    print(f"   - Số lần ưu tiên Handcrafted (MFCC/Pitch): {hc_wins} ({100*hc_wins/len(gates):.2f}%)")
else:
    print("ℹChế độ hiện tại không sử dụng Gating. Bỏ qua bước phân tích này.")

## 6. Experiment Comparison

In [ ]:
import pandas as pd
import os
import json

# List all experiments
exp_base_dir = "./outputs/experiments"
if os.path.exists(exp_base_dir):
    experiments = []
    for exp_name_dir in sorted(os.listdir(exp_base_dir)):
        exp_path = os.path.join(exp_base_dir, exp_name_dir)
        results_file = os.path.join(exp_path, "results.json")
        if os.path.exists(results_file):
            with open(results_file, "r") as f:
                data = json.load(f)
                config = data.get("config", {})
                experiments.append({
                    "Experiment": exp_name_dir,
                    "Mode": config.get("mode", ""),
                    "Fusion": config.get("fusion_method", "N/A"),
                    "Feature": config.get("feature_mode", "N/A"),
                    "PTM": config.get("pretrained_model", "N/A"),
                    "Best Val EER": f"{data.get('best_val_eer', 0):.4f}",
                    "Best Val MinDCF": f"{data.get('best_val_mindcf',0):.4f}",
                    "Epochs": data.get("epochs_trained", 0),
                })
    
    if experiments:
        df = pd.DataFrame(experiments)
        print("\n" + "="*120)
        print("EXPERIMENT COMPARISON")
        print("="*120)
        print(df.to_string(index=False))
        print("="*120)
    else:
        print("No experiments found.")
else:
    print(f"Directory {exp_base_dir} does not exist yet.")

========================================================================================================================
EXPERIMENT COMPARISON
========================================================================================================================
                                    Experiment  Mode Fusion    Feature      PTM Best Val EER Best Val MinDCF  Epochs
                    Mode1_PTM_train_raw_hubert     1               N/A   hubert       8.5400          0.4730      12
                  Mode1_PTM_train_raw_wav2vec2     1               N/A wav2vec2       8.9300          0.4927      16
                     Mode1_PTM_train_raw_wavlm     1               N/A    wavlm       8.2700          0.4640      12
                  Mode1_PTM_train_vi_3s_hubert     1               N/A   hubert       6.2000          0.3231      14
                Mode1_PTM_train_vi_3s_wav2vec2     1               N/A wav2vec2       7.0400          0.3538      14
                   Mode1_PTM_train_vi_3s_wavlm     1               N/A    wavlm       6.0200          0.2925      17
                  Mode1_PTM_train_vi_5s_hubert     1               N/A   hubert       5.4000          0.2893      23
                Mode1_PTM_train_vi_5s_wav2vec2     1               N/A wav2vec2       5.4900          0.2958      21
                   Mode1_PTM_train_vi_5s_wavlm     1               N/A    wavlm       4.7900          0.2289      18
                  Mode1_PTM_train_vi_7s_hubert     1               N/A   hubert       5.5700          0.3234      22
                Mode1_PTM_train_vi_7s_wav2vec2     1               N/A wav2vec2       7.3500          0.3430      23
                   Mode1_PTM_train_vi_7s_wavlm     1               N/A    wavlm       6.1800          0.3305      23
                Mode1_PTM_train_vi_full_hubert     1               N/A   hubert      14.3500          0.7172      12
              Mode1_PTM_train_vi_full_wav2vec2     1               N/A wav2vec2      15.5600          0.7468       8
                 Mode1_PTM_train_vi_full_wavlm     1               N/A    wavlm      14.1700          0.7205       8
                  Mode2_HC_train_raw_mfbe_only     2         mfbe_only      N/A       9.3400          0.5193      31
                 Mode2_HC_train_raw_mfbe_pitch     2        mfbe_pitch      N/A      10.5100          0.6184      23
                  Mode2_HC_train_raw_mfcc_only     2         mfcc_only      N/A      10.2600          0.5674      21
                 Mode2_HC_train_raw_mfcc_pitch     2        mfcc_pitch      N/A      10.1300          0.5153      25
                 Mode2_HC_train_raw_pitch_only     2        pitch_only      N/A      30.8700          1.0000      11
                Mode2_HC_train_vi_3s_mfbe_only     2         mfbe_only      N/A       5.0800          0.2591      10
               Mode2_HC_train_vi_3s_mfbe_pitch     2        mfbe_pitch      N/A       4.7200          0.2411      15
                Mode2_HC_train_vi_3s_mfcc_only     2         mfcc_only      N/A       4.3000          0.2167      22
               Mode2_HC_train_vi_3s_mfcc_pitch     2        mfcc_pitch      N/A       4.5200          0.2151      23
               Mode2_HC_train_vi_3s_pitch_only     2        pitch_only      N/A      22.5400          0.9706      16
                Mode2_HC_train_vi_5s_mfbe_only     2         mfbe_only      N/A       3.8900          0.2132      25
               Mode2_HC_train_vi_5s_mfbe_pitch     2        mfbe_pitch      N/A       4.0900          0.2320      23
                Mode2_HC_train_vi_5s_mfcc_only     2         mfcc_only      N/A       4.8400          0.2408      15
               Mode2_HC_train_vi_5s_mfcc_pitch     2        mfcc_pitch      N/A       4.5700          0.2340      13
               Mode2_HC_train_vi_5s_pitch_only     2        pitch_only      N/A      21.3000          1.0000      17
                Mode2_HC_train_vi_7s_mfbe_only     2         mfbe_only      N/A       7.0400          0.4289      15
               Mode2_HC_train_vi_7s_mfbe_pitch     2        mfbe_pitch      N/A       6.9400          0.4158      14
                Mode2_HC_train_vi_7s_mfcc_only     2         mfcc_only      N/A       6.0600          0.3475      14
               Mode2_HC_train_vi_7s_mfcc_pitch     2        mfcc_pitch      N/A       5.7900          0.3540      31
               Mode2_HC_train_vi_7s_pitch_only     2        pitch_only      N/A      27.1100          0.9994      28
              Mode2_HC_train_vi_full_mfbe_only     2         mfbe_only      N/A      17.0500          0.8089      21
             Mode2_HC_train_vi_full_mfbe_pitch     2        mfbe_pitch      N/A      19.6100          0.8130      18
              Mode2_HC_train_vi_full_mfcc_only     2         mfcc_only      N/A      16.8800          0.8007      19
             Mode2_HC_train_vi_full_mfcc_pitch     2        mfcc_pitch      N/A      18.1100          0.8021      22
             Mode2_HC_train_vi_full_pitch_only     2        pitch_only      N/A      30.2000          0.9997      10
       Mode3_concat_train_raw_hubert_mfbe_only     3 concat  mfbe_only   hubert       7.6400          0.3880      11
      Mode3_concat_train_raw_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       8.4100          0.4271      12
       Mode3_concat_train_raw_hubert_mfcc_only     3 concat  mfcc_only   hubert       8.0300          0.4335       8
      Mode3_concat_train_raw_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       7.6100          0.4009      10
      Mode3_concat_train_raw_hubert_pitch_only     3 concat pitch_only   hubert       9.6600          0.4854       8
     Mode3_concat_train_raw_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       7.5600          0.5043       6
    Mode3_concat_train_raw_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       8.4300          0.4727      10
     Mode3_concat_train_raw_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       8.7900          0.5059       7
    Mode3_concat_train_raw_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       8.0800          0.4811       7
    Mode3_concat_train_raw_wav2vec2_pitch_only     3 concat pitch_only wav2vec2      10.4600          0.5140       7
        Mode3_concat_train_raw_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       8.4700          0.4379       8
       Mode3_concat_train_raw_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       7.6300          0.4412       7
        Mode3_concat_train_raw_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       7.9300          0.4547       7
       Mode3_concat_train_raw_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       8.7400          0.4248       9
       Mode3_concat_train_raw_wavlm_pitch_only     3 concat pitch_only    wavlm       9.7800          0.4269       9
     Mode3_concat_train_vi_3s_hubert_mfbe_only     3 concat  mfbe_only   hubert       4.8400          0.2547       9
    Mode3_concat_train_vi_3s_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       5.2100          0.2421      14
     Mode3_concat_train_vi_3s_hubert_mfcc_only     3 concat  mfcc_only   hubert       4.8500          0.2180       6
    Mode3_concat_train_vi_3s_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       5.2200          0.2802       7
    Mode3_concat_train_vi_3s_hubert_pitch_only     3 concat pitch_only   hubert       7.1700          0.3412      10
   Mode3_concat_train_vi_3s_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       8.3000          0.3974       8
  Mode3_concat_train_vi_3s_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       7.8800          0.3734      11
   Mode3_concat_train_vi_3s_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       8.2300          0.3733      12
  Mode3_concat_train_vi_3s_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       8.3200          0.4019       8
  Mode3_concat_train_vi_3s_wav2vec2_pitch_only     3 concat pitch_only wav2vec2       7.6900          0.3778       8
      Mode3_concat_train_vi_3s_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       5.2900          0.2458       8
     Mode3_concat_train_vi_3s_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       5.0100          0.2223      10
      Mode3_concat_train_vi_3s_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       4.6200          0.2120       7
     Mode3_concat_train_vi_3s_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       5.4400          0.2616       9
     Mode3_concat_train_vi_3s_wavlm_pitch_only     3 concat pitch_only    wavlm       7.0500          0.3595       6
     Mode3_concat_train_vi_5s_hubert_mfbe_only     3 concat  mfbe_only   hubert       4.9000          0.2756       6
    Mode3_concat_train_vi_5s_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       4.8200          0.2590       7
     Mode3_concat_train_vi_5s_hubert_mfcc_only     3 concat  mfcc_only   hubert       5.2500          0.2723       7
    Mode3_concat_train_vi_5s_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       5.1600          0.2581       7
    Mode3_concat_train_vi_5s_hubert_pitch_only     3 concat pitch_only   hubert       7.3200          0.3783      10
   Mode3_concat_train_vi_5s_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       4.7400          0.2490       7
  Mode3_concat_train_vi_5s_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       4.5200          0.2515       8
   Mode3_concat_train_vi_5s_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       5.2600          0.2627      11
  Mode3_concat_train_vi_5s_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       5.1700          0.2664       6
  Mode3_concat_train_vi_5s_wav2vec2_pitch_only     3 concat pitch_only wav2vec2       6.5600          0.3048       9
      Mode3_concat_train_vi_5s_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       4.4000          0.2343       6
     Mode3_concat_train_vi_5s_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       4.5900          0.2442       6
      Mode3_concat_train_vi_5s_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       4.4900          0.2656      11
     Mode3_concat_train_vi_5s_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       4.7600          0.2496       8
     Mode3_concat_train_vi_5s_wavlm_pitch_only     3 concat pitch_only    wavlm       6.0900          0.3091       6
     Mode3_concat_train_vi_7s_hubert_mfbe_only     3 concat  mfbe_only   hubert       5.8300          0.3317      18
    Mode3_concat_train_vi_7s_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       4.7200          0.2914      10
     Mode3_concat_train_vi_7s_hubert_mfcc_only     3 concat  mfcc_only   hubert       5.6100          0.3152      12
    Mode3_concat_train_vi_7s_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       5.8700          0.3717       6
    Mode3_concat_train_vi_7s_hubert_pitch_only     3 concat pitch_only   hubert       7.7900          0.3608      10
   Mode3_concat_train_vi_7s_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       6.4900          0.3690       9
  Mode3_concat_train_vi_7s_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       5.8600          0.3574      10
   Mode3_concat_train_vi_7s_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       6.0800          0.3441      10
  Mode3_concat_train_vi_7s_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       4.8800          0.2764      18
  Mode3_concat_train_vi_7s_wav2vec2_pitch_only     3 concat pitch_only wav2vec2       8.5600          0.3684      13
      Mode3_concat_train_vi_7s_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       5.4000          0.3595       7
     Mode3_concat_train_vi_7s_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       5.1300          0.3255      12
      Mode3_concat_train_vi_7s_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       5.6800          0.3400      12
     Mode3_concat_train_vi_7s_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       5.5400          0.2980      12
     Mode3_concat_train_vi_7s_wavlm_pitch_only     3 concat pitch_only    wavlm       8.6300          0.3712      14
   Mode3_concat_train_vi_full_hubert_mfbe_only     3 concat  mfbe_only   hubert      13.7400          0.7044       6
  Mode3_concat_train_vi_full_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert      14.2800          0.7012       7
   Mode3_concat_train_vi_full_hubert_mfcc_only     3 concat  mfcc_only   hubert      13.6700          0.7039       6
  Mode3_concat_train_vi_full_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert      15.2000          0.7573       6
  Mode3_concat_train_vi_full_hubert_pitch_only     3 concat pitch_only   hubert      12.8300          0.6938       6
 Mode3_concat_train_vi_full_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2      15.1600          0.7404       6
Mode3_concat_train_vi_full_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2      15.1600          0.7350       6
 Mode3_concat_train_vi_full_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2      15.4100          0.7327       6
Mode3_concat_train_vi_full_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2      15.5600          0.7426       6
Mode3_concat_train_vi_full_wav2vec2_pitch_only     3 concat pitch_only wav2vec2      13.6900          0.7238       6
    Mode3_concat_train_vi_full_wavlm_mfbe_only     3 concat  mfbe_only    wavlm      15.8500          0.7130       7
   Mode3_concat_train_vi_full_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm      14.8000          0.7250       6
    Mode3_concat_train_vi_full_wavlm_mfcc_only     3 concat  mfcc_only    wavlm      14.8200          0.7214       6
   Mode3_concat_train_vi_full_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm      16.3300          0.7381       6
   Mode3_concat_train_vi_full_wavlm_pitch_only     3 concat pitch_only    wavlm      15.1300          0.7270       7
         Mode3_film_train_raw_hubert_mfbe_only     3   film  mfbe_only   hubert       7.9100          0.4105      10
        Mode3_film_train_raw_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       8.2400          0.4257       8
         Mode3_film_train_raw_hubert_mfcc_only     3   film  mfcc_only   hubert       7.7900          0.4055      12
        Mode3_film_train_raw_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       7.3900          0.4016      14
        Mode3_film_train_raw_hubert_pitch_only     3   film pitch_only   hubert       8.8800          0.4475       9
       Mode3_film_train_raw_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       8.2900          0.4504      10
      Mode3_film_train_raw_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       8.0100          0.4273      12
       Mode3_film_train_raw_wav2vec2_mfcc_only     3   film  mfcc_only wav2vec2       8.0600          0.4309      10
      Mode3_film_train_raw_wav2vec2_mfcc_pitch     3   film mfcc_pitch wav2vec2       7.7300          0.4347      11
      Mode3_film_train_raw_wav2vec2_pitch_only     3   film pitch_only wav2vec2       9.0100          0.4608       9
          Mode3_film_train_raw_wavlm_mfbe_only     3   film  mfbe_only    wavlm       8.0000          0.4469       7
         Mode3_film_train_raw_wavlm_mfbe_pitch     3   film mfbe_pitch    wavlm       7.8300          0.4211      10
          Mode3_film_train_raw_wavlm_mfcc_only     3   film  mfcc_only    wavlm       7.6500          0.4142       8
         Mode3_film_train_raw_wavlm_mfcc_pitch     3   film mfcc_pitch    wavlm       7.3500          0.4253       8
         Mode3_film_train_raw_wavlm_pitch_only     3   film pitch_only    wavlm       9.2800          0.4910       7
       Mode3_film_train_vi_3s_hubert_mfbe_only     3   film  mfbe_only   hubert       4.1000          0.2046      14
      Mode3_film_train_vi_3s_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       4.4500          0.1995      10
       Mode3_film_train_vi_3s_hubert_mfcc_only     3   film  mfcc_only   hubert       4.4000          0.2155       8
      Mode3_film_train_vi_3s_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       4.2000          0.1900       6
      Mode3_film_train_vi_3s_hubert_pitch_only     3   film pitch_only   hubert       6.0200          0.2816      13
     Mode3_film_train_vi_3s_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       6.4900          0.3317      11
    Mode3_film_train_vi_3s_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       6.8000          0.3174      15
     Mode3_film_train_vi_3s_wav2vec2_mfcc_only     3   film  mfcc_only wav2vec2       6.9500          0.3646      10
    Mode3_film_train_vi_3s_wav2vec2_mfcc_pitch     3   film mfcc_pitch wav2vec2       6.7800          0.3418      11
    Mode3_film_train_vi_3s_wav2vec2_pitch_only     3   film pitch_only wav2vec2       6.7500          0.3430      12
        Mode3_film_train_vi_3s_wavlm_mfbe_only     3   film  mfbe_only    wavlm       4.6400          0.2102      17
       Mode3_film_train_vi_3s_wavlm_mfbe_pitch     3   film mfbe_pitch    wavlm       4.6200          0.2233      10
        Mode3_film_train_vi_3s_wavlm_mfcc_only     3   film  mfcc_only    wavlm       4.1900          0.1967      11
       Mode3_film_train_vi_3s_wavlm_mfcc_pitch     3   film mfcc_pitch    wavlm       4.5600          0.2286       9
       Mode3_film_train_vi_3s_wavlm_pitch_only     3   film pitch_only    wavlm       5.8400          0.2657       9
       Mode3_film_train_vi_5s_hubert_mfbe_only     3   film  mfbe_only   hubert       4.2200          0.2233       7
      Mode3_film_train_vi_5s_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       4.2200          0.2167       9
       Mode3_film_train_vi_5s_hubert_mfcc_only     3   film  mfcc_only   hubert       4.5000          0.2457       7
      Mode3_film_train_vi_5s_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       3.9400          0.2070       9
      Mode3_film_train_vi_5s_hubert_pitch_only     3   film pitch_only   hubert       5.7300          0.2890       7
     Mode3_film_train_vi_5s_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       4.0600          0.2048       7
    Mode3_film_train_vi_5s_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       3.9800          0.2097       8
     Mode3_film_train_vi_5s_wav2vec2_mfcc_only     3   film  mfcc_only wav2vec2       4.3300          0.2373       8
    Mode3_film_train_vi_5s_wav2vec2_mfcc_pitch     3   film mfcc_pitch wav2vec2       4.5500          0.2260       9
    Mode3_film_train_vi_5s_wav2vec2_pitch_only     3   film pitch_only wav2vec2       5.7400          0.2849       8
        Mode3_film_train_vi_5s_wavlm_mfbe_only     3   film  mfbe_only    wavlm       4.0200          0.2195       7
       Mode3_film_train_vi_5s_wavlm_mfbe_pitch     3   film mfbe_pitch    wavlm       3.8000          0.1954       8
        Mode3_film_train_vi_5s_wavlm_mfcc_only     3   film  mfcc_only    wavlm       3.9100          0.2153       6
       Mode3_film_train_vi_5s_wavlm_mfcc_pitch     3   film mfcc_pitch    wavlm       4.2100          0.2096       8
       Mode3_film_train_vi_5s_wavlm_pitch_only     3   film pitch_only    wavlm       5.5300          0.2441      10
       Mode3_film_train_vi_7s_hubert_mfbe_only     3   film  mfbe_only   hubert       3.8600          0.2715      14
      Mode3_film_train_vi_7s_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       4.6100          0.3042      12
       Mode3_film_train_vi_7s_hubert_mfcc_only     3   film  mfcc_only   hubert       3.7500          0.2686      13
      Mode3_film_train_vi_7s_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       3.0900          0.2129      23
      Mode3_film_train_vi_7s_hubert_pitch_only     3   film pitch_only   hubert       6.0500          0.3368      11
     Mode3_film_train_vi_7s_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       4.5200          0.3154      12
    Mode3_film_train_vi_7s_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       4.5400          0.3121       8

In [ ]:
import gc
import glob
import os

import torch
from train import train

# ==============================
# RUN TRAIN_RAW - MODE 1/2/3 - 7 HC FEATURES
# ==============================

ROOT_DIR = "D:/"
EMBEDDING_PATH = r"F:/train_raw/wav2vec2_shards"
HC_BASE = r"D:/extracted_features/train_raw"

# PTM input mode:
# - "precomputed": dùng PTM shards tại EMBEDDING_PATH
# - "on_the_fly": đọc waveform từ AUDIO_BASE_DIR và trích PTM trong model runtime
PTM_INPUT_MODE = "on_the_fly"
if PTM_INPUT_MODE not in ["precomputed", "on_the_fly"]:
    raise ValueError(f"SV_PTM_INPUT_MODE must be precomputed|on_the_fly, got: {PTM_INPUT_MODE}")

USE_PTM_ON_THE_FLY = PTM_INPUT_MODE == "on_the_fly"
PTM_MODEL_ID = "facebook/wav2vec2-base"
AUDIO_BASE_DIR = r"D:/Speech_Verification/audio/train_raw"
AUDIO_SAMPLE_RATE = 16000
MAX_AUDIO_SECONDS = 4

print(f"PTM input mode: {PTM_INPUT_MODE}")
if USE_PTM_ON_THE_FLY:
    if not AUDIO_BASE_DIR:
        raise ValueError(
            "SV_AUDIO_BASE_DIR is required for on_the_fly mode. "
            "Example: set SV_AUDIO_BASE_DIR to your train_raw audio root."
        )
    print(f"PTM runtime model: {PTM_MODEL_ID}")
    print(f"Audio base dir: {AUDIO_BASE_DIR}")

# Re-shard config mới
PTM_SAMPLES_PER_SHARD = 200

# Gợi ý an toàn RAM/VRAM
MODE1_BATCH_SIZE = 16
MODE2_BATCH_SIZE = 128
MODE3_BATCH_SIZE = 16
MODE2_MAX_FRAMES = 350
MODE3_MAX_FRAMES = 350
MODE2_VAL_BATCH_SIZE = 128
MODE3_VAL_BATCH_SIZE = 16
MODE3_MIXED_PRECISION = True
VALIDATE_EVERY_EPOCHS = 1
# Fast-epoch knobs: giảm mạnh wall-time mỗi epoch cho on_the_fly
MAX_TRAIN_STEPS_PER_EPOCH = 2500
TRAIN_SUBSET_FRACTION = 0.30
MAX_TRAIN_SAMPLES = 0

# DataLoader knobs (điều chỉnh trực tiếp trong notebook, không dùng env)
NUM_WORKERS = 6
WIN_MODE13_MAX_WORKERS = 6
PIN_MEMORY = True
PERSISTENT_WORKERS = True
PREFETCH_FACTOR = 6
NON_BLOCKING_TRANSFER = True

# Chặn sớm trường hợp shard quá lớn gây crash kernel
MAX_SAFE_SHARD_GB = 8

# Nếu shard PTM quá lớn, mặc định KHÔNG chạy Mode 3 để tránh kernel crash.
# Muốn ép chạy: set SV_ALLOW_MODE3_LARGE_SHARD=1 trước khi chạy cell.
ALLOW_MODE3_LARGE_SHARD = False

FEATURE_DIRS_7 = [
    "mfbe_shards",
    "mfcc_shards",
    "pitch_shards",
    "mfbe_pitch_shards",
    "mfcc_pitch_shards",
    "fbank_shards",
    "fbank_pitch_shards",
]
MODE2_FEATURE_DIRS = ["fbank_shards", "fbank_pitch_shards"]
MODE3_FEATURE_DIRS = FEATURE_DIRS_7

FEAT_MODE_MAP = {
    "mfbe_shards": "mfbe_only",
    "mfcc_shards": "mfcc_only",
    "pitch_shards": "pitch_only",
    "mfbe_pitch_shards": "mfbe_pitch",
    "mfcc_pitch_shards": "mfcc_pitch",
    "fbank_shards": "fbank_only",
    "fbank_pitch_shards": "fbank_pitch",
}

EXPERIMENTS_DIRNAME = "experiments_train_raw_w2v2_7hc"

# cross_attention tốn VRAM; chỉ bật khi thực sự cần
RUN_CROSS_ATTENTION = False
FUSION_METHODS_MODE3 = ["gating", "film", "concat"] + (["cross_attention"] if RUN_CROSS_ATTENTION else [])

# Giảm phân mảnh CUDA allocator: cấu hình trực tiếp theo biến notebook, không dùng env var.
PYTORCH_CUDA_ALLOC_CONF = "expandable_segments:True,max_split_size_mb:128"


def _cleanup_after_run():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def _run_train_safe(args, tag):
    try:
        train(args)
    finally:
        _cleanup_after_run()
        print(f"[CLEANUP] Done after {tag}")


def _largest_ptm_shard_gb(shard_dir):
    if not os.path.isdir(shard_dir):
        return 0.0, None
    max_size = 0
    max_name = None
    for fn in os.listdir(shard_dir):
        if not fn.endswith(".pt"):
            continue
        fp = os.path.join(shard_dir, fn)
        sz = os.path.getsize(fp)
        if sz > max_size:
            max_size = sz
            max_name = fn
    return max_size / (1024 ** 3), max_name


def _precheck_embedding_shards_or_raise(shard_dir):
    biggest_gb, biggest_name = _largest_ptm_shard_gb(shard_dir)
    print(f"Largest PTM shard: {biggest_name} | {biggest_gb:.2f} GB")
    if biggest_gb > MAX_SAFE_SHARD_GB:
        print(
            f"[WARN] PTM shard quá lớn ({biggest_gb:.2f} GB > {MAX_SAFE_SHARD_GB:.2f} GB). "
            f"Tiếp tục chạy theo aligned-prefix mode (không chặn bằng RuntimeError)."
        )
    return biggest_gb


def _apply_ptm_runtime_args(args):
    args.use_ptm_on_the_fly = bool(USE_PTM_ON_THE_FLY)
    args.ptm_model_id = PTM_MODEL_ID
    args.audio_base_dir = AUDIO_BASE_DIR
    args.audio_sample_rate = int(AUDIO_SAMPLE_RATE)
    args.max_audio_seconds = float(MAX_AUDIO_SECONDS)
    args.num_workers = int(NUM_WORKERS)
    args.win_mode13_max_workers = int(WIN_MODE13_MAX_WORKERS)
    args.pin_memory = bool(PIN_MEMORY)
    args.persistent_workers = bool(PERSISTENT_WORKERS)
    args.prefetch_factor = int(PREFETCH_FACTOR)
    args.non_blocking_transfer = bool(NON_BLOCKING_TRANSFER)
    args.validate_every = int(VALIDATE_EVERY_EPOCHS)
    args.max_train_steps_per_epoch = int(MAX_TRAIN_STEPS_PER_EPOCH)
    args.train_subset_fraction = float(TRAIN_SUBSET_FRACTION)
    args.max_train_samples = int(MAX_TRAIN_SAMPLES)


def run_train_mode1_mode2_mode3_7hc():
    if USE_PTM_ON_THE_FLY:
        biggest_gb = 0.0
        should_run_mode1 = False
        should_run_mode3 = True
        print("[INFO] on_the_fly mode: skip PTM shard precheck and disable Mode1 in this cell.")
    else:
        biggest_gb = _precheck_embedding_shards_or_raise(EMBEDDING_PATH)
        allow_mode1_with_large_shard = False
        should_run_mode1 = (biggest_gb <= MAX_SAFE_SHARD_GB) or allow_mode1_with_large_shard
        should_run_mode3 = (biggest_gb <= MAX_SAFE_SHARD_GB) or ALLOW_MODE3_LARGE_SHARD

    # --------------------------
    # MODE 1: PTM only (run once)
    # --------------------------
    mode1_exp_name = "Mode1_PTM_train_raw_wav2vec2"
    mode1_ckpt = os.path.join("./outputs", EXPERIMENTS_DIRNAME, mode1_exp_name, "best_model.pth")

    if USE_PTM_ON_THE_FLY:
        print("[SKIP] MODE1 disabled in on_the_fly mode (cell này tập trung Mode3 fusion).")
    elif should_run_mode1 and not os.path.isfile(mode1_ckpt):
        args = get_base_args()
        args.output_dir = "./outputs"
        args.experiments_dirname = EXPERIMENTS_DIRNAME
        args.mode = 1
        args.duration = "train_raw"
        args.pretrained_model = "wav2vec2"
        args.embedding_path = EMBEDDING_PATH
        args.feature_path = ""
        args.feature_mode = "mfcc_pitch"
        args.batch_size = MODE1_BATCH_SIZE
        args.max_frames = MODE2_MAX_FRAMES
        args.val_batch_size = MODE2_VAL_BATCH_SIZE
        args.skip_model_summary = True
        args.num_epochs = 50
        args.early_stop_patience = 7
        args.lr_scheduler = "plateau"
        args.lr_scheduler_patience = 3
        args.use_augment = True
        args.exp_name = mode1_exp_name
        _apply_ptm_runtime_args(args)

        print("\n" + "=" * 80)
        print(f"RUN MODE1: {args.exp_name}")
        print("=" * 80)
        _run_train_safe(args, args.exp_name)
    elif not should_run_mode1:
        print("[SKIP] MODE1 vì PTM shard quá lớn, tránh crash kernel.")
    else:
        print(f"[SKIP] MODE1 checkpoint already exists: {mode1_ckpt}")

    # --------------------------
    # MODE 2: chỉ chạy fbank + fbank_pitch
    # --------------------------
    for feat_dir in MODE2_FEATURE_DIRS:
        feature_path = os.path.join(HC_BASE, feat_dir)
        feat_mode = FEAT_MODE_MAP[feat_dir]

        if not os.path.isdir(feature_path):
            print(f"[SKIP] Missing feature shard dir: {feature_path}")
            continue

        mode2_exp_name = f"Mode2_HC_train_raw_{feat_mode}"
        mode2_ckpt = os.path.join("./outputs", EXPERIMENTS_DIRNAME, mode2_exp_name, "best_model.pth")

        if not os.path.isfile(mode2_ckpt):
            args = get_base_args()
            args.output_dir = "./outputs"
            args.experiments_dirname = EXPERIMENTS_DIRNAME
            args.mode = 2
            args.duration = "train_raw"
            args.pretrained_model = "wav2vec2"
            args.embedding_path = EMBEDDING_PATH
            args.feature_path = feature_path
            args.feature_mode = feat_mode
            args.batch_size = MODE2_BATCH_SIZE
            args.max_frames = MODE2_MAX_FRAMES
            args.val_batch_size = MODE2_VAL_BATCH_SIZE
            args.skip_model_summary = True
            args.num_epochs = 50
            args.early_stop_patience = 7
            args.lr_scheduler = "plateau"
            args.lr_scheduler_patience = 3
            args.fusion_method = "concat"
            args.use_gating = False
            args.use_augment = True
            args.exp_name = mode2_exp_name
            _apply_ptm_runtime_args(args)

            print("\n" + "=" * 80)
            print(f"RUN MODE2: {args.exp_name}")
            print("=" * 80)
            _run_train_safe(args, args.exp_name)
        else:
            print(f"[SKIP] MODE2 checkpoint already exists: {mode2_ckpt}")

    # --------------------------
    # MODE 3: vẫn chạy đủ 7 HC features
    # --------------------------
    if not should_run_mode3:
        print(
            "[SKIP] MODE3 vì PTM shard đang quá lớn so với ngưỡng an toàn. "
            "Để ép chạy (có rủi ro crash), set SV_ALLOW_MODE3_LARGE_SHARD=1."
        )
    else:
        for feat_dir in MODE3_FEATURE_DIRS:
            feature_path = os.path.join(HC_BASE, feat_dir)
            feat_mode = FEAT_MODE_MAP[feat_dir]

            if not os.path.isdir(feature_path):
                print(f"[SKIP] Missing feature shard dir: {feature_path}")
                continue

            for fusion in FUSION_METHODS_MODE3:
                mode3_exp_name = f"Mode3_{fusion}_train_raw_wav2vec2_{feat_mode}"
                mode3_ckpt = os.path.join("./outputs", EXPERIMENTS_DIRNAME, mode3_exp_name, "best_model.pth")

                if os.path.isfile(mode3_ckpt):
                    print(f"[SKIP] MODE3 checkpoint already exists: {mode3_ckpt}")
                    continue

                args = get_base_args()
                args.output_dir = "./outputs"
                args.experiments_dirname = EXPERIMENTS_DIRNAME
                args.mode = 3
                args.duration = "train_raw"
                args.pretrained_model = "wav2vec2"
                args.embedding_path = "" if USE_PTM_ON_THE_FLY else EMBEDDING_PATH
                args.feature_path = feature_path
                args.feature_mode = feat_mode
                args.fusion_method = fusion
                args.use_gating = (fusion == "gating")
                args.branch_dropout_prob = 0.05
                args.batch_size = MODE3_BATCH_SIZE
                args.max_frames = MODE3_MAX_FRAMES
                args.val_batch_size = MODE3_VAL_BATCH_SIZE
                args.learning_rate = 5e-5
                args.mixed_precision = bool(MODE3_MIXED_PRECISION)
                args.skip_model_summary = True
                args.num_epochs = 50
                args.early_stop_patience = 7
                args.lr_scheduler = "plateau"
                args.lr_scheduler_patience = 3
                args.use_augment = True
                args.use_two_stage_ft = False
                args.stage1_epochs = 6
                args.stage2_ptm_lr_scale = 0.35
                args.freeze_ptm_extractor = True
                args.train_mode3_ptm_layer_fusion = True
                args.use_mode3_warmstart = False
                args.use_mode3_init_mode1 = False
                args.use_mode3_init_mode2 = False
                # Train Mode3 from scratch (no warm-start for early-fusion setup)
                args.init_mode1_ckpt = None
                args.init_mode2_ckpt = None
                args.exp_name = mode3_exp_name
                _apply_ptm_runtime_args(args)

                print("\n" + "=" * 80)
                print(f"RUN MODE3: {args.exp_name}")
                print("=" * 80)
                _run_train_safe(args, args.exp_name)


run_train_mode1_mode2_mode3_7hc()

PTM input mode: on_the_fly
PTM runtime model: facebook/wav2vec2-base
Audio base dir: D:/Speech_Verification/audio/train_raw
[INFO] on_the_fly mode: skip PTM shard precheck and disable Mode1 in this cell.
[SKIP] MODE1 disabled in on_the_fly mode (cell này tập trung Mode3 fusion).
[SKIP] MODE2 checkpoint already exists: ./outputs\experiments_train_raw_w2v2_7hc\Mode2_HC_train_raw_fbank_only\best_model.pth
[SKIP] MODE2 checkpoint already exists: ./outputs\experiments_train_raw_w2v2_7hc\Mode2_HC_train_raw_fbank_pitch\best_model.pth

================================================================================
RUN MODE3: Mode3_gating_train_raw_wav2vec2_mfbe_only
================================================================================
TensorBoard logs will be saved to: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_gating_train_raw_wav2vec2_mfbe_only\tensorboard_logs

================================================================================
SPEAKER VERIFICATION TRAINING - CONFIGURATION
================================================================================
Experiment Name                Mode3_gating_train_raw_wav2vec2_mfbe_only
Device                         cuda
Mode                           3 (1=PTM, 2=Handcrafted, 3=Fusion)
Fusion Method                  gating
Feature Mode                   mfbe_only
PTM Input Source               on-the-fly
Use Gating                     True
Use Augment                    True
PTM On-the-fly                 True
PTM Runtime Model              facebook/wav2vec2-base
Audio Base Dir                 D:/Speech_Verification/audio/train_raw
Audio Sample Rate              16000

Learning Rate                  5e-05
Optimizer                      ADAM
Batch Size                     16
Epochs                         50
Weight Decay                   0.001
Mixed Precision                True

Early Stop Patience            7
LR Scheduler                   plateau
AAM Margin                     0.25
AAM Scale                      30
Branch Dropout (Mode3)         0.05
Use 2-Stage FT (Mode3)         False
Stage1 Epochs                  6
Stage2 PTM LR Scale            0.35
Mode3 Warm-start               False
Mode3 PTM Residual Alpha       0.0
Freeze PTM Extractor           True
Train PTM Layer Fusion         True

Experiment Dir                 ./outputs\experiments_train_raw_w2v2_7hc\Mode3_gating_train_raw_wav2vec2_mfbe_only
================================================================================

Spk-Balanced Sampler           False
Hard Negative Mining           False
Hard Neg Weight/TopK           0.03 / 8
Augment Prob                   0.3
Feature Noise Std              0.003
Embedding Noise Std            0.002
Validation Batch Size          16
Num Workers                    6
Pin Memory                     True
Persistent Workers             True
Prefetch Factor                6
Validate Every (epochs)        1
Max Train Steps/Epoch          2500
Train Subset Fraction          0.300
Max Train Samples              All
Val Max Pos Pairs              5000
Loading Train/Val data...
ℹ Mode3 join mode: filename-based (aligned fast-path disabled).
🔍 Đang nạp metadata Handcrafted từ: D:/extracted_features/train_raw\mfbe_shards...
✅ Đã nạp xong metadata 26 HC shards. Tổng số sample HC: 258168
📦 PTM input source: on-the-fly audio
✅ Mode3 on-the-fly: dùng HC metadata làm sample index (258168 samples), bỏ qua PTM precomputed shards.

🎤 CHIA DỮ LIỆU THEO OPEN-SET (Unseen Speakers):
   - Tập Train: 2023 speakers (231657 samples)
   - Tập Val:   357 speakers (26511 samples)

[FAST-EPOCH] Train subset fraction applied: 0.300 -> 69497 train samples
✓ Loaded 2023 speakers
  Train: 69497, Val: 26511

Creating model...

c:\Users\Dung\anaconda3\Lib\site-packages\transformers\configuration_utils.py:334: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.05
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 2023
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

ℹ Mode3 warm-start disabled by args.use_mode3_warmstart=False

Generating model summary...
✓ Model summary saved to ./outputs\experiments_train_raw_w2v2_7hc\Mode3_gating_train_raw_wav2vec2_mfbe_only\model_summary.txt

[Trainable Params by Group]
  - PTM Extractor     : 0
  - PTM Layer Fusion  : 3,841
  - HC Encoder        : 891,904
  - Temporal Fusion   : 1,771,008
  - Speaker Backbone  : 9,723,456

c:\Users\Dung\anaconda3\Lib\site-packages\torch\profiler\profiler.py:217: UserWarning: Warning: Profiler clears events at the end of each cycle.Only events from the current cycle will be reported.To keep events across cycles, set acc_events=True.
  _warn_once(

[PROFILE] Estimated GFLOPs/sample (actual batch profiler): 34.6817
Đang chuẩn bị fixed validation trials...
✓ Đã nạp fixed validation trials: ./outputs\fixed_val_trials\val_trials_train_raw_26511s_357spk_3cf0118b3732.json
✓ Đã đồng bộ trial protocol csv: ./outputs\fixed_val_trials\val_trials_train_raw_26511s_357spk_3cf0118b3732.csv
  Positive pairs: 5000 | Negative pairs: 5000
Starting training...

Epoch   1 | Train Loss: 8.8790, Acc: 0.2429 | EER: 14.90%, MinDCF: 0.7490 | LR: 0.000050 | TrainTime: 4632.08s, ValTime: 3461.12s, EpochTime: 8093.19s

Epoch   2 | Train Loss: 6.1482, Acc: 0.3694 | EER: 13.40%, MinDCF: 0.6708 | LR: 0.000050 | TrainTime: 4562.86s, ValTime: 3057.94s, EpochTime: 7620.80s

Epoch   3 | Train Loss: 4.9211, Acc: 0.4472 | EER: 13.44%, MinDCF: 0.5952 | LR: 0.000050 | TrainTime: 5239.19s, ValTime: 3454.17s, EpochTime: 8693.35s
EarlyStopping counter: 1/7

Epoch   4 | Train Loss: 4.1750, Acc: 0.5040 | EER: 11.74%, MinDCF: 0.5572 | LR: 0.000050 | TrainTime: 5081.56s, ValTime: 3349.74s, EpochTime: 8431.29s

Epoch   5 | Train Loss: 3.5761, Acc: 0.5536 | EER: 12.04%, MinDCF: 0.5616 | LR: 0.000050 | TrainTime: 4986.23s, ValTime: 2273.27s, EpochTime: 7259.50s
EarlyStopping counter: 1/7

Epoch   6 | Train Loss: 3.1858, Acc: 0.5862 | EER: 10.44%, MinDCF: 0.5084 | LR: 0.000050 | TrainTime: 4540.42s, ValTime: 2978.87s, EpochTime: 7519.28s

Epoch   7 | Train Loss: 2.8479, Acc: 0.6178 | EER: 9.86%, MinDCF: 0.4702 | LR: 0.000050 | TrainTime: 4519.87s, ValTime: 2975.19s, EpochTime: 7495.05s

Epoch   8 | Train Loss: 2.5616, Acc: 0.6444 | EER: 10.44%, MinDCF: 0.4854 | LR: 0.000050 | TrainTime: 4507.66s, ValTime: 2973.80s, EpochTime: 7481.46s
EarlyStopping counter: 1/7

Epoch   9 | Train Loss: 2.3387, Acc: 0.6684 | EER: 10.24%, MinDCF: 0.4822 | LR: 0.000050 | TrainTime: 4379.58s, ValTime: 2143.81s, EpochTime: 6523.39s
EarlyStopping counter: 2/7

Epoch  10 | Train Loss: 2.1329, Acc: 0.6904 | EER: 10.18%, MinDCF: 0.4462 | LR: 0.000050 | TrainTime: 3209.90s, ValTime: 2126.46s, EpochTime: 5336.37s
EarlyStopping counter: 3/7

Epoch  11 | Train Loss: 1.9507, Acc: 0.7113 | EER: 9.84%, MinDCF: 0.4732 | LR: 0.000050 | TrainTime: 3184.44s, ValTime: 2531.55s, EpochTime: 5715.98s

Epoch  12 | Train Loss: 1.8117, Acc: 0.7266 | EER: 10.78%, MinDCF: 0.5022 | LR: 0.000050 | TrainTime: 5071.73s, ValTime: 3187.93s, EpochTime: 8259.66s
EarlyStopping counter: 1/7

Epoch  13 | Train Loss: 1.6648, Acc: 0.7442 | EER: 10.78%, MinDCF: 0.5028 | LR: 0.000050 | TrainTime: 4740.38s, ValTime: 2763.48s, EpochTime: 7503.86s
EarlyStopping counter: 2/7

Epoch  14 | Train Loss: 1.5559, Acc: 0.7593 | EER: 10.30%, MinDCF: 0.5020 | LR: 0.000050 | TrainTime: 3238.01s, ValTime: 2138.70s, EpochTime: 5376.71s
EarlyStopping counter: 3/7

Epoch  15 | Train Loss: 1.4527, Acc: 0.7734 | EER: 8.64%, MinDCF: 0.4366 | LR: 0.000050 | TrainTime: 3229.78s, ValTime: 2144.01s, EpochTime: 5373.79s

Epoch  16 | Train Loss: 1.3526, Acc: 0.7873 | EER: 9.18%, MinDCF: 0.5002 | LR: 0.000050 | TrainTime: 3210.22s, ValTime: 2153.69s, EpochTime: 5363.91s
EarlyStopping counter: 1/7

Epoch  17 | Train Loss: 1.2579, Acc: 0.8010 | EER: 9.54%, MinDCF: 0.4526 | LR: 0.000050 | TrainTime: 3223.86s, ValTime: 2609.80s, EpochTime: 5833.65s
EarlyStopping counter: 2/7

Epoch  18 | Train Loss: 1.1742, Acc: 0.8110 | EER: 9.24%, MinDCF: 0.4490 | LR: 0.000050 | TrainTime: 4556.70s, ValTime: 2987.73s, EpochTime: 7544.43s
EarlyStopping counter: 3/7

Epoch  19 | Train Loss: 1.1066, Acc: 0.8219 | EER: 11.02%, MinDCF: 0.4980 | LR: 0.000025 | TrainTime: 4473.63s, ValTime: 2948.69s, EpochTime: 7422.32s
EarlyStopping counter: 4/7

Epoch  20 | Train Loss: 0.9067, Acc: 0.8581 | EER: 9.98%, MinDCF: 0.4632 | LR: 0.000025 | TrainTime: 4457.70s, ValTime: 2953.93s, EpochTime: 7411.63s
EarlyStopping counter: 5/7

Epoch  21 | Train Loss: 0.8381, Acc: 0.8722 | EER: 9.72%, MinDCF: 0.4612 | LR: 0.000025 | TrainTime: 4929.86s, ValTime: 3416.99s, EpochTime: 8346.84s
EarlyStopping counter: 6/7

Epoch  22 | Train Loss: 0.7699, Acc: 0.8817 | EER: 9.96%, MinDCF: 0.4402 | LR: 0.000025 | TrainTime: 5181.67s, ValTime: 3416.98s, EpochTime: 8598.65s
EarlyStopping counter: 7/7

✓ Early stopping triggered!

Analyzing gating weights...

[CLEANUP] Done after Mode3_gating_train_raw_wav2vec2_mfbe_only

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (26511,) + inhomogeneous part.

In [ ]:
# Single run standalone: Mode3_film_train_raw_wav2vec2_mfcc_pitch
import argparse
import gc
import os

import torch
from train import train

# ==============================
# STANDALONE CONFIG
# ==============================
ROOT_DIR = "D:/"
EMBEDDING_PATH = r"F:/train_raw/wav2vec2_shards"
HC_BASE = r"D:/extracted_features/train_raw"

PTM_INPUT_MODE = "on_the_fly"  # "precomputed" | "on_the_fly"
PTM_MODEL_ID = "facebook/wav2vec2-base"
AUDIO_BASE_DIR = r"D:/Speech_Verification/audio/train_raw"
AUDIO_SAMPLE_RATE = 16000
MAX_AUDIO_SECONDS = 4

EXPERIMENTS_DIRNAME = "experiments_train_raw_w2v2_7hc"

MODE3_BATCH_SIZE = 16
MODE3_MAX_FRAMES = 350
MODE3_VAL_BATCH_SIZE = 16
MODE3_MIXED_PRECISION = True

# DataLoader / speed knobs
NUM_WORKERS = 6
WIN_MODE13_MAX_WORKERS = 6
PIN_MEMORY = True
PERSISTENT_WORKERS = True
PREFETCH_FACTOR = 6
NON_BLOCKING_TRANSFER = True

# Train speed knobs
VALIDATE_EVERY_EPOCHS = 1
MAX_TRAIN_STEPS_PER_EPOCH = 2500
TRAIN_SUBSET_FRACTION = 0.30
MAX_TRAIN_SAMPLES = 0

# Fast validation knobs
FAST_VAL = True
FAST_VAL_EVERY = 2               # validate every 2 epochs
FAST_VAL_MAX_POS_PAIRS = 2500    # fewer validation pairs

USE_PTM_ON_THE_FLY = PTM_INPUT_MODE == "on_the_fly"
if PTM_INPUT_MODE not in ["precomputed", "on_the_fly"]:
    raise ValueError(f"PTM_INPUT_MODE must be precomputed|on_the_fly, got: {PTM_INPUT_MODE}")

if USE_PTM_ON_THE_FLY and not AUDIO_BASE_DIR:
    raise ValueError("AUDIO_BASE_DIR is required when PTM_INPUT_MODE='on_the_fly'.")

print(f"PTM input mode: {PTM_INPUT_MODE}")
if USE_PTM_ON_THE_FLY:
    print(f"PTM runtime model: {PTM_MODEL_ID}")
    print(f"Audio base dir: {AUDIO_BASE_DIR}")

FEAT_MODE_MAP = {
    "mfbe_shards": "mfbe_only",
    "mfcc_shards": "mfcc_only",
    "pitch_shards": "pitch_only",
    "mfbe_pitch_shards": "mfbe_pitch",
    "mfcc_pitch_shards": "mfcc_pitch",
    "fbank_shards": "fbank_only",
    "fbank_pitch_shards": "fbank_pitch",
}

def get_base_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output_dir", type=str, default="./outputs")
    parser.add_argument("--experiments_dirname", type=str, default="experiments_new")
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--learning_rate", type=float, default=1e-4)
    parser.add_argument("--lr_scheduler", type=str, default="plateau")
    parser.add_argument("--num_epochs", type=int, default=60)
    parser.add_argument("--optimizer", type=str, default="adam")
    parser.add_argument("--weight_decay", type=float, default=1e-3)
    parser.add_argument("--aam_margin", type=float, default=0.25)
    parser.add_argument("--aam_scale", type=float, default=30)
    parser.add_argument("--embedding_dim", type=int, default=512)
    parser.add_argument("--mixed_precision", type=bool, default=True)
    parser.add_argument("--early_stop_patience", type=int, default=12)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--augment_prob", type=float, default=0.30)
    parser.add_argument("--feature_noise_std", type=float, default=0.003)
    parser.add_argument("--embedding_noise_std", type=float, default=0.002)
    parser.add_argument("--max_frames", type=int, default=350)

    parser.add_argument("--mode", type=int, default=3)
    parser.add_argument("--exp_name", type=str, default="")
    parser.add_argument("--embedding_path", type=str, default="")
    parser.add_argument("--feature_path", type=str, default="")
    parser.add_argument("--feature_mode", type=str, default="")
    parser.add_argument("--fusion_method", type=str, default="")
    parser.add_argument("--use_gating", type=bool, default=False)
    parser.add_argument("--use_augment", type=bool, default=True)
    parser.add_argument("--branch_dropout_prob", type=float, default=0.0)

    parser.add_argument("--use_two_stage_ft", type=bool, default=True)
    parser.add_argument("--stage1_epochs", type=int, default=6)
    parser.add_argument("--stage2_ptm_lr_scale", type=float, default=0.35)

    parser.add_argument("--duration", type=str, default="")
    parser.add_argument("--pretrained_model", type=str, default="")
    parser.add_argument("--init_mode1_ckpt", type=str, default=None)
    parser.add_argument("--init_mode2_ckpt", type=str, default=None)
    parser.add_argument("--use_ptm_on_the_fly", type=bool, default=False)
    parser.add_argument("--ptm_model_id", type=str, default="facebook/wav2vec2-base")
    parser.add_argument("--audio_base_dir", type=str, default="")
    parser.add_argument("--audio_sample_rate", type=int, default=16000)
    parser.add_argument("--max_audio_seconds", type=float, default=8.0)

    args, _ = parser.parse_known_args([])
    return args

def _cleanup_after_run():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def _run_train_safe(args, tag):
    try:
        train(args)
    finally:
        _cleanup_after_run()
        print(f"[CLEANUP] Done after {tag}")

def _apply_ptm_runtime_args(args):
    args.use_ptm_on_the_fly = bool(USE_PTM_ON_THE_FLY)
    args.ptm_model_id = PTM_MODEL_ID
    args.audio_base_dir = AUDIO_BASE_DIR
    args.audio_sample_rate = int(AUDIO_SAMPLE_RATE)
    args.max_audio_seconds = float(MAX_AUDIO_SECONDS)
    args.num_workers = int(NUM_WORKERS)
    args.win_mode13_max_workers = int(WIN_MODE13_MAX_WORKERS)
    args.pin_memory = bool(PIN_MEMORY)
    args.persistent_workers = bool(PERSISTENT_WORKERS)
    args.prefetch_factor = int(PREFETCH_FACTOR)
    args.non_blocking_transfer = bool(NON_BLOCKING_TRANSFER)
    args.validate_every = int(VALIDATE_EVERY_EPOCHS)
    args.max_train_steps_per_epoch = int(MAX_TRAIN_STEPS_PER_EPOCH)
    args.train_subset_fraction = float(TRAIN_SUBSET_FRACTION)
    args.max_train_samples = int(MAX_TRAIN_SAMPLES)

feat_dir = "fbank_pitch_shards"
fusion = "film"
feature_path = os.path.join(HC_BASE, feat_dir)
feat_mode = FEAT_MODE_MAP[feat_dir]
mode3_exp_name = f"Mode3_{fusion}_train_raw_wav2vec2_{feat_mode}"
mode3_ckpt = os.path.join("./outputs", EXPERIMENTS_DIRNAME, mode3_exp_name, "best_model.pth")

if not os.path.isdir(feature_path):
    print(f"[SKIP] Missing feature shard dir: {feature_path}")
elif os.path.isfile(mode3_ckpt):
    print(f"[SKIP] MODE3 checkpoint already exists: {mode3_ckpt}")
else:
    args = get_base_args()
    args.output_dir = "./outputs"
    args.experiments_dirname = EXPERIMENTS_DIRNAME
    args.mode = 3
    args.duration = "train_raw"
    args.pretrained_model = "wav2vec2"
    args.embedding_path = "" if USE_PTM_ON_THE_FLY else EMBEDDING_PATH
    args.feature_path = feature_path
    args.feature_mode = feat_mode
    args.fusion_method = fusion
    args.use_gating = False
    args.branch_dropout_prob = 0.05
    args.batch_size = MODE3_BATCH_SIZE
    args.max_frames = MODE3_MAX_FRAMES
    args.val_batch_size = MODE3_VAL_BATCH_SIZE
    args.learning_rate = 5e-5
    args.mixed_precision = bool(MODE3_MIXED_PRECISION)
    args.skip_model_summary = True
    args.num_epochs = 50
    args.early_stop_patience = 7
    args.lr_scheduler = "plateau"
    args.lr_scheduler_patience = 3
    args.use_augment = True
    args.use_two_stage_ft = False
    args.stage1_epochs = 6
    args.stage2_ptm_lr_scale = 0.35
    args.freeze_ptm_extractor = True
    args.train_mode3_ptm_layer_fusion = True
    args.use_mode3_warmstart = False
    args.use_mode3_init_mode1 = False
    args.use_mode3_init_mode2 = False
    args.init_mode1_ckpt = None
    args.init_mode2_ckpt = None
    args.exp_name = mode3_exp_name

    if FAST_VAL:
        args.validate_every = int(FAST_VAL_EVERY)
        args.val_max_pos_pairs = int(FAST_VAL_MAX_POS_PAIRS)
        args.val_batch_size = max(int(args.val_batch_size), 16)

    _apply_ptm_runtime_args(args)

    print("\n" + "=" * 80)
    print(f"RUN MODE3 SINGLE: {args.exp_name}")
    if FAST_VAL:
        print(f"FAST_VAL enabled | validate_every={args.validate_every} | val_max_pos_pairs={args.val_max_pos_pairs}")
    print("=" * 80)
    _run_train_safe(args, args.exp_name)

PTM input mode: on_the_fly
PTM runtime model: facebook/wav2vec2-base
Audio base dir: D:/Speech_Verification/audio/train_raw

================================================================================
RUN MODE3 SINGLE: Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch
FAST_VAL enabled | validate_every=1 | val_max_pos_pairs=2500
================================================================================
TensorBoard logs will be saved to: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\tensorboard_logs

================================================================================
SPEAKER VERIFICATION TRAINING - CONFIGURATION
================================================================================
Experiment Name                Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch
Device                         cuda
Mode                           3 (1=PTM, 2=Handcrafted, 3=Fusion)
Fusion Method                  cross_attention
Feature Mode                   fbank_pitch
PTM Input Source               on-the-fly
Use Gating                     False
Use Augment                    True
PTM On-the-fly                 True
PTM Runtime Model              facebook/wav2vec2-base
Audio Base Dir                 D:/Speech_Verification/audio/train_raw
Audio Sample Rate              16000

Learning Rate                  5e-05
Optimizer                      ADAM
Batch Size                     16
Epochs                         50
Weight Decay                   0.001
Mixed Precision                True

Early Stop Patience            7
LR Scheduler                   plateau
AAM Margin                     0.25
AAM Scale                      30
Branch Dropout (Mode3)         0.05
Use 2-Stage FT (Mode3)         False
Stage1 Epochs                  6
Stage2 PTM LR Scale            0.35
Mode3 Warm-start               False
Mode3 PTM Residual Alpha       0.0
Freeze PTM Extractor           True
Train PTM Layer Fusion         True

Experiment Dir                 ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch
================================================================================

Spk-Balanced Sampler           False
Hard Negative Mining           False
Hard Neg Weight/TopK           0.03 / 8
Augment Prob                   0.3
Feature Noise Std              0.003
Embedding Noise Std            0.002
Validation Batch Size          16
Num Workers                    6
Pin Memory                     True
Persistent Workers             True
Prefetch Factor                6
Validate Every (epochs)        1
Max Train Steps/Epoch          2500
Train Subset Fraction          0.300
Max Train Samples              All
Val Max Pos Pairs              2500
Loading Train/Val data...
ℹ Mode3 join mode: filename-based (aligned fast-path disabled).
🔍 Đang nạp metadata Handcrafted từ: D:/extracted_features/train_raw\fbank_pitch_shards...
✅ Đã nạp xong metadata 26 HC shards. Tổng số sample HC: 258168
📦 PTM input source: on-the-fly audio
✅ Mode3 on-the-fly: dùng HC metadata làm sample index (258168 samples), bỏ qua PTM precomputed shards.

🎤 CHIA DỮ LIỆU THEO OPEN-SET (Unseen Speakers):
   - Tập Train: 2023 speakers (231657 samples)
   - Tập Val:   357 speakers (26511 samples)

[FAST-EPOCH] Train subset fraction applied: 0.300 -> 69497 train samples
✓ Loaded 2023 speakers
  Train: 69497, Val: 26511

Creating model...

c:\Users\Dung\anaconda3\Lib\site-packages\transformers\configuration_utils.py:334: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.05
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 2023
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

ℹ Mode3 warm-start disabled by args.use_mode3_warmstart=False

Generating model summary...
✓ Model summary saved to ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\model_summary.txt

[Trainable Params by Group]
  - PTM Extractor     : 0
  - PTM Layer Fusion  : 3,841
  - HC Encoder        : 893,184
  - Temporal Fusion   : 2,363,904
  - Speaker Backbone  : 9,723,456

c:\Users\Dung\anaconda3\Lib\site-packages\torch\profiler\profiler.py:217: UserWarning: Warning: Profiler clears events at the end of each cycle.Only events from the current cycle will be reported.To keep events across cycles, set acc_events=True.
  _warn_once(

[PROFILE] Estimated GFLOPs/sample (actual batch profiler): 35.0987
Đang chuẩn bị fixed validation trials...
✓ Đã nạp fixed validation trials: ./outputs\fixed_val_trials\val_trials_train_raw_26511s_357spk_3cf0118b3732.json
✓ Đã đồng bộ trial protocol csv: ./outputs\fixed_val_trials\val_trials_train_raw_26511s_357spk_3cf0118b3732.csv
  Positive pairs: 2500 | Negative pairs: 2500
Starting training...

Epoch   1 | Train Loss: 8.8271, Acc: 0.2482 | EER: 15.48%, MinDCF: 0.6972 | LR: 0.000050 | TrainTime: 4696.20s, ValTime: 3065.89s, EpochTime: 7762.09s

Epoch   2 | Train Loss: 6.2403, Acc: 0.3669 | EER: 15.88%, MinDCF: 0.6284 | LR: 0.000050 | TrainTime: 4622.28s, ValTime: 3036.85s, EpochTime: 7659.13s
EarlyStopping counter: 1/7

Epoch   3 | Train Loss: 5.0648, Acc: 0.4456 | EER: 14.44%, MinDCF: 0.6036 | LR: 0.000050 | TrainTime: 4622.23s, ValTime: 3038.01s, EpochTime: 7660.24s

Epoch   4 | Train Loss: 4.3167, Acc: 0.5002 | EER: 11.08%, MinDCF: 0.5588 | LR: 0.000050 | TrainTime: 4544.46s, ValTime: 2974.80s, EpochTime: 7519.26s

Epoch   5 | Train Loss: 3.8180, Acc: 0.5393 | EER: 11.16%, MinDCF: 0.5680 | LR: 0.000050 | TrainTime: 4487.19s, ValTime: 3023.83s, EpochTime: 7511.02s
EarlyStopping counter: 1/7

Epoch   6 | Train Loss: 3.3942, Acc: 0.5779 | EER: 10.56%, MinDCF: 0.5220 | LR: 0.000050 | TrainTime: 5199.16s, ValTime: 3419.61s, EpochTime: 8618.77s

Epoch   7 | Train Loss: 3.0452, Acc: 0.6065 | EER: 11.60%, MinDCF: 0.5404 | LR: 0.000050 | TrainTime: 5185.36s, ValTime: 3421.27s, EpochTime: 8606.63s
EarlyStopping counter: 1/7

Epoch   8 | Train Loss: 2.7530, Acc: 0.6357 | EER: 11.36%, MinDCF: 0.5152 | LR: 0.000050 | TrainTime: 5179.93s, ValTime: 3419.52s, EpochTime: 8599.45s
EarlyStopping counter: 2/7

Epoch   9 | Train Loss: 2.5462, Acc: 0.6546 | EER: 10.60%, MinDCF: 0.5272 | LR: 0.000050 | TrainTime: 5188.49s, ValTime: 3421.61s, EpochTime: 8610.10s
EarlyStopping counter: 3/7

Epoch  10 | Train Loss: 2.2891, Acc: 0.6828 | EER: 10.08%, MinDCF: 0.5008 | LR: 0.000050 | TrainTime: 5159.65s, ValTime: 3318.92s, EpochTime: 8478.57s

Epoch  11 | Train Loss: 2.1393, Acc: 0.6977 | EER: 10.64%, MinDCF: 0.4964 | LR: 0.000050 | TrainTime: 5045.84s, ValTime: 3390.22s, EpochTime: 8436.05s
EarlyStopping counter: 1/7

Epoch  12 | Train Loss: 1.9702, Acc: 0.7156 | EER: 8.56%, MinDCF: 0.4736 | LR: 0.000050 | TrainTime: 5120.02s, ValTime: 3383.36s, EpochTime: 8503.38s

Epoch  13 | Train Loss: 1.7967, Acc: 0.7354 | EER: 8.60%, MinDCF: 0.4668 | LR: 0.000050 | TrainTime: 5120.82s, ValTime: 3383.74s, EpochTime: 8504.56s
EarlyStopping counter: 1/7

Epoch  14 | Train Loss: 1.7007, Acc: 0.7485 | EER: 8.56%, MinDCF: 0.4436 | LR: 0.000050 | TrainTime: 4718.45s, ValTime: 3269.88s, EpochTime: 7988.34s
EarlyStopping counter: 2/7

Epoch  15 | Train Loss: 1.5977, Acc: 0.7592 | EER: 12.40%, MinDCF: 0.5300 | LR: 0.000050 | TrainTime: 5144.29s, ValTime: 3362.90s, EpochTime: 8507.19s
EarlyStopping counter: 3/7

Epoch  16 | Train Loss: 1.4896, Acc: 0.7759 | EER: 11.08%, MinDCF: 0.4904 | LR: 0.000025 | TrainTime: 5018.79s, ValTime: 3303.99s, EpochTime: 8322.78s
EarlyStopping counter: 4/7

Epoch  17 | Train Loss: 1.2292, Acc: 0.8128 | EER: 10.48%, MinDCF: 0.4744 | LR: 0.000025 | TrainTime: 4656.79s, ValTime: 2967.21s, EpochTime: 7624.00s
EarlyStopping counter: 5/7

Epoch  18 | Train Loss: 1.1012, Acc: 0.8341 | EER: 10.92%, MinDCF: 0.5016 | LR: 0.000025 | TrainTime: 4486.65s, ValTime: 2967.29s, EpochTime: 7453.94s
EarlyStopping counter: 6/7

Epoch  19 | Train Loss: 1.0208, Acc: 0.8451 | EER: 10.40%, MinDCF: 0.5120 | LR: 0.000025 | TrainTime: 4498.17s, ValTime: 2965.70s, EpochTime: 7463.87s
EarlyStopping counter: 7/7

✓ Early stopping triggered!

✓ Training completed!
  Best validation EER: 8.5600
  Experiment dir: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch
  Config: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\config.json
  Results: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\results.json
  Results CSV: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\results.csv
  Summary JSON (all modes): ./outputs\experiments_train_raw_w2v2_7hc\summary_all_modes.json
  Summary CSV (all modes): ./outputs\experiments_train_raw_w2v2_7hc\summary_all_modes.csv
  Model: ./outputs\experiments_train_raw_w2v2_7hc\Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch\best_model.pth
[CLEANUP] Done after Mode3_cross_attention_train_raw_wav2vec2_fbank_pitch

In [ ]:
import gc
import glob
import json
import os
import warnings

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
import torchaudio
from tqdm.auto import tqdm

from model import get_model
from metrics import compute_eer, compute_mindcf

warnings.filterwarnings("ignore")

# ============================================================================
# INFERENCE ALL MODELS x ALL TEST SETS (NO ENSEMBLE)
# ============================================================================
REPORT_PREFIX = "inference_all_models_v1"
TEST_BASE_DIR = r"D:/test_o"
LIST_GT_DIR = os.path.join(TEST_BASE_DIR, "list_gt")
OUTPUT_DIR = "./outputs"
P_TARGET = 0.05

# PTM inference mode:
# - "on_the_fly": read waveform and extract PTM runtime in model
# - "precomputed": use PTM .pt embedding files from test set
PTM_INFERENCE_MODE = "precomputed"
if PTM_INFERENCE_MODE not in ["on_the_fly", "precomputed"]:
    raise ValueError(f"SV_PTM_INFER_MODE must be on_the_fly|precomputed, got: {PTM_INFERENCE_MODE}")

TEST_AUDIO_BASE_DIR = r"D:/test_o_wav"
MAX_AUDIO_SECONDS = 12.0

# Map trial test-set name -> folder name under TEST_AUDIO_BASE_DIR
TEST_AUDIO_SPLIT_MAP = {
    "full_length": "raw",
    "test_vi": "vi_full",
    "test_3s": "3s",
    "test_5s": "5s",
    "test_7s": "7s",
}

# Filter tùy chọn: đặt None để lấy tất cả
MODE_FILTER = [1, 2, 3]
FUSION_FILTER = None  # ví dụ: ["concat", "gating", "film", "cross_attention"]

TEST_SET_CONFIGS = [
    {"name": "full_length", "trial_file": "test_list_gt.csv", "duration": "full_length"},
    {"name": "test_vi", "trial_file": "test_list_gt_vi.csv", "duration": "test_vi"},
    {"name": "test_3s", "trial_file": "test_list_gt_3s.csv", "duration": "test_3s"},
    {"name": "test_5s", "trial_file": "test_list_gt_5s.csv", "duration": "test_5s"},
    {"name": "test_7s", "trial_file": "test_list_gt_7s.csv", "duration": "test_7s"},
]

SOURCE_EXPERIMENT_ROOTS = []
for pattern in ["./outputs/experiments_final"]:
    for candidate in sorted(glob.glob(pattern)):
        if os.path.isdir(candidate) and candidate not in SOURCE_EXPERIMENT_ROOTS:
            SOURCE_EXPERIMENT_ROOTS.append(candidate)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")
print(f"Report prefix: {REPORT_PREFIX}")
print(f"PTM inference mode: {PTM_INFERENCE_MODE}")
print(f"Test audio base dir: {TEST_AUDIO_BASE_DIR}")
print("Source experiment roots:")
for root in SOURCE_EXPERIMENT_ROOTS:
    print(" -", root)

HC_FILENAME_MAP = {
    "mfbe_only": "Only_MFBE.pt",
    "pitch_only": "Only_Pitch.pt",
    "mfcc_only": "Only_MFCC.pt",
    "mfbe_pitch": "MFBE_Pitch.pt",
    "mfcc_pitch": "MFCC_Pitch.pt",
    "fbank_only": "Only_FBank.pt",
    "fbank_pitch": "FBank_Pitch.pt",
}


def parse_trial_csv(trial_csv_path: str) -> pd.DataFrame:
    raw_df = pd.read_csv(trial_csv_path, header=None)
    if raw_df.shape[1] >= 3:
        df = raw_df.iloc[:, :3].copy()
        df.columns = ["label", "path1", "path2"]
    else:
        df = raw_df.rename(columns={0: "raw"}).copy()
        parsed = df["raw"].astype(str).str.strip('"').str.extract(r"^\s*([01])\s+(.+?)\s+(.+?)\s*$")
        parsed.columns = ["label", "path1", "path2"]
        df = parsed
    df["label"] = df["label"].astype(int)
    df["path1"] = df["path1"].astype(str)
    df["path2"] = df["path2"].astype(str)
    df = df.reset_index(drop=True)
    df["trial_idx"] = np.arange(len(df), dtype=np.int64)
    return df[["trial_idx", "label", "path1", "path2"]]


def _candidate_keys(path_text: str):
    p = str(path_text).replace('\\\\', '/').strip()
    base = os.path.basename(p)
    stem = os.path.splitext(base)[0]
    rel = p.lstrip('./')
    p_us = p.replace('/', '_')
    rel_us = rel.replace('/', '_')
    base_us = base.replace('/', '_')
    stem_us = os.path.splitext(base_us)[0]
    out, seen = [], set()
    for key in [p, rel, base, stem, p_us, rel_us, base_us, stem_us]:
        if key not in seen:
            out.append(key)
            seen.add(key)
    return out


def _register_lookup(lookup, path_text, value):
    for key in _candidate_keys(path_text):
        if key not in lookup:
            lookup[key] = value


def _get_feature_from_lookup(lookup, path_text):
    if lookup is None:
        return None
    for key in _candidate_keys(path_text):
        if key in lookup:
            return lookup[key]
    return None


def resolve_ptm_path(ptm_name: str, ptm_dir: str):
    if ptm_dir is None:
        return None
    ptm_name = str(ptm_name).lower()
    cands = [
        os.path.join(ptm_dir, f"Embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"all_embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"{ptm_name}.pt"),
    ]
    for p in cands:
        if os.path.exists(p):
            return p
    return None


def resolve_hc_path(feature_mode: str, feature_dir: str):
    if feature_dir is None:
        return None
    feature_mode = str(feature_mode).lower()
    if feature_mode in HC_FILENAME_MAP:
        p = os.path.join(feature_dir, HC_FILENAME_MAP[feature_mode])
        if os.path.exists(p):
            return p
    for p in [
        os.path.join(feature_dir, f"{feature_mode}.pt"),
        os.path.join(feature_dir, f"all_features_{feature_mode}.pt"),
    ]:
        if os.path.exists(p):
            return p
    return None


def _to_float_tensor(value):
    if torch.is_tensor(value):
        return value.float().detach().cpu()
    return torch.tensor(value, dtype=torch.float32)


def build_lookup_from_pt_file(obj, value_field: str):
    lookup = {}
    if not isinstance(obj, dict):
        raise ValueError(f"Unsupported .pt format: expected dict, got {type(obj).__name__}")

    # Case 1: chuẩn filenames + values
    if "filenames" in obj and value_field in obj:
        filenames = obj.get("filenames", [])
        values = obj.get(value_field, [])

        # Nếu values là tensor batch thì tách theo dim 0
        if torch.is_tensor(values):
            if values.dim() >= 2:
                values = [values[i] for i in range(values.shape[0])]
            else:
                values = [values]

        # Nếu filenames khớp, map theo filenames
        if isinstance(filenames, (list, tuple)) and len(filenames) == len(values) and len(filenames) > 0:
            for idx, name in enumerate(filenames):
                _register_lookup(lookup, str(name), _to_float_tensor(values[idx]))
            return lookup

        # filenames rỗng hoặc mismatch -> fallback theo index, không raise
        if isinstance(values, (list, tuple)) and len(values) > 0:
            for idx, value in enumerate(values):
                _register_lookup(lookup, f"idx_{idx}", _to_float_tensor(value))
            return lookup

    # Case 2: dict keyed-by-name -> tensor
    if len(obj) > 0 and all(isinstance(k, str) for k in obj.keys()):
        for name, value in obj.items():
            if torch.is_tensor(value):
                _register_lookup(lookup, str(name), _to_float_tensor(value))
        if len(lookup) > 0:
            return lookup

    raise ValueError("Unsupported .pt format: missing usable tensor entries")


def _safe_float(value, default=None):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def discover_experiments(exp_roots):
    experiments = []
    seen = set()
    for root in exp_roots:
        if not os.path.isdir(root):
            continue
        for exp_dir in sorted(glob.glob(os.path.join(root, "*"))):
            model_path = os.path.join(exp_dir, "best_model.pth")
            config_path = os.path.join(exp_dir, "config.json")
            results_path = os.path.join(exp_dir, "results.json")
            if not (os.path.exists(model_path) and os.path.exists(config_path)):
                continue

            exp_name = os.path.basename(exp_dir)
            dedup_key = (root, exp_name)
            if dedup_key in seen:
                continue
            seen.add(dedup_key)

            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)

            results = {}
            if os.path.exists(results_path):
                with open(results_path, "r", encoding="utf-8") as f:
                    results = json.load(f)

            mode = int(cfg.get("mode", 3))
            fusion = str(cfg.get("fusion_method", "concat")).lower()

            if MODE_FILTER is not None and mode not in MODE_FILTER:
                continue
            if FUSION_FILTER is not None and fusion not in FUSION_FILTER:
                continue

            experiments.append({
                "exp_name": exp_name,
                "root_dir": root,
                "exp_dir": exp_dir,
                "model_path": model_path,
                "mode": mode,
                "fusion_method": fusion,
                "feature_mode": str(cfg.get("feature_mode", "mfbe_pitch")).lower(),
                "pretrained_model": str(cfg.get("pretrained_model", "wavlm")).lower(),
                "duration": str(cfg.get("duration", "")).lower(),
                "use_ptm_on_the_fly": bool(cfg.get("use_ptm_on_the_fly", False)),
                "ptm_model_id": str(cfg.get("ptm_model_id", "facebook/wav2vec2-base")),
                "audio_sample_rate": int(cfg.get("audio_sample_rate", 16000)),
                "best_val_eer": _safe_float(results.get("best_val_eer"), np.inf),
            })
    return experiments


def get_test_set_dirs(test_set_name: str, duration: str):
    base_dir = os.path.join(TEST_BASE_DIR, test_set_name)
    ptm_dir = os.path.join(base_dir, "embeddings")
    feature_dir = os.path.join(base_dir, "features")
    if duration and duration != "full_length":
        alt_ptm = os.path.join(base_dir, duration, "embeddings")
        alt_hc = os.path.join(base_dir, duration, "features")
        if os.path.isdir(alt_ptm):
            ptm_dir = alt_ptm
        if os.path.isdir(alt_hc):
            feature_dir = alt_hc
    return ptm_dir, feature_dir


def score_df_to_dense_arrays(score_df, num_trials):
    if score_df is None or len(score_df) == 0:
        return None
    if score_df["trial_idx"].duplicated().any():
        dup_count = int(score_df["trial_idx"].duplicated().sum())
        raise RuntimeError(f"Duplicate trial_idx detected in score_df: {dup_count}")
    score_vec = np.full(num_trials, np.nan, dtype=np.float32)
    label_vec = np.full(num_trials, -1, dtype=np.int32)
    trial_idx = score_df["trial_idx"].to_numpy(dtype=np.int64)
    labels = score_df["label"].to_numpy(dtype=np.int32)
    scores = score_df["score"].to_numpy(dtype=np.float32)
    score_vec[trial_idx] = scores
    label_vec[trial_idx] = labels
    return score_vec, label_vec


def summarize_scores_from_arrays(labels_np, scores_np):
    eer, _ = compute_eer(labels_np, scores_np)
    mindcf, _ = compute_mindcf(labels_np, scores_np, p_target=P_TARGET)
    return {
        "EER (%)": float(eer * 100.0),
        "MinDCF": float(mindcf),
        "Used Pairs": int(len(scores_np)),
    }


def _resolve_audio_path(path_text: str, test_set_name: str, duration: str):
    p = str(path_text).strip().replace("\\", "/")
    if os.path.isfile(p):
        return os.path.normpath(p)

    rel = p.lstrip("./")
    rel_no_wav = rel[4:] if rel.lower().startswith("wav/") else rel
    base = os.path.basename(rel_no_wav)
    stem, ext = os.path.splitext(base)
    exts = [ext] if ext else [".wav", ".flac", ".mp3", ".m4a"]

    split = TEST_AUDIO_SPLIT_MAP.get(test_set_name, test_set_name)
    roots = [TEST_AUDIO_BASE_DIR, TEST_BASE_DIR]
    roots = [r for r in roots if r]

    cands = []
    for root in roots:
        cands.extend([
            os.path.join(root, rel),
            os.path.join(root, rel_no_wav),
            os.path.join(root, split, rel),
            os.path.join(root, split, rel_no_wav),
            os.path.join(root, test_set_name, rel),
            os.path.join(root, test_set_name, rel_no_wav),
        ])
        if stem:
            for e in exts:
                cands.extend([
                    os.path.join(root, stem + e),
                    os.path.join(root, split, stem + e),
                    os.path.join(root, test_set_name, stem + e),
                    os.path.join(root, split, "wav", stem + e),
                    os.path.join(root, test_set_name, "wav", stem + e),
                ])

    seen = set()
    for cand in cands:
        norm = os.path.normpath(cand)
        if norm in seen:
            continue
        seen.add(norm)
        if os.path.isfile(norm):
            return norm

    return None


def _load_audio_for_infer(path_text: str, test_set_name: str, duration: str, sample_rate: int):
    resolved = _resolve_audio_path(path_text, test_set_name, duration)
    if resolved is None:
        return None, None

    wav, sr = torchaudio.load(resolved)
    if wav.dim() == 2 and wav.size(0) > 1:
        wav = wav.mean(dim=0, keepdim=True)
    if wav.dim() == 2:
        wav = wav.squeeze(0)

    if int(sr) != int(sample_rate):
        wav = torchaudio.functional.resample(wav, orig_freq=int(sr), new_freq=int(sample_rate))

    if MAX_AUDIO_SECONDS is not None and float(MAX_AUDIO_SECONDS) > 0:
        max_n = int(float(MAX_AUDIO_SECONDS) * int(sample_rate))
        if wav.numel() > max_n:
            wav = wav[:max_n]

    wav = wav.float().contiguous()
    return wav, int(wav.shape[0])


@torch.no_grad()
def build_pair_score_df(model, mode, ptm_lookup, hc_lookup, trials_df, test_set_name, duration, sample_rate):
    unique_paths = set(trials_df["path1"].tolist() + trials_df["path2"].tolist())
    path_to_emb = {}

    for path in tqdm(sorted(unique_paths), desc="Embedding paths", leave=False):
        hc_feat = _get_feature_from_lookup(hc_lookup, path) if mode in [2, 3] else None
        if mode in [2, 3] and hc_feat is None:
            continue

        inputs = {}

        if mode in [1, 3]:
            if PTM_INFERENCE_MODE == "on_the_fly":
                wav, wav_len = _load_audio_for_infer(path, test_set_name, duration, sample_rate)
                if wav is None:
                    continue
                inputs["audio"] = wav.unsqueeze(0).to(DEVICE).float()
                inputs["audio_lengths"] = torch.tensor([wav_len], dtype=torch.long, device=DEVICE)
            else:
                ptm_feat = _get_feature_from_lookup(ptm_lookup, path)
                if ptm_feat is None:
                    continue
                inputs["embedding"] = ptm_feat.unsqueeze(0).to(DEVICE).float()

        if mode in [2, 3]:
            inputs["feature"] = hc_feat.unsqueeze(0).to(DEVICE).float()

        _, emb = model(**inputs)
        path_to_emb[path] = F.normalize(emb, p=2, dim=1).squeeze(0).detach().cpu().numpy().astype(np.float32)

    if len(path_to_emb) < 2:
        return None

    trial_idx_list, valid_labels, pair_i, pair_j = [], [], [], []
    paths = list(path_to_emb.keys())
    path_to_idx = {p: i for i, p in enumerate(paths)}
    emb_matrix = np.stack([path_to_emb[p] for p in paths], axis=0)

    for _, row in trials_df.iterrows():
        p1 = row["path1"]
        p2 = row["path2"]
        if p1 not in path_to_idx or p2 not in path_to_idx:
            continue
        trial_idx_list.append(int(row["trial_idx"]))
        valid_labels.append(int(row["label"]))
        pair_i.append(path_to_idx[p1])
        pair_j.append(path_to_idx[p2])

    if len(pair_i) == 0:
        return None

    pair_i = np.asarray(pair_i, dtype=np.int32)
    pair_j = np.asarray(pair_j, dtype=np.int32)
    raw_scores = np.sum(emb_matrix[pair_i] * emb_matrix[pair_j], axis=1).astype(np.float32)

    return pd.DataFrame({
        "trial_idx": np.asarray(trial_idx_list, dtype=np.int64),
        "label": np.asarray(valid_labels, dtype=np.int32),
        "score": raw_scores,
    })


LOOKUP_CACHE = {"ptm": {}, "hc": {}}


def clear_lookup_cache():
    LOOKUP_CACHE["ptm"].clear()
    LOOKUP_CACHE["hc"].clear()
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def get_ptm_lookup(test_set_name, duration, ptm_name, ptm_dir):
    if PTM_INFERENCE_MODE == "on_the_fly":
        return None
    key = (test_set_name, duration, ptm_name)
    if key not in LOOKUP_CACHE["ptm"]:
        ptm_path = resolve_ptm_path(ptm_name, ptm_dir)
        LOOKUP_CACHE["ptm"][key] = None if ptm_path is None else build_lookup_from_pt_file(
            torch.load(ptm_path, map_location="cpu"),
            "embeddings",
        )
    return LOOKUP_CACHE["ptm"][key]


def get_hc_lookup(test_set_name, duration, feature_mode, feature_dir):
    key = (test_set_name, duration, feature_mode)
    if key not in LOOKUP_CACHE["hc"]:
        hc_path = resolve_hc_path(feature_mode, feature_dir)
        LOOKUP_CACHE["hc"][key] = None if hc_path is None else build_lookup_from_pt_file(
            torch.load(hc_path, map_location="cpu"),
            "features",
        )
    return LOOKUP_CACHE["hc"][key]


@torch.no_grad()
def score_single_experiment(exp_info, trials_df, test_set_name, ptm_dir, feature_dir):
    model = None
    ckpt = None
    score_df = None
    try:
        mode = exp_info["mode"]
        ptm_name = exp_info["pretrained_model"]
        feature_mode = exp_info["feature_mode"]
        is_on_the_fly_ckpt = bool(exp_info.get("use_ptm_on_the_fly", False))

        # Cell này chạy on-the-fly thật cho nhánh PTM.
        # Chỉ giữ checkpoint hỗ trợ on-the-fly để tránh mismatch kiến trúc/weights.
        if PTM_INFERENCE_MODE == "on_the_fly" and mode in [1, 3] and not is_on_the_fly_ckpt:
            return None

        ptm_lookup = get_ptm_lookup(test_set_name, exp_info["duration"], ptm_name, ptm_dir) if mode in [1, 3] else None
        hc_lookup = get_hc_lookup(test_set_name, exp_info["duration"], feature_mode, feature_dir) if mode in [2, 3] else None

        if mode in [1, 3] and PTM_INFERENCE_MODE == "precomputed" and ptm_lookup is None:
            return None
        if mode in [2, 3] and hc_lookup is None:
            return None

        model = get_model(
            num_speakers=1000,
            device=str(DEVICE),
            mode=mode,
            fusion_method=exp_info["fusion_method"],
            feature_mode=feature_mode,
            use_gating=(exp_info["fusion_method"] == "gating"),
            use_ptm_on_the_fly=is_on_the_fly_ckpt,
            ptm_model_id=str(exp_info.get("ptm_model_id", "facebook/wav2vec2-base")),
            ptm_sample_rate=int(exp_info.get("audio_sample_rate", 16000)),
        )
        ckpt = torch.load(exp_info["model_path"], map_location=DEVICE)
        model.load_state_dict(ckpt["model_state_dict"], strict=True)
        model.eval()

        score_df = build_pair_score_df(
            model,
            mode,
            ptm_lookup,
            hc_lookup,
            trials_df,
            test_set_name,
            exp_info["duration"],
            int(exp_info.get("audio_sample_rate", 16000)),
        )
        dense_pack = score_df_to_dense_arrays(score_df, len(trials_df))
        if dense_pack is None:
            return None

        score_vec, label_vec = dense_pack
        valid_mask = np.isfinite(score_vec)
        if valid_mask.sum() == 0:
            return None

        metrics = summarize_scores_from_arrays(label_vec[valid_mask], score_vec[valid_mask])
        return {
            "TestSet": test_set_name,
            "Experiment": exp_info["exp_name"],
            "Mode": mode,
            "Fusion": exp_info["fusion_method"],
            "Feature": feature_mode,
            "PTM": ptm_name,
            "Duration": exp_info["duration"],
            "PTM_Input_Mode": PTM_INFERENCE_MODE,
            **metrics,
            "Missing Pairs": int(len(trials_df) - int(valid_mask.sum())),
            "Best Val EER": None if np.isinf(exp_info.get("best_val_eer", np.inf)) else exp_info.get("best_val_eer"),
        }
    finally:
        del score_df
        del ckpt
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()


all_experiments = discover_experiments(SOURCE_EXPERIMENT_ROOTS)
print(f"Discovered {len(all_experiments)} experiments after filters")

if len(all_experiments) == 0:
    raise RuntimeError("Không tìm thấy model phù hợp để inference.")

if PTM_INFERENCE_MODE == "on_the_fly":
    before_count = len(all_experiments)
    all_experiments = [
        e for e in all_experiments
        if e["mode"] not in [1, 3] or bool(e.get("use_ptm_on_the_fly", False))
    ]
    print(
        "Filtered experiments for on-the-fly PTM: "
        f"{before_count} -> {len(all_experiments)}"
    )

if len(all_experiments) == 0:
    raise RuntimeError("Không còn experiment tương thích sau khi lọc on-the-fly.")

os.makedirs(OUTPUT_DIR, exist_ok=True)
all_rows = []

for test_cfg in TEST_SET_CONFIGS:
    clear_lookup_cache()
    test_set_name = test_cfg["name"]
    test_root = test_cfg.get("test_dir", TEST_BASE_DIR)
    trial_path = None
    if bool(test_cfg.get("trial_in_test_dir", False)):
        preferred = test_cfg.get("trial_file", "")
        if preferred:
            cand = os.path.join(test_root, preferred)
            if os.path.exists(cand):
                trial_path = cand
        if trial_path is None:
            txt_candidates = sorted(glob.glob(os.path.join(test_root, "list_gt*.txt")))
            if len(txt_candidates) == 0:
                txt_candidates = sorted(glob.glob(os.path.join(test_root, "*.txt")))
            if len(txt_candidates) > 0:
                trial_path = txt_candidates[0]
    if trial_path is None:
        trial_path = os.path.join(LIST_GT_DIR, test_cfg["trial_file"])
    duration = test_cfg.get("duration", "")
    out_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_{test_set_name}.csv")

    print("\n" + "=" * 88)
    print(f"TEST SET: {test_set_name}")
    print("=" * 88)

    if trial_path is None or (not os.path.exists(trial_path)):
        print(f"[SKIP] Missing trial file: {trial_path}")
        continue

    if bool(test_cfg.get("trial_in_test_dir", False)):
        ptm_dir = os.path.join(test_root, "embeddings")
        feature_dir = os.path.join(test_root, "features")
    else:
        ptm_dir, feature_dir = get_test_set_dirs(test_set_name, duration)
    if PTM_INFERENCE_MODE == "precomputed" and not os.path.isdir(ptm_dir):
        print(f"[SKIP] Missing PTM embedding dir for precomputed mode: {ptm_dir}")
        continue

    trials_df = parse_trial_csv(trial_path)
    rows = []

    for exp_info in tqdm(all_experiments, desc=f"Inference {test_set_name}"):
        try:
            row = score_single_experiment(exp_info, trials_df, test_set_name, ptm_dir, feature_dir)
            if row is not None:
                rows.append(row)
        except Exception as ex:
            print(f"[ERROR] {test_set_name} | {exp_info['exp_name']}: {type(ex).__name__} - {ex}")
        finally:
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    if len(rows) == 0:
        print(f"[WARN] No valid result rows for {test_set_name}")
        continue

    df = pd.DataFrame(rows).sort_values(["EER (%)", "MinDCF"], ascending=[True, True]).reset_index(drop=True)
    df.to_csv(out_path, index=False)
    print(f"Saved: {out_path}")
    display(df.head(30))

    all_rows.extend(rows)

all_df = pd.DataFrame(all_rows)
all_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_all_testsets.csv")
if len(all_df) > 0:
    all_df = all_df.sort_values(["TestSet", "EER (%)", "MinDCF"], ascending=[True, True, True]).reset_index(drop=True)
    all_df.to_csv(all_path, index=False)
    print(f"Saved total report: {all_path}")
    display(all_df.head(50))
else:
    print("No valid inference rows generated.")

Device: cuda
Report prefix: inference_all_models_v1
PTM inference mode: on_the_fly
Test audio base dir: D:/test_o_wav
Source experiment roots:
 - ./outputs/experiments_train_raw_w2v2_7hc
Discovered 3 experiments after filters
Filtered experiments for on-the-fly PTM: 3 -> 3

========================================================================================
TEST SET: full_length
========================================================================================

Inference full_length:   0%|          | 0/3 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

Embedding paths:   0%|          | 0/17786 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,125,249
  Trainable parameters: 106,125,249
======================================================================

Embedding paths:   0%|          | 0/17786 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

Embedding paths:   0%|          | 0/17786 [00:00<?, ?it/s]

Saved: ./outputs\inference_all_models_v1_full_length.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,full_length,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.902978,0.625071,9895,0,8.56
1,full_length,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,5.072004,0.690893,9895,0,NaN
2,full_length,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,5.227605,0.628219,9895,0,9.44

========================================================================================
TEST SET: test_vi
========================================================================================

Inference test_vi:   0%|          | 0/3 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,125,249
  Trainable parameters: 106,125,249
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

Saved: ./outputs\inference_all_models_v1_test_vi.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,test_vi,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.929095,0.258396,9895,0,9.44
1,test_vi,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,3.969673,0.266609,9895,0,NaN
2,test_vi,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.815109,0.281851,9895,0,8.56

========================================================================================
TEST SET: test_3s
========================================================================================

Inference test_3s:   0%|          | 0/3 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,125,249
  Trainable parameters: 106,125,249
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

Saved: ./outputs\inference_all_models_v1_test_3s.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,test_3s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.476019,0.582813,9895,0,9.44
1,test_3s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.044118,0.617350,9895,0,8.56
2,test_3s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,4.091408,0.605910,9895,0,NaN

========================================================================================
TEST SET: test_5s
========================================================================================

Inference test_5s:   0%|          | 0/3 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,125,249
  Trainable parameters: 106,125,249
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

Saved: ./outputs\inference_all_models_v1_test_5s.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,test_5s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.253722,0.810763,9895,0,8.56
1,test_5s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,4.497193,0.674142,9895,0,9.44
2,test_5s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,4.497193,0.709576,9895,0,NaN

========================================================================================
TEST SET: test_7s
========================================================================================

Inference test_7s:   0%|          | 0/3 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: cross_attention
  Feature mode: fbank_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 107,357,633
  Trainable parameters: 107,357,633
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,125,249
  Trainable parameters: 106,125,249
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: gating
  Feature mode: mfbe_only
  Use gating: True
  Branch dropout prob: 0.0
  Mode3 PTM residual alpha: 0.0
  PTM on-the-fly: True
  PTM runtime model: facebook/wav2vec2-base
  PTM sample rate: 16000
  Num speakers: 1000
  Total parameters: 106,763,457
  Trainable parameters: 106,763,457
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

Saved: ./outputs\inference_all_models_v1_test_7s.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,test_7s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,3.306993,0.574839,9895,0,8.56
1,test_7s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.354284,0.552657,9895,0,9.44
2,test_7s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,3.597754,0.597759,9895,0,NaN

Saved total report: ./outputs\inference_all_models_v1_all_testsets.csv

,TestSet,Experiment,Mode,Fusion,Feature,PTM,Duration,PTM_Input_Mode,EER (%),MinDCF,Used Pairs,Missing Pairs,Best Val EER
0,full_length,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.902978,0.625071,9895,0,8.56
1,full_length,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,5.072004,0.690893,9895,0,NaN
2,full_length,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,5.227605,0.628219,9895,0,9.44
3,test_3s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.476019,0.582813,9895,0,9.44
4,test_3s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.044118,0.617350,9895,0,8.56
5,test_3s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,4.091408,0.605910,9895,0,NaN
6,test_5s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.253722,0.810763,9895,0,8.56
7,test_5s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,4.497193,0.674142,9895,0,9.44
8,test_5s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,4.497193,0.709576,9895,0,NaN
9,test_7s,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,3.306993,0.574839,9895,0,8.56
10,test_7s,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.354284,0.552657,9895,0,9.44
11,test_7s,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,3.597754,0.597759,9895,0,NaN
12,test_vi,Mode3_film_train_raw_wav2vec2_mfcc_pitch,3,film,mfcc_pitch,wav2vec2,train_raw,on_the_fly,3.929095,0.258396,9895,0,9.44
13,test_vi,Mode3_gating_train_raw_wav2vec2_mfbe_only,3,gating,mfbe_only,wav2vec2,train_raw,on_the_fly,3.969673,0.266609,9895,0,NaN
14,test_vi,Mode3_cross_attention_train_raw_wav2vec2_fbank...,3,cross_attention,fbank_pitch,wav2vec2,train_raw,on_the_fly,4.815109,0.281851,9895,0,8.56