# Speaker Verification Training & Inference

Complete pipeline for speaker verification using:
- **PTM Encoder**: WavLM/HuBERT/Wav2Vec2 (multi-layer weighted sum)
- **Handcrafted Encoder**: MFBE + F0 features with CNN
- **Fusion Methods**: Concatenation or Cross-Attention
- **Backbone**: ECAPA-TDNN
- **Loss**: AAM-Softmax
- **Features**: Early stopping, LR scheduling, heatmap visualization

## 1. Setup & Parse Arguments

In [1]:
# Auto-reload modules
%load_ext autoreload
%autoreload 2

import os

# Workaround cho lỗi trùng OpenMP runtime (libiomp5md.dll) trên Windows
# Phải set trước khi import numpy/torch
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("OMP_NUM_THREADS", "1")

import torch
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import argparse
import sys
from datetime import datetime

# Check device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

Device: cuda
GPU: NVIDIA GeForce RTX 5080
GPU Memory: 17.09 GB

In [2]:
from config import (
    BATCH_SIZE, NUM_EPOCHS, LEARNING_RATE, EMBEDDING_DIM,
    MODE, FUSION_METHOD, FEATURE_MODE,
    CHECKPOINT_DIR, BEST_MODEL_NAME,
)
from train import train

# 1. Cấu hình các biến lặp
ROOT_DIR = "D:/"
durations = ['train_raw', 'train_vi_full', 'train_vi_3s', 'train_vi_5s', 'train_vi_7s']
pretrained_models = ['hubert', 'wavlm', 'wav2vec2']

# Tên thư mục feature trên ổ cứng
feature_folders = ['mfbe', 'pitch', 'mfcc', 'mfbe_pitch', 'mfcc_pitch']

# Fusion methods
fusion_methods = ["gating", "film", "concat"]

# Map tên thư mục sang tên config FEATURE_MODE để model nhận diện đúng dim
feat_name_map = {
    'mfbe': 'mfbe_only',
    'pitch': 'pitch_only',
    'mfcc': 'mfcc_only',
    'mfbe_pitch': 'mfbe_pitch',
    'mfcc_pitch': 'mfcc_pitch'
}

dur_prefix_map = {
    'train_raw': '',
    'train_vi_3s': '3s_',
    'train_vi_5s': '5s_',
    'train_vi_7s': '7s_',
    'train_vi_full': 'full_'
}

def get_base_args():
    """Hàm tạo arguments cơ bản giống như lúc parse_args()"""
    parser = argparse.ArgumentParser()
    # Thêm các đối số cơ bản
    parser.add_argument("--output_dir", type=str, default="./outputs")
    parser.add_argument("--experiments_dirname", type=str, default="experiments_new")
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--learning_rate", type=float, default=0.0001)
    parser.add_argument("--lr_scheduler", type=str, default="plateau")
    parser.add_argument("--num_epochs", type=int, default=60)
    parser.add_argument("--optimizer", type=str, default="adam")
    parser.add_argument("--weight_decay", type=float, default=0.001)
    parser.add_argument("--aam_margin", type=float, default=0.25)
    parser.add_argument("--aam_scale", type=float, default=30)
    parser.add_argument("--embedding_dim", type=int, default=512)
    parser.add_argument("--mixed_precision", type=bool, default=True)
    parser.add_argument("--early_stop_patience", type=int, default=12)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--augment_prob", type=float, default=0.30)
    parser.add_argument("--feature_noise_std", type=float, default=0.003)
    parser.add_argument("--embedding_noise_std", type=float, default=0.002)
    
    # Sẽ gán động trong lúc lặp
    parser.add_argument("--mode", type=int, default=3)
    parser.add_argument("--exp_name", type=str, default="")
    parser.add_argument("--embedding_path", type=str, default="")
    parser.add_argument("--feature_path", type=str, default="")
    parser.add_argument("--feature_mode", type=str, default="")
    parser.add_argument("--fusion_method", type=str, default="")
    parser.add_argument("--use_gating", type=bool, default=False)
    parser.add_argument("--use_augment", type=bool, default=True)
    parser.add_argument("--branch_dropout_prob", type=float, default=0.0)
    
    # 2-stage fine-tune cho Mode 3
    parser.add_argument("--use_two_stage_ft", type=bool, default=True)
    parser.add_argument("--stage1_epochs", type=int, default=6)
    parser.add_argument("--stage2_ptm_lr_scale", type=float, default=0.35)
    
    # Custom fields để lưu lại log
    parser.add_argument("--duration", type=str, default="")
    parser.add_argument("--pretrained_model", type=str, default="")
    parser.add_argument("--init_mode1_ckpt", type=str, default=None)
    parser.add_argument("--init_mode2_ckpt", type=str, default=None)
    
    args, _ = parser.parse_known_args([])
    return args

def check_skip(exp_name, experiments_dirname="experiments_new"):
    """Cơ chế Skip if done: Kiểm tra xem kết quả đã tồn tại chưa"""
    results_file = os.path.join("./outputs", experiments_dirname, exp_name, "results.json")
    if os.path.exists(results_file):
        print(f"⏭ Bỏ qua {exp_name} - Đã huấn luyện xong!")
        return True
    return False

## 2. Training

In [3]:
# # Cập nhật tên exp để biết đang chạy fusion gì
# fusion = "cross_attention" # Ví dụ: đang chạy fusion gating
# dur = "train_raw" # Ví dụ: đang chạy với duration full
# ptm = "wavlm" # Ví dụ: đang chạy với pretrained model hubert
# feat_dir = "mfbe_pitch" # Ví dụ: đang chạy với feature mfbe_pitch
# feat_mode = feat_name_map[feat_dir]

# exp_name = f"Mode3_{fusion}_{dur}_{ptm}_{feat_mode}"

# print(f"\n{'='*60}\nĐANG CHẠY: {exp_name}\n{'='*60}")
# args = get_base_args()
# args.mode = 3
# args.exp_name = exp_name
# args.duration = dur
# args.pretrained_model = ptm
# args.feature_mode = feat_mode
# args.fusion_method = fusion    

# prefix = dur_prefix_map[dur]
# args.embedding_path = os.path.join(ROOT_DIR, "Embeddings", dur, f"{prefix}{ptm}_shards")
# args.feature_path = os.path.join(ROOT_DIR, "extracted_features", dur, f"{feat_dir}_shards")

# # Bật cờ use_gating nếu fusion là gating (để log/phân tích)
# args.use_gating = True if fusion == "gating" else False
# args.use_augment = True # Mode 3 dùng augment để tăng độ robust

# train(args)

In [ ]:
import gc
import os
import time
import traceback

import pandas as pd
import torch

from train import train

SEARCH_TAG = "overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1"
EXPERIMENTS_DIRNAME = f"experiments_{SEARCH_TAG}"
REPORT_PREFIX = SEARCH_TAG

# Đặt None để chạy full qua đêm; đặt số nhỏ như 1 hoặc 2 để test nhanh
MAX_RUNS = None

FEAT_NAME_MAP = {
    "mfbe": "mfbe_only",
    "pitch": "pitch_only",
    "mfcc": "mfcc_only",
    "mfbe_pitch": "mfbe_pitch",
    "mfcc_pitch": "mfcc_pitch",
}

DUR_PREFIX_MAP = {
    "train_raw": "",
    "train_vi_3s": "3s_",
    "train_vi_5s": "5s_",
    "train_vi_7s": "7s_",
    "train_vi_full": "full_",
}


def get_cell7_base_args():
    args = get_base_args()
    args.experiments_dirname = EXPERIMENTS_DIRNAME
    args.early_stop_patience = 10
    args.use_two_stage_ft = False
    args.stage1_epochs = 0
    args.stage2_ptm_lr_scale = 1.0
    return args


def check_skip_cell7(exp_name, experiments_dirname=EXPERIMENTS_DIRNAME):
    results_file = os.path.join("./outputs", experiments_dirname, exp_name, "results.json")
    if os.path.exists(results_file):
        print(f"[SKIP] {exp_name} already finished")
        return True
    return False


def make_exp_name(cfg):
    ap = str(cfg["augment_prob"]).replace(".", "p")
    fn = str(cfg["feature_noise_std"]).replace(".", "p")
    en = str(cfg["embedding_noise_std"]).replace(".", "p")
    am = str(cfg["aam_margin"]).replace(".", "p")
    scale_tag = str(int(cfg["aam_scale"]))
    return SEARCH_TAG + "_" + cfg["tag"] + "_ap" + ap + "_fn" + fn + "_en" + en + "_m" + am + "_s" + scale_tag


def build_run_plan():
    base = {
        "fusion": "film",
        "duration": "train_raw",
        "ptm": "wav2vec2",
        "feat_dir": "mfcc_pitch",
        "branch_dropout_prob": 0.05,
        "num_epochs": 60,
        "early_stop_patience": 10,
        "learning_rate": 1e-4,
        "weight_decay": 1e-3,
        "use_two_stage_ft": False,
        "stage1_epochs": 0,
        "stage2_ptm_lr_scale": 1.0,
    }
    base["feat_mode"] = FEAT_NAME_MAP[base["feat_dir"]]

    grid = [
        {"tag": "top_bal_s42", "seed": 42, "use_augment": True, "augment_prob": 0.30, "feature_noise_std": 0.003, "embedding_noise_std": 0.002, "aam_margin": 0.25, "aam_scale": 30},
        {"tag": "top_full_s42", "seed": 42, "use_augment": True, "augment_prob": 0.20, "feature_noise_std": 0.005, "embedding_noise_std": 0.002, "aam_margin": 0.25, "aam_scale": 30},
        {"tag": "near1_s42", "seed": 42, "use_augment": True, "augment_prob": 0.25, "feature_noise_std": 0.004, "embedding_noise_std": 0.002, "aam_margin": 0.25, "aam_scale": 30},
        {"tag": "near2_s42", "seed": 42, "use_augment": True, "augment_prob": 0.30, "feature_noise_std": 0.005, "embedding_noise_std": 0.001, "aam_margin": 0.25, "aam_scale": 30},
        {"tag": "aam1_s42", "seed": 42, "use_augment": True, "augment_prob": 0.20, "feature_noise_std": 0.005, "embedding_noise_std": 0.002, "aam_margin": 0.20, "aam_scale": 32},
        {"tag": "aam2_s42", "seed": 42, "use_augment": True, "augment_prob": 0.30, "feature_noise_std": 0.003, "embedding_noise_std": 0.002, "aam_margin": 0.20, "aam_scale": 32},
        {"tag": "top_bal_s3407", "seed": 3407, "use_augment": True, "augment_prob": 0.30, "feature_noise_std": 0.003, "embedding_noise_std": 0.002, "aam_margin": 0.25, "aam_scale": 30},
        {"tag": "top_full_s3407", "seed": 3407, "use_augment": True, "augment_prob": 0.20, "feature_noise_std": 0.005, "embedding_noise_std": 0.002, "aam_margin": 0.25, "aam_scale": 30},
    ]

    run_plan = []
    for cfg in grid:
        merged = dict(base)
        merged.update(cfg)
        merged["exp_name"] = make_exp_name(cfg)
        run_plan.append(merged)
    return run_plan


def run_one(cfg):
    args = get_cell7_base_args()
    args.mode = 3
    args.exp_name = cfg["exp_name"]
    args.duration = cfg["duration"]
    args.pretrained_model = cfg["ptm"]
    args.feature_mode = cfg["feat_mode"]
    args.fusion_method = cfg["fusion"]
    args.branch_dropout_prob = cfg["branch_dropout_prob"]
    args.use_gating = False
    args.use_augment = cfg["use_augment"]
    args.augment_prob = cfg["augment_prob"]
    args.feature_noise_std = cfg["feature_noise_std"]
    args.embedding_noise_std = cfg["embedding_noise_std"]
    args.num_epochs = cfg["num_epochs"]
    args.early_stop_patience = cfg["early_stop_patience"]
    args.learning_rate = cfg["learning_rate"]
    args.weight_decay = cfg["weight_decay"]
    args.aam_margin = cfg["aam_margin"]
    args.aam_scale = cfg["aam_scale"]
    args.use_two_stage_ft = cfg["use_two_stage_ft"]
    args.stage1_epochs = cfg["stage1_epochs"]
    args.stage2_ptm_lr_scale = cfg["stage2_ptm_lr_scale"]
    args.seed = cfg["seed"]

    prefix = DUR_PREFIX_MAP[cfg["duration"]]
    args.embedding_path = os.path.join(ROOT_DIR, "Embeddings", cfg["duration"], prefix + cfg["ptm"] + "_shards")
    args.feature_path = os.path.join(ROOT_DIR, "extracted_features", cfg["duration"], cfg["feat_dir"] + "_shards")
    args.init_mode1_ckpt = os.path.join(
        "./outputs",
        "experiments",
        "Mode1_PTM_" + cfg["duration"] + "_" + cfg["ptm"],
        "best_model.pth",
    )
    args.init_mode2_ckpt = os.path.join(
        "./outputs",
        "experiments",
        "Mode2_HC_" + cfg["duration"] + "_" + cfg["feat_mode"],
        "best_model.pth",
    )
    train(args)


run_plan = build_run_plan()
if MAX_RUNS is not None:
    run_plan = run_plan[: max(0, int(MAX_RUNS))]

print("SEARCH_TAG:", SEARCH_TAG)
print("EXPERIMENTS_DIRNAME:", EXPERIMENTS_DIRNAME)
print("REPORT_PREFIX:", REPORT_PREFIX)
print("TOTAL RUNS:", len(run_plan))
for i, cfg in enumerate(run_plan, 1):
    print("[{0:02d}] {1}".format(i, cfg["exp_name"]))

results = []
wall_start = time.time()
os.makedirs("./outputs", exist_ok=True)

for i, cfg in enumerate(run_plan, 1):
    if check_skip_cell7(cfg["exp_name"]):
        results.append({"exp_name": cfg["exp_name"], "status": "skipped_existing", "minutes": 0.0})
        continue

    run_start = time.time()
    print("\n" + "=" * 72)
    print("[{0}/{1}] START: {2}".format(i, len(run_plan), cfg["exp_name"]))
    print("=" * 72)

    try:
        run_one(cfg)
        minutes = round((time.time() - run_start) / 60.0, 2)
        results.append({"exp_name": cfg["exp_name"], "status": "done", "minutes": minutes})
        print("DONE:", cfg["exp_name"], "|", minutes, "min")
    except KeyboardInterrupt:
        print("Interrupted by user. Stop overnight plan.")
        raise
    except Exception as ex:
        minutes = round((time.time() - run_start) / 60.0, 2)
        results.append({"exp_name": cfg["exp_name"], "status": "error: " + type(ex).__name__, "minutes": minutes})
        print("ERROR:", cfg["exp_name"], "->", type(ex).__name__, ex)
        traceback.print_exc()
        print("Continue to next run...")
    finally:
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

summary_df = pd.DataFrame(results)
summary_path = os.path.join("./outputs", SEARCH_TAG + "_overnight_run_summary.csv")
if len(summary_df) > 0:
    summary_df.to_csv(summary_path, index=False)
    print("Saved overnight summary:", summary_path)
    print(summary_df.to_string(index=False))

print("Total wall time (hours):", round((time.time() - wall_start) / 3600.0, 2))
print("Morning steps: run Cell 11 rồi Cell 12.")

## 3. Tensorboard

In [ ]:
# Load TensorBoard extension
%load_ext tensorboard

# Chạy giao diện TensorBoard trỏ vào thư mục chứa tất cả các experiments
%tensorboard --logdir train/outputs/experiments

## 4. Benchmark & Ensemble

In [1]:
import gc
import os
import glob
import json
import warnings
from collections import OrderedDict
from itertools import combinations

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from tqdm.auto import tqdm

from model import get_model
from metrics import compute_eer, compute_mindcf

warnings.filterwarnings("ignore")

# ============================================================================
# CONFIG
# - Duration ensemble: keep the requested fixed duration combinations
# - Representation ensemble: generate all PTM/HC combinations within the same duration
# - Equal-weight runs are generated first, then anchor-biased weights
# - Ensemble scores are combined by fixed trial_idx vectors, not DataFrame merge
# - Explicit cache cleanup between test sets to avoid kernel crash on long runs
# - Resume mode: skip test sets that already have per-test CSV reports
# ============================================================================
REPORT_PREFIX = "ensemble_duration_representation_v2"
TEST_BASE_DIR = r"D:\test_o"
LIST_GT_DIR = os.path.join(TEST_BASE_DIR, "list_gt")
OUTPUT_DIR = "./outputs"
P_TARGET = 0.05
SKIP_EXISTING_TEST_REPORTS = True

TARGET_MODE = 3
TARGET_FUSION = "film"
ANCHOR_DURATION = "train_raw"
ANCHOR_PTM = "wav2vec2"
ANCHOR_FEATURE = "mfcc_pitch"

DURATION_ORDER = ["train_raw", "train_vi_full", "train_vi_3s", "train_vi_5s", "train_vi_7s"]
PTM_ORDER = ["wav2vec2", "wavlm", "hubert"]
FEATURE_ORDER = ["mfcc_pitch", "mfbe_pitch", "mfcc_only", "mfbe_only", "pitch_only"]

TEST_SET_CONFIGS = [
    {"name": "full_length", "trial_file": "test_list_gt.csv", "duration": "full_length"},
    {"name": "test_vi", "trial_file": "test_list_gt_vi.csv", "duration": "test_vi"},
    {"name": "test_3s", "trial_file": "test_list_gt_3s.csv", "duration": "test_3s"},
    {"name": "test_5s", "trial_file": "test_list_gt_5s.csv", "duration": "test_5s"},
    {"name": "test_7s", "trial_file": "test_list_gt_7s.csv", "duration": "test_7s"},
]

SOURCE_EXPERIMENT_ROOTS = []
for pattern in ["./outputs/experiments", "./outputs/experiments_*"]:
    for candidate in sorted(glob.glob(pattern)):
        if os.path.isdir(candidate) and candidate not in SOURCE_EXPERIMENT_ROOTS:
            SOURCE_EXPERIMENT_ROOTS.append(candidate)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")
print(f"Report prefix: {REPORT_PREFIX}")
print(f"Target mode/fusion: {TARGET_MODE}/{TARGET_FUSION}")
print(f"Skip existing per-test reports: {SKIP_EXISTING_TEST_REPORTS}")
print("Source experiment roots:")
for root in SOURCE_EXPERIMENT_ROOTS:
    print(" -", root)

HC_FILENAME_MAP = {
    "mfbe_only": "Only_MFBE.pt",
    "pitch_only": "Only_Pitch.pt",
    "mfcc_only": "Only_MFCC.pt",
    "mfbe_pitch": "MFBE_Pitch.pt",
    "mfcc_pitch": "MFCC_Pitch.pt",
}

BASE_DURATION_ENSEMBLE_SPECS = [
    {"family": "duration", "name": "raw_vi_full", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_3s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_3s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_5s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_5s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_7s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_7s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_3s_5s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_3s__wav2vec2__mfcc_pitch",
        "train_vi_5s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_3s_7s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_3s__wav2vec2__mfcc_pitch",
        "train_vi_7s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_5s_7s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_5s__wav2vec2__mfcc_pitch",
        "train_vi_7s__wav2vec2__mfcc_pitch",
    ]},
    {"family": "duration", "name": "raw_vi_full_3s_5s_7s", "members": [
        "train_raw__wav2vec2__mfcc_pitch",
        "train_vi_full__wav2vec2__mfcc_pitch",
        "train_vi_3s__wav2vec2__mfcc_pitch",
        "train_vi_5s__wav2vec2__mfcc_pitch",
        "train_vi_7s__wav2vec2__mfcc_pitch",
    ]},
]

def parse_trial_csv(trial_csv_path: str) -> pd.DataFrame:
    raw_df = pd.read_csv(trial_csv_path, header=None)
    if raw_df.shape[1] >= 3:
        df = raw_df.iloc[:, :3].copy()
        df.columns = ["label", "path1", "path2"]
    else:
        df = raw_df.rename(columns={0: "raw"}).copy()
        parsed = df["raw"].astype(str).str.strip('"').str.extract(r"^\s*([01])\s+(.+?)\s+(.+?)\s*$")
        parsed.columns = ["label", "path1", "path2"]
        df = parsed
    df["label"] = df["label"].astype(int)
    df["path1"] = df["path1"].astype(str)
    df["path2"] = df["path2"].astype(str)
    df = df.reset_index(drop=True)
    df["trial_idx"] = np.arange(len(df), dtype=np.int64)
    return df[["trial_idx", "label", "path1", "path2"]]

def _candidate_keys(path_text: str):
    p = str(path_text).replace('\\', '/').strip()
    base = os.path.basename(p)
    stem = os.path.splitext(base)[0]
    rel = p.lstrip('./')
    out, seen = [], set()
    for key in [p, rel, base, stem]:
        if key not in seen:
            out.append(key)
            seen.add(key)
    return out

def _register_lookup(lookup, path_text, value):
    for key in _candidate_keys(path_text):
        if key not in lookup:
            lookup[key] = value

def _get_feature_from_lookup(lookup, path_text):
    if lookup is None:
        return None
    for key in _candidate_keys(path_text):
        if key in lookup:
            return lookup[key]
    return None

def resolve_ptm_path(ptm_name: str, ptm_dir: str):
    ptm_name = str(ptm_name).lower()
    cands = [
        os.path.join(ptm_dir, f"Embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"all_embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"embeddings_{ptm_name}.pt"),
        os.path.join(ptm_dir, f"{ptm_name}.pt"),
    ]
    for p in cands:
        if os.path.exists(p):
            return p
    return None

def resolve_hc_path(feature_mode: str, feature_dir: str):
    feature_mode = str(feature_mode).lower()
    if feature_mode in HC_FILENAME_MAP:
        p = os.path.join(feature_dir, HC_FILENAME_MAP[feature_mode])
        if os.path.exists(p):
            return p
    for p in [
        os.path.join(feature_dir, f"{feature_mode}.pt"),
        os.path.join(feature_dir, f"all_features_{feature_mode}.pt"),
    ]:
        if os.path.exists(p):
            return p
    return None

def _to_float_tensor(value):
    if torch.is_tensor(value):
        return value.float().detach().cpu()
    return torch.tensor(value, dtype=torch.float32)

def build_lookup_from_pt_file(obj, value_field: str):
    lookup = {}
    if not isinstance(obj, dict):
        raise ValueError(f"Unsupported .pt format: expected dict, got {type(obj).__name__}")

    if "filenames" in obj and value_field in obj:
        filenames = obj["filenames"]
        values = obj[value_field]
        if len(filenames) != len(values):
            raise ValueError(
                f"Unsupported .pt format: len(filenames)={len(filenames)} != len({value_field})={len(values)}"
            )
        for idx, name in enumerate(filenames):
            _register_lookup(lookup, str(name), _to_float_tensor(values[idx]))
        return lookup

    if len(obj) > 0 and all(isinstance(k, str) for k in obj.keys()):
        for name, value in obj.items():
            if isinstance(value, (dict, list, tuple, str, int, float, bool, type(None))) and not torch.is_tensor(value):
                continue
            _register_lookup(lookup, str(name), _to_float_tensor(value))
        if len(lookup) > 0:
            return lookup

    raise ValueError("Unsupported .pt format: missing expected keys")

def _safe_float(value, default=None):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default

def _ordered_index(value, ordered_values):
    try:
        return ordered_values.index(value)
    except ValueError:
        return len(ordered_values)

def _config_alias(duration, ptm_name, feature_mode):
    return f"{duration}__{ptm_name}__{feature_mode}"

def _short_feature_name(feature_mode):
    return str(feature_mode).replace("_only", "")

def _canonical_member_sort_key(alias):
    duration, ptm_name, feature_mode = alias.split("__", 2)
    anchor_bias = 0 if (duration == ANCHOR_DURATION and ptm_name == ANCHOR_PTM and feature_mode == ANCHOR_FEATURE) else 1
    return (
        anchor_bias,
        _ordered_index(duration, DURATION_ORDER),
        _ordered_index(ptm_name, PTM_ORDER),
        _ordered_index(feature_mode, FEATURE_ORDER),
        alias,
    )

def discover_experiments(exp_roots):
    experiments = []
    seen = set()
    for root in exp_roots:
        if not os.path.isdir(root):
            continue
        for exp_dir in sorted(glob.glob(os.path.join(root, "*"))):
            model_path = os.path.join(exp_dir, "best_model.pth")
            config_path = os.path.join(exp_dir, "config.json")
            results_path = os.path.join(exp_dir, "results.json")
            if not (os.path.exists(model_path) and os.path.exists(config_path)):
                continue
            exp_name = os.path.basename(exp_dir)
            dedup_key = (root, exp_name)
            if dedup_key in seen:
                continue
            seen.add(dedup_key)
            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)
            results = {}
            if os.path.exists(results_path):
                with open(results_path, "r", encoding="utf-8") as f:
                    results = json.load(f)
            experiments.append({
                "exp_name": exp_name,
                "root_dir": root,
                "exp_dir": exp_dir,
                "model_path": model_path,
                "mode": int(cfg.get("mode", 3)),
                "fusion_method": str(cfg.get("fusion_method", "concat")).lower(),
                "feature_mode": str(cfg.get("feature_mode", "mfbe_pitch")).lower(),
                "pretrained_model": str(cfg.get("pretrained_model", "wavlm")).lower(),
                "duration": str(cfg.get("duration", "")).lower(),
                "branch_dropout_prob": _safe_float(cfg.get("branch_dropout_prob"), None),
                "use_augment": bool(cfg.get("use_augment", False)),
                "best_val_eer": _safe_float(results.get("best_val_eer"), np.inf),
            })
    return experiments

def build_exact_config_bank(experiments):
    grouped = OrderedDict()
    for exp in experiments:
        if exp["mode"] != TARGET_MODE:
            continue
        if exp["fusion_method"] != TARGET_FUSION:
            continue
        if not exp["duration"] or not exp["pretrained_model"] or not exp["feature_mode"]:
            continue
        alias = _config_alias(exp["duration"], exp["pretrained_model"], exp["feature_mode"])
        grouped.setdefault(alias, []).append(exp)

    resolved = OrderedDict()
    rows = []
    for alias in sorted(grouped.keys(), key=_canonical_member_sort_key):
        candidates = sorted(
            grouped[alias],
            key=lambda x: (np.isinf(x.get("best_val_eer", np.inf)), x.get("best_val_eer", np.inf), x["exp_name"]),
        )
        picked = candidates[0]
        resolved[alias] = picked
        rows.append({
            "alias": alias,
            "picked_experiment": picked["exp_name"],
            "candidate_count": len(candidates),
            "duration": picked["duration"],
            "ptm": picked["pretrained_model"],
            "feature": picked["feature_mode"],
            "fusion": picked["fusion_method"],
            "best_val_eer": None if np.isinf(picked.get("best_val_eer", np.inf)) else picked.get("best_val_eer"),
        })
    return resolved, pd.DataFrame(rows)

def make_weight_variants(member_count):
    if member_count == 2:
        return [
            ("eq", [0.5, 0.5]),
            ("a60", [0.6, 0.4]),
            ("a70", [0.7, 0.3]),
        ]
    if member_count == 3:
        return [
            ("eq", [1 / 3, 1 / 3, 1 / 3]),
            ("a50", [0.5, 0.3, 0.2]),
            ("a60", [0.6, 0.25, 0.15]),
        ]
    if member_count == 4:
        return [
            ("eq", [0.25, 0.25, 0.25, 0.25]),
            ("a45", [0.45, 0.25, 0.15, 0.15]),
            ("a50", [0.5, 0.2, 0.15, 0.15]),
        ]
    if member_count == 5:
        return [
            ("eq", [0.2, 0.2, 0.2, 0.2, 0.2]),
            ("a40", [0.4, 0.25, 0.15, 0.1, 0.1]),
            ("a45", [0.45, 0.2, 0.15, 0.1, 0.1]),
        ]
    equal = [1.0 / member_count] * member_count
    return [("eq", equal)]

def _append_weighted_jobs(jobs, family, name_prefix, member_aliases):
    ordered_members = sorted(member_aliases, key=_canonical_member_sort_key)
    for weight_tag, weights in make_weight_variants(len(ordered_members)):
        weight_sum = sum(weights)
        normalized = [float(w / weight_sum) for w in weights]
        jobs.append({
            "family": family,
            "name": name_prefix,
            "member_aliases": ordered_members,
            "weights": normalized,
            "weight_tag": weight_tag,
            "ensemble_name": f"ENS_{family}_{name_prefix}__{weight_tag}",
        })

def expand_duration_jobs(base_specs, exact_bank):
    jobs = []
    for spec in base_specs:
        missing = [alias for alias in spec["members"] if alias not in exact_bank]
        if missing:
            print(f"[SKIP DURATION] {spec['name']} missing members: {missing}")
            continue
        _append_weighted_jobs(jobs, spec["family"], spec["name"], spec["members"])
    return jobs

def _subset_lists(aliases):
    aliases = sorted(aliases, key=_canonical_member_sort_key)
    out = []
    for size in range(2, len(aliases) + 1):
        for combo in combinations(aliases, size):
            out.append(list(combo))
    return out

def generate_representation_jobs(exact_bank):
    jobs = []
    grouped_by_duration = OrderedDict()
    for alias, exp in exact_bank.items():
        grouped_by_duration.setdefault(exp["duration"], []).append((alias, exp))

    for duration in sorted(grouped_by_duration.keys(), key=lambda d: (_ordered_index(d, DURATION_ORDER), d)):
        items = grouped_by_duration[duration]
        by_feature = OrderedDict()
        by_ptm = OrderedDict()

        for alias, exp in items:
            by_feature.setdefault(exp["feature_mode"], []).append(alias)
            by_ptm.setdefault(exp["pretrained_model"], []).append(alias)

        for feature_mode, aliases in sorted(by_feature.items(), key=lambda kv: (_ordered_index(kv[0], FEATURE_ORDER), kv[0])):
            if len(aliases) < 2:
                continue
            for member_aliases in _subset_lists(aliases):
                ptm_tags = [exact_bank[a]["pretrained_model"] for a in member_aliases]
                name_prefix = f"{duration}_ptm_{feature_mode}__{'_'.join(ptm_tags)}"
                _append_weighted_jobs(jobs, "representation_ptm", name_prefix, member_aliases)

        for ptm_name, aliases in sorted(by_ptm.items(), key=lambda kv: (_ordered_index(kv[0], PTM_ORDER), kv[0])):
            if len(aliases) < 2:
                continue
            for member_aliases in _subset_lists(aliases):
                feat_tags = [_short_feature_name(exact_bank[a]["feature_mode"]) for a in member_aliases]
                name_prefix = f"{duration}_hc_{ptm_name}__{'_'.join(feat_tags)}"
                _append_weighted_jobs(jobs, "representation_hc", name_prefix, member_aliases)

    return jobs

def get_test_set_dirs(test_set_name: str, duration: str):
    base_dir = os.path.join(TEST_BASE_DIR, test_set_name)
    ptm_dir = os.path.join(base_dir, "embeddings")
    feature_dir = os.path.join(base_dir, "features")
    if duration and duration != "full_length":
        alt_ptm = os.path.join(base_dir, duration, "embeddings")
        alt_hc = os.path.join(base_dir, duration, "features")
        if os.path.isdir(alt_ptm):
            ptm_dir = alt_ptm
        if os.path.isdir(alt_hc):
            feature_dir = alt_hc
    return ptm_dir, feature_dir

def build_path_embedding_dict(model, mode, ptm_lookup, hc_lookup, paths):
    path_to_emb = {}
    for path in tqdm(sorted(paths), desc="Embedding paths", leave=False):
        ptm_feat = _get_feature_from_lookup(ptm_lookup, path) if mode in [1, 3] else None
        hc_feat = _get_feature_from_lookup(hc_lookup, path) if mode in [2, 3] else None
        if mode in [1, 3] and ptm_feat is None:
            continue
        if mode in [2, 3] and hc_feat is None:
            continue

        inputs = {}
        if mode in [1, 3]:
            inputs["embedding"] = ptm_feat.unsqueeze(0).to(DEVICE).float()
        if mode in [2, 3]:
            inputs["feature"] = hc_feat.unsqueeze(0).to(DEVICE).float()

        _, emb = model(**inputs)
        path_to_emb[path] = F.normalize(emb, p=2, dim=1).squeeze(0).detach().cpu().numpy().astype(np.float32)
    return path_to_emb

def build_pair_score_df(model, mode, ptm_lookup, hc_lookup, trials_df):
    unique_paths = set(trials_df["path1"].tolist() + trials_df["path2"].tolist())
    path_to_emb = build_path_embedding_dict(model, mode, ptm_lookup, hc_lookup, unique_paths)
    if len(path_to_emb) < 2:
        return None

    trial_idx_list, valid_labels, pair_i, pair_j = [], [], [], []
    paths = list(path_to_emb.keys())
    path_to_idx = {p: i for i, p in enumerate(paths)}
    emb_matrix = np.stack([path_to_emb[p] for p in paths], axis=0)

    for _, row in trials_df.iterrows():
        trial_idx = int(row["trial_idx"])
        p1 = row["path1"]
        p2 = row["path2"]
        if p1 not in path_to_idx or p2 not in path_to_idx:
            continue
        trial_idx_list.append(trial_idx)
        valid_labels.append(int(row["label"]))
        pair_i.append(path_to_idx[p1])
        pair_j.append(path_to_idx[p2])

    if len(pair_i) == 0:
        return None

    pair_i = np.asarray(pair_i, dtype=np.int32)
    pair_j = np.asarray(pair_j, dtype=np.int32)
    raw_scores = np.sum(emb_matrix[pair_i] * emb_matrix[pair_j], axis=1).astype(np.float32)
    return pd.DataFrame({
        "trial_idx": np.asarray(trial_idx_list, dtype=np.int64),
        "label": np.asarray(valid_labels, dtype=np.int32),
        "score": raw_scores,
    })

def summarize_scores_from_arrays(labels_np, scores_np):
    eer, _ = compute_eer(labels_np, scores_np)
    mindcf, _ = compute_mindcf(labels_np, scores_np, p_target=P_TARGET)
    return {
        "EER (%)": float(eer * 100.0),
        "MinDCF": float(mindcf),
        "Used Pairs": int(len(scores_np)),
    }

def score_df_to_dense_arrays(score_df, num_trials):
    if score_df is None or len(score_df) == 0:
        return None
    if score_df["trial_idx"].duplicated().any():
        dup_count = int(score_df["trial_idx"].duplicated().sum())
        raise RuntimeError(f"Duplicate trial_idx detected in score_df: {dup_count}")
    score_vec = np.full(num_trials, np.nan, dtype=np.float32)
    label_vec = np.full(num_trials, -1, dtype=np.int32)
    trial_idx = score_df["trial_idx"].to_numpy(dtype=np.int64)
    labels = score_df["label"].to_numpy(dtype=np.int32)
    scores = score_df["score"].to_numpy(dtype=np.float32)
    score_vec[trial_idx] = scores
    label_vec[trial_idx] = labels
    return score_vec, label_vec

LOOKUP_CACHE = {"ptm": {}, "hc": {}}

def clear_lookup_cache():
    LOOKUP_CACHE["ptm"].clear()
    LOOKUP_CACHE["hc"].clear()
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

def get_ptm_lookup(test_set_name, duration, ptm_name, ptm_dir):
    key = (test_set_name, duration, ptm_name)
    if key not in LOOKUP_CACHE["ptm"]:
        ptm_path = resolve_ptm_path(ptm_name, ptm_dir)
        LOOKUP_CACHE["ptm"][key] = None if ptm_path is None else build_lookup_from_pt_file(
            torch.load(ptm_path, map_location="cpu"),
            "embeddings",
        )
    return LOOKUP_CACHE["ptm"][key]

def get_hc_lookup(test_set_name, duration, feature_mode, feature_dir):
    key = (test_set_name, duration, feature_mode)
    if key not in LOOKUP_CACHE["hc"]:
        hc_path = resolve_hc_path(feature_mode, feature_dir)
        LOOKUP_CACHE["hc"][key] = None if hc_path is None else build_lookup_from_pt_file(
            torch.load(hc_path, map_location="cpu"),
            "features",
        )
    return LOOKUP_CACHE["hc"][key]

@torch.no_grad()
def score_single_experiment(exp_info, trials_df, test_set_name, ptm_dir, feature_dir):
    model = None
    ckpt = None
    score_df = None
    try:
        mode = exp_info["mode"]
        ptm_name = exp_info["pretrained_model"]
        feature_mode = exp_info["feature_mode"]

        ptm_lookup = get_ptm_lookup(test_set_name, exp_info["duration"], ptm_name, ptm_dir) if mode in [1, 3] else None
        hc_lookup = get_hc_lookup(test_set_name, exp_info["duration"], feature_mode, feature_dir) if mode in [2, 3] else None
        if mode in [1, 3] and ptm_lookup is None:
            return None, None, None
        if mode in [2, 3] and hc_lookup is None:
            return None, None, None

        model = get_model(
            num_speakers=1000,
            device=str(DEVICE),
            mode=mode,
            fusion_method=exp_info["fusion_method"],
            feature_mode=feature_mode,
            use_gating=(exp_info["fusion_method"] == "gating"),
        )
        ckpt = torch.load(exp_info["model_path"], map_location=DEVICE)
        model.load_state_dict(ckpt["model_state_dict"], strict=True)
        model.eval()

        score_df = build_pair_score_df(model, mode, ptm_lookup, hc_lookup, trials_df)
        if score_df is None or len(score_df) == 0:
            return None, None, None

        dense_pack = score_df_to_dense_arrays(score_df, len(trials_df))
        if dense_pack is None:
            return None, None, None
        score_vec, label_vec = dense_pack
        valid_mask = np.isfinite(score_vec)
        metrics = summarize_scores_from_arrays(label_vec[valid_mask], score_vec[valid_mask])
        row = {
            "TestSet": test_set_name,
            "Experiment": exp_info["exp_name"],
            "Kind": "single",
            "Family": "single",
            "Members": exp_info["exp_name"],
            "Weights": "1.0",
            "Mode": mode,
            "Fusion": exp_info["fusion_method"],
            "Feature": feature_mode,
            "PTM": ptm_name,
            "Duration": exp_info["duration"],
            **metrics,
            "Missing Pairs": int(len(trials_df) - int(valid_mask.sum())),
        }
        return row, score_vec, label_vec
    finally:
        del score_df
        del ckpt
        del model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

def score_ensemble_job(job, test_set_name, trials_df, score_cache, exact_bank):
    member_aliases = job["member_aliases"]
    member_exp_names = [exact_bank[alias]["exp_name"] for alias in member_aliases]
    score_vectors = []
    label_reference = None
    for exp_name in member_exp_names:
        cache_item = score_cache.get(exp_name)
        if cache_item is None:
            return None
        score_vec, label_vec = cache_item
        if label_reference is None:
            label_reference = label_vec
        elif not np.array_equal(label_reference, label_vec):
            raise RuntimeError(f"Label mismatch across ensemble members for {job['ensemble_name']}")
        score_vectors.append(score_vec)

    stacked = np.stack(score_vectors, axis=0)
    valid_mask = np.all(np.isfinite(stacked), axis=0)
    used_pairs = int(valid_mask.sum())
    if used_pairs == 0:
        return None

    weights = np.asarray(job["weights"], dtype=np.float32).reshape(-1, 1)
    fused_scores = np.sum(stacked * weights, axis=0)
    labels_used = label_reference[valid_mask]
    scores_used = fused_scores[valid_mask]
    metrics = summarize_scores_from_arrays(labels_used, scores_used)
    resolved_members = [exact_bank[alias]["exp_name"] for alias in member_aliases]
    return {
        "TestSet": test_set_name,
        "Experiment": job["ensemble_name"],
        "Kind": "ensemble",
        "Family": job["family"],
        "Members": " | ".join(member_aliases),
        "ResolvedMembers": " | ".join(resolved_members),
        "Weights": ",".join([f"{w:.4f}" for w in job["weights"]]),
        "Mode": "ensemble",
        "Fusion": "ensemble",
        "Feature": "ensemble",
        "PTM": "ensemble",
        "Duration": "multi",
        **metrics,
        "Missing Pairs": int(len(trials_df) - used_pairs),
    }

all_experiments = discover_experiments(SOURCE_EXPERIMENT_ROOTS)
print(f"Discovered {len(all_experiments)} experiments")

exact_bank, bank_df = build_exact_config_bank(all_experiments)
bank_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_exact_config_bank.csv")
os.makedirs(OUTPUT_DIR, exist_ok=True)
bank_df.to_csv(bank_path, index=False)
print(f"Saved exact config bank: {bank_path}")
display(bank_df)

duration_jobs = expand_duration_jobs(BASE_DURATION_ENSEMBLE_SPECS, exact_bank)
representation_jobs = generate_representation_jobs(exact_bank)
ensemble_jobs = duration_jobs + representation_jobs

plan_rows = []
for job in ensemble_jobs:
    plan_rows.append({
        "ensemble_name": job["ensemble_name"],
        "family": job["family"],
        "members": " | ".join(job["member_aliases"]),
        "weights": ",".join([f"{w:.4f}" for w in job["weights"]]),
    })
plan_df = pd.DataFrame(plan_rows)
plan_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_ensemble_plan.csv")
plan_df.to_csv(plan_path, index=False)
print(f"Saved ensemble plan: {plan_path}")
display(plan_df.head(50))

resolved_members = exact_bank
if len(resolved_members) == 0:
    raise RuntimeError("Không resolve được model nào trong exact config bank.")

all_results = []
for test_cfg in TEST_SET_CONFIGS:
    clear_lookup_cache()
    test_set_name = test_cfg["name"]
    trial_path = os.path.join(LIST_GT_DIR, test_cfg["trial_file"])
    duration = test_cfg.get("duration", "")
    out_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_{test_set_name}.csv")
    print("\n" + "=" * 88)
    print(f"TEST SET: {test_set_name}")
    print("=" * 88)

    if SKIP_EXISTING_TEST_REPORTS and os.path.exists(out_path):
        print(f"[SKIP TEST] Existing report found: {out_path}")
        try:
            existing_df = pd.read_csv(out_path)
            all_results.extend(existing_df.to_dict(orient="records"))
            print(f"Loaded {len(existing_df)} existing rows from {test_set_name}")
        except Exception as ex:
            print(f"⚠ Could not load existing report {out_path}: {ex}")
        continue

    if not os.path.exists(trial_path):
        print(f"⚠ Skip {test_set_name}: missing trial file {trial_path}")
        continue

    ptm_dir, feature_dir = get_test_set_dirs(test_set_name, duration)
    if not os.path.isdir(ptm_dir) or not os.path.isdir(feature_dir):
        print(f"⚠ Skip {test_set_name}: missing feature directories")
        continue

    trials_df = parse_trial_csv(trial_path)
    score_cache = {}
    per_test_rows = []

    for alias, exp_info in tqdm(resolved_members.items(), desc=f"Singles {test_set_name}"):
        try:
            row, score_vec, label_vec = score_single_experiment(exp_info, trials_df, test_set_name, ptm_dir, feature_dir)
            if row is not None and score_vec is not None and label_vec is not None:
                row["BankAlias"] = alias
                per_test_rows.append(row)
                score_cache[exp_info["exp_name"]] = (score_vec, label_vec)
        except Exception as ex:
            print(f"[ERROR][single] {test_set_name} | {alias} | {exp_info['exp_name']}: {ex}")
        finally:
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    for job in tqdm(ensemble_jobs, desc=f"Ensembles {test_set_name}"):
        try:
            row = score_ensemble_job(job, test_set_name, trials_df, score_cache, exact_bank)
            if row is not None:
                per_test_rows.append(row)
        except Exception as ex:
            print(f"[ERROR][ensemble] {test_set_name} | {job['ensemble_name']}: {ex}")

    per_test_df = pd.DataFrame(per_test_rows)
    if len(per_test_df) == 0:
        print(f"⚠ No valid results for {test_set_name}")
        clear_lookup_cache()
        del score_cache
        del per_test_rows
        gc.collect()
        continue

    per_test_df = per_test_df.sort_values(["EER (%)", "MinDCF"], ascending=[True, True]).reset_index(drop=True)
    per_test_df.to_csv(out_path, index=False)
    print(f"✓ Saved: {out_path}")
    display(per_test_df.head(30))
    all_results.extend(per_test_rows)

    clear_lookup_cache()
    del score_cache
    del trials_df
    del per_test_rows
    del per_test_df
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

all_df = pd.DataFrame(all_results)
all_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_all_models.csv")
if len(all_df) > 0:
    all_df = all_df.sort_values(["TestSet", "EER (%)", "MinDCF"], ascending=[True, True, True]).reset_index(drop=True)
    all_df.to_csv(all_path, index=False)
    print(f"✓ Saved total report: {all_path}")
    display(all_df.head(50))
else:
    print("⚠ No valid benchmark or ensemble results.")

Device: cuda
Report prefix: ensemble_duration_representation_v2
Target mode/fusion: 3/film
Skip existing per-test reports: True
Source experiment roots:
 - ./outputs/experiments
 - ./outputs\experiments_grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam
 - ./outputs\experiments_new
 - ./outputs\experiments_new_round2_no2stage
 - ./outputs\experiments_overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1
Discovered 299 experiments
Saved exact config bank: ./outputs\ensemble_duration_representation_v2_exact_config_bank.csv

,alias,picked_experiment,candidate_count,duration,ptm,feature,fusion,best_val_eer
0,train_raw__wav2vec2__mfcc_pitch,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...,26,train_raw,wav2vec2,mfcc_pitch,film,7.27
1,train_raw__wav2vec2__mfbe_pitch,Mode3_film_train_raw_wav2vec2_mfbe_pitch,1,train_raw,wav2vec2,mfbe_pitch,film,8.01
2,train_raw__wav2vec2__mfcc_only,Mode3_film_train_raw_wav2vec2_mfcc_only,1,train_raw,wav2vec2,mfcc_only,film,8.06
3,train_raw__wav2vec2__mfbe_only,Mode3_film_train_raw_wav2vec2_mfbe_only,1,train_raw,wav2vec2,mfbe_only,film,8.29
4,train_raw__wav2vec2__pitch_only,Mode3_film_train_raw_wav2vec2_pitch_only,1,train_raw,wav2vec2,pitch_only,film,9.01
...,...,...,...,...,...,...,...,...
70,train_vi_7s__hubert__mfcc_pitch,Mode3_film_train_vi_7s_hubert_mfcc_pitch,1,train_vi_7s,hubert,mfcc_pitch,film,3.09
71,train_vi_7s__hubert__mfbe_pitch,Mode3_film_train_vi_7s_hubert_mfbe_pitch,1,train_vi_7s,hubert,mfbe_pitch,film,4.61
72,train_vi_7s__hubert__mfcc_only,Mode3_film_train_vi_7s_hubert_mfcc_only,1,train_vi_7s,hubert,mfcc_only,film,3.75
73,train_vi_7s__hubert__mfbe_only,Mode3_film_train_vi_7s_hubert_mfbe_only,1,train_vi_7s,hubert,mfbe_only,film,3.86
74,train_vi_7s__hubert__pitch_only,Mode3_film_train_vi_7s_hubert_pitch_only,1,train_vi_7s,hubert,pitch_only,film,6.05

Saved ensemble plan: ./outputs\ensemble_duration_representation_v2_ensemble_plan.csv

,ensemble_name,family,members,weights
0,ENS_duration_raw_vi_full__eq,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.5000,0.5000"
1,ENS_duration_raw_vi_full__a60,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.6000,0.4000"
2,ENS_duration_raw_vi_full__a70,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.7000,0.3000"
3,ENS_duration_raw_vi_full_3s__eq,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.3333,0.3333,0.3333"
4,ENS_duration_raw_vi_full_3s__a50,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.5000,0.3000,0.2000"
5,ENS_duration_raw_vi_full_3s__a60,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.6000,0.2500,0.1500"
6,ENS_duration_raw_vi_full_5s__eq,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.3333,0.3333,0.3333"
7,ENS_duration_raw_vi_full_5s__a50,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.5000,0.3000,0.2000"
8,ENS_duration_raw_vi_full_5s__a60,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.6000,0.2500,0.1500"
9,ENS_duration_raw_vi_full_7s__eq,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.3333,0.3333,0.3333"
10,ENS_duration_raw_vi_full_7s__a50,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.5000,0.3000,0.2000"
11,ENS_duration_raw_vi_full_7s__a60,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.6000,0.2500,0.1500"
12,ENS_duration_raw_vi_full_3s_5s__eq,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.2500,0.2500,0.2500,0.2500"
13,ENS_duration_raw_vi_full_3s_5s__a45,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.4500,0.2500,0.1500,0.1500"
14,ENS_duration_raw_vi_full_3s_5s__a50,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.5000,0.2000,0.1500,0.1500"
15,ENS_duration_raw_vi_full_3s_7s__eq,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.2500,0.2500,0.2500,0.2500"
16,ENS_duration_raw_vi_full_3s_7s__a45,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.4500,0.2500,0.1500,0.1500"
17,ENS_duration_raw_vi_full_3s_7s__a50,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.5000,0.2000,0.1500,0.1500"
18,ENS_duration_raw_vi_full_5s_7s__eq,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.2500,0.2500,0.2500,0.2500"
19,ENS_duration_raw_vi_full_5s_7s__a45,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.4500,0.2500,0.1500,0.1500"
20,ENS_duration_raw_vi_full_5s_7s__a50,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.5000,0.2000,0.1500,0.1500"
21,ENS_duration_raw_vi_full_3s_5s_7s__eq,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.2000,0.2000,0.2000,0.2000,0.2000"
22,ENS_duration_raw_vi_full_3s_5s_7s__a40,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.4000,0.2500,0.1500,0.1000,0.1000"
23,ENS_duration_raw_vi_full_3s_5s_7s__a45,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.4500,0.2000,0.1500,0.1000,0.1000"
24,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.5000"
25,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.4000"
26,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.7000,0.3000"
27,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__h...,"0.5000,0.5000"
28,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__h...,"0.6000,0.4000"
29,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__h...,"0.7000,0.3000"
30,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wavlm__mfcc_pitch | train_raw__hube...,"0.5000,0.5000"
31,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wavlm__mfcc_pitch | train_raw__hube...,"0.6000,0.4000"
32,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wavlm__mfcc_pitch | train_raw__hube...,"0.7000,0.3000"
33,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.3333,0.3333,0.3333"
34,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.3000,0.2000"
35,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500"
36,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__w...,"0.5000,0.5000"
37,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__w...,"0.6000,0.4000"
38,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__w...,"0.7000,0.3000"
39,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__h...,"0.5000,0.5000"
40,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__h...,"0.6000,0.4000"
41,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__h...,"0.7000,0.3000"
42,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wavlm__mfbe_pitch | train_raw__hube...,"0.5000,0.5000"
43,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wavlm__mfbe_pitch | train_raw__hube...,"0.6000,0.4000"
44,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wavlm__mfbe_pitch | train_raw__hube...,"0.7000,0.3000"
45,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__w...,"0.3333,0.3333,0.3333"
46,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__w...,"0.5000,0.3000,0.2000"
47,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__w...,"0.6000,0.2500,0.1500"
48,ENS_representation_ptm_train_raw_ptm_mfcc_only...,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.5000,0.5000"
49,ENS_representation_ptm_train_raw_ptm_mfcc_only...,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.6000,0.4000"

========================================================================================
TEST SET: full_length
========================================================================================
[SKIP TEST] Existing report found: ./outputs\ensemble_duration_representation_v2_full_length.csv
Loaded 1569 existing rows from full_length

========================================================================================
TEST SET: test_vi
========================================================================================

Singles test_vi:   0%|          | 0/75 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/12292 [00:00<?, ?it/s]

Ensembles test_vi:   0%|          | 0/1494 [00:00<?, ?it/s]

✓ Saved: ./outputs\ensemble_duration_representation_v2_test_vi.csv

,TestSet,Experiment,Kind,Family,Members,Weights,Mode,Fusion,Feature,PTM,Duration,EER (%),MinDCF,Used Pairs,Missing Pairs,BankAlias,ResolvedMembers
0,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.313705,0.219495,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
1,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.347571,0.221015,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
2,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.354284,0.222571,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
3,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,3.354284,0.227361,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
4,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.388150,0.236142,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
5,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.394862,0.234951,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
6,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.394862,0.236995,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
7,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.394862,0.240328,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
8,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,3.401574,0.234018,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
9,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.435441,0.223468,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
10,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.435441,0.229405,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
11,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.476019,0.237484,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
12,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.509885,0.234427,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
13,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__h...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.516598,0.226019,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
14,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.4500,0.2500,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.516598,0.236880,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
15,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.550464,0.233707,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
16,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.557176,0.231547,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
17,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,3.557176,0.232578,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
18,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.2000,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.557176,0.233200,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
19,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.557176,0.233707,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
20,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.557176,0.234524,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
21,test_vi,ENS_duration_raw_vi_full_3s__a60,ensemble,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.557176,0.239199,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
22,test_vi,ENS_duration_raw_vi_full__a70,ensemble,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.557176,0.252549,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
23,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.563888,0.238461,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
24,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.4500,0.2000,0.1500,0.1000,0.1000",ensemble,ensemble,ensemble,ensemble,multi,3.591042,0.239510,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
25,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.597754,0.228490,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
26,test_vi,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__h...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.597754,0.229636,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
27,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.4500,0.2500,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.597754,0.233689,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
28,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.597754,0.236880,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
29,test_vi,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.2000,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.597754,0.237057,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...

========================================================================================
TEST SET: test_3s
========================================================================================

Singles test_3s:   0%|          | 0/75 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/9912 [00:00<?, ?it/s]

Ensembles test_3s:   0%|          | 0/1494 [00:00<?, ?it/s]

✓ Saved: ./outputs\ensemble_duration_representation_v2_test_3s.csv

,TestSet,Experiment,Kind,Family,Members,Weights,Mode,Fusion,Feature,PTM,Duration,EER (%),MinDCF,Used Pairs,Missing Pairs,BankAlias,ResolvedMembers
0,test_3s,ENS_representation_hc_train_vi_5s_hc_wav2vec2_...,ensemble,representation_hc,train_vi_5s__wav2vec2__mfcc_pitch | train_vi_5...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.273127,0.590259,9895,0,NaN,Mode3_film_train_vi_5s_wav2vec2_mfcc_pitch | M...
1,test_3s,ENS_representation_ptm_train_vi_3s_ptm_mfcc_on...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfcc_only | train_vi_3s...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.320417,0.595831,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfcc_only | Mo...
2,test_3s,ENS_representation_ptm_train_vi_3s_ptm_mfbe_pi...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfbe_pitch | train_vi_3...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.347571,0.540534,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfbe_pitch | M...
3,test_3s,ENS_representation_hc_train_vi_5s_hc_wav2vec2_...,ensemble,representation_hc,train_vi_5s__wav2vec2__mfcc_pitch | train_vi_5...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.347571,0.586757,9895,0,NaN,Mode3_film_train_vi_5s_wav2vec2_mfcc_pitch | M...
4,test_3s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.388150,0.592889,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
5,test_3s,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__h...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.394862,0.553717,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfbe_pitch | Mod...
6,test_3s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.2500,0.2500,0.2500,0.2500",ensemble,ensemble,ensemble,ensemble,multi,3.394862,0.573931,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
7,test_3s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.394862,0.593103,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
8,test_3s,ENS_representation_ptm_train_vi_3s_ptm_mfcc_on...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfcc_only | train_vi_3s...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.394862,0.601616,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfcc_only | Mo...
9,test_3s,ENS_representation_ptm_train_vi_3s_ptm_mfbe_on...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfbe_only | train_vi_3s...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.394862,0.610885,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfbe_only | Mo...
10,test_3s,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfbe_pitch | train_raw__w...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.394862,0.613045,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfbe_pitch | Mod...
11,test_3s,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.394862,0.619778,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
12,test_3s,ENS_representation_ptm_train_raw_ptm_mfbe_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfbe_pitch | train_raw__h...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.401574,0.561698,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfbe_pitch | Mod...
13,test_3s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,3.401574,0.574438,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
14,test_3s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfcc_only | train_vi_3s__...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.401574,0.585245,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfcc_only | Mode...
15,test_3s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.401574,0.589264,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
16,test_3s,ENS_representation_hc_train_vi_5s_hc_wav2vec2_...,ensemble,representation_hc,train_vi_5s__wav2vec2__mfcc_pitch | train_vi_5...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.401574,0.603360,9895,0,NaN,Mode3_film_train_vi_5s_wav2vec2_mfcc_pitch | M...
17,test_3s,ENS_representation_ptm_train_vi_3s_ptm_mfcc_on...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfcc_only | train_vi_3s...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,3.401574,0.609518,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfcc_only | Mo...
18,test_3s,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfbe_pitch | train_raw__w...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,3.428728,0.582643,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfbe_pitch | Mod...
19,test_3s,ENS_representation_hc_train_vi_5s_hc_wav2vec2_...,ensemble,representation_hc,train_vi_5s__wav2vec2__mfcc_pitch | train_vi_5...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.428728,0.590845,9895,0,NaN,Mode3_film_train_vi_5s_wav2vec2_mfcc_pitch | M...
20,test_3s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfcc_pitch | train_vi_3s_...,"0.2500,0.2500,0.2500,0.2500",ensemble,ensemble,ensemble,ensemble,multi,3.428728,0.591467,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfcc_pitch | Mod...
21,test_3s,ENS_representation_ptm_train_vi_3s_ptm_mfcc_on...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfcc_only | train_vi_3s...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.428728,0.591529,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfcc_only | Mo...
22,test_3s,ENS_representation_hc_train_vi_5s_hc_wav2vec2_...,ensemble,representation_hc,train_vi_5s__wav2vec2__mfcc_pitch | train_vi_5...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,3.428728,0.600827,9895,0,NaN,Mode3_film_train_vi_5s_wav2vec2_mfcc_pitch | M...
23,test_3s,ENS_representation_ptm_train_vi_3s_ptm_mfcc_on...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfcc_only | train_vi_3s...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.428728,0.609091,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfcc_only | Mo...
24,test_3s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_only | train_vi_3s__...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.428728,0.610451,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_only | Mode...
25,test_3s,ENS_representation_ptm_train_vi_3s_ptm_mfbe_pi...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfbe_pitch | train_vi_3...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.435441,0.545653,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfbe_pitch | M...
26,test_3s,ENS_representation_ptm_train_vi_3s_ptm_mfbe_pi...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfbe_pitch | train_vi_3...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,3.435441,0.552017,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfbe_pitch | M...
27,test_3s,ENS_representation_ptm_train_vi_full_ptm_mfcc_...,ensemble,representation_ptm,train_vi_full__wav2vec2__mfcc_only | train_vi_...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.435441,0.558869,9895,0,NaN,Mode3_film_train_vi_full_wav2vec2_mfcc_only | ...
28,test_3s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.435441,0.568732,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
29,test_3s,ENS_representation_ptm_train_vi_3s_ptm_mfbe_on...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfbe_only | train_vi_3s...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.435441,0.570954,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfbe_only | Mo...

========================================================================================
TEST SET: test_5s
========================================================================================

Singles test_5s:   0%|          | 0/75 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/5321 [00:00<?, ?it/s]

Ensembles test_5s:   0%|          | 0/1494 [00:00<?, ?it/s]

✓ Saved: ./outputs\ensemble_duration_representation_v2_test_5s.csv

,TestSet,Experiment,Kind,Family,Members,Weights,Mode,Fusion,Feature,PTM,Duration,EER (%),MinDCF,Used Pairs,Missing Pairs,BankAlias,ResolvedMembers
0,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.098121,0.785131,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
1,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,4.098121,0.808301,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
2,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,4.125275,0.783452,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
3,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.125275,0.785985,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
4,test_5s,ENS_representation_ptm_train_vi_full_ptm_mfcc_...,ensemble,representation_ptm,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,4.125275,0.801039,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
5,test_5s,ENS_representation_ptm_train_vi_full_ptm_mfcc_...,ensemble,representation_ptm,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.125275,0.805128,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
6,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.4500,0.2500,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.125275,0.808203,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
7,test_5s,Mode3_film_train_vi_full_wavlm_mfbe_pitch,single,single,Mode3_film_train_vi_full_wavlm_mfbe_pitch,1.0,3,film,mfbe_pitch,wavlm,train_vi_full,4.131987,0.749551,9895,0,train_vi_full__wavlm__mfbe_pitch,NaN
8,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.131987,0.784313,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
9,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.131987,0.805457,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
10,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.131987,0.807092,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
11,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.5000,0.2000,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.131987,0.808825,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
12,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.2500,0.2500,0.2500,0.2500",ensemble,ensemble,ensemble,ensemble,multi,4.131987,0.811625,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
13,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.5000,0.2000,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.138699,0.787059,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
14,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.138699,0.789104,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
15,test_5s,ENS_representation_ptm_train_vi_3s_ptm_mfbe_on...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfbe_only | train_vi_3s...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,4.138699,0.795059,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfbe_only | Mo...
16,test_5s,Mode3_film_train_vi_full_wavlm_mfcc_pitch,single,single,Mode3_film_train_vi_full_wavlm_mfcc_pitch,1.0,3,film,mfcc_pitch,wavlm,train_vi_full,4.138699,0.809429,9895,0,train_vi_full__wavlm__mfcc_pitch,NaN
17,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,4.165853,0.782128,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
18,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.165853,0.787602,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
19,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.165853,0.792837,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
20,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.165853,0.801466,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
21,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,4.165853,0.803004,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
22,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,4.165853,0.807465,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
23,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.165853,0.808398,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
24,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.165853,0.809368,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
25,test_5s,ENS_representation_ptm_train_raw_ptm_mfbe_only...,ensemble,representation_ptm,train_raw__wavlm__mfbe_only | train_raw__huber...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,4.172565,0.628273,9895,0,NaN,Mode3_film_train_raw_wavlm_mfbe_only | Mode3_f...
26,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfbe_pitch | train_vi_fu...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.172565,0.733365,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfbe_pitch | Mo...
27,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.2500,0.2500,0.2500,0.2500",ensemble,ensemble,ensemble,ensemble,multi,4.172565,0.789140,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
28,test_5s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.172565,0.792703,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
29,test_5s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.4000,0.2500,0.1500,0.1000,0.1000",ensemble,ensemble,ensemble,ensemble,multi,4.172565,0.798510,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...

========================================================================================
TEST SET: test_7s
========================================================================================

Singles test_7s:   0%|          | 0/75 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,491,905
  Trainable parameters: 11,491,905
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_pitch
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,543,105
  Trainable parameters: 11,543,105
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfcc_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,490,625
  Trainable parameters: 11,490,625
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: mfbe_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,541,825
  Trainable parameters: 11,541,825
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

======================================================================
Model created successfully
  Mode: 3 (1=PTM, 2=Handcrafted, 3=Fusion)
  Fusion method: film
  Feature mode: pitch_only
  Use gating: False
  Branch dropout prob: 0.0
  Num speakers: 1000
  Total parameters: 11,440,705
  Trainable parameters: 11,440,705
======================================================================

Embedding paths:   0%|          | 0/2686 [00:00<?, ?it/s]

Ensembles test_7s:   0%|          | 0/1494 [00:00<?, ?it/s]

✓ Saved: ./outputs\ensemble_duration_representation_v2_test_7s.csv

,TestSet,Experiment,Kind,Family,Members,Weights,Mode,Fusion,Feature,PTM,Duration,EER (%),MinDCF,Used Pairs,Missing Pairs,BankAlias,ResolvedMembers
0,test_7s,ENS_representation_ptm_train_vi_full_ptm_mfcc_...,ensemble,representation_ptm,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.063522,0.549767,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
1,test_7s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_only | train_vi_3s__...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.063522,0.563649,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_only | Mode...
2,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.070234,0.542737,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
3,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.070234,0.545501,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
4,test_7s,ENS_representation_ptm_train_vi_full_ptm_mfcc_...,ensemble,representation_ptm,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.097388,0.542799,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
5,test_7s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.097388,0.560139,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
6,test_7s,Mode3_film_train_vi_full_wavlm_mfcc_pitch,single,single,Mode3_film_train_vi_full_wavlm_mfcc_pitch,1.0,3,film,mfcc_pitch,wavlm,train_vi_full,3.104101,0.544257,9895,0,train_vi_full__wavlm__mfcc_pitch,NaN
7,test_7s,ENS_representation_ptm_train_vi_full_ptm_mfcc_...,ensemble,representation_ptm,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.104101,0.549029,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
8,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.104101,0.551890,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
9,test_7s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_only | train_vi_3s__...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.104101,0.560787,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_only | Mode...
10,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.110813,0.552726,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
11,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.5000,0.2000,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.137967,0.549571,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
12,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.137967,0.549962,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
13,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.137967,0.550505,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
14,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.137967,0.553544,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
15,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.144679,0.544257,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
16,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,3.144679,0.546319,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
17,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.144679,0.548345,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
18,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,3.144679,0.550505,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
19,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.4500,0.2500,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.144679,0.550584,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
20,test_7s,ENS_representation_ptm_train_vi_3s_ptm_mfbe_on...,ensemble,representation_ptm,train_vi_3s__wav2vec2__mfbe_only | train_vi_3s...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.144679,0.550798,9895,0,NaN,Mode3_film_train_vi_3s_wav2vec2_mfbe_only | Mo...
21,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.144679,0.552220,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
22,test_7s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_only | train_vi_3s__...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.144679,0.561507,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_only | Mode...
23,test_7s,ENS_representation_hc_train_vi_3s_hc_hubert__m...,ensemble,representation_hc,train_vi_3s__hubert__mfbe_pitch | train_vi_3s_...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,3.144679,0.568511,9895,0,NaN,Mode3_film_train_vi_3s_hubert_mfbe_pitch | Mod...
24,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,3.151391,0.546301,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
25,test_7s,Mode3_film_train_vi_3s_hubert_mfbe_only,single,single,Mode3_film_train_vi_3s_hubert_mfbe_only,1.0,3,film,mfbe_only,hubert,train_vi_3s,3.151391,0.548363,9895,0,train_vi_3s__hubert__mfbe_only,NaN
26,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,3.151391,0.549358,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
27,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,3.151391,0.554318,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...
28,test_7s,ENS_representation_ptm_train_vi_full_ptm_mfcc_...,ensemble,representation_ptm,train_vi_full__wav2vec2__mfcc_pitch | train_vi...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.151391,0.561098,9895,0,NaN,Mode3_film_train_vi_full_wav2vec2_mfcc_pitch_b...
29,test_7s,ENS_representation_hc_train_vi_full_hc_wavlm__...,ensemble,representation_hc,train_vi_full__wavlm__mfcc_pitch | train_vi_fu...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,3.158104,0.548363,9895,0,NaN,Mode3_film_train_vi_full_wavlm_mfcc_pitch | Mo...

✓ Saved total report: ./outputs\ensemble_duration_representation_v2_all_models.csv

,TestSet,Experiment,Kind,Family,Members,Weights,Mode,Fusion,Feature,PTM,Duration,EER (%),MinDCF,Used Pairs,Missing Pairs,BankAlias,ResolvedMembers
0,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.253722,0.528829,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
1,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,4.253722,0.531691,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
2,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.260435,0.525150,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
3,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.334879,0.526706,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
4,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,4.334879,0.542827,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
5,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__h...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.416036,0.533442,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
6,full_length,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...,single,single,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...,1.0,3,film,mfcc_pitch,wav2vec2,train_raw,4.416036,0.534509,9895,0,train_raw__wav2vec2__mfcc_pitch,NaN
7,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.416036,0.549484,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
8,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.449902,0.542863,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
9,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,4.456615,0.532411,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
10,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,4.456615,0.543681,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
11,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,4.456615,0.547147,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
12,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.490481,0.544676,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
13,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_pitc...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_pitch | train_raw__h...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,4.497193,0.532545,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
14,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.497193,0.550827,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
15,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.497193,0.552560,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
16,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.497193,0.553004,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
17,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.497193,0.554701,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
18,full_length,ENS_duration_raw_vi_full_3s__a60,ensemble,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.503905,0.542339,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
19,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.503905,0.545352,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
20,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.2000,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.503905,0.551626,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
21,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.531059,0.551546,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
22,full_length,ENS_duration_raw_vi_full__a70,ensemble,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.531059,0.551858,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
23,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.537772,0.549520,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
24,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.2000,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.537772,0.552071,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
25,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.4500,0.2500,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.537772,0.554586,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
26,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.4500,0.2500,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.537772,0.555342,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
27,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.537772,0.557856,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
28,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,4.537772,0.560932,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
29,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.4500,0.2000,0.1500,0.1000,0.1000",ensemble,ensemble,ensemble,ensemble,multi,4.571638,0.555848,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
30,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.2000,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.571638,0.559217,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
31,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,4.571638,0.563012,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
32,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.578350,0.539032,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
33,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,4.578350,0.556666,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
34,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.578350,0.559180,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
35,full_length,ENS_duration_raw_vi_full_3s_5s__a50,ensemble,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.5000,0.2000,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.578350,0.561865,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
36,full_length,ENS_duration_raw_vi_full_3s_7s__a50,ensemble,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.5000,0.2000,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.578350,0.571000,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
37,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.4500,0.2500,0.1500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.585062,0.562994,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
38,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.2500,0.2500,0.2500,0.2500",ensemble,ensemble,ensemble,ensemble,multi,4.585062,0.569962,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
39,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.612216,0.545164,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
40,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.5000,0.5000",ensemble,ensemble,ensemble,ensemble,multi,4.612216,0.546427,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
41,full_length,ENS_duration_raw_vi_full_3s__a50,ensemble,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.612216,0.550400,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
42,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.4000,0.2500,0.1500,0.1000,0.1000",ensemble,ensemble,ensemble,ensemble,multi,4.612216,0.560345,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
43,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.3333,0.3333,0.3333",ensemble,ensemble,ensemble,ensemble,multi,4.618928,0.542748,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
44,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.4000",ensemble,ensemble,ensemble,ensemble,multi,4.618928,0.548703,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
45,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.618928,0.550515,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
46,full_length,ENS_representation_ptm_train_raw_ptm_mfcc_only...,ensemble,representation_ptm,train_raw__wav2vec2__mfcc_only | train_raw__wa...,"0.7000,0.3000",ensemble,ensemble,ensemble,ensemble,multi,4.618928,0.552266,9895,0,NaN,Mode3_film_train_raw_wav2vec2_mfcc_only | Mode...
47,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.618928,0.555555,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
48,full_length,ENS_duration_raw_vi_full_5s__a60,ensemble,duration,train_raw__wav2vec2__mfcc_pitch | train_vi_ful...,"0.6000,0.2500,0.1500",ensemble,ensemble,ensemble,ensemble,multi,4.618928,0.565136,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...
49,full_length,ENS_representation_hc_train_raw_hc_wav2vec2__m...,ensemble,representation_hc,train_raw__wav2vec2__mfcc_pitch | train_raw__w...,"0.5000,0.3000,0.2000",ensemble,ensemble,ensemble,ensemble,multi,4.618928,0.568175,9895,0,NaN,grid_film_raw_w2v2_mfccpitch_bdrop0p05_aug_aam...

In [ ]:
# ============================================================================
# RANK RESULTS: full_length EER first, then test_vi EER
# Works for both single models and ensembles
# ============================================================================
import os
import pandas as pd

REPORT_PREFIX = globals().get("REPORT_PREFIX", "ensemble_duration_representation_v2")
OUTPUT_DIR = "./outputs"
full_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_full_length.csv")
vi_path = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_test_vi.csv")

if not os.path.exists(full_path) or not os.path.exists(vi_path):
    raise FileNotFoundError("Thiếu report full_length hoặc test_vi. Hãy chạy Cell 11 trước.")

df_full = pd.read_csv(full_path)
df_vi = pd.read_csv(vi_path)

keep_cols = [
    col for col in [
        "Experiment",
        "Kind",
        "Family",
        "BankAlias",
        "Members",
        "ResolvedMembers",
        "Weights",
        "Mode",
        "Fusion",
        "Feature",
        "PTM",
        "Duration",
        "EER (%)",
        "MinDCF",
        "Used Pairs",
        "Missing Pairs",
    ]
    if col in df_full.columns
]

df_full = df_full[keep_cols].rename(columns={
    "EER (%)": "EER_full",
    "MinDCF": "MinDCF_full",
    "Used Pairs": "UsedPairs_full",
    "Missing Pairs": "MissingPairs_full",
})
df_vi = df_vi[keep_cols].rename(columns={
    "EER (%)": "EER_test_vi",
    "MinDCF": "MinDCF_test_vi",
    "Used Pairs": "UsedPairs_test_vi",
    "Missing Pairs": "MissingPairs_test_vi",
})

merge_cols = [col for col in df_full.columns if col not in ["EER_full", "MinDCF_full", "UsedPairs_full", "MissingPairs_full"]]
merged = pd.merge(
    df_full,
    df_vi[[col for col in df_vi.columns if col in merge_cols or col in ["EER_test_vi", "MinDCF_test_vi", "UsedPairs_test_vi", "MissingPairs_test_vi"]]],
    on=merge_cols,
    how="inner",
)

if len(merged) == 0:
    print("Không có kết quả giao nhau giữa full_length và test_vi.")
else:
    ranked = merged.sort_values(["EER_full", "EER_test_vi"], ascending=[True, True]).reset_index(drop=True)
    print("TOP results (ưu tiên full_length EER -> test_vi EER):")
    display(ranked.head(30))

    out_rank = os.path.join(OUTPUT_DIR, f"{REPORT_PREFIX}_rank_full_then_test_vi.csv")
    ranked.to_csv(out_rank, index=False)
    print(f"✓ Saved ranking: {out_rank}")

    print("\nTop ensemble only:")
    if "Kind" in ranked.columns:
        display(ranked[ranked["Kind"] == "ensemble"].head(20))

TOP models (ưu tiên full_length EER -> test_vi EER):

,Experiment,Mode,Fusion,Feature,PTM,EER_full,MinDCF_full,EER_test_vi,MinDCF_test_vi
0,overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1...,3,film,mfcc_pitch,wav2vec2,4.659507,0.585016,5.820301,0.493460
1,overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1...,3,film,mfcc_pitch,wav2vec2,4.700085,0.605910,5.905429,0.480735
2,overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1...,3,film,mfcc_pitch,wav2vec2,4.706798,0.589264,6.185825,0.502154
3,overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1...,3,film,mfcc_pitch,wav2vec2,4.862399,0.594260,5.641707,0.471954
4,overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1...,3,film,mfcc_pitch,wav2vec2,4.862399,0.585382,6.432872,0.499235
5,overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1...,3,film,mfcc_pitch,wav2vec2,4.869112,0.608631,6.084022,0.527095
6,overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1...,3,film,mfcc_pitch,wav2vec2,5.105870,0.586786,6.509662,0.500254
7,overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1...,3,film,mfcc_pitch,wav2vec2,5.193739,0.575081,6.773384,0.498934

✓ Saved ranking: ./outputs\overnight_film_raw_w2v2_mfccpitch_ptmstatic_v1_rank_full_then_test_vi.csv

## 5. Gating Analysis (Only for Mode 3 + Gating)

In [ ]:
from train import analyze_gating_behavior
import matplotlib.image as mpimg

# Load Best Model
best_model_path = os.path.join(exp_dir, BEST_MODEL_NAME)
model, _, _, _ = load_checkpoint(best_model_path, model)
model = model.to(device)

# Kiểm tra điều kiện để chạy phân tích
if args.mode == 3 and args.fusion_method == "gating":
    print("Đang thực hiện phân tích cơ chế Gating trên tập Test...")
    
    # Gọi hàm phân tích từ train.py
    # Lưu ý: Hàm này trả về 2 giá trị: gates (trọng số PTM) và labels
    gates, labels = analyze_gating_behavior(model, test_loader, device, exp_dir)
    
    # Hiển thị biểu đồ phân phối trọng số đã được lưu
    gate_plot_path = os.path.join(exp_dir, "gating_analysis", "gate_distribution.png")
    if os.path.exists(gate_plot_path):
        plt.figure(figsize=(10, 6))
        img = mpimg.imread(gate_plot_path)
        plt.imshow(img)
        plt.axis('off')
        plt.title("Phân phối trọng số Gating (Trục X > 0.5 ưu tiên PTM, < 0.5 ưu tiên Handcrafted)")
        plt.show()
        
    # In thông tin thống kê tóm tắt
    ptm_wins = np.sum(gates > 0.5)
    hc_wins = np.sum(gates <= 0.5)
    print(f"Thống kê nhanh:")
    print(f"   - Số lần ưu tiên PTM (WavLM/HuBERT): {ptm_wins} ({100*ptm_wins/len(gates):.2f}%)")
    print(f"   - Số lần ưu tiên Handcrafted (MFCC/Pitch): {hc_wins} ({100*hc_wins/len(gates):.2f}%)")
else:
    print("ℹChế độ hiện tại không sử dụng Gating. Bỏ qua bước phân tích này.")

## 6. Experiment Comparison

In [1]:
import pandas as pd
import os
import json

# List all experiments
exp_base_dir = "./outputs/experiments"
if os.path.exists(exp_base_dir):
    experiments = []
    for exp_name_dir in sorted(os.listdir(exp_base_dir)):
        exp_path = os.path.join(exp_base_dir, exp_name_dir)
        results_file = os.path.join(exp_path, "results.json")
        if os.path.exists(results_file):
            with open(results_file, "r") as f:
                data = json.load(f)
                config = data.get("config", {})
                experiments.append({
                    "Experiment": exp_name_dir,
                    "Mode": config.get("mode", ""),
                    "Fusion": config.get("fusion_method", "N/A"),
                    "Feature": config.get("feature_mode", "N/A"),
                    "PTM": config.get("pretrained_model", "N/A"),
                    "Best Val EER": f"{data.get('best_val_eer', 0):.4f}",
                    "Best Val MinDCF": f"{data.get('best_val_mindcf',0):.4f}",
                    "Epochs": data.get("epochs_trained", 0),
                })
    
    if experiments:
        df = pd.DataFrame(experiments)
        print("\n" + "="*120)
        print("EXPERIMENT COMPARISON")
        print("="*120)
        print(df.to_string(index=False))
        print("="*120)
    else:
        print("No experiments found.")
else:
    print(f"Directory {exp_base_dir} does not exist yet.")

========================================================================================================================
EXPERIMENT COMPARISON
========================================================================================================================
                                    Experiment  Mode Fusion    Feature      PTM Best Val EER Best Val MinDCF  Epochs
                    Mode1_PTM_train_raw_hubert     1               N/A   hubert       8.5400          0.4730      12
                  Mode1_PTM_train_raw_wav2vec2     1               N/A wav2vec2       8.9300          0.4927      16
                     Mode1_PTM_train_raw_wavlm     1               N/A    wavlm       8.2700          0.4640      12
                  Mode1_PTM_train_vi_3s_hubert     1               N/A   hubert       6.2000          0.3231      14
                Mode1_PTM_train_vi_3s_wav2vec2     1               N/A wav2vec2       7.0400          0.3538      14
                   Mode1_PTM_train_vi_3s_wavlm     1               N/A    wavlm       6.0200          0.2925      17
                  Mode1_PTM_train_vi_5s_hubert     1               N/A   hubert       5.4000          0.2893      23
                Mode1_PTM_train_vi_5s_wav2vec2     1               N/A wav2vec2       5.4900          0.2958      21
                   Mode1_PTM_train_vi_5s_wavlm     1               N/A    wavlm       4.7900          0.2289      18
                  Mode1_PTM_train_vi_7s_hubert     1               N/A   hubert       5.5700          0.3234      22
                Mode1_PTM_train_vi_7s_wav2vec2     1               N/A wav2vec2       7.3500          0.3430      23
                   Mode1_PTM_train_vi_7s_wavlm     1               N/A    wavlm       6.1800          0.3305      23
                Mode1_PTM_train_vi_full_hubert     1               N/A   hubert      14.3500          0.7172      12
              Mode1_PTM_train_vi_full_wav2vec2     1               N/A wav2vec2      15.5600          0.7468       8
                 Mode1_PTM_train_vi_full_wavlm     1               N/A    wavlm      14.1700          0.7205       8
                  Mode2_HC_train_raw_mfbe_only     2         mfbe_only      N/A       9.3400          0.5193      31
                 Mode2_HC_train_raw_mfbe_pitch     2        mfbe_pitch      N/A      10.5100          0.6184      23
                  Mode2_HC_train_raw_mfcc_only     2         mfcc_only      N/A      10.2600          0.5674      21
                 Mode2_HC_train_raw_mfcc_pitch     2        mfcc_pitch      N/A      10.1300          0.5153      25
                 Mode2_HC_train_raw_pitch_only     2        pitch_only      N/A      30.8700          1.0000      11
                Mode2_HC_train_vi_3s_mfbe_only     2         mfbe_only      N/A       5.0800          0.2591      10
               Mode2_HC_train_vi_3s_mfbe_pitch     2        mfbe_pitch      N/A       4.7200          0.2411      15
                Mode2_HC_train_vi_3s_mfcc_only     2         mfcc_only      N/A       4.3000          0.2167      22
               Mode2_HC_train_vi_3s_mfcc_pitch     2        mfcc_pitch      N/A       4.5200          0.2151      23
               Mode2_HC_train_vi_3s_pitch_only     2        pitch_only      N/A      22.5400          0.9706      16
                Mode2_HC_train_vi_5s_mfbe_only     2         mfbe_only      N/A       3.8900          0.2132      25
               Mode2_HC_train_vi_5s_mfbe_pitch     2        mfbe_pitch      N/A       4.0900          0.2320      23
                Mode2_HC_train_vi_5s_mfcc_only     2         mfcc_only      N/A       4.8400          0.2408      15
               Mode2_HC_train_vi_5s_mfcc_pitch     2        mfcc_pitch      N/A       4.5700          0.2340      13
               Mode2_HC_train_vi_5s_pitch_only     2        pitch_only      N/A      21.3000          1.0000      17
                Mode2_HC_train_vi_7s_mfbe_only     2         mfbe_only      N/A       7.0400          0.4289      15
               Mode2_HC_train_vi_7s_mfbe_pitch     2        mfbe_pitch      N/A       6.9400          0.4158      14
                Mode2_HC_train_vi_7s_mfcc_only     2         mfcc_only      N/A       6.0600          0.3475      14
               Mode2_HC_train_vi_7s_mfcc_pitch     2        mfcc_pitch      N/A       5.7900          0.3540      31
               Mode2_HC_train_vi_7s_pitch_only     2        pitch_only      N/A      27.1100          0.9994      28
              Mode2_HC_train_vi_full_mfbe_only     2         mfbe_only      N/A      17.0500          0.8089      21
             Mode2_HC_train_vi_full_mfbe_pitch     2        mfbe_pitch      N/A      19.6100          0.8130      18
              Mode2_HC_train_vi_full_mfcc_only     2         mfcc_only      N/A      16.8800          0.8007      19
             Mode2_HC_train_vi_full_mfcc_pitch     2        mfcc_pitch      N/A      18.1100          0.8021      22
             Mode2_HC_train_vi_full_pitch_only     2        pitch_only      N/A      30.2000          0.9997      10
       Mode3_concat_train_raw_hubert_mfbe_only     3 concat  mfbe_only   hubert       7.6400          0.3880      11
      Mode3_concat_train_raw_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       8.4100          0.4271      12
       Mode3_concat_train_raw_hubert_mfcc_only     3 concat  mfcc_only   hubert       8.0300          0.4335       8
      Mode3_concat_train_raw_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       7.6100          0.4009      10
      Mode3_concat_train_raw_hubert_pitch_only     3 concat pitch_only   hubert       9.6600          0.4854       8
     Mode3_concat_train_raw_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       7.5600          0.5043       6
    Mode3_concat_train_raw_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       8.4300          0.4727      10
     Mode3_concat_train_raw_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       8.7900          0.5059       7
    Mode3_concat_train_raw_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       8.0800          0.4811       7
    Mode3_concat_train_raw_wav2vec2_pitch_only     3 concat pitch_only wav2vec2      10.4600          0.5140       7
        Mode3_concat_train_raw_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       8.4700          0.4379       8
       Mode3_concat_train_raw_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       7.6300          0.4412       7
        Mode3_concat_train_raw_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       7.9300          0.4547       7
       Mode3_concat_train_raw_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       8.7400          0.4248       9
       Mode3_concat_train_raw_wavlm_pitch_only     3 concat pitch_only    wavlm       9.7800          0.4269       9
     Mode3_concat_train_vi_3s_hubert_mfbe_only     3 concat  mfbe_only   hubert       4.8400          0.2547       9
    Mode3_concat_train_vi_3s_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       5.2100          0.2421      14
     Mode3_concat_train_vi_3s_hubert_mfcc_only     3 concat  mfcc_only   hubert       4.8500          0.2180       6
    Mode3_concat_train_vi_3s_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       5.2200          0.2802       7
    Mode3_concat_train_vi_3s_hubert_pitch_only     3 concat pitch_only   hubert       7.1700          0.3412      10
   Mode3_concat_train_vi_3s_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       8.3000          0.3974       8
  Mode3_concat_train_vi_3s_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       7.8800          0.3734      11
   Mode3_concat_train_vi_3s_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       8.2300          0.3733      12
  Mode3_concat_train_vi_3s_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       8.3200          0.4019       8
  Mode3_concat_train_vi_3s_wav2vec2_pitch_only     3 concat pitch_only wav2vec2       7.6900          0.3778       8
      Mode3_concat_train_vi_3s_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       5.2900          0.2458       8
     Mode3_concat_train_vi_3s_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       5.0100          0.2223      10
      Mode3_concat_train_vi_3s_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       4.6200          0.2120       7
     Mode3_concat_train_vi_3s_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       5.4400          0.2616       9
     Mode3_concat_train_vi_3s_wavlm_pitch_only     3 concat pitch_only    wavlm       7.0500          0.3595       6
     Mode3_concat_train_vi_5s_hubert_mfbe_only     3 concat  mfbe_only   hubert       4.9000          0.2756       6
    Mode3_concat_train_vi_5s_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       4.8200          0.2590       7
     Mode3_concat_train_vi_5s_hubert_mfcc_only     3 concat  mfcc_only   hubert       5.2500          0.2723       7
    Mode3_concat_train_vi_5s_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       5.1600          0.2581       7
    Mode3_concat_train_vi_5s_hubert_pitch_only     3 concat pitch_only   hubert       7.3200          0.3783      10
   Mode3_concat_train_vi_5s_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       4.7400          0.2490       7
  Mode3_concat_train_vi_5s_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       4.5200          0.2515       8
   Mode3_concat_train_vi_5s_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       5.2600          0.2627      11
  Mode3_concat_train_vi_5s_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       5.1700          0.2664       6
  Mode3_concat_train_vi_5s_wav2vec2_pitch_only     3 concat pitch_only wav2vec2       6.5600          0.3048       9
      Mode3_concat_train_vi_5s_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       4.4000          0.2343       6
     Mode3_concat_train_vi_5s_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       4.5900          0.2442       6
      Mode3_concat_train_vi_5s_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       4.4900          0.2656      11
     Mode3_concat_train_vi_5s_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       4.7600          0.2496       8
     Mode3_concat_train_vi_5s_wavlm_pitch_only     3 concat pitch_only    wavlm       6.0900          0.3091       6
     Mode3_concat_train_vi_7s_hubert_mfbe_only     3 concat  mfbe_only   hubert       5.8300          0.3317      18
    Mode3_concat_train_vi_7s_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert       4.7200          0.2914      10
     Mode3_concat_train_vi_7s_hubert_mfcc_only     3 concat  mfcc_only   hubert       5.6100          0.3152      12
    Mode3_concat_train_vi_7s_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert       5.8700          0.3717       6
    Mode3_concat_train_vi_7s_hubert_pitch_only     3 concat pitch_only   hubert       7.7900          0.3608      10
   Mode3_concat_train_vi_7s_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2       6.4900          0.3690       9
  Mode3_concat_train_vi_7s_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2       5.8600          0.3574      10
   Mode3_concat_train_vi_7s_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2       6.0800          0.3441      10
  Mode3_concat_train_vi_7s_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2       4.8800          0.2764      18
  Mode3_concat_train_vi_7s_wav2vec2_pitch_only     3 concat pitch_only wav2vec2       8.5600          0.3684      13
      Mode3_concat_train_vi_7s_wavlm_mfbe_only     3 concat  mfbe_only    wavlm       5.4000          0.3595       7
     Mode3_concat_train_vi_7s_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm       5.1300          0.3255      12
      Mode3_concat_train_vi_7s_wavlm_mfcc_only     3 concat  mfcc_only    wavlm       5.6800          0.3400      12
     Mode3_concat_train_vi_7s_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm       5.5400          0.2980      12
     Mode3_concat_train_vi_7s_wavlm_pitch_only     3 concat pitch_only    wavlm       8.6300          0.3712      14
   Mode3_concat_train_vi_full_hubert_mfbe_only     3 concat  mfbe_only   hubert      13.7400          0.7044       6
  Mode3_concat_train_vi_full_hubert_mfbe_pitch     3 concat mfbe_pitch   hubert      14.2800          0.7012       7
   Mode3_concat_train_vi_full_hubert_mfcc_only     3 concat  mfcc_only   hubert      13.6700          0.7039       6
  Mode3_concat_train_vi_full_hubert_mfcc_pitch     3 concat mfcc_pitch   hubert      15.2000          0.7573       6
  Mode3_concat_train_vi_full_hubert_pitch_only     3 concat pitch_only   hubert      12.8300          0.6938       6
 Mode3_concat_train_vi_full_wav2vec2_mfbe_only     3 concat  mfbe_only wav2vec2      15.1600          0.7404       6
Mode3_concat_train_vi_full_wav2vec2_mfbe_pitch     3 concat mfbe_pitch wav2vec2      15.1600          0.7350       6
 Mode3_concat_train_vi_full_wav2vec2_mfcc_only     3 concat  mfcc_only wav2vec2      15.4100          0.7327       6
Mode3_concat_train_vi_full_wav2vec2_mfcc_pitch     3 concat mfcc_pitch wav2vec2      15.5600          0.7426       6
Mode3_concat_train_vi_full_wav2vec2_pitch_only     3 concat pitch_only wav2vec2      13.6900          0.7238       6
    Mode3_concat_train_vi_full_wavlm_mfbe_only     3 concat  mfbe_only    wavlm      15.8500          0.7130       7
   Mode3_concat_train_vi_full_wavlm_mfbe_pitch     3 concat mfbe_pitch    wavlm      14.8000          0.7250       6
    Mode3_concat_train_vi_full_wavlm_mfcc_only     3 concat  mfcc_only    wavlm      14.8200          0.7214       6
   Mode3_concat_train_vi_full_wavlm_mfcc_pitch     3 concat mfcc_pitch    wavlm      16.3300          0.7381       6
   Mode3_concat_train_vi_full_wavlm_pitch_only     3 concat pitch_only    wavlm      15.1300          0.7270       7
         Mode3_film_train_raw_hubert_mfbe_only     3   film  mfbe_only   hubert       7.9100          0.4105      10
        Mode3_film_train_raw_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       8.2400          0.4257       8
         Mode3_film_train_raw_hubert_mfcc_only     3   film  mfcc_only   hubert       7.7900          0.4055      12
        Mode3_film_train_raw_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       7.3900          0.4016      14
        Mode3_film_train_raw_hubert_pitch_only     3   film pitch_only   hubert       8.8800          0.4475       9
       Mode3_film_train_raw_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       8.2900          0.4504      10
      Mode3_film_train_raw_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       8.0100          0.4273      12
       Mode3_film_train_raw_wav2vec2_mfcc_only     3   film  mfcc_only wav2vec2       8.0600          0.4309      10
      Mode3_film_train_raw_wav2vec2_mfcc_pitch     3   film mfcc_pitch wav2vec2       7.7300          0.4347      11
      Mode3_film_train_raw_wav2vec2_pitch_only     3   film pitch_only wav2vec2       9.0100          0.4608       9
          Mode3_film_train_raw_wavlm_mfbe_only     3   film  mfbe_only    wavlm       8.0000          0.4469       7
         Mode3_film_train_raw_wavlm_mfbe_pitch     3   film mfbe_pitch    wavlm       7.8300          0.4211      10
          Mode3_film_train_raw_wavlm_mfcc_only     3   film  mfcc_only    wavlm       7.6500          0.4142       8
         Mode3_film_train_raw_wavlm_mfcc_pitch     3   film mfcc_pitch    wavlm       7.3500          0.4253       8
         Mode3_film_train_raw_wavlm_pitch_only     3   film pitch_only    wavlm       9.2800          0.4910       7
       Mode3_film_train_vi_3s_hubert_mfbe_only     3   film  mfbe_only   hubert       4.1000          0.2046      14
      Mode3_film_train_vi_3s_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       4.4500          0.1995      10
       Mode3_film_train_vi_3s_hubert_mfcc_only     3   film  mfcc_only   hubert       4.4000          0.2155       8
      Mode3_film_train_vi_3s_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       4.2000          0.1900       6
      Mode3_film_train_vi_3s_hubert_pitch_only     3   film pitch_only   hubert       6.0200          0.2816      13
     Mode3_film_train_vi_3s_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       6.4900          0.3317      11
    Mode3_film_train_vi_3s_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       6.8000          0.3174      15
     Mode3_film_train_vi_3s_wav2vec2_mfcc_only     3   film  mfcc_only wav2vec2       6.9500          0.3646      10
    Mode3_film_train_vi_3s_wav2vec2_mfcc_pitch     3   film mfcc_pitch wav2vec2       6.7800          0.3418      11
    Mode3_film_train_vi_3s_wav2vec2_pitch_only     3   film pitch_only wav2vec2       6.7500          0.3430      12
        Mode3_film_train_vi_3s_wavlm_mfbe_only     3   film  mfbe_only    wavlm       4.6400          0.2102      17
       Mode3_film_train_vi_3s_wavlm_mfbe_pitch     3   film mfbe_pitch    wavlm       4.6200          0.2233      10
        Mode3_film_train_vi_3s_wavlm_mfcc_only     3   film  mfcc_only    wavlm       4.1900          0.1967      11
       Mode3_film_train_vi_3s_wavlm_mfcc_pitch     3   film mfcc_pitch    wavlm       4.5600          0.2286       9
       Mode3_film_train_vi_3s_wavlm_pitch_only     3   film pitch_only    wavlm       5.8400          0.2657       9
       Mode3_film_train_vi_5s_hubert_mfbe_only     3   film  mfbe_only   hubert       4.2200          0.2233       7
      Mode3_film_train_vi_5s_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       4.2200          0.2167       9
       Mode3_film_train_vi_5s_hubert_mfcc_only     3   film  mfcc_only   hubert       4.5000          0.2457       7
      Mode3_film_train_vi_5s_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       3.9400          0.2070       9
      Mode3_film_train_vi_5s_hubert_pitch_only     3   film pitch_only   hubert       5.7300          0.2890       7
     Mode3_film_train_vi_5s_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       4.0600          0.2048       7
    Mode3_film_train_vi_5s_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       3.9800          0.2097       8
     Mode3_film_train_vi_5s_wav2vec2_mfcc_only     3   film  mfcc_only wav2vec2       4.3300          0.2373       8
    Mode3_film_train_vi_5s_wav2vec2_mfcc_pitch     3   film mfcc_pitch wav2vec2       4.5500          0.2260       9
    Mode3_film_train_vi_5s_wav2vec2_pitch_only     3   film pitch_only wav2vec2       5.7400          0.2849       8
        Mode3_film_train_vi_5s_wavlm_mfbe_only     3   film  mfbe_only    wavlm       4.0200          0.2195       7
       Mode3_film_train_vi_5s_wavlm_mfbe_pitch     3   film mfbe_pitch    wavlm       3.8000          0.1954       8
        Mode3_film_train_vi_5s_wavlm_mfcc_only     3   film  mfcc_only    wavlm       3.9100          0.2153       6
       Mode3_film_train_vi_5s_wavlm_mfcc_pitch     3   film mfcc_pitch    wavlm       4.2100          0.2096       8
       Mode3_film_train_vi_5s_wavlm_pitch_only     3   film pitch_only    wavlm       5.5300          0.2441      10
       Mode3_film_train_vi_7s_hubert_mfbe_only     3   film  mfbe_only   hubert       3.8600          0.2715      14
      Mode3_film_train_vi_7s_hubert_mfbe_pitch     3   film mfbe_pitch   hubert       4.6100          0.3042      12
       Mode3_film_train_vi_7s_hubert_mfcc_only     3   film  mfcc_only   hubert       3.7500          0.2686      13
      Mode3_film_train_vi_7s_hubert_mfcc_pitch     3   film mfcc_pitch   hubert       3.0900          0.2129      23
      Mode3_film_train_vi_7s_hubert_pitch_only     3   film pitch_only   hubert       6.0500          0.3368      11
     Mode3_film_train_vi_7s_wav2vec2_mfbe_only     3   film  mfbe_only wav2vec2       4.5200          0.3154      12
    Mode3_film_train_vi_7s_wav2vec2_mfbe_pitch     3   film mfbe_pitch wav2vec2       4.5400          0.3121       8